### ISSUE TITLE
Improvements to the README

### ISSUE THREAD

**Issue by helenmasters** [AdoptOpenJDK/openjdk-tests#1]
As a user new to the Adopt OpenJDK area the README needs to have more information in it. It would benefit from a section along the lines of 'what is in this repository and why would I want to use it?'

In addition I've been trying to follow the steps outlined and there are some changes required there too.  In the section below there isn't a test directory, the instruction `cd /test/TestConfig` doesn't work as TestConfig is at the top level. In addition it would be useful to put in an example for the format of the `platform_on_which_to_test`. Ideally there would be a list of all the available platforms which are valid for running tests on (this could be a link out to another github project containing the releases).

```
cd /test/TestConfig
  export JAVA_BIN=/location_of_JVM_under_test
  export SPEC=platform_on_which_to_test
  export JAVA_VERSION=[SE80|SE90] (SE90 default value)
  make -f run_configure.mk
```

**Comment by helenmasters** [comment]
Please provide example settings for JAVA_BIN too, reference https://github.com/AdoptOpenJDK/openjdk-tests/issues/5

**Comment by helenmasters** [comment]
As Shelley mentioned here https://github.com/AdoptOpenJDK/openjdk-tests/issues/7 the dependencies don't get pulled in by default so this instruction needs to be added to the README.

**Comment by smlambert** [comment]
Closing this for now, as Helen's points have been addressed.  We will need to do another pass of documentation improvements, but can create fresh issue listing those enhancements.
