### ISSUE TITLE
Add link to test results details from TAP list view

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#10]
We generate TAP results for all tests that we run from this test infrastructure.  Since many different types of test frameworks can be called by this infrastructure, we wanted to have this standardized high-level view of test results. 

The many types of test frameworks each produce their own type of test results, which we will also like to show, if they are present. Currently you can see more detailed test output from the console view, but this is not convenient to search through.   When there are extra test results / artifacts, we should try to link to a view of them from the TAP results list view (for each test group).  

For testing tests, this means linking to the html (or xml) pages that get created).  
For jtreg tests and other types of tests/frameworks, we should determine which output files contain most useful information to link to.

This means we should ensure that test artifacts are kept for the Jenkins test builds that we keep.

**Comment by karianna** [comment]
What is TAP?

**Comment by smlambert** [comment]
Test Anything Protocol (https://testanything.org/) super simple agreed upon results format... allows us to unify many different types of tests/frameworks under one roof (including 3rd party app tests, perf tests, etc).

**Comment by karianna** [comment]
Cool thanks! :-)

**Comment by gdams** [comment]
so the issue with using jenkins artifacts is that the artifacts get replaced every time there is a new build, perhaps we need somewhere to dump all the test artifacts that we can then keep and link to such as an ftp server?

**Comment by karianna** [comment]
@gdams - How does the current flow work?  Is it: 1.) Jenkins slave builds an OpenJDK binary on say the s390 slave. 2.) That image gets copied back to master? OR stays on the s390 slave? 3.) The s390 'test' host then somehow needs to drag that binary across to itself in order to test it....

**Comment by gdams** [comment]
the image gets archived which means that it is essentially copied to master

**Comment by karianna** [comment]
I think I see now - so we have an order of operations issue in teh we want to keep an archive on builds to test against but *not* display that archive on GitHub under nightly or tagged releases as they're not tested yet.  Jenkins can archive those binaries on master but we'll likely run out of space?

**Comment by gdams** [comment]
jenkins is already archiving the latest nightly for each platform on master, as long as we test quickly there should be no issue

**Comment by karianna** [comment]
Could have jenkins store say the last 5 JIC?

**Comment by smlambert** [comment]
Closing this issue, as we will pursue the use of the richer test output options (junit/testng as preference), will open a different issue/enhancement for the work.
