### ISSUE TITLE
Eclipse Testing steps with Adopt build

### ISSUE THREAD

**Issue by suman-mitra** [AdoptOpenJDK/openjdk-tests#1000]
1. Download ant   https://www.apache.org/dist/ant/binaries/apache-ant-1.10.3-bin.tar.gz
2. Download OpenJ9/OpenJDK  from https://adoptopenjdk.net/
3. go to the link http://download.eclipse.org/eclipse/downloads/drops4
     a) search for "Integration Builds"  , it will be displayed like "4.11 Integration Builds".
         Here 4.11 is the latest Eclipse version.

     b) Select the latest build name , say "I20190307-0500" and click on this build name. It will take you to a new page with a heading like "Eclipse 4.11.0 Integration Build: I20190307-0500"

     c) In the new page mentioned as above, search for a table with a heading "Summary of Unit Tests Results"
     d) click on the any of the tested platform link in this table, say, "ep411I-unit-cen64-gtk3-java8
linux.gtk.x86_648.0"
     e) this will take us to a new page which will have "branch or hash" , e.g. 
            eclipse.platform.releng.aggregator: master (branch or hash: d9928288e9b1750835ba704b1df87c23179869a3)

      f) Copy this hash and the build id, in this case
           buildId=I20190307-0500
           -DEBUILDER_HASH=d9928288e9b1750835ba704b1df87c23179869a3

4) now export the below
     Java PATH,ANT_HOME,JAVA_HOME
     export buildId=I20190307-0500
     export WORKSPACE=/home/testuser/Eclipse4.11/
     this is the place from where we will run our tests and the artifacts will be stored
     export JOB_NAME=ep49I-unit-cen64-gtk3  
       JOB_NAME is required by Eclipse, which is usually supplied by their test infra. We can hardcode this value. I usually keep it constant, it can change based on the eclipse version and OS.

5) we need to have a display too. Open a vnc session for the machine which you are using.

6) open a terminal in the vnc, go to WORKSPACE dir and export all of those mentioned in step 4.

7) Run the below command

   wget -O getEBuilder.xml --no-verbose   http://git.eclipse.org/c/platform/eclipse.platform.releng.aggregator.git/plain/production/testScripts/hudsonBootstrap/getEBuilder.xml 2>&1

    It will fetch getEBuilder.xml and place it in the WORKSPACE dir.

8) Now run the below command , which will start to run the Eclipse tests

      ant -f getEBuilder.xml -Djava.io.tmpdir=${WORKSPACE}/tmp -DbuildId=$buildId  -DeclipseStream=4.11.0 -DEBUILDER_HASH=5263935c3fd5154486109e58e7de0626db119a19  -DdownloadURL=http://download.eclipse.org/eclipse/downloads/drops4/${buildId}  -Dosgi.os=linux -Dosgi.ws=gtk -Dosgi.arch=x86_64 -DtestSuite=sdkTests

In this command we need to replace "-DEBUILDER_HASH" value (mentioned in 3f) and "-DeclipseStream" value. Currently "-DeclipseStream" is set to 4.11.0 which implies it is Eclipse4.11. We may need to change when we switch to a new version

**Comment by smlambert** [comment]
Closing this with a reference to the open #172 issue, should we want to return to it and progress it.
