### ISSUE TITLE
All test builds on windows failed with msg 'replace ./jdk-11.0.2+9-jre/bin/awt.dll? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL 22:57:03  (EOF or read error, treating as "[N]one" ...)'

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1010]
All test builds on windows failed with msg 'replace ./jdk-11.0.2+9-jre/bin/awt.dll? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL 22:57:03  (EOF or read error, treating as "[N]one" ...)'

```
2:56:53  unzip file: OpenJDK11U-jdk_x64_windows_hotspot_2019-03-20-19-07.zip ...
22:57:03  unzip file: OpenJDK11U-jre_x64_windows_hotspot_2019-03-20-19-07.zip ...
22:57:03  replace ./jdk-11.0.2+9-jre/bin/awt.dll? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
22:57:03  (EOF or read error, treating as "[N]one" ...)
[Pipeline] }
```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_windows/172/console

**Comment by sophia-guo** [comment]
There is no changes in openjdk-tests repo related with this issue. Looks like there is window jre build changes? @karianna

**Comment by karianna** [comment]
> There is no changes in openjdk-tests repo related with this issue. Looks like there is window jre build changes? @karianna

@sophia-guo This may be due to the issues we're having with Jenkins today.  Let me know in 24 hours if it's still an issue.

**Comment by sophia-guo** [comment]
Looks good now. Close it. Thanks @karianna
