### ISSUE TITLE
Support JDKnext test builds

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#1018]
[JDKnext test build](https://ci.eclipse.org/openj9/view/Test/job/Test-extended.functional-JDKnext-linux_x86-64_cmprssptrs/) is a JDK_VERSION agnostic build. It depends on TKG to auto-detect JDK_VERSION (and/or JDK_IMPL).

To support this, 
- JDK_VERSION and JDK_IMPL should be the optional parameters in [JenkinsfileBase](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase)
- JDK_VERSION should set to empty for JDKnext job in [testJobTemplate](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate)

**Comment by llxia** [comment]
Currently, JDK_VERSION is used for setting JAVA_HOME value, so this issue is blocked by 
https://github.com/eclipse/openj9/pull/5155 
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1001

**Comment by Mesbah-Alam** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1001 has been resolved.
