### ISSUE TITLE
Add sleep & retry logic around the curl on the SDK

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-tests#1033]
In the even we have a network blip while trying to curl an SDK, we should introduce a sleep and retry in an attempt to recover before failing outright. I can think of 2 options of where to add the fix.
1. In JenkinsfileBase around this if/else block
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L249
1. In the get.sh script around the curl
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/get.sh#L159
The bash may be more difficult but it would wrap only the curl command we are addressing with this issue (which has pros and cons itself). It would also work for users running the get.sh directly (not on Jenkins).

Thoughts @llxia ?

**Comment by llxia** [comment]
I would prefer option 2 In the get.sh script around the curl. As you mentioned, it would also help local runs.

fyi @ShelleyLambert @sophia-guo

**Comment by sophia-guo** [comment]
Set sleep 30 second and retry 5 times. If not enough we can increase the setup.
