### ISSUE TITLE
JniInvocationTest does not run on macosx

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#1035]
This test only runs on jdk12, on mac, and it doesn't pass on openj9 or hotspot binaries because of the following error, which occurs at the start:

```
TEST RESULT: Error. Use -nativepath to specify the location of native code
```

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_hs_openjdktest_x86-64_macos/15/console
https://ci.adoptopenjdk.net/job/openjdk12_j9_openjdktest_x86-64_macos/17/console

Until I get access to a mac machine to run this test on, I can't prove that it isn't framework setup that's causing this. Will raise this externally once I've run this directly and reproduced the bug.

**Comment by smlambert** [comment]
Please exclude that test with the following link:
https://github.com/AdoptOpenJDK/openjdk-build/issues/248

We need the native test libs to be built and passed to the test job, in order to run native tests.

**Comment by adamfarley** [comment]
Ah, ok. Will do. Thanks.
