### ISSUE TITLE
Common naming convention for test builds

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#1037]
As we maintain various test builds across multiple Jenkins, it would be better if we have a common naming convention for all test builds. This will help users to navigate and triage.

The proposed format:
`Test_openjdk<JDK_VERSION>_<JDK_IMPL>_<TARGET>_<ARCH_OS>_<SUFFIX>`

For example, 
`Test_openjdk11_hs_sanity.openjdk_ppc64le_linux`
`Test_openjdk8_j9_extended.system_x86-64_linux_xl`
`Test_openjdk11_hs_extended.external_tomcat_x86-64_linux` // tomcat is the subfolder

SUFFIX can be empty or BUILD_TYPE (i.e., Nightly, Release, etc). BUILD_TYPE is used in OpenJ9 Jenkins. For details, please see https://github.com/eclipse/openj9/issues/5210

If additional information is needed in the test build name in the future (i.e., vendor info), we can add it later.

fyi @ShelleyLambert @sophia-guo @Mesbah-Alam

**Comment by smlambert** [comment]
Given https://github.com/AdoptOpenJDK/openjdk-tests/pull/1047 and https://github.com/AdoptOpenJDK/openjdk-build/pull/1125 were merged and new jobs have been generated (see https://github.com/AdoptOpenJDK/openjdk-tests/issues/1168), this can be closed.
