### ISSUE TITLE
Exclude native functional tests from thirdparty containers 

### ISSUE THREAD

**Issue by chandrams** [AdoptOpenJDK/openjdk-tests#1054]
Issue #714, included openj9 sanity functional tests to run in docker containers. As part of this native functional tests are also run, but these fail as the native libraries are built on openj9 CI jenkins and to resolve these we decided to exclude these tests for now. 

Below pull request has included a change to exclude native tests by including a new type tag. Will need to modify the playlist to include this.
https://github.com/eclipse/openj9/pull/5191

**Comment by llxia** [comment]
Functional tests should be properly tagged. We just need to change the following line to `make _sanity.functional.regular`

https://github.com/AdoptOpenJDK/openjdk-tests/blob/c1b49a0a1f8cc15f6b3d698e8805c230dd56a442/thirdparty_containers/functional-test/dockerfile/functional-test.sh#L74

**Comment by chandrams** [comment]
Thanks @llxia 

I have made the above change and submitted a grinder, but get this error:
20:00:34       [exec] ant -f scripts/build_test.xml -DTEST_ROOT=/openjdk-tests/TestConfig/.. -DBUILD_ROOT=/openjdk-tests/TestConfig/../../jvmtest -DJAVA_BIN=/opt/java/openjdk/bin -DJDK_VERSION=8 -DJCL_VERSION=latest -DBUILD_LIST=systemtest -DRESOURCES_DIR=/openjdk-tests/TestConfig/../../jvmtest/TestConfig/resources -DPLATFORM=linux_x86-64_cr -DJDK_HOME=/opt/java/openjdk/bin/../.. -DJVM_VERSION=openjdk8-openj9
20:00:34       [exec] Error: JAVA_HOME is not defined correctly.
20:00:34       [exec]   We cannot execute /opt/java/openjdk/bin/../../bin/java
20:00:34       [exec] makefile:82: recipe for target 'compile' failed

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1432/console

**Comment by chandrams** [comment]
I get the same error, when I removed setting JAVA_HOME and JAVA_BIN in another branch where I made changes to remove hardcoding of SPEC in the script:

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1434/console

Do we need to set JAVA_HOME and JAVA_BIN explicitly? But in either case with setting (grinder in above comment) and without setting I still get the same error.  Am I missing anything here @llxia ?

**Comment by smlambert** [comment]
I believe the points mentioned in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1054#issuecomment-481254291 are now fixed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1206 so we should try to resolve this issue by retrying the _sanity.functional.regular target (as the other issues seen in the grinder should now be resolved).

**Comment by smlambert** [comment]
Adding this to the August milestone, as there should be nothing blocking the completion of a PR for this now.

**Comment by llxia** [comment]
PR #1252 is merged. Close this issue.
