### ISSUE TITLE
Update jenkins job to consume openjdk-tests/buildenv dir 

### ISSUE THREAD

**Issue by TianyuZuo** [AdoptOpenJDK/openjdk-tests#106]
Based on the PR github.com/AdoptOpenJDK/openjdk-tests/pull/105

Build folder is going to be renamed to buildenv, which will affect all test related Jenkins builds. Once the PR is merged, we will need to update the jenkins jobs' configuration to meet the #105  changes

**Comment by smlambert** [comment]
please co-ordinate the changes to jenkinsfiles with the rename of buildenv dir, so there is not a period of 'brokenness'

**Comment by smlambert** [comment]
This one can be closed, as all test builds are now referring to files in buildenv
