### ISSUE TITLE
JDK 8 sanity.openjdk JRE math tests expect j2jre-image

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-tests#1062]
When running JDK 8 sanity.openjdk tests on an upstream build like:
https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u212-b02/OpenJDK8U-x64_linux_8u212b02_ea.tar.gz

`jdk_math_jre_0` tests fail with `Error: JDK not found: /home/jenkins/workspace/Grinder/openjdkbinary/j2jre-image`:

```
10:17:40  ===============================================
10:17:40  Running test jdk_math_jre_0 ...
10:17:40  ===============================================
10:17:40  jdk_math_jre_0 Start Time: Mon Apr  8 01:17:30 2019 Epoch Time (ms): 1554711450483
10:17:40  Nothing to be done for setup.
10:17:40  variation: NoOptions
10:17:40  JVM_OPTIONS:  
10:17:40  { itercnt=1; \
10:17:40  mkdir -p "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_1554711131946/jdk_math_jre_0"; \
10:17:40  cd "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_1554711131946/jdk_math_jre_0"; \
10:17:40  "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/java" -Xmx512m -jar "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/jtreg/lib/jtreg.jar" \
10:17:40  -agentvm -a -ea -esa -v:fail,error,time,nopass -retain:fail,error -ignore:quiet -timeoutFactor:8 -xml:verify -concurrency:4  -vmoptions:"-Xmx512m  " \
10:17:40  -w "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/work" \
10:17:40  -r "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/report" \
10:17:40  -compilejdk:"/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/../.." \
10:17:40  -jdk:"/home/jenkins/workspace/Grinder/openjdkbinary/j2jre-image" \
10:17:40  -exclude:"/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../openjdk_regression/openjdk-jdk/jdk/test/ProblemList.txt" \
10:17:40  -exclude:"/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/ProblemList_openjdk8.txt" \
10:17:40  "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../openjdk_regression/openjdk-jdk/jdk/test:jdk_math"; \
10:17:40  if [ $? -eq 0 ] ; then echo ""; echo "jdk_math_jre_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../..;  else echo ""; echo "jdk_math_jre_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_1554711131946/TestTargetResult";
10:17:40  Error: JDK not found: /home/jenkins/workspace/Grinder/openjdkbinary/j2jre-image
10:17:40  
10:17:40  jdk_math_jre_0_FAILED
10:17:40  
10:17:40  Nothing to be done for teardown.
```

See:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1427/console

The reason for this seems to be that the jenkins job sets `JRE_IMAGE=/home/jenkins/workspace/Grinder/openjdkbinary/j2jre-image` explicitly. Two issues: 1.) for a JDK 8 upstream OpenJDK build, that directory is `j2re-image`. 2) For a custom JDK it should perhaps use `/path/to/openjdkbinary/j2sdk-image/jre` or something.

**Comment by jerboaa** [comment]
@ShelleyLambert FYI. Maybe there is a parameter I'm missing? Thanks.

**Comment by smlambert** [comment]
I am going to assume we've just matched to the AdoptOpenJDK builds at the moment (and would have assumed that the location of the jre would have common/standard naming). We should either parameterize or see if the @AdoptOpenJDK/build team wants to align the location of jre (j2jre vs j2re).

@sophia-guo can you please check what would be involved to parameterize that directory location?

**Comment by jerboaa** [comment]
> I am going to assume we've just matched to the AdoptOpenJDK builds at the moment (and would have assumed that the location of the jre would have common/standard naming). We should either parameterize or see if the @AdoptOpenJDK/build team wants to align the location of jre (j2jre vs j2re).

FYI: Here is the output of an upstream OpenJDK `images` directory after a regular build. No special config flags etc.

```
$ ls -1
j2re-image
j2sdk-image
lib
sec-bin.zip
src
src.zip
symbols
```

So I'm not sure where `j2jre` name comes from. Perhaps from OpenJ9?

**Comment by sophia-guo** [comment]
j2jre should be from AdoptOpenJDK builds originally. Not sure if something changed I will update it to align with AdoptOpenJDK builds.

As for parameterizing it can be easily added as a build parameter in grinder as JRE_IMAGE is defined as environment variable. I will update it too.

**Comment by sophia-guo** [comment]
However the issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/1062#issue-430356971 is actually caused by the JRE SDK missing. Jdk_math_jre can only work when both JDK SDK and JRE SDK are provided, which is the case of upstream AdoptOpenJDK builds AdoptOpenJDK builds https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/

For grinder the use need to provide the link of both SDK and JRE. Something like "https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/lastSuccessfulBuild/artifact/workspace/target/OpenJDK8U-jdk_x64_linux_hotspot_2019-04-08-03-27.tar.gz https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/lastSuccessfulBuild/artifact/workspace/target/OpenJDK8U-jre_x64_linux_hotspot_2019-04-08-03-27.tar.gz"

For test builds triggered by upstream AdoptOpenJDK builds which is the case of AdopOpenJDK builds https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/.

**Comment by jerboaa** [comment]
> However the issue [#1062 (comment)](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1062#issue-430356971) is actually caused by the JRE SDK missing. Jdk_math_jre can only work when both JDK SDK and JRE SDK are provided, which is the case of upstream AdoptOpenJDK builds AdoptOpenJDK builds https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/

FWIW, my local script has `export JRE_IMAGE=$OPENJDK_BUILD/jre` where `$OPENJDK_BUILD` is a JDK (a superset of JRE). That works fine. Not sure why both, a JDK and a JRE tarball are required for jenkins testing. I'd think it would be good to pass tests with "just" a JDK :-)

> For grinder the use need to provide the link of both SDK and JRE. Something like "https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/lastSuccessfulBuild/artifact/workspace/target/OpenJDK8U-jdk_x64_linux_hotspot_2019-04-08-03-27.tar.gz https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/lastSuccessfulBuild/artifact/workspace/target/OpenJDK8U-jre_x64_linux_hotspot_2019-04-08-03-27.tar.gz"
> 
> Hmm, that also means it only works with customized URL.

Yes. Customized URL only takes a JDK (via `CUSTOMIZED_SDK_URL`) at this point I believe.

**Comment by sophia-guo** [comment]
> Hmm, that also means it only works with customized URL.
Have to clarify this. When using grinder it only works with customized URL. That is if SDK_RESOURCE=nightly/releases it won't work as nightly/releases only provide JDK tarball. 

The main purpose of jdk_math_jre is a smoke tests for JRE tarballs as AdoptOpenJDK provides JRE images. However jtreg testframework needs a JDK to compile tests. That's why we need both tarballs. And jdk_math_jre is the only test required both JDK and JRE tarballs.

**Comment by sophia-guo** [comment]
Close by #1077
