### ISSUE TITLE
jdk_io: java/io/Serializable/unresolvableObjectStreamClass/UnresolvableObjectStreamClass.java fail

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#107]
Execution failed: `main' threw exception: java.lang.NoClassDefFoundError: MySerializable

**Comment by akolarkunnu** [comment]
I rerun and not able to reproduce:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/116/testReport/
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/117/testReport/

**Comment by akolarkunnu** [comment]
Re-enabled these tests by PR #230
