### ISSUE TITLE
Add ulimit to the machine info that gets output in build

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#1079]
Requested by releng, we'd like to see the output of `ulimit -a` in the job output. This will aide in determining what kind of ulimit we need to set in the test machines for, especially, system tests to run. 

We can add this command to the list of commands that are already being executed as part of machine info collection in the builds. 

Note, unlike the rest of the commands in [MachineInfo.java](https://github.com/eclipse/openj9/blob/master/test/TestConfig/src/org/openj9/envInfo/MachineInfo.java),`ulimit -a` outputs a multi-line content, e.g. 

```
Mesbahs-MacBook-Pro:wycheproof Mesbah_Alam@ca.ibm.com$ sh ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1418
virtual memory          (kbytes, -v) unlimited

```

**Comment by smlambert** [comment]
Just as uname is broken up into several parts in MachineInfo, you can do the same with ulimit, depending on what you want to include in the output.

As in, not calling with -a that returns multi-line reply, but some of the subcalls that matter for the point of this exercise (how are system tests failing?  (max number of open fd's -n ?)

-a     All current limits are reported
-c     The maximum size of core files created
-d     The maximum size of a process's data segment
-e     The maximum scheduling priority ("nice")
-f     The  maximum  size  of files written by the shell and its
       children
-i     The maximum number of pending signals
-l     The maximum size that may be locked into memory
-m     The maximum resident set size (has no effect on Linux)
-n     The maximum number of open file descriptors (most systems
       do not allow this value to be set)
-p     The pipe size in 512-byte blocks (this may not be set)
-q     The maximum number of bytes in POSIX message queues
-r     The maximum real-time scheduling priority
-s     The maximum stack size
-t     The maximum amount of cpu time in seconds
-u     The  maximum  number  of  processes available to a single
       user
-v     The maximum amount of virtual  memory  available  to  the
       shell

**Comment by Mesbah-Alam** [comment]
Added ulimit to MachineInfo : https://github.com/eclipse/openj9/compare/master...Mesbah-Alam:addUlimitToMachineInfoPrintout?expand=1

The above change doesn't seem to produce consistent results: 

[AIX](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1519/console): 

```
17:10:32  ulimit: time(seconds)        unlimited
17:10:32  file(blocks)         unlimited
17:10:32  data(kbytes)         unlimited
17:10:32  stack(kbytes)        32768
17:10:32  memory(kbytes)       32768
17:10:32  coredump(blocks)     unlimited
17:10:32  nofiles(descriptors) unlimited
17:10:32  threads(per process) unlimited
17:10:32  processes(per user)  unlimited
```

[Linux x86-64](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1516/console) : null
[Cygwin / Windows](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1517/console) : null
[Linux S390](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1520/console): null
[MacOS](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1518/console) : 
```
17:06:11  ulimit: core file size          (blocks, -c) 0
17:06:11  data seg size           (kbytes, -d) unlimited
17:06:11  file size               (blocks, -f) unlimited
17:06:11  max locked memory       (kbytes, -l) unlimited
17:06:11  max memory size         (kbytes, -m) unlimited
17:06:11  open files                      (-n) 10240
17:06:11  pipe size            (512 bytes, -p) 1
17:06:11  stack size              (kbytes, -s) 65532
17:06:11  cpu time               (seconds, -t) unlimited
17:06:11  max user processes              (-u) 266
17:06:11  virtual memory          (kbytes, -v) unlimited
```

**Comment by Mesbah-Alam** [comment]
@jdekonin , As mentioned in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1079#issuecomment-483867367, I am curious to try out not using `ulimit -a`, but use specific sub-calls to see if those work on all platforms. Could you please let me know what specific output would be useful to you ? ( I know you mentioned -c (core file generation) on Slack, is there anything else that might be useful?)

**Comment by smlambert** [comment]
Based on the comment on original issue : https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/253#issuecomment-482915034

the value in question was from ulimit -u

**Comment by jdekonin** [comment]
Through various issues on different platforms I have found all of these can impact a successful test run, it all depends on how the machine was setup that was donated; c, d, m, n, s, u.

I just figured all would be easer.

**Comment by Mesbah-Alam** [comment]
I think invoking `ulimit -a` and printing the output in the build keeps things simple. 

Even though `ulimit -a` returns a multi-line output, it comes in a formatted list which can be output easily in the build. Besides, It's cheaper to make a single Runtime.exec() call using `uname -a`, parse the multi-line output and print them in a list, than making one separate call to Runtime.exec() with each option, which would amount to at least 6 calls (for c,d,m,n,s,u), or more.  

* * * 

Also, `ulimit` is a bit different than other commands in that it needs to be run in a shell. As I found out earlier, simply calling "ulimit a" via Runtime.exec() doesn't work. We have to call it in a shell, e.g., `sh ulimit -a`. As reported in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1079#issuecomment-483868246, this doesn't work on a few platforms, e.g. Linux where, it turns out that we need to use the `-c` option, e.g. ```Runtime.getRuntime().exec(new String[] { "bash", "-c", "ulimit -a" });``` -- then we get the right output (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1531/console).
