### ISSUE TITLE
wycheproof test build failed

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1095]
JDK 11 failures:
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk11_hs_external_extended_wycheproof_x86-64_linux/

https://ci.adoptopenjdk.net/view/Test_external/job/openjdk11_j9_external_extended_wycheproof_x86-64_linux/

JDK 8 failures:
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_external_extended_wycheproof_x86-64_linux/1/console

https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_j9_external_extended_wycheproof_x86-64_linux/1/console

FYI @Mesbah-Alam

**Comment by sophia-guo** [comment]
Two issues here: 

1. tests are limited to `<subset>8</subset>`, which caused JDK11 test failure.
2. tests are leveled as `<level>sanity</level>`, which caused JDK8 test failure.

We should run the test against all jdk version and as level extended?

**Comment by smlambert** [comment]
Partly my bad... I added the jdk11 jobs without checking that it was ready for or applicable to jdk11.  These tests should be run in extended level for now.

**Comment by sophia-guo** [comment]
Close by #1101 and #1108
