### ISSUE TITLE
hotspot_jre : ACTION: driver -- Failed. 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#110]
Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of REASON: User specified action: run driver/timeout=720 TestShrinkAuxiliaryData05 

gc/g1/TestShrinkAuxiliaryData05.java
gc/g1/TestShrinkAuxiliaryData10.java
gc/g1/TestShrinkAuxiliaryData15.java
gc/g1/TestShrinkAuxiliaryData20.java

other failed similar tests:
runtime/os/AvailableProcessors.java 
18:30:58 ACTION: driver -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'Found expected processors: ' missing from stdout/stderr
18:30:58 REASON: User specified action: run driver AvailableProcessors

**Comment by akolarkunnu** [comment]
This is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8180904.

**Comment by smlambert** [comment]
Closing as now listed in summary issue #345
