### ISSUE TITLE
jdk_net :ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Failed

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#111]
REASON: Assumed action based on file name: run main GetMacAddress 

java/net/NetworkInterface/GetMacAddress.java

**Comment by akolarkunnu** [comment]
I rerun and not able to reproduce : https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/114/testReport/

**Comment by akolarkunnu** [comment]
Re-enabled these tests by PR #230
