### ISSUE TITLE
Switch extended test builds in external category to weekly

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1123]
Switch extended test builds in external category to weekly. Set up a parent build to trigger downstream build weekly.

- [x] set up parent build to trigger builds weekly
https://ci.adoptopenjdk.net/view/Test_external_weekly/job/openjdk_externaltest_extended_weekly/configure

- [x] turn off currently test builds triggered by upstream builds jobs

- [x] move those test builds to a separate tab https://ci.adoptopenjdk.net/view/Test_external_weekly/

- [x] remove trigger from upstream build https://github.com/AdoptOpenJDK/openjdk-build/pull/1075

**Comment by sophia-guo** [comment]
For now build is scheduled as 'H 20 * * 0'. If jobs can not be finished due to limited resources( 4 docker machines) will need to separate downstream jobs by either jdk version or impls.

**Comment by smlambert** [comment]
Of the new xLinux machines, the ubuntu ones appear to have docker installed on them... see https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1596/console run on https://ci.adoptopenjdk.net/computer/test-godaddy-ubuntu1604-x64-2/.  

I can add the docker label on those machines, if we check that all the ubuntu ones have it installed.

**Comment by sophia-guo** [comment]
Yes, all those new xLinux with ubuntu ones (test-godaddy-ubuntu1604-x64-1/2/3/4) have docker installed. However may not be installed correctly. Running test hit the https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/721

And I have tried rerun on those 4  machines and got the similar issue:

```
20:23:17       [exec] Step 5/12 : RUN apt-get update 	&& apt-get -y install 	apt-transport-https 	ca-certificates 	dirmngr 	curl 	git 	make 	unzip 	vim 	tar 	wget 	ant
20:23:17       [exec]  ---> Running in 2d31710bd87d
20:23:50       [exec] Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
20:23:50       [exec]   Could not connect to archive.ubuntu.com:80 (91.189.88.161), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.149), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.162), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.23), connection timed out
20:23:50       [exec] Err:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
```
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1599/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1598/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1597/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1596/console

**Comment by sophia-guo** [comment]
Done. Close it.
