### ISSUE TITLE
Parameterize openjdk sources used for testing

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-tests#1124]
This is somewhat related to https://github.com/AdoptOpenJDK/openjdk-tests/issues/1082

We'd like to automatically run the test pipeline on upstream OpenJDK hotspot Early Access (EA) builds so as to be able to automate consistent testing across platform specific builds and have test results available publicly.

While [get.sh](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/get.sh) has parameters for the JDK under test via `--sdk_resource customized` and `--customizedURL <url>`, the same is not possible for matching JDK sources. It is assumed the sources are in "sync" at AdoptOpenJDK/openjdk-jdkXu, where `X` is the JDK version like 8, 11, 12, etc. This assumption doesn't hold for EA upstream builds which have been built from sources *ahead* of the AdoptOpenJDK git mirrors. This is mostly an issue of running OpenJDK regression tests on customized builds.

In order to make this more flexible, I'd propose to implement something similar to `--sdk_resource` and `--customizedURL <url>`, but for JDK sources. Once that's implemented, Jenkins files could get enhanced to expose those new parameters. Then it should be possible to run the test pipeline on upstream builds automatically as soon as they become available at:
https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases and
https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases

**Comment by jerboaa** [comment]
@ShelleyLambert Thoughts? @stooke FYI

**Comment by smlambert** [comment]
Yes, I agree.  In #1082, I may have suggested exposing those parameters in the Jenkinsfile, but this is a good suggestion if we expose those parameters even earlier in get.sh, as it will allow for greater flexibility.

FYI @llxia @sophia-guo
