### ISSUE TITLE
Add Open Liberty for Performance Testing

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-tests#1127]
In order to measure performance for different workloads, we should use Open Liberty to run various apps such as DayTrader7 and AcmeAir on it. 

### About Open Liberty
Open Liberty is one of most flexible and popular server runtime available to Java developers.
https://openliberty.io/

### Runtime Requirement
Java SE 8, 11 and 12 are all compatible runtimes for Open Liberty.

### Benchmarks to Measure
DT7
AcmeAir
Others: To be declared

### Metrics to Measure
Startup Time
Footprint
Others: To be declared

### Assigned Contributor
I'll be working on adding Open Liberty with the support for various apps.

**Comment by piyush286** [comment]
Thanks Shelley for the reminder! I'll take a look at that issue first thing on Monday in case I don't get time today due to some perf blockers. Sorry for the delay!

**Comment by smlambert** [comment]
Was there anything left to do for this issue?

**Comment by piyush286** [comment]
Liberty DT7 startup and throughput have been added. Didn't get around to adding AcmeAir, but that's usually less popular, so we can close this. Thanks Shelley!
