### ISSUE TITLE
Test builds failing with Error running javac compiler

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#1130]
Recent test runs - e.g. this one at eclipse/openj9 - https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_windows_Release/4/console - are failing at the test build stage with
```
16:45:28  C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.system_x86-64_windows_Release\openjdk-tests\TestConfig\src\build_envInfo.xml:69: The following error occurred while executing this line:
16:45:28  C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.system_x86-64_windows_Release\openjdk-tests\TestConfig\src\build_envInfo.xml:42: Error running \javac compiler
```

**Comment by pshipton** [comment]
@renfeiw @llxia 

Lan indicated that https://github.com/eclipse/openj9/commit/ef65564225f6a7cde2a6437670eb99dceb63342f#diff-6bd0638039381a91233a57fba97b060e needs to be ported to the OpenJ9 v0.14.2-release branch.

**Comment by lumpfish** [comment]
Looks like this is the PR: https://github.com/eclipse/openj9/pull/5744 ?

**Comment by lumpfish** [comment]
Tests running OK again now, closing.
