### ISSUE TITLE
Perf Prerequisite: Allow Jenkins Daemon User to Kill Processes Without Requiring Password

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-tests#1137]
### Background
For perf testing, we need to make sure that no stale processes (i.e. unwanted, old or failed) are running to ensure that the machine isn't used for any other workload besides the currently running performance build. 

Hence, whenever we launch any performance job, we need to make sure that no other processes are running. If they are, benchmark script should kill those jobs before actually launching the benchmark run or measuring performance since any other running processes could taint the results. 

Since all the Jenkins and benchmark scripts are launched by Jenkins daemon user (i.e. user that's used for running the Jenkins daemon), that user should have the right privileges in order to kill other processes without requiring a password. 

### Problem Description
Currently, Jenkins daemon user doesn't seem to have the privilege to use `kill` utility.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1610/console
```
14:29:51  | Terminating Any Running Java Processes
14:29:51  
14:29:51  Local date: Tue May 14 18:29:50 UTC 2019
14:29:51  List of Java processes to terminate:
14:29:51  Killing: 9042
14:29:51  9852
14:29:51  10335
14:29:51  11018
14:29:51  11601
14:29:51  /home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/performance/liberty/scripts/bin/common_utils.sh: line 1816: kill: (9042) - Operation not permitted
...
...
14:30:42  Tue May 14 18:30:41 UTC 2019: Waiting 10s for JVMs to die
14:30:51  !!! WARNING !!! Could not terminate running Java processes. Exiting
```

### Easy Possible Solution
This might be a straight forward way though we can always explore other options if they are better. 
`<JENKINS_DAEMON_USER> ALL = NOPASSWD: <PATH_TO_KILL_UTILITY>/kill` 

I do understand the slight risk from the above solution. It's possible that someone could kill the Jenkins agent but I believe the Jenkins daemon reconnects quickly. Anyway, the benchmark scripts need to make sure that they are killing the right jobs.

We could extend this list for other tools such as `perf` for getting profiling benchmarks that require sudo access in future if needed. 

This requirement is just for all perf machines (label: `ci.role.perf`).

**Comment by smlambert** [comment]
There is no need to duplicate issues at openjdk-tests and openjdk-infrastructure, please close this one in favour of the infra issue you opened.

**Comment by piyush286** [comment]
@smlambert Sure thing! Sorry, I didn't mean to spam by opening 2 different issues.

I created this issue here since it's a prerequisite specific to this project/repo mainly and it might not be for other projects under Adopt. Though I do clearly understand that this work involves the infrastructure. Hence, I had opened a very specific issue for requesting this on 2 particular machines since those are the only perf machines available currently. 

Another incentive for opening this issue was to document the need for some prerequisite somewhere. I think it might be good to have the documentation for this project under this repo rather than infrastructure repo.  

The prerequisites mentioned in this issue and others aren't specific to one PR so it might be good to put this documentation somewhere where the following pull requests for other perf tests and infrastructure issues can refer to. Another alternative place for such documentation could be the Wiki but write access would be an issue. Another option could be to put it under `openjdk-tests/doc` but it might not be very flexible, documentation that would require a review though PR and something that won't be available to reference while opening some issue on the infrastructure repo.

I believe some prerequisites are common and don't need much explaination/documentation such as the ones here (https://github.com/eclipse/openj9/blob/master/test/docs/Prerequisites.md) but some of the perf ones such as this one might not be very self-explanatory and would need some justification. 

Anyway, I'm fine with whatever you might think would be a good way to add and maintain some documentation so please let me know what you might prefer :)
