### ISSUE TITLE
Perf Prerequisite: Install Software Testing Automation Framework (STAF)

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-tests#1138]
### Background

When running benchmarks that require more than one machine, it's crucial to have a reliable service that can allow the communication between those machines. There are several benchmarks such as Spark (Hibench) and Open Liberty with Daytrader that require at least two machines in order to conduct performance runs.

Software Testing Automation Framework (STAF) has several features and takes care of almost all problems for benchmarking using multiple machines. My team has been using this framework for quite sometime and it seems to be really helpful for setting up and running benchmarks. Once installed, machines don't require passwords to communicate with each other.

About STAF (http://staf.sourceforge.net/) : "The Software Testing Automation Framework (STAF) is an open source, multi-platform, multi-language framework designed around the idea of reusable components, called services (such as process invocation, resource management, logging, and monitoring). STAF removes the tedium of building an automation infrastructure, thus enabling you to focus on building your automation solution. The STAF framework provides the foundation upon which to build higher level solutions, and provides a pluggable approach supported across a large variety of platforms and languages."

### Alternative to STAF

We could possibly use SSH keys but they don't supply all the benefits of STAF. While SSH keys are simple to use for some basic things, STAF is way more convenient and user-friendly when it comes to running complex scenarios.

### Proposed Changes

Install STAF on all perf machines (label: ci.role.perf) so that perf machines can easily communicate with other perf machines while running a workload that requires several nodes.

**Comment by smlambert** [comment]
There is no need to duplicate issues at openjdk-tests and openjdk-infrastructure, please close this one in favour of the infra issue you opened.
