### ISSUE TITLE
False positive - openjdk8_j9_external_extended_lucene-solr_x86-64_linux

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1141]
https://ci.adoptopenjdk.net/view/Test_external_weekly/job/openjdk8_j9_external_extended_lucene-solr_x86-64_linux/57/console

02:56:26  BUILD FAILED
02:56:26  /lucene-solr/build.xml:21: The following error occurred while executing this line:
02:56:26  /lucene-solr/lucene/common-build.xml:297: Minimum supported Java version is 11.
02:56:26  

FYI @sophia-guo

**Comment by sophia-guo** [comment]
Currently for external tests 'build stage' is building the images and 'test stage' actually including 'building the project and testing'.  The error happened to 'test stage' building process, which setting the jenkins job as unstable should be fine. Though need to investigate why/when the project required Java 11 as minimum requirement. Note we haven't updated the test script recently.

**Comment by smlambert** [comment]
yes, I think its been not working for a while (note, the job's execution time is 6 min, but if actually runs tests, should be 1+ hour).

**Comment by sophia-guo** [comment]
We are getting the latest lucene-solr from github, which supports latest JDK version by default. So we need to update to support different jdk version based on different release tag, which is similar to what elasticsearch does.

**Comment by sophia-guo** [comment]
LUCENE-8738: Move to Java 11 as minimum Java version 
https://github.com/apache/lucene-solr/commit/faaee86efb01fa6e431fcb129cfb956c7d62d514#diff-19368e03d39aad04e99c31652e9827d6

According to this commit release tag before this time should be good with JDK 8. Will give it a try. In the meanwhile not sure if there is some document to have those information.

**Comment by smlambert** [comment]
We can add README to any test folder.  

Perhaps we add a section to https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/thirdparty_containers/README.md with a table on details/exceptions/versions or unique rules for sub-folders, or have each subfolder with its own README to document this info as you suggest.
