### ISSUE TITLE
Extract Short JDK Name 

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-tests#1144]
### Problem Description

Currently, we don't extract the JDK name while downloading a JDK in `getBinaryOpenjdk()` in `get.sh` as shown below. 

https://github.com/AdoptOpenJDK/openjdk-tests/blob/4865e8d913fb4f4a43307e6d8cfd400946ca0dc9/get.sh#L138-L188 

This one line info is pretty handy for displaying benchmark results since it doesn't take space for storing and can be easily used for querying data from the database for a build, without requiring to search multiple times for a specific build. 

This one line product info is also expected by the Test Result Summary Service for parsing and storing benchmark results for different builds as shown below.

https://github.com/AdoptOpenJDK/openjdk-test-tools/blob/858993efb7e454786dba984856ed454e3290bd26/TestResultSummaryService/parsers/BenchmarkParser.js#L8

While we do print the java version, it doesn't have the summarized info of the java stream, bit, platform, java implementation and date in one line. In fact, java version could be missing some info such as the platform info in the HotSpot java version as shown below.

**Example for OpenJ9 Java Version**
```
16:01:38  curl -OLJks --retry 5 --retry-delay 300  https://api.adoptopenjdk.net/v2/binary/nightly/openjdk8?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk&heap_size=normal
16:01:49  unzip file: OpenJDK8U-jdk_x64_linux_openj9_2019-05-21-11-05.tar.gz ...
16:01:51  Run /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java -version
16:01:52  openjdk version "1.8.0_222"
16:01:52  OpenJDK Runtime Environment (build 1.8.0_222-201905180358-b02)
16:01:52  Eclipse OpenJ9 VM (build master-72a537c81, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190518_311 (JIT enabled, AOT enabled)
16:01:52  OpenJ9   - 72a537c81
16:01:52  OMR      - 3172276c
16:01:52  JCL      - 7b46afb743 based on jdk8u222-b02)

```

**Example for HotSpot Java Version**
```
13:56:37  curl -OLJks --retry 5 --retry-delay 300  https://api.adoptopenjdk.net/v2/binary/nightly/openjdk8?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&type=jdk&heap_size=normal
13:56:47  unzip file: OpenJDK8U-jdk_x64_linux_hotspot_2019-05-21-11-05.tar.gz ...
13:56:48  Run /home/jenkins/workspace/Piyush-Grinder/openjdkbinary/j2sdk-image/bin/java -version
13:56:48  openjdk version "1.8.0_212"
13:56:48  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-201905180333-b03)
13:56:48  OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)
```

### Proposed Changes
We should extract the name from the downloaded binary and export it so that it's available for use in benchmark scripts and other places if needed.

For example, if we download `OpenJDK8U-jdk_x64_linux_openj9_2019-05-21-11-05.tar.gz`, then we should extract `OpenJDK8U-jdk_x64_linux_openj9_2019-05-21-11-05`.

Similarly, `OpenJDK8U-jdk_x64_linux_hotspot_2019-05-21-11-05.tar.gz` should give `OpenJDK8U-jdk_x64_linux_hotspot_2019-05-21-11-05`.

**Comment by llxia** [comment]
I think it is not a good idea to rely on the file name to determine SDK information such as java stream, platform, java implementation and date, etc. A filename may not have accurate information and it can be modified easily. Different sites are highly likely to have a different naming convention.

For example, the file generated from Openj9 is called `OpenJ9-JDK11-ppc64le_linux-20190524-022309.tar.gz`

**Comment by piyush286** [comment]
Yeah I do agree that the names could be different unless we're always pulling our builds from one place which might be consistently be sticking to one naming convention.

Anyway, I guess we can decide our own convention and use that to generate this short JDK name instead of parsing that info from the archive file name.

**Comment by piyush286** [comment]
Closing this issue since we've added support to dynamically get the JDK version and date on TRSS, which can be used in various tools such as Tabular View and Perf Compare.
