### ISSUE TITLE
jdk_math_jre tests fail on win32 openjdk8-openj9

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#1159]
jdk_math_jre tests are failing on win32 openjdk8-openj9 builds with the following message:
```
03:56:03  Error: JDK not found: C:\Users\jenkins\workspace\openjdk8_j9_openjdktest_x86-32_windows\openjdkbinary\j2re-image
```
e.g. https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_x86-32_windows/232/console.

Only affecting win32 openjdk8-openj9 builds, not other platforms and not win32 openjdk8-hotspot builds

**Comment by sophia-guo** [comment]
Job was configured as running against nightly sdk, which doesn't have jre jdk. Updated configuration.

Looks good. https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_x86-32_windows/238/console

Job failure status is due to jenkins issue.
