### ISSUE TITLE
openjdk8_j9_external_sanity_thorntail-mp-tck_x86-64_linux test failing

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#1161]
External test openjdk8_j9_external_sanity_thorntail-mp-tck_x86-64_linux is failing with:
```
11:22:07          [[1;34mINFO[m] 
11:22:07          [[1;34mINFO[m] -------------------------------------------------------
11:22:07          [[1;34mINFO[m]  T E S T S
11:22:07          [[1;34mINFO[m] -------------------------------------------------------
11:22:07          [[1;34mINFO[m] Running [1mTestSuite[m
11:22:07          Jun 02, 2019 10:21:46 AM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
11:22:07          WARNING: Failed downloading io/thorntail/bom/2.4.1.Final-SNAPSHOT/maven-metadata.xml from https://repo.gradle.org/gradle/libs-releases-local/. Reason: 
11:22:07          org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata io.thorntail:bom:2.4.1.Final-SNAPSHOT/maven-metadata.xml in gradle (https://repo.gradle.org/gradle/libs-releases-local)
11:22:07          Jun 02, 2019 10:21:47 AM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
11:22:07          WARNING: Failed downloading io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/. Reason: 
11:22:07          org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.thorntail:bom:pom:2.4.1.Final-SNAPSHOT from/to gradle (https://repo.gradle.org/gradle/libs-releases-local): Error transferring file: Server returned HTTP response code: 409 for URL: https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom
11:22:07          Jun 02, 2019 10:21:47 AM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
11:22:07          WARNING: Failed downloading io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/. Reason: 
11:22:07          org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.thorntail:bom:pom:2.4.1.Final-SNAPSHOT from/to gradle (https://repo.gradle.org/gradle/libs-releases-local): Error transferring file: Server returned HTTP response code: 409 for URL: https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom
11:22:07          Jun 02, 2019 10:21:48 AM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
11:22:07          WARNING: Failed downloading io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/. Reason: 
11:22:07          org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.thorntail:bom:pom:2.4.1.Final-SNAPSHOT from/to gradle (https://repo.gradle.org/gradle/libs-releases-local): Error transferring file: Server returned HTTP response code: 409 for URL: https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom
11:22:07          Jun 02, 2019 10:21:49 AM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
11:22:07          WARNING: Failed downloading io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/. Reason: 
11:22:07          org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.thorntail:bom:pom:2.4.1.Final-SNAPSHOT from/to gradle (https://repo.gradle.org/gradle/libs-releases-local): Error transferring file: Server returned HTTP response code: 409 for URL: https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom
11:22:07          Jun 02, 2019 10:21:49 AM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
11:22:07          WARNING: Failed downloading io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/. Reason: 
11:22:07          org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.thorntail:bom:pom:2.4.1.Final-SNAPSHOT from/to gradle (https://repo.gradle.org/gradle/libs-releases-local): Error transferring file: Server returned HTTP response code: 409 for URL: https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom
11:22:07          Jun 02, 2019 10:21:50 AM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
11:22:07          WARNING: Failed downloading io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/. Reason: 
11:22:07          org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.thorntail:bom:pom:2.4.1.Final-SNAPSHOT from/to gradle (https://repo.gradle.org/gradle/libs-releases-local): Error transferring file: Server returned HTTP response code: 409 for URL: https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom
11:22:07          Jun 02, 2019 10:21:50 AM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
11:22:07          WARNING: Failed downloading io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/. Reason: 
11:22:07          org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.thorntail:bom:pom:2.4.1.Final-SNAPSHOT from/to gradle (https://repo.gradle.org/gradle/libs-releases-local): Error transferring file: Server returned HTTP response code: 409 for URL: https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom
11:22:07          [[1;31mERROR[m] [1;31mTests [0;1mrun: [0;1m21[m, [1;31mFailures: [0;1;31m7[m, Errors: 0, [1;33mSkipped: [0;1;33m14[m, Time elapsed: 9.521 s[1;31m <<< FAILURE![m - in [1mTestSuite[m
11:22:07          [[1;31mERROR[m] arquillianBeforeClass(org.eclipse.microprofile.health.tck.MultipleProceduresFailedTest)  Time elapsed: 5.937 s  <<< FAILURE!
11:22:07          org.jboss.arquillian.container.spi.client.container.DeploymentException: 
11:22:07          Found 1 problems while building POM model from /thorntail/testsuite/microprofile-tcks/health/pom.xml
11:22:07          1/ [ERROR] Non-resolvable import POM: Failed to resolve POM for io.thorntail:bom:2.4.1.Final-SNAPSHOT due to Could not transfer artifact io.thorntail:bom:pom:2.4.1.Final-SNAPSHOT from/to gradle (https://repo.gradle.org/gradle/libs-releases-local): Error transferring file: Server returned HTTP response code: 409 for URL: https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom @ io.thorntail.testsuite:thorntail-microprofile-tck-health:2.4.1.Final-SNAPSHOT, /thorntail/testsuite/microprofile-tcks/health/pom.xml
```
e.g. https://ci.adoptopenjdk.net/job/openjdk8_j9_external_sanity_thorntail-mp-tck_x86-64_linux/65/console

hotspot tests are not seeing the same issue: https://ci.adoptopenjdk.net/job/openjdk8_hs_external_sanity_thorntail-mp-tck_x86-64_linux/72/consoleFull

Accessing the referenced URL https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pomi n a web browser returns
```
status | 409
message | "The repository 'libs-releases-local' rejected the resolution of an artifact 'libs-releases-local:io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom' due to conflict in the snapshot release handling policy."
```
I can't see why the openj9 tests would be trying to access the URL but not the hotspot tests.  @sophia-guo - any ideas?

**Comment by sophia-guo** [comment]
This should not be the reason that failed the openj9 tests. The hotspot tests also got the same access failures.
<img width="1319" alt="Screen Shot 2019-06-04 at 10 02 18 AM" src="https://user-images.githubusercontent.com/18030625/58885511-5a5e3400-86b0-11e9-8843-310aed887092.png">

**Comment by lumpfish** [comment]
Is that https://ci.adoptopenjdk.net/job/openjdk8_hs_external_sanity_thorntail-mp-tck_x86-64_linux/72/consoleFull ?  I can't see that time stamp (04:05:12) in that job?

**Comment by sophia-guo** [comment]
Yes, it is. It's at the end of the job. Loading takes time for consoleFull. Try this https://ci.adoptopenjdk.net/job/openjdk8_hs_external_sanity_thorntail-mp-tck_x86-64_linux/72/console

**Comment by lumpfish** [comment]
Well - end of that log for me says:
```
03:12:06  TAP Reports Processing: FINISH
[Pipeline] junit
03:12:06  Recording test results
[Pipeline] fileExists
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Finished: SUCCESS
```
I can only think some time zone magic is going on!

**Comment by lumpfish** [comment]
Anyway, elsewhere in the log I have found three occurrences similar to:
```
11:22:07          [[1;34mINFO[m] Building zip: /thorntail/boms/bom/target/bom-2.4.1.Final-SNAPSHOT-m2repo.zip
11:22:07          JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/06/02 10:20:06 - please wait.
11:22:07          JVMDUMP032I JVM requested System dump using '/thorntail/core.20190602.102006.28.0001.dmp' in response to an event
11:22:07          JVMPORT048E Failed to create system dump because a non-regular file "/thorntail/core" exists with the same name as the expected system dump file
11:22:07          JVMDUMP012E Error in System dump: /thorntail/core.20190602.102006.28.0001.dmp
11:22:07          JVMDUMP032I JVM requested Heap dump using '/thorntail/heapdump.20190602.102006.28.0002.phd' in response to an event
11:22:07          JVMDUMP010I Heap dump written to /thorntail/heapdump.20190602.102006.28.0002.phd
11:22:07          JVMDUMP032I JVM requested Java dump using '/thorntail/javacore.20190602.102006.28.0003.txt' in response to an event
11:22:07          JVMDUMP010I Java dump written to /thorntail/javacore.20190602.102006.28.0003.txt
11:22:07          JVMDUMP032I JVM requested Snap dump using '/thorntail/Snap.20190602.102006.28.0004.trc' in response to an event
11:22:07          JVMDUMP010I Snap dump written to /thorntail/Snap.20190602.102006.28.0004.trc
11:22:07          JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
```
which doesn't look good.

**Comment by lumpfish** [comment]
The output file attached to the failing job https://ci.adoptopenjdk.net/job/openjdk8_j9_external_sanity_thorntail-mp-tck_x86-64_linux/65 only contains the test stdout / stderr output, not the jvm dumps.  @sophia-guo - is that expected?

**Comment by smlambert** [comment]
From j9 console, results:
08:00:47          [[1;34mINFO[m] Results:
08:00:47          [[1;34mINFO[m] 
08:00:47          [[1;31mERROR[m] [1;31mFailures: [m
08:00:47          [[1;31mERROR[m] [1;31m  DelegateProcedureSuccessfulTest>Arquillian.arquillianBeforeClass:96 » Deployment[m
08:00:47          [[1;31mERROR[m] [1;31m  EnforceQualifierTest>Arquillian.arquillianBeforeClass:96 » Deployment Found 1 ...[m
08:00:47          [[1;31mERROR[m] [1;31m  HealthCheckResponseAttributesTest>Arquillian.arquillianBeforeClass:96 » Deployment[m
08:00:47          [[1;31mERROR[m] [1;31m  MultipleProceduresFailedTest>Arquillian.arquillianBeforeClass:96 » Deployment ...[m
08:00:47          [[1;31mERROR[m] [1;31m  NoProcedureSuccessfulTest>Arquillian.arquillianBeforeClass:96 » Deployment Fou...[m
08:00:47          [[1;31mERROR[m] [1;31m  SingleProcedureFailedTest>Arquillian.arquillianBeforeClass:96 » Deployment Fou...[m
08:00:47          [[1;31mERROR[m] [1;31m  SingleProcedureSuccessfulTest>Arquillian.arquillianBeforeClass:96 » Deployment[m
08:00:47          [[1;34mINFO[m] 
08:00:47          [[1;31mERROR[m] [1;31mTests run: 21, Failures: 7, Errors: 0, Skipped: 14[m
08:00:47          [[1;34mINFO[m] 
08:00:47          [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
08:00:47          [[1;34mINFO[m] [1mReactor Summary for MicroProfile TCK: Parent 2.4.1.Final-SNAPSHOT:[m
08:00:47          [[1;34mINFO[m] 
08:00:47          [[1;34mINFO[m] MicroProfile TCK: Parent ........................... [1;32mSUCCESS[m [  3.622 s]
08:00:47          [[1;34mINFO[m] MicroProfile TCK: Health ........................... [1;31mFAILURE[m [ 15.132 s]
08:00:47          [[1;34mINFO[m] MicroProfile TCK: Config ........................... [1;33mSKIPPED[m
08:00:47          [[1;34mINFO[m] MicroProfile TCK: JWT .............................. [1;33mSKIPPED[m
08:00:47          [[1;34mINFO[m] MicroProfile TCK: Metrics .......................... [1;33mSKIPPED[m
08:00:47          [[1;34mINFO[m] MicroProfile TCK: Fault Tolerance .................. [1;33mSKIPPED[m
08:00:47          [[1;34mINFO[m] MicroProfile TCK: RestClient ....................... [1;33mSKIPPED[m
08:00:47          [[1;34mINFO[m] MicroProfile TCK: OpenAPI .......................... [1;33mSKIPPED[m
08:00:47          [[1;34mINFO[m] MicroProfile TCK: OpenTracing ...................... [1;33mSKIPPED[m
08:00:47          [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
08:00:47          [[1;34mINFO[m] [1;31mBUILD FAILURE[m
08:00:47          [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
08:00:47          [[1;34mINFO[m] Total time:  29.171 s
08:00:47          [[1;34mINFO[m] Finished at: 2019-06-04T06:00:27Z
08:00:47          [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
08:00:47          [[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-surefire-plugin:2.22.0:test[m [1m(default-test)[m on project [36mthorntail-microprofile-tck-health[m: [1;31mThere are test failures.[m
08:00:47          [[1;31mERROR[m] [1;31m[m
08:00:47          [[1;31mERROR[m] [1;31mPlease refer to /thorntail/testsuite/microprofile-tcks/health/target/surefire-reports for the individual test results.[m
08:00:47          [[1;31mERROR[m] [1;31mPlease refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.[m
08:00:47          [[1;31mERROR[m] -> [1m[Help 1][m
08:00:47          [[1;31mERROR[m] 
08:00:47          [[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
08:00:47          [[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
08:00:47          [[1;31mERROR[m] 
08:00:47          [[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
08:00:47          [[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
08:00:47          [[1;31mERROR[m] 
08:00:47          [[1;31mERROR[m] After correcting the problems, you can resume the build with the command
08:00:47          [[1;31mERROR[m]   [1mmvn <goals> -rf :thorntail-microprofile-tck-health[m
08:00:47          
08:00:47          thorntail_microprofile_tck_0_FAILED
08:00:47      duration_ms: 1539777

From hs console results:
04:11:40  [[1;34mINFO[m] Results:
04:11:40  [[1;34mINFO[m] 
04:11:40  [[1;34mINFO[m] [1;32mTests run: 66, Failures: 0, Errors: 0, Skipped: 0[m
04:11:40  [[1;34mINFO[m] 
04:11:40  [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
04:11:40  [[1;34mINFO[m] [1mReactor Summary for MicroProfile TCK: Parent 2.4.1.Final-SNAPSHOT:[m
04:11:40  [[1;34mINFO[m] 
04:11:40  [[1;34mINFO[m] MicroProfile TCK: Parent ........................... [1;32mSUCCESS[m [  5.874 s]
04:11:40  [[1;34mINFO[m] MicroProfile TCK: Health ........................... [1;32mSUCCESS[m [05:22 min]
04:11:40  [[1;34mINFO[m] MicroProfile TCK: Config ........................... [1;32mSUCCESS[m [10:08 min]
04:11:40  [[1;34mINFO[m] MicroProfile TCK: JWT .............................. [1;32mSUCCESS[m [16:34 min]
04:11:40  [[1;34mINFO[m] MicroProfile TCK: Metrics .......................... [1;32mSUCCESS[m [44:48 min]
04:11:40  [[1;34mINFO[m] MicroProfile TCK: Fault Tolerance .................. [1;32mSUCCESS[m [  01:16 h]
04:11:40  [[1;34mINFO[m] MicroProfile TCK: RestClient ....................... [1;32mSUCCESS[m [53:03 min]
04:11:40  [[1;34mINFO[m] MicroProfile TCK: OpenAPI .......................... [1;32mSUCCESS[m [14:02 min]
04:11:40  [[1;34mINFO[m] MicroProfile TCK: OpenTracing ...................... [1;32mSUCCESS[m [07:05 min]
04:11:40  [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
04:11:40  [[1;34mINFO[m] [1;32mBUILD SUCCESS[m
04:11:40  [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
04:11:40  [[1;34mINFO[m] Total time:  03:47 h
04:11:40  [[1;34mINFO[m] Finished at: 2019-06-04T02:11:38Z
04:11:40  [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
04:11:40  microprofile tck testsuite finish
04:11:47  
04:11:47  thorntail_microprofile_tck_0_PASSED

**Comment by smlambert** [comment]
Believe you will have to recreate this failure locally and grab dump files from Docker image as we do not currently copy them out of the container to archive the artifacts.

**Comment by lumpfish** [comment]
I've rerun the test locally and see the following output:
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DelegateProcedureSuccessfulTest>Arquillian.arquillianBeforeClass:96 » Deployment
[ERROR]   EnforceQualifierTest>Arquillian.arquillianBeforeClass:96 » Deployment Found 1 ...
[ERROR]   HealthCheckResponseAttributesTest>Arquillian.arquillianBeforeClass:96 » Deployment
[ERROR]   MultipleProceduresFailedTest>Arquillian.arquillianBeforeClass:96 » Deployment ...
[ERROR]   NoProcedureSuccessfulTest>Arquillian.arquillianBeforeClass:96 » Deployment Fou...
[ERROR]   SingleProcedureFailedTest>Arquillian.arquillianBeforeClass:96 » Deployment Fou...
[ERROR]   SingleProcedureSuccessfulTest>Arquillian.arquillianBeforeClass:96 » Deployment
[INFO] 
[ERROR] Tests run: 21, Failures: 7, Errors: 0, Skipped: 14
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for MicroProfile TCK: Parent 2.4.1.Final-SNAPSHOT:
[INFO] 
[INFO] MicroProfile TCK: Parent ........................... SUCCESS [  7.887 s]
[INFO] MicroProfile TCK: Health ........................... FAILURE [ 32.266 s]
[INFO] MicroProfile TCK: Config ........................... SKIPPED
[INFO] MicroProfile TCK: JWT .............................. SKIPPED
[INFO] MicroProfile TCK: Metrics .......................... SKIPPED
[INFO] MicroProfile TCK: Fault Tolerance .................. SKIPPED
[INFO] MicroProfile TCK: RestClient ....................... SKIPPED
[INFO] MicroProfile TCK: OpenAPI .......................... SKIPPED
[INFO] MicroProfile TCK: OpenTracing ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```
The failing tests are all seeing the error 409 http response described in the issue description:
```
1/ [ERROR] Non-resolvable import POM: Failed to resolve POM for io.thorntail:bom:2.4.1.Final-SNAPSHOT due to Could not transfer artifact io.thorntail:bom:pom:2.4.1.Final-SNAPSHOT from/to gradle (https://repo.gradle.org/gradle/libs-releases-local): Error transferring file: Server returned HTTP response code: 409 for URL: https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.4.1.Final-SNAPSHOT/bom-2.4.1.Final-SNAPSHOT.pom @ io.thorntail.testsuite:thorntail-microprofile-tck-health:2.4.1.Final-SNAPSHOT, /thorntail/testsuite/microprofile-tcks/health/pom.xml

	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.loadPomFromFile(MavenWorkingSessionImpl.java:176)
	at org.jboss.shrinkwrap.resolver.impl.maven.task.LoadPomTask.execute(LoadPomTask.java:84)
	at org.jboss.shrinkwrap.resolver.impl.maven.PomlessResolveStageBaseImpl.loadPomFromFile(PomlessResolveStageBaseImpl.java:67)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenResolverSystemBaseImpl.loadPomFromFile(MavenResolverSystemBaseImpl.java:166)
	at org.wildfly.swarm.arquillian.adapter.MavenProfileLoader.loadPom(MavenProfileLoader.java:39)
	at org.wildfly.swarm.arquillian.adapter.MavenDependencyDeclarationFactory.create(MavenDependencyDeclarationFactory.java:37)
	at org.wildfly.swarm.arquillian.adapter.UberjarSimpleContainer.start(UberjarSimpleContainer.java:206)
	at org.wildfly.swarm.arquillian.adapter.WildFlySwarmContainer.deploy(WildFlySwarmContainer.java:82)
	... 104 more
```
I'll try rerunning with the same jdk build the test last passed on to see if the tests now fail with that build too.

**Comment by lumpfish** [comment]
I've confirmed that the test now fails with the same jdk build which previously passed here: https://ci.adoptopenjdk.net/job/openjdk8_j9_external_sanity_thorntail-mp-tck_x86-64_linux/40/console
So I assume something has changed in the test suite or its dependencies.

**Comment by sophia-guo** [comment]
Actually openj9 has never been passed the test. Thorntail-mp-tck test build has been updated to run tests taken from the MicroProfile TCKs instead of any other MicroProfile test. https://github.com/AdoptOpenJDK/openjdk-tests/pull/1117  The passing build https://ci.adoptopenjdk.net/job/openjdk8_j9_external_sanity_thorntail-mp-tck_x86-64_linux/40 was running the original Thorntail's own Mircorprofile tests.
