### ISSUE TITLE
Identify initial set of test targets for AQA v1.0 (July release)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1166]
Need to identify the set of specific test targets we will use initially with rationale for why, along with any exceptional cases/circumstances/exclusions to be documented.

Top-level targets for initial review:

sanity.openjdk
extended.openjdk 

sanity.system 
extended.system

special.functional

sanity.external

sanity.perf

could potentially consider sanity.functional dependent on https://github.com/eclipse/openj9/pull/6001

<img width="515" alt="Screen Shot 2019-06-07 at 9 46 56 AM" src="https://user-images.githubusercontent.com/2836948/59108591-45301200-8909-11e9-9ab0-e15a191b561f.png">

**Comment by karianna** [comment]
Is that a Milestone I see? ;-)

**Comment by smlambert** [comment]
haha, it was bound to happen sooner or later!  Beginning of the milestone era has arrived in openjdk-tests
