### ISSUE TITLE
Generate test jobs at ci.adoptopenjdk.net with new naming scheme

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1168]
Test jobs have been auto-generated at other projects/Jenkins servers (see https://github.com/AdoptOpenJDK/openjdk-tests/issues/890).  We will do similar at AdoptOpenJDK (taking on a new naming convention, to make more consistent across projects and make tooling like TRSS easier to write.

We want to create more types of nightly and weekly test jobs (as part of the AQA v1.0 deliverables in time for the July release).

This will need to be co-ordinated with a change in the build pipelines, which currently rely on the test job names to trigger launching.

In this issue, we will need to do the following:

- generate the jobs 

- verify they run

- change build pipelines to trigger newly generated jobs

- delete old test jobs

**Comment by smlambert** [comment]
Jobs generated:
- special.functional for openj9,hotspot jdk8
- sanity.perf, extended.perf for openj9,hotspot  jdk8,jdk11 x86-64_linux

**Comment by llxia** [comment]
Regenerated the above jobs without `_Nightly` suffix.

**Comment by llxia** [comment]
Once https://github.com/AdoptOpenJDK/openjdk-build/pull/1125 is merged, I will manually rename the top level external test job names to match with the new naming convention. For example, `openjdk11_hs_externaltest_x86-64_linux` will be renamed to `Test_openjdk11_hs_sanity.external_x86-64_linux`.

External test jobs cannot be auto-gened as they are the top-level test jobs and have special configuration.

**Comment by llxia** [comment]
External test jobs are renamed and top-level jobs configure are updated.
https://ci.adoptopenjdk.net/view/Test_external/

**Comment by smlambert** [comment]
Deleted the jobs that were generated with the unneeded suffixes.  I believe this can be closed now.
