### ISSUE TITLE
jdk_beans: ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Error: the child property type is not override the parent property type

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#117]
<pre>18:34:20 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Error: the child property type is not override the parent property type
18:34:20 REASON: Assumed action based on file name: run main Test8027648 
18:34:20 TIME:   0.807 seconds
18:34:20 messages:
18:34:20 command: main Test8027648
18:34:20 reason: Assumed action based on file name: run main Test8027648 
18:34:20 Mode: othervm
18:34:20 elapsed time (seconds): 0.807
18:34:20 configuration:
18:34:20 STDOUT:
18:34:20 STDERR:
18:34:20 java.lang.Error: the child property type is not override the parent property type
18:34:20 	at Test8027648.test(Test8027648.java:45)
18:34:20 	at Test8027648.main(Test8027648.java:38)
18:34:20 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:34:20 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:34:20 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:34:20 	at java.lang.reflect.Method.invoke(Method.java:498)
18:34:20 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
18:34:20 	at java.lang.Thread.run(Thread.java:748)
18:34:20 
18:34:20 JavaTest Message: Test threw exception: java.lang.Error: the child property type is not override the parent property type
18:34:20 JavaTest Message: shutting down test
18:34:20 
18:34:20 STATUS:Failed.`main' threw exception: java.lang.Error: the child property type is not override the parent property type
18:34:20 rerun:
18:34:20 HOME=/home/jenkins \
18:34:20 LANG=en_US.UTF-8 \
18:34:20 PATH=/bin:/usr/bin \
18:34:20 CLASSPATH=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/beans/Introspector/Test8027648.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/beans/Introspector:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
18:34:20     /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
18:34:20         -Dtest.src=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/beans/Introspector \
18:34:20         -Dtest.src.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/beans/Introspector \
18:34:20         -Dtest.classes=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/beans/Introspector/Test8027648.d \
18:34:20         -Dtest.class.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/beans/Introspector/Test8027648.d \
18:34:20         -Dtest.vm.opts='-ea -esa -Xmx512m' \
18:34:20         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
18:34:20         -Dtest.compiler.opts= \
18:34:20         -Dtest.java.opts= \
18:34:20         -Dtest.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:34:20         -Dcompile.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:34:20         -Dtest.timeout.factor=4.0 \
18:34:20         -ea \
18:34:20         -esa \
18:34:20         -Xmx512m \
18:34:20         com.sun.javatest.regtest.agent.MainWrapper /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/java/beans/Introspector/Test8027648.d/main.0.jta
18:34:20 
18:34:20 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Error: the child property type is not override the parent property type
</pre>
java/beans/Introspector/Test8027648.java
java/beans/PropertyEditor/6380849/TestPropertyEditor.java
java/beans/PropertyEditor/TestColorClass.java
java/beans/PropertyEditor/TestColorClassJava.java
java/beans/PropertyEditor/TestColorClassNull.java
java/beans/PropertyEditor/TestColorClassValue.java
java/beans/PropertyEditor/TestFontClass.java
java/beans/PropertyEditor/TestFontClassJava.java
java/beans/PropertyEditor/TestFontClassNull.java
java/beans/PropertyEditor/TestFontClassValue.java
java/beans/XMLEncoder/java_awt_ScrollPane.java

**Comment by akolarkunnu** [comment]
java/beans/PropertyEditor/TestFontClass.java
java/beans/PropertyEditor/TestFontClassJava.java
java/beans/PropertyEditor/TestFontClassNull.java
java/beans/PropertyEditor/TestFontClassValue.java

Above 4 test cases failed with :
Execution failed: `main' threw exception: java.lang.Error: could not find editor for class java.awt.Font 
java.lang.Error: could not find editor for class java.awt.Font
	at TestEditor.<init>(TestEditor.java:35)
	at TestFontClass.main(TestFontClass.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.lang.Thread.run(Thread.java:748)

**Comment by akolarkunnu** [comment]
java/beans/PropertyEditor/TestColorClass.java
java/beans/PropertyEditor/TestColorClassJava.java
java/beans/PropertyEditor/TestColorClassNull.java
java/beans/PropertyEditor/TestColorClassValue.java

Above 4 test cases failed with :
Execution failed: `main' threw exception: java.lang.Error: could not find editor for class java.awt.Color
java.lang.Error: could not find editor for class java.awt.Color
	at TestEditor.<init>(TestEditor.java:35)
	at TestColorClass.main(TestColorClass.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.lang.Thread.run(Thread.java:748)

**Comment by akolarkunnu** [comment]
It is related to https://github.com/AdoptOpenJDK/openjdk-tests/issues/49

**Comment by smlambert** [comment]
Closing as now listed in summary issue #346
