### ISSUE TITLE
jdk_nio: ACTION: main -- Error. Agent communication error: java.io.EOFException; check console log for any additional details

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#118]
19:02:51 ACTION: main -- Error. Agent communication error: java.io.EOFException; check console log for any additional details
19:02:51 REASON: Assumed action based on file name: run main Basic 
19:02:51 TIME:   4.596 seconds
19:02:51 messages:
19:02:51 command: main Basic
19:02:51 reason: Assumed action based on file name: run main Basic 
19:02:51 Mode: agentvm
19:02:51 Agent id: 0
19:02:51 elapsed time (seconds): 4.596
19:02:51 configuration:
19:02:51 Boot Layer
19:02:51   class path: /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
19:02:51               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
19:02:51               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
19:02:51 
19:02:51 Test Layer
19:02:51   class path: /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/java/nio/Buffer/Basic.d
19:02:51               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/Buffer
19:02:51 
19:02:51 rerun:
19:02:51 HOME=/home/jenkins \
19:02:51 LANG=en_US.UTF-8 \
19:02:51 PATH=/bin:/usr/bin \
19:02:51     /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
19:02:51         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/java/nio/Buffer/Basic.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/Buffer \
19:02:51         -Dtest.src=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/Buffer \
19:02:51         -Dtest.src.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/Buffer \
19:02:51         -Dtest.classes=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/java/nio/Buffer/Basic.d \
19:02:51         -Dtest.class.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/java/nio/Buffer/Basic.d \
19:02:51         -Dtest.vm.opts='-ea -esa -Xmx512m' \
19:02:51         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
19:02:51         -Dtest.compiler.opts= \
19:02:51         -Dtest.java.opts= \
19:02:51         -Dtest.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
19:02:51         -Dcompile.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
19:02:51         -Dtest.timeout.factor=4.0 \
19:02:51         -classpath /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/java/nio/Buffer/Basic.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/Buffer:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
19:02:51         Basic
19:02:51 
19:02:51 TEST RESULT: Error. Agent communication error: java.io.EOFException; check console log for any additional details

java/nio/Buffer/Basic.java
sun/nio/ch/TestMaxCachedBufferSize.java.TestMaxCachedBufferSize
sun/nio/cs/FindDecoderBugs.java.FindDecoderBugs
sun/nio/cs/FindEncoderBugs.java.FindEncoderBugs

**Comment by akolarkunnu** [comment]
These failures are not reproducible: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/158/testReport/

**Comment by akolarkunnu** [comment]
This tests are enabled by PR #237

**Comment by sophia-guo** [comment]
@akolarkunnu 
java/nio/Buffer/Basic.java still fails. It maybe a intermittent failure

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_linux/35/

**Comment by sophia-guo** [comment]
Test is "error" instead of "fail", will exclude it.

**Comment by smlambert** [comment]
Closing as stale.
