### ISSUE TITLE
Enable testing on OpenJ9 WindowsXL

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-tests#1194]
Windows XL builds were added via https://github.com/AdoptOpenJDK/openjdk-build/issues/1099. However the test jobs were not generated since we don't have machine capacity to run them in a timely manner. I'm opening this issue so it's not lost and testing does get enabled if/when we get the machine capacity.

**Comment by smlambert** [comment]
Adding to July milestone, pending more Windows machines available for test.

**Comment by smlambert** [comment]
Windows XL test jobs have now been generated:
https://ci.adoptopenjdk.net/view/all/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl/
https://ci.adoptopenjdk.net/view/all/job/Test_openjdk11_j9_sanity.system_x86-64_windows_xl/

https://ci.adoptopenjdk.net/view/all/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows_xl/
https://ci.adoptopenjdk.net/view/all/job/Test_openjdk11_j9_extended.system_x86-64_windows_xl/

https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_openjdk11_j9_sanity.perf_x86-64_windows_xl/
