### ISSUE TITLE
java/net/NetworkInterface/IPv4Only.java fails with openj9 jdk8 AIX

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1197]
java/net/NetworkInterface/IPv4Only.java fails with AIX openj9 jdk8. 

```
Standard Error

java.lang.RuntimeException: NetworkInterfaceV6List failed - found v6 address 0:0:0:0:0:0:0:1%lo0
	at IPv4Only.main(IPv4Only.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:819)

JavaTest Message: Test threw exception: java.lang.RuntimeException: NetworkInterfaceV6List failed - found v6 address 0:0:0:0:0:0:0:1%lo0
```
Note:
Test passed with openj9 jdk11 on AIX.

The test difference is

- JDK8:   'System.setProperty("java.net.preferIPv4Stack","true");'
- JDK11:  * @run main/othervm -Djava.net.preferIPv4Stack=true IPv4Only

Believe the test http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/8226f355c61c/test/java/net/NetworkInterface/IPv4Only.java should be updated as 'Setting the property at runtime won't have any affect if the net native libraries have already been loaded'

https://github.com/eclipse/openj9/issues/6266#issuecomment-505531856 Thanks @DanHeidinga for figuring it out.

**Comment by sophia-guo** [comment]
@karianna Could anyone help to report in JBS?

**Comment by karianna** [comment]
Have posted in #jbs channel in Adopt slack for a volunteer.

**Comment by jerboaa** [comment]
Filed as https://bugs.openjdk.java.net/browse/JDK-8226928

**Comment by sophia-guo** [comment]
Reported in JBS and didn't find in problemlist. Suppose has been fixed.
