### ISSUE TITLE
jdk11 openj9 Perf tests fail to build

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#1204]
Currently the "Perf" tests fail to build:
```
11:03:03  make[1]: Entering directory '/home/jenkins/workspace/openjdk11_j9_perftest_x86-64_linux/openjdk-tests'
11:03:03  make[1]: autoGen.mk: No such file or directory
11:03:03  make[1]: *** No rule to make target 'autoGen.mk'.  Stop.
11:03:03  make[1]: Leaving directory '/home/jenkins/workspace/openjdk11_j9_perftest_x86-64_linux/openjdk-tests'
11:03:03  settings.mk:281: recipe for target 'compile-..' failed
```
https://ci.adoptopenjdk.net/job/openjdk11_j9_perftest_x86-64_linux/265/console

**Comment by llxia** [comment]
This is due to folder rename - `performance` is changed to `perf`.
https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/perf

The Jenkins job configure is updated. It passed in my test build:
https://ci.adoptopenjdk.net/job/openjdk11_j9_perftest_x86-64_linux/266/

**Comment by llxia** [comment]
All openjdkXX_XX_perftest_XXX jobs are updated.

**Comment by smlambert** [comment]
thanks @llxia
