### ISSUE TITLE
sbt output includes 'junk' characters

### ISSUE THREAD

**Issue by hughesj** [AdoptOpenJDK/openjdk-tests#1209]
The scala language tests run using the `sbt` build tool. Here's an [example of the build output](https://ci.adoptopenjdk.net/view/Test_external_weekly/job/openjdk8_j9_external_extended_scala_x86-64_linux/63/consoleFull). Output such as:

```02:11:59  [0m[[0m[33mwarn[0m] [0m[0mthere were 22 deprecation warnings (since 2.13.0); re-run with -deprecation for details[0m```

can be improved by disabling colour output from `sbt` using the flag:

```-Dsbt.log.noformat=true```

Ref: https://stackoverflow.com/questions/44665301/sbt-output-in-jenkins-giving-junk-characters

**Comment by smlambert** [comment]
I will try it out [where we call sbt]( https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/scala/dockerfile/scala-test.sh#L48), thanks for the tip @hughesj
