### ISSUE TITLE
hotspot_jre: runtime/ErrorHandling/TestCrashOnOutOfMemoryError.java failed

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#121]
18:30:52 ACTION: build -- Not run. Test running...
18:30:52 REASON: User specified action: run build jdk.test.lib.* 
18:30:52 TIME:   .lib.* seconds
18:30:52 messages:
18:30:52 command: build jdk.test.lib.*
18:30:52 reason: User specified action: run build jdk.test.lib.* 
18:30:52 
18:30:52 TEST RESULT: Error. can't find jdk.test.lib.* in test directory or libraries

same issue for following tests:
runtime/ErrorHandling/TestCrashOnOutOfMemoryError.java
runtime/ErrorHandling/TestExitOnOutOfMemoryError.java

**Comment by akolarkunnu** [comment]
This is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8151295.

**Comment by smlambert** [comment]
Closing as now listed in summary issue #345

**Comment by zzambers** [comment]
Actually [JDK-8151295](https://bugs.openjdk.java.net/browse/JDK-8151295), was not backported to openjdk 8. New bug was created instead: [JDK-8218613](https://bugs.openjdk.org/browse/JDK-8218613).
