### ISSUE TITLE
Triage jdk8u222-b10_openj9-0.15.1

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#1227]
x64Mac_XL:
- sanity.openjdk : 7 failures => https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl/7/testReport/
    java/net/Inet6Address/B6206527.java.B6206527
    java/net/Inet6Address/B6558853.java.B6558853
    java/net/InetAddress/CheckJNI.java.CheckJNI
    java/net/Socket/LinkLocal.java.LinkLocal
    java/net/ipv6tests/B6521014.java.B6521014
    java/net/ipv6tests/TcpTest.java.TcpTest
    java/net/ipv6tests/UdpTest.java.UdpTest
These are most likely a known issue with testing on Mac10.14: https://github.com/eclipse/openj9/issues/6035
Same set (and more) fail with Hotspot : https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder_Advanced/330/testReport/

Win64:
- sanity.openjdk : 1 failure => https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows/6/
java/util/Locale/LocaleProviders.sh.LocaleProviders
    Passes locally, likely node issue : https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder_Advanced/334/console
- sanity.system : Pass
- extended.system : Pass

zLinux:
- sanity.openjdk : 1 failure => https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux/7/testReport/
java/nio/channels/Selector/LotsOfChannels.java.LotsOfChannels
- sanity.system : 8 failures => https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_s390x_linux/7/tapResults/
   Pass at ci.eclipse
- extended.system : Pass

AIX:
- sanity.openjdk : JOB failed (out of memory) ==> https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/2/
- sanity.system : JOB failed (out of memory) ==> https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_ppc64_aix/1/
- extended.system : JOB failed (out of memory) ==> https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_ppc64_aix/1/

**Comment by smlambert** [comment]
hi @andrew-m-leonard - if this triage effort is done (with relevant issues raised), can we close this?

**Comment by andrew-m-leonard** [comment]
yes closing
