### ISSUE TITLE
Triage jdk11.0.4_openj9-0.15.1

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#1229]
Triage for release runs found here:

https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/511/

Results of this issue to be copied into this issue by someone who has access:

https://github.com/AdoptOpenJDK/TSC/issues/99#issuecomment-512639394

**Comment by adamfarley** [comment]
**Windowsxl**
- sanity.openjdk

ReuseAddressTest.java - Address in use (likely non-blocking)
BitSetStreamTest.java - Unknown. Investigating.

03:25:48  test BitSetStreamTest.testRandomStream(): failure
03:25:48  java.lang.NullPointerException
03:25:48  	at BitSetStreamTest.testBitSetContents(BitSetStreamTest.java:238)
03:25:48  	at BitSetStreamTest.testRandomStream(BitSetStreamTest.java:227)
03:25:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:25:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:25:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:25:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
03:25:48  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
03:25:48  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
03:25:48  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
03:25:48  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
03:25:48  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
03:25:48  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
03:25:48  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
03:25:48  	at org.testng.TestRunner.run(TestRunner.java:623)
03:25:48  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
03:25:48  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
03:25:48  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
03:25:48  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
03:25:48  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
03:25:48  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
03:25:48  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
03:25:48  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
03:25:48  	at org.testng.TestNG.run(TestNG.java:1018)
03:25:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
03:25:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
03:25:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:25:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:25:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:25:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
03:25:48  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
03:25:48  	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by smlambert** [comment]
hi @adamfarley, has this triage effort completed (with relevant issues raised)?  If so, we can close this issue.

**Comment by adamfarley** [comment]
Hi @smlambert - Issues weren't raised for these at the time, as my focus was on identifying blockers for the release.

Many of these issues haven't been seen since, though one or two have. Will raise issues for, and exclude, the latter,

**Comment by adamfarley** [comment]
Triage progress:

**Windows xl**
- sanity.openjdk
  - ReuseAddressTest.java - Address in use (Likely non-blocking)
  - BitSetStreamTest.java - 

**x86-64_mac_xl**
- sanity.openjdk
  - BitSetStreamTest.java - 
  - AddNodeChangeListener.java, CheckUserPrefsStorage.sh, RemoveReadOnlyNode.java, and RemoveUnregedListener.java - 

**x86-64_mac**
- sanity.openjdk
  - ClassLoader/Assert.java - timeout (Likely non-blocking)
  - Promiscuous.java - Known (closed) issue: https://github.com/eclipse/openj9/issues/4128

- extended.system
  - SharedClasses.SCM23.MultiThread_0 - 
  - SharedClassesAPI_0 - 

**s390x_linux**
- sanity.openjdk
  - java/lang/StringBuffer/CompactStringBuffer.java 
  - java/net/httpclient/ConnectTimeoutNoProxyAsync.java - 
  - java/net/httpclient/ConnectTimeoutNoProxySync.java - 
  - java/net/httpclient/ConnectTimeoutWithProxyAsync.java - 
  - java/net/httpclient/ConnectTimeoutWithProxySync.java - 
  - java/nio/channels/Selector/LotsOfChannels.java - 
  - java/nio/channels/Selector/SelectWithConsumer.java -

**Comment by adamfarley** [comment]
Addendum: excluding the following tests from openJ9 runs on the relevant platforms until their issues are resolved: 

ClassLoader/Assert.java
Promiscuous.java
SharedClassesAPI_0
java/lang/StringBuffer/CompactStringBuffer.java

PR: (in progress)

Won't add the http tests until we're sure it's not just a temporary machine issue.
