### ISSUE TITLE
hotspot_jre: runtime/Final/PutfieldError.java failed with Error can't find  ***

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#123]
18:30:53 TEST: runtime/Final/PutfieldError.java
18:30:53 TEST JDK: /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../..
18:30:53 
18:30:53 ACTION: compile -- Error. can't find jasm
18:30:53 REASON: User specified action: run compile Bad.jasm 
18:30:53 TIME:   0.0 seconds
18:30:53 messages:
18:30:53 command: compile /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/Final/Bad.jasm
18:30:53 reason: User specified action: run compile Bad.jasm 
18:30:53 elapsed time (seconds): 0.0
18:30:53 configuration:
18:30:53 rerun:
18:30:53     /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/java \
18:30:53     -classpath  \
18:30:53     org.openjdk.asmtools.jasm.Main -d /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/runtime/Final/PutfieldError.d /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/Final/Bad.jasm
18:30:53 
18:30:53 TEST RESULT: Error. can't find jasm

test with same issue:
runtime/Final/PutfieldError.java can't find jasm
runtime/stackMapCheck/StackMapCheck.java   can't find jasm
runtime/classFileParserBug/BadNameAndType.java can't find jcoder
runtime/handlerInTry/LoadHandlerInTry.java can't find jasm

**Comment by akolarkunnu** [comment]
It is because asmtools.jar is missing in the jtreg/lib. asmtools.jar has to add in the classpath of jtreg MANIFEST.MF file.

**Comment by sophia-guo** [comment]
Tried with latest jtreg-4.2.0-tip.tar.gz. Works. The only concern is the latest jtreg-4.2.0-tip.tar.gz do not have jh.jar anymore. Not sure it's expected or not. The latest jtreg-4.2-b11.tar.gz do have both asmtools.jar and jh.jar.

**Comment by sophia-guo** [comment]
jtreg-4.2.0-tip.tar.gz updated https://ci.adoptopenjdk.net/job/jtreg/. Close this.
