### ISSUE TITLE
jdk_security: sun/security/pkcs11/Secmod/AddTrustedCert.java failed with `main' threw exception: java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_READ_ONLY

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#125]
19:58:21 ACTION: main -- Failed. Execution failed: `main' threw exception: java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_READ_ONLY
19:58:21 REASON: User specified action: run main/othervm AddTrustedCert 
19:58:21 TIME:   1.614 seconds
19:58:21 messages:
19:58:21 command: main AddTrustedCert
19:58:21 reason: User specified action: run main/othervm AddTrustedCert 
19:58:21 Mode: othervm [/othervm specified]
19:58:21 elapsed time (seconds): 1.614
19:58:21 configuration:
19:58:21 STDOUT:
19:58:21 SunPKCS11-NSSKeyStore version 1.8
19:58:21 entries: 1
19:58:21 [mykey]
19:58:21 first entry = Trusted certificate entry:
19:58:21 [
19:58:21 [
19:58:21   Version: V3
19:58:21   Subject: EMAILADDRESS=info@opentsa.org, CN=OpenTSA Root CA, O=OpenTSA, L=Dublin, ST=Co. Dublin, C=IE
19:58:21   Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5
19:58:21 
19:58:21   Key:  Sun RSA public key, 2048 bits
19:58:21   modulus: 28015647916364875829141896049677220882914191436294605577513377891910662717336292436491710471594406842772073838695462019009454723293288506992417485761129126311538268002377286178684649711932051555842344360775863345218752895239460508761587090794001550599392104457188635329925564746414056111210478603450167440907565077703922928621867939042884745257219423496925695838757642236269036957557147241224660577528253185760515264362748497612078896510637739121732184250485539505699485155279825000189178169555672844007672373755234739866676449460941418806853690713277829199399068163905100762713680303566487520616527043839846563616127
19:58:21   public exponent: 65537
19:58:21   Validity: [From: Thu Oct 17 20:51:34 UTC 2002,
19:58:21                To: Mon Oct 16 20:51:34 UTC 2006]
19:58:21   Issuer: EMAILADDRESS=info@opentsa.org, CN=OpenTSA Root CA, O=OpenTSA, L=Dublin, ST=Co. Dublin, C=IE
19:58:21   SerialNumber: [    00]
19:58:21 
19:58:21 Certificate Extensions: 6
19:58:21 [1]: ObjectId: 2.5.29.35 Criticality=false
19:58:21 AuthorityKeyIdentifier [
19:58:21 KeyIdentifier [

Tests with similar issue:
sun/security/pkcs11/Secmod/AddTrustedCert.java
sun/security/pkcs11/ec/TestECDH.java
sun/security/pkcs11/ec/TestECDSA.java
sun/security/pkcs11/ec/TestECGenSpec.java
sun/security/pkcs11/rsa/TestCACerts.java
sun/security/rsa/TestCACerts.java
tools/launcher/TestSpecialArgs.java
javax/crypto/CryptoPermission/CryptoPolicyFallback.java
javax/crypto/CryptoPermission/TestUnlimited.java

**Comment by smlambert** [comment]
@sophia-guo you can close old issues that I raised back in June as duplicates, as your issues are 'fresher'...  this is a duplicate of #69

**Comment by sophia-guo** [comment]
jdk_core is a super group of
jdk_core = \
    :jdk_lang \
    :jdk_util \
    :jdk_math \
    :jdk_io \
    :jdk_nio \
    :jdk_net \
    :jdk_rmi \
    :jdk_time \
    :jdk_security \
    :jdk_text \
    :core_tools \
    :jdk_other

Will adding core_tools and delete this group. Test build running time is expected to be one hour less. 

Update this failure tests to be under jdk_security.

**Comment by smlambert** [comment]
Thanks Sophia!

**Comment by sophia-guo** [comment]
core_tools is a subset of jdk_tools, which is enabled. Will just delete jdk_core group.

**Comment by akolarkunnu** [comment]
Fail reason for the below 3 test cases matches with the #70 

sun/security/pkcs11/ec/TestECDH.java
sun/security/pkcs11/ec/TestECDSA.java
sun/security/pkcs11/ec/TestECGenSpec.java

So removing these from bug description.

**Comment by akolarkunnu** [comment]
tools/launcher/TestSpecialArgs.java don't have any relation with this failure and it is not there in problem list, so removing that also from description.

**Comment by akolarkunnu** [comment]
The failures javax/crypto/CryptoPermission/CryptoPolicyFallback.java and javax/crypto/CryptoPermission/TestUnlimited.java are not reproducible.

**Comment by akolarkunnu** [comment]
Now all test failures except sun/security/pkcs11/Secmod/AddTrustedCert.java are tracking through different bug ids. And now it is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8180837

**Comment by smlambert** [comment]
Closing stale issues as they are not being addressed and fresh ones can/will be raised via nightly triage.
