### ISSUE TITLE
Remove wget calls from openjdk-tests scripts

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1250]
We currently use both curl and wget. To reduce the number of dependencies we have, we will shift to use only curl (since wget is not available on some platforms).

Search all build.xml files and support scripts to replace wget with curl calls.

**Comment by llxia** [comment]
Except for `external` folder, the only place left is in `perf` folder

https://github.com/AdoptOpenJDK/openjdk-tests/blob/2dfd08c5687e7d85db49717e9bf249394c02ea3c/perf/liberty/scripts/bin/database_utils.sh#L49

https://github.com/AdoptOpenJDK/openjdk-tests/blob/2dfd08c5687e7d85db49717e9bf249394c02ea3c/perf/liberty/scripts/bin/database_utils.sh#L63

**Comment by llxia** [comment]
The `wget` in TKG repo also needs to be removed:
https://github.com/AdoptOpenJDK/TKG/blob/899b2e59dc3389b3bef505d4bbee493b01c3eef2/scripts/getDependencies.pl#L237

**Comment by nikolamilijevic1** [comment]
@llxia here are all the remaining occurrences of `wget` in `openjdk-tests` as requested:
(note this is excluding docker files that download wget while downloading dependant executable files)
https://github.com/AdoptOpenJDK/openjdk-tests/blob/87e8885ed0428b4f4a2e4acd6acb1255180650c9/perf/liberty/scripts/bin/database_utils.sh#L45
https://github.com/AdoptOpenJDK/openjdk-tests/blob/87e8885ed0428b4f4a2e4acd6acb1255180650c9/perf/liberty/scripts/bin/database_utils.sh#L59
https://github.com/AdoptOpenJDK/openjdk-tests/blob/87e8885ed0428b4f4a2e4acd6acb1255180650c9/buildenv/jenkins/getDependency#L38
https://github.com/AdoptOpenJDK/openjdk-tests/blob/87e8885ed0428b4f4a2e4acd6acb1255180650c9/perf/liberty/scripts/resource/client_scripts/reset.sh#L52
https://github.com/AdoptOpenJDK/openjdk-tests/blob/87e8885ed0428b4f4a2e4acd6acb1255180650c9/perf/liberty/scripts/resource/client_scripts/configure.sh#L63
https://github.com/AdoptOpenJDK/openjdk-tests/blob/87e8885ed0428b4f4a2e4acd6acb1255180650c9/perf/liberty/scripts/resource/client_scripts/configure.sh#L90

**Comment by smlambert** [comment]
Only 3 places where wget is still used:
- in action.yml (on github action runners where its installed)
- in external tests run via Docker (where wget is installed)
- in perf/liberty shell scripts (in [database_utils.sh](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/perf/liberty/scripts/bin/database_utils.sh), [reset.sh](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/perf/liberty/scripts/resource/client_scripts/reset.sh), [configure.sh](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/perf/liberty/scripts/resource/client_scripts/configure.sh) scripts)

**Comment by smlambert** [comment]
This is likely as far as we are going to get with this one, closing.  If someone has the will to complete the rest, then it can be re-opened.
