### ISSUE TITLE
jdk11u build pipeline extended system test runs fail

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#1294]
All the extended system tests run by the build pipeline for the rerelease of jdk11u on MacOS failed with these messages:
```
Can't open perl script "/stf/stf.core/scripts/stf.pl": No such file or directory
```
Looks like something may be wrong with setting the test root directory which should prefix '/stf' in the playlist or testkitgen variables.
Job is https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac/25/console

**Comment by lumpfish** [comment]
The tests execute OK when I reran them as a Test_grinder job: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1925/console

**Comment by smlambert** [comment]
@lumpfish you have shared a link to jdk11 builds (jdk8 looks ok, https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_x86-64_mac/22/), should update the title of this issue to match.

FYI @Mesbah-Alam @llxia

**Comment by llxia** [comment]
The next jdk11 build is fine https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac/26/

**Comment by lumpfish** [comment]
Sorry - it should all have said jdk11, not jdk8.  Updated the title and comments.

Yes, follow on builds are ok, weird a parameter should go 'missing' though.

**Comment by smlambert** [comment]
that is odd... wonder if there were temporary changes in build pipeline code (maybe should look)?  we can keep this open for the next few runs, to make sure its not some strange intermittent behaviour

**Comment by sophia-guo** [comment]
Looks like build workspace is not clean  https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac/25/console

```
10:40:46  clean:
10:40:46     [delete] Deleting: /Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_mac/openjdk-tests/TestConfig/autoGenEnv.mk
10:40:46     [delete] Deleting directory /Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_mac/openjdk-tests/TestConfig/src/bin
10:40:46     [delete] Deleting: /Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_mac/openjdk-tests/TestConfig/src/EnvDetector.jar
```

In a clean build there should be those files.

My guess is because of this  TEST AUTO GEN  wasn't SUCCESSFUL.

```
10:42:52  Generating make file /Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_mac/openjdk-tests/TestConfig/scripts/testKitGen/../../../system/sharedClasses/autoGen.mk
10:42:52  
10:42:52  Generating make file /Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_mac/openjdk-tests/TestConfig/scripts/testKitGen/../../../system/autoGen.mk
10:42:52  
10:42:52  Generating make file /Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_mac/openjdk-tests/TestConfig/scripts/testKitGen/../../../systemtest/openj9-systemtest/openj9.build/autoGen.mk
10:42:52  perl scripts/tools/getDependencies.pl -path '/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_mac/openjdk-tests/TestConfig/../TestConfig/lib' -task default -os os.osx
...
```

Normally it should be 

```
05:13:01  Generating make file /Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../autoGen.mk
05:13:01  
05:13:01  Generated dependencies.mk
05:13:01  
05:13:01  Generated utils.mk
05:13:01  
05:13:01  Generated count.mk
05:13:01  
05:13:01  TEST AUTO GEN SUCCESSFUL
```

**Comment by karianna** [comment]
given #1299 Can this be closed now?

**Comment by sophia-guo** [comment]
I believe so. If happens again we can reopen or open a new one.
