### ISSUE TITLE
Non applicable tests for openjdk11-openj9 implementation

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1297]
These tests have been permanently excluded since they currently unsuitable for OpenJ9:
- https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/965d0c0df359f3da224b865701bbcc044b7104c2/test/jdk/java/lang/StackWalker/LocalsAndOperands.java#L1 as per https://github.com/eclipse/openj9/issues/6704
- https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/965d0c0df359f3da224b865701bbcc044b7104c2/test/jdk/java/lang/StackWalker/ReflectionFrames.java#L1 as per https://github.com/eclipse/openj9/issues/6724
- https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/965d0c0df359f3da224b865701bbcc044b7104c2/test/jdk/java/lang/invoke/ClassSpecializerTest.java#L1 as per https://github.com/eclipse/openj9/issues/6779

**Comment by adam-thorpe** [comment]
Can i suggest a change to this to help with readability; using the format:
java/lang/String/test1.java      [link to issue]

As it is quite hard to see which tests are in this list

**Comment by M-Davies** [comment]
Done 👍

**Comment by adam-thorpe** [comment]
jdk/internal/misc/TerminatingThreadLocal/TestTerminatingThreadLocal.java https://github.com/eclipse/openj9/issues/7167 11,13

**Comment by M-Davies** [comment]
I noticed that the links to the files were all pointing to JDK11 files and not their own implementations. This has been fixed

**Comment by adam-thorpe** [comment]
java/lang/Class/GetModuleTest.java on jdk11 and 13: https://github.com/eclipse/openj9/issues/3040

**Comment by adam-thorpe** [comment]
java/util/concurrent/atomic/VMSupportsCS8.java on jdk8 and 11: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1347

**Comment by adam-thorpe** [comment]
java/lang/ClassLoader/LibraryPathProperty.java on jdk11+ https://github.com/eclipse/openj9/issues/8440

**Comment by adam-thorpe** [comment]
java/util/logging/TestLoggerWeakRefLeak.java (all versions) https://github.com/AdoptOpenJDK/openjdk-tests/issues/1352

**Comment by smlambert** [comment]
Permanently excluding, java/util/WeakHashMap/GCDuringIteration.java (for jdk11+, https://github.com/eclipse/openj9/issues/10256) via #2083

**Comment by smlambert** [comment]
java/lang/StringBuilder/HugeCapacity.java (for jdk16, https://github.com/eclipse/openj9/issues/10582) via https://github.com/AdoptOpenJDK/openjdk-tests/pull/2141

**Comment by andrew-m-leonard** [comment]
Adding for jdk8 only:
```
com/sun/crypto/provider/Cipher/AES/TestAESCiphers/TestAESWithProviderChange.java
com/sun/crypto/provider/Cipher/AES/TestAESCiphers/TestAESWithRemoveAddProvider.java
```
Highlighted originally by issue: https://github.com/eclipse/openj9/issues/11614

**Comment by psoujany** [comment]
Excluding java/lang/management/MemoryMXBean/ResetPeakMemoryUsage on openj9 as this test is specific to hotspot.
Excluding the above on jdk11+.

**Comment by andrew-m-leonard** [comment]
- com/sun/jdi/JdbMethodExitTest.sh as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415
- com/sun/jdi/Redefine-g.sh as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415
- com/sun/jdi/AllLineLocations.java as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415
- com/sun/jdi/EarlyReturnTest.java as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415
- com/sun/jdi/MethodExitReturnValuesTest.java as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415
- com/sun/jdi/NativeInstanceFilter.java as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415
- com/sun/jdi/PopAndStepTest.java as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415
- com/sun/jdi/PopAsynchronousTest.java as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415
- com/sun/jdi/PopSynchronousTest.java as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415
- com/sun/jdi/RedefineCrossStart.java as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415
- com/sun/jdi/redefineMethod/RedefineTest.java as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/2415

**Comment by psoujany** [comment]
Excluding below tests as per #2422 
java/lang/management/ManagementFactory/ValidateOpenTypes.java
java/lang/management/MemoryMXBean/MemoryManagement.java
java/lang/management/ManagementFactory/ProxyTypeMapping.java
java/lang/management/MemoryMXBean/CollectionUsageThreshold.java
java/lang/management/MemoryMXBean/LowMemoryTest2.sh
java/lang/management/GarbageCollectorMXBean/GcInfoCompositeType.java
java/lang/management/CompositeData/MemoryUsageCompositeData.java
javax/management/remote/mandatory/connection/DefaultAgentFilterTest.java
sun/management/jmxremote/bootstrap/LocalManagementTest.java
sun/management/jmxremote/startstop/JMXStartStopTest.java
sun/management/jmxremote/startstop/JMXStatusPerfCountersTest.java
sun/management/jmxremote/startstop/JMXStatusTest.java
java/nio/channels/Selector/OutOfBand.java
java/nio/channels/FileChannel/directio/ReadDirect.java
java/nio/channels/FileChannel/directio/PreadDirect.java
java/nio/channels/FileChannel/directio/PwriteDirect.java
java/nio/channels/FileChannel/TempDirectBuffersReclamation.java

**Comment by psoujany** [comment]
Excluding below tests as per #2590 
java/lang/management/MemoryMXBean/MemoryManagementConcMarkSweepGC.sh
java/lang/management/MemoryMXBean/MemoryManagementParallelGC.sh
java/lang/management/MemoryMXBean/MemoryManagementSerialGC.sh
java/lang/management/MemoryMXBean/MemoryTestAllGC.sh
java/lang/management/MemoryMXBean/MemoryTest.java
java/lang/management/MemoryMXBean/LowMemoryTest.java
javax/management/Introspector/ClassLeakTest.java
java/lang/management/MemoryMXBean/MemoryTestZGC.sh

**Comment by psoujany** [comment]
Excluding below test on OpenJ9 for JDK11+ releases.
tools/launcher/MainClassCantBeLoadedTest.java

**Comment by psoujany** [comment]
Excluding below tests on OpenJ9 for JDK11+ releases.
com/sun/management/DiagnosticCommandMBean/DcmdMBeanDoubleInvocationTest.java
com/sun/management/DiagnosticCommandMBean/DcmdMBeanInvocationTest.java
com/sun/management/DiagnosticCommandMBean/DcmdMBeanPermissionsTest.java
com/sun/management/DiagnosticCommandMBean/DcmdMBeanTest.java

**Comment by psoujany** [comment]
Excluding below test as per runtimes/backlog/issues/795
sun/security/ssl/CipherSuite/DisabledCurve.java

**Comment by ChengJin01** [comment]
Excluding below test on OpenJ9 for JDK20 as per https://github.com/adoptium/aqa-tests/pull/4489 given `VaList` was removed in https://openjdk.org/jeps/442:
java/foreign/valist/VaListTest.java

**Comment by psoujany** [comment]
Excluding below test as per https://github.com/adoptium/aqa-tests/issues/4535
sun/security/pkcs12/KeytoolOpensslInteropTest.java

**Comment by psoujany** [comment]
Excluding below tests on z/OS for both JDK11 and JDK17
java/lang/management/MemoryMXBean/MemoryManagementConcMarkSweepGC.sh
java/lang/management/MemoryMXBean/MemoryManagementParallelGC.sh
java/lang/management/MemoryMXBean/MemoryManagementSerialGC.sh
java/lang/management/MemoryMXBean/MemoryTestAllGC.sh
java/lang/management/MemoryMXBean/MemoryTest.java
java/lang/management/MemoryMXBean/LowMemoryTest.java
javax/management/Introspector/ClassLeakTest.java
java/lang/management/MemoryMXBean/MemoryTestZGC.sh
com/sun/management/OperatingSystemMXBean/GetFreePhysicalMemorySize.java
java/nio/channels/FileChannel/directio/WriteDirect.java
java/nio/channels/DatagramChannel/Promiscuous.java
java/lang/management/MemoryMXBean/MemoryManagementConcMarkSweepGC.sh
java/lang/management/MemoryMXBean/MemoryManagementParallelGC.sh
java/lang/management/MemoryMXBean/MemoryManagementSerialGC.sh
java/lang/management/MemoryMXBean/MemoryTestAllGC.sh
java/lang/management/MemoryMXBean/MemoryTest.java
java/lang/management/MemoryMXBean/LowMemoryTest.java
javax/management/Introspector/ClassLeakTest.java
java/lang/management/MemoryMXBean/MemoryTestZGC.sh
com/sun/management/OperatingSystemMXBean/GetFreePhysicalMemorySize.java
java/nio/channels/FileChannel/directio/WriteDirect.java
java/nio/channels/DatagramChannel/Promiscuous.java

**Comment by psoujany** [comment]
Excluding below tests on JDK17 z/OS
java/foreign/SafeFunctionAccessTest.java
java/foreign/TestNative.java
java/foreign/TestSymbolLookup.java

**Comment by psoujany** [comment]
Excluding below tests on JDK17 z/OS
java/foreign/TestVarArgs.java
java/foreign/valist/VaListTest.java
java/foreign/virtual/TestVirtualCalls.java
javax/xml/crypto/dsig/SecureValidation.java

**Comment by llxia** [comment]
exclude javax/management/security/HashedPasswordFileTest.java as per https://github.com/eclipse-openj9/openj9/issues/20587#issuecomment-2479467441
