### ISSUE TITLE
Mac: jdk_security1: java/security/KeyStore/PKCS12/MetadataStoreLoadTest.java failed with `main' threw exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#130]
<pre>22:25:40 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Keytool Command execution failed : [/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/keytool, -debug, -genkeypair, -alias, testkey_metadata, -keystore, /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore/PKCS12/MetadataStoreLoadTest.d/ks.pkcs12, -dname, CN=TestKey, T=FuncTestCertKey, O=Oracle, OU=JDKSQE, C=US, -storepass, passwd, -keypass, passwd, -validity, 7300, -keyalg, rsa, -storetype, pkcs12]
22:25:40 REASON: User specified action: run main MetadataStoreLoadTest 
22:25:40 TIME:   1.015 seconds
22:25:40 messages:
22:25:40 command: main MetadataStoreLoadTest
22:25:40 reason: User specified action: run main MetadataStoreLoadTest 
22:25:40 Mode: agentvm
22:25:40 Agent id: 0
22:25:40 elapsed time (seconds): 1.015
22:25:40 configuration:
22:25:40 Boot Layer
22:25:40   class path: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
22:25:40               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
22:25:40               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
22:25:40 
22:25:40 Test Layer
22:25:40   class path: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore/PKCS12/MetadataStoreLoadTest.d
22:25:40               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/security/KeyStore/PKCS12
22:25:40               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/lib/testlibrary
22:25:40               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/lib/testlibrary
22:25:40               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore
22:25:40               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/security/KeyStore
22:25:40 
22:25:40 rerun:
22:25:40 HOME=/Users/jenkins \
22:25:40 PATH=/bin:/usr/bin \
22:25:40     /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
22:25:40         -Dtest.class.path.prefix=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore/PKCS12/MetadataStoreLoadTest.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/security/KeyStore/PKCS12:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/lib/testlibrary:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore \
22:25:40         -Dtest.src=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/security/KeyStore/PKCS12 \
22:25:40         -Dtest.src.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/security/KeyStore/PKCS12:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/lib/testlibrary:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/security/KeyStore \
22:25:40         -Dtest.classes=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore/PKCS12/MetadataStoreLoadTest.d \
22:25:40         -Dtest.class.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore/PKCS12/MetadataStoreLoadTest.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/lib/testlibrary:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore \
22:25:40         -Dtest.vm.opts='-ea -esa -Xmx512m' \
22:25:40         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
22:25:40         -Dtest.compiler.opts= \
22:25:40         -Dtest.java.opts= \
22:25:40         -Dtest.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
22:25:40         -Dcompile.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
22:25:40         -Dtest.timeout.factor=4.0 \
22:25:40         -classpath /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore/PKCS12/MetadataStoreLoadTest.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/security/KeyStore/PKCS12:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/lib/testlibrary:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/lib/testlibrary:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/security/KeyStore:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
22:25:40         MetadataStoreLoadTest
22:25:40 STDOUT:
22:25:40 Command line: [/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/keytool -debug -genkeypair -alias testkey_metadata -keystore /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore/PKCS12/MetadataStoreLoadTest.d/ks.pkcs12 -dname CN=TestKey, T=FuncTestCertKey, O=Oracle, OU=JDKSQE, C=US -storepass passwd -keypass passwd -validity 7300 -keyalg rsa -storetype pkcs12]
22:25:40 --- ProcessLog ---
22:25:40 cmd: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/keytool -debug -genkeypair -alias testkey_metadata -keystore /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore/PKCS12/MetadataStoreLoadTest.d/ks.pkcs12 -dname CN=TestKey, T=FuncTestCertKey, O=Oracle, OU=JDKSQE, C=US -storepass passwd -keypass passwd -validity 7300 -keyalg rsa -storetype pkcs12
22:25:40 exitvalue: 1
22:25:40 stderr: Exception in thread "main" java.lang.Exception: Key pair not generated, alias <testkey_metadata> already exists
22:25:40 	at sun.security.tools.keytool.Main.doGenKeyPair(Main.java:1597)
22:25:40 	at sun.security.tools.keytool.Main.doCommands(Main.java:966)
22:25:40 	at sun.security.tools.keytool.Main.run(Main.java:343)
22:25:40 	at sun.security.tools.keytool.Main.main(Main.java:336)
22:25:40 
22:25:40 stdout: keytool error: java.lang.Exception: Key pair not generated, alias <testkey_metadata> already exists
22:25:40 
22:25:40 
22:25:40 keytool error: java.lang.Exception: Key pair not generated, alias <testkey_metadata> already exists
22:25:40 Exception in thread "main" java.lang.Exception: Key pair not generated, alias <testkey_metadata> already exists
22:25:40 	at sun.security.tools.keytool.Main.doGenKeyPair(Main.java:1597)
22:25:40 	at sun.security.tools.keytool.Main.doCommands(Main.java:966)
22:25:40 	at sun.security.tools.keytool.Main.run(Main.java:343)
22:25:40 	at sun.security.tools.keytool.Main.main(Main.java:336)
22:25:40 
22:25:40 STDERR:
22:25:40  stdout: [keytool error: java.lang.Exception: Key pair not generated, alias <testkey_metadata> already exists
22:25:40 ];
22:25:40  stderr: [Exception in thread "main" java.lang.Exception: Key pair not generated, alias <testkey_metadata> already exists
22:25:40 	at sun.security.tools.keytool.Main.doGenKeyPair(Main.java:1597)
22:25:40 	at sun.security.tools.keytool.Main.doCommands(Main.java:966)
22:25:40 	at sun.security.tools.keytool.Main.run(Main.java:343)
22:25:40 	at sun.security.tools.keytool.Main.main(Main.java:336)
22:25:40 ]
22:25:40  exitValue = 1
22:25:40 
22:25:40 java.lang.RuntimeException: Expected to get exit value of [0]
22:25:40 
22:25:40 	at jdk.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:361)
22:25:40 	at Utils.executeKeytoolCommand(Utils.java:68)
22:25:40 	at Utils.createKeyStore(Utils.java:108)
22:25:40 	at Utils.createKeyStore(Utils.java:87)
22:25:40 	at Utils.createKeyStore(Utils.java:81)
22:25:40 	at MetadataStoreLoadTest.setUp(MetadataStoreLoadTest.java:123)
22:25:40 	at MetadataStoreLoadTest.main(MetadataStoreLoadTest.java:117)
22:25:40 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:25:40 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:25:40 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:25:40 	at java.lang.reflect.Method.invoke(Method.java:498)
22:25:40 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
22:25:40 	at java.lang.Thread.run(Thread.java:748)
22:25:40 java.lang.RuntimeException: Keytool Command execution failed : [/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/keytool, -debug, -genkeypair, -alias, testkey_metadata, -keystore, /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore/PKCS12/MetadataStoreLoadTest.d/ks.pkcs12, -dname, CN=TestKey, T=FuncTestCertKey, O=Oracle, OU=JDKSQE, C=US, -storepass, passwd, -keypass, passwd, -validity, 7300, -keyalg, rsa, -storetype, pkcs12]
22:25:40 	at Utils.executeKeytoolCommand(Utils.java:74)
22:25:40 	at Utils.createKeyStore(Utils.java:108)
22:25:40 	at Utils.createKeyStore(Utils.java:87)
22:25:40 	at Utils.createKeyStore(Utils.java:81)
22:25:40 	at MetadataStoreLoadTest.setUp(MetadataStoreLoadTest.java:123)
22:25:40 	at MetadataStoreLoadTest.main(MetadataStoreLoadTest.java:117)
22:25:40 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:25:40 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:25:40 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:25:40 	at java.lang.reflect.Method.invoke(Method.java:498)
22:25:40 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
22:25:40 	at java.lang.Thread.run(Thread.java:748)
22:25:40 Caused by: java.lang.RuntimeException: Expected to get exit value of [0]
22:25:40 
22:25:40 	at jdk.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:361)
22:25:40 	at Utils.executeKeytoolCommand(Utils.java:68)
22:25:40 	... 11 more
22:25:40 
22:25:40 JavaTest Message: Test threw exception: java.lang.RuntimeException
22:25:40 JavaTest Message: shutting down test
22:25:40 
22:25:40 
22:25:40 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Keytool Command execution failed : [/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/keytool, -debug, -genkeypair, -alias, testkey_metadata, -keystore, /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/security/KeyStore/PKCS12/MetadataStoreLoadTest.d/ks.pkcs12, -dname, CN=TestKey, T=FuncTestCertKey, O=Oracle, OU=JDKSQE, C=US, -storepass, passwd, -keypass, passwd, -validity, 7300, -keyalg, rsa, -storetype, pkcs12]
</pre>

Similar testcases failed;
java/security/KeyStore/PKCS12/MetadataStoreLoadTest.java
java/security/KeyStore/PKCS12/StoreTrustedCertAPITest.java
java/security/KeyStore/PKCS12/StoreTrustedCertKeytool.java

**Comment by akolarkunnu** [comment]
I rerun these test cases on mac, and not able to reproduce. On linux these already pass on test CI.

**Comment by akolarkunnu** [comment]
Created a PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/219

**Comment by akolarkunnu** [comment]
It resolved by PR #219
