### ISSUE TITLE
test jobs cleans up

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1307]
Test jobs configured by jenkins pipeline under this repo need some clean up

1. Obsolete jobs need to be removed -- note due to the permission jobs needs to be removed by person with permission
2. Working Jobs need to do the clean up by themselves 
          

- [x]  jobs generated by [jobTemplate]( https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate) - Done #1299

- [ ] jobs manually generated using [jenkins pipeline](https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/buildenv/jenkins) - if possible switch to generate by jobTemplate. If job name changes remove obsolete jobs. If not manually update job configuration with 'Clean before checkout' solution

**Comment by smlambert** [comment]
In our Monday meeting, I think we found and deleted most test jobs that needed removal.

**Comment by karianna** [comment]
@smlambert can this be closed now?

**Comment by smlambert** [comment]
@sophia-guo - for the 2nd point in this issue, I think that refers to the extended.external targets, is there still an outstanding action for this issue?

**Comment by sophia-guo** [comment]
Thanks @smlambert for #1340 and rename jobs at https://ci.adoptopenjdk.net/view/Test_upstream/. I will re-generate those tests so they do cleanup workspace by themselves with history remains.

**Comment by sophia-guo** [comment]
All existing jobs under https://ci.adoptopenjdk.net/view/Test_functional/ are regenerated with self cleanup. There are a few jobs should be deleted:

https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_hs_special.functional_s390x_zos/
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_hs_special.functional_x86-64_linux_xl/
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_hs_special.functional_x86-64_mac_xl/
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_j9_special.functional_x86-32_windows/
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_j9_sanity.functional_x86-32_windows/
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_j9_extended.functional_x86-32_windows/
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_hs_special.functional_x86-64_mac_xl/
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_j9_special.functional_aarch64_linux/
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_j9_extended.functional_aarch64_linux/
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_j9_sanity.functional_aarch64_linux/

Once those jobs are deleted we can close this issue.

**Comment by smlambert** [comment]
Jobs listed above are now deleted, thanks @sophia-guo !
