### ISSUE TITLE
mac: jdk_jdi : com/sun/jdi/* failed with Execution failed: `main' threw exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#132]
<pre>
21:18:49 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.NullPointerException
21:18:49 REASON: User specified action: run main/othervm RedefineTest 
21:18:49 TIME:   0.636 seconds
21:18:49 messages:
21:18:49 command: main RedefineTest
21:18:49 reason: User specified action: run main/othervm RedefineTest 
21:18:49 Mode: othervm [/othervm specified]
21:18:49 elapsed time (seconds): 0.636
21:18:49 configuration:
21:18:49 STDOUT:
21:18:49 ERROR: transport error 202: gethostbyname: unknown host
21:18:49 ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
21:18:49 JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
21:18:49 STDERR:
21:18:49 run args: [RedefineTarg]
21:18:49 VM initialization failed for: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/java -classpath /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/com/sun/jdi/redefine/RedefineTest.d -Xdebug -Xrunjdwp:transport=dt_socket,address=DXU773:62846,suspend=y RedefineTarg
21:18:49 
21:18:49 
21:18:49  Target VM failed to initialize.
21:18:49 java.lang.NullPointerException
21:18:49 	at VMConnection.open(VMConnection.java:196)
21:18:49 	at TestScaffold.connect(TestScaffold.java:632)
21:18:49 	at TestScaffold.startUp(TestScaffold.java:363)
21:18:49 	at TestScaffold.startTo(TestScaffold.java:373)
21:18:49 	at TestScaffold.startToMain(TestScaffold.java:368)
21:18:49 	at RedefineTest.runTests(RedefineTest.java:274)
21:18:49 	at TestScaffold.startTests(TestScaffold.java:429)
21:18:49 	at RedefineTest.main(RedefineTest.java:79)
21:18:49 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:18:49 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:18:49 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:18:49 	at java.lang.reflect.Method.invoke(Method.java:498)
21:18:49 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
21:18:49 	at java.lang.Thread.run(Thread.java:748)
21:18:49 
21:18:49 JavaTest Message: Test threw exception: java.lang.NullPointerException
21:18:49 JavaTest Message: shutting down test
21:18:49 
21:18:49 STATUS:Failed.`main' threw exception: java.lang.NullPointerException
21:18:49 rerun:
21:18:49 HOME=/Users/jenkins \
21:18:49 PATH=/bin:/usr/bin \
21:18:49 CLASSPATH=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/com/sun/jdi/redefine/RedefineTest.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/com/sun/jdi/redefine:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/com/sun/jdi:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/com/sun/jdi:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
21:18:49     /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
21:18:49         -Dtest.class.path.prefix=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/com/sun/jdi/redefine/RedefineTest.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/com/sun/jdi/redefine:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/com/sun/jdi \
21:18:49         -Dtest.src=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/com/sun/jdi/redefine \
21:18:49         -Dtest.src.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/com/sun/jdi/redefine:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/com/sun/jdi \
21:18:49         -Dtest.classes=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/com/sun/jdi/redefine/RedefineTest.d \
21:18:49         -Dtest.class.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/com/sun/jdi/redefine/RedefineTest.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/com/sun/jdi \
21:18:49         -Dtest.vm.opts='-ea -esa -Xmx512m' \
21:18:49         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
21:18:49         -Dtest.compiler.opts= \
21:18:49         -Dtest.java.opts= \
21:18:49         -Dtest.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
21:18:49         -Dcompile.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
21:18:49         -Dtest.timeout.factor=4.0 \
21:18:49         -ea \
21:18:49         -esa \
21:18:49         -Xmx512m \
21:18:49         com.sun.javatest.regtest.agent.MainWrapper /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/com/sun/jdi/redefine/RedefineTest.d/main.0.jta
21:18:49 
21:18:49 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.NullPointerException
</pre>

90 testcases have same issue:
com/sun/jdi/*
com/sun/jdi/connect/spi/DebugUsingCustomConnector.java
com/sun/jdi/oom/OomDebugTest.java
com/sun/jdi/redefine/RedefineTest.java
com/sun/jdi/redefineMethod/RedefineTest.java
com/sun/jdi/sde/FilterMangleTest.java
com/sun/jdi/sde/MangleStepTest.java
com/sun/jdi/sde/MangleTest.java
com/sun/jdi/sde/SourceDebugExtensionTest.java
com/sun/jdi/sde/TemperatureTableTest.java

**Comment by akolarkunnu** [comment]
It's a machine configuration issue. 
1) Assign a host name to the machine by following below steps:
    - Choose Apple menu -> System Preferences, then click Sharing).
    - Click Edit, then enter a local hostname.
2) Add this machine name entry in /etc/hosts file with machine ip address.
    Eg:  127.0.0.1       mymachine
3) Reboot the machine to reflect the changes.

**Comment by smlambert** [comment]
I reran the tests that we hoped would be fixed by https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/131 just now (on test-macincloud-macos1010-1), but they still fail:

ERROR: transport error 202: gethostbyname: unknown host
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]

You can find the entire set of test results here: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/129/testReport/

**Comment by akolarkunnu** [comment]
It resolved by PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/226
