### ISSUE TITLE
JTReg Test Failure: java/util/concurrent/atomic/VMSupportsCS8.java

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-tests#1347]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/497/
Version: 8 and 11 only
Platform: all

Test throws a NullPointerException when running the line: `System.getProperty("sun.cpu.isalist")`. This is caused when there is no property with that key (per  https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/System.html#getProperty(java.lang.String) )
When the line is removed, and the other part of the OR statement is taken, the test passes (see below). Therefore I believe this to be a problem with the test.
This test does seem to pass on 13 so not sure if the functionality of getProperty was changed and not reflected in javadoc.

Test:
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/2d77cb2d93340eb234ef7e6563cfa858fd133aec/test/jdk/java/util/concurrent/atomic/VMSupportsCS8.java#L36

Error:
```
java.lang.NullPointerException
15:47:05  	at VMSupportsCS8.main(VMSupportsCS8.java:37)
15:47:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:47:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:47:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:47:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:47:05  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
15:47:05  	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by smlambert** [comment]
Does this only affect openj9?  Is there a plan to update the upstream test material?  If not, should it be considered hotspot specific test and go into the exclude permanently bucket?

**Comment by adam-thorpe** [comment]
Yes this is just openj9. Had a dig and couldn't see any references to the test in jbs so I assume not? So yeah this can be permanently excluded and added to the list

**Comment by adam-thorpe** [comment]
Hang on sorry, the test was changed and fixed in JDK12+ https://bugs.openjdk.java.net/browse/JDK-8185496 although I don't see any sign of a plan to backport the change
