### ISSUE TITLE
mac : jdk_bean : tests failed with `main' threw exception: different exception

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#135]
example
<pre>
18:49:08 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Error: could not find editor for class java.awt.Color
18:49:08 REASON: Assumed action based on file name: run main TestColorClassValue 
18:49:08 TIME:   1.34 seconds
18:49:08 messages:
18:49:08 command: main TestColorClassValue
18:49:08 reason: Assumed action based on file name: run main TestColorClassValue 
18:49:08 Mode: othervm
18:49:08 elapsed time (seconds): 1.34
18:49:08 configuration:
18:49:08 STDOUT:
18:49:08 Property class: class java.awt.Color
18:49:08 STDERR:
18:49:08 java.lang.Error: could not find editor for class java.awt.Color
18:49:08 	at TestEditor.<init>(TestEditor.java:35)
18:49:08 	at TestColorClassValue.main(TestColorClassValue.java:35)
18:49:08 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:49:08 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:49:08 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:49:08 	at java.lang.reflect.Method.invoke(Method.java:498)
18:49:08 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
18:49:08 	at java.lang.Thread.run(Thread.java:748)
18:49:08 
18:49:08 JavaTest Message: Test threw exception: java.lang.Error: could not find editor for class java.awt.Color
18:49:08 JavaTest Message: shutting down test
18:49:08 
18:49:08 STATUS:Failed.`main' threw exception: java.lang.Error: could not find editor for class java.awt.Color
18:49:08 rerun:
18:49:08 HOME=/Users/jenkins \
18:49:08 PATH=/bin:/usr/bin \
18:49:08 CLASSPATH=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/beans/PropertyEditor/TestColorClassValue.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/beans/PropertyEditor:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
18:49:08     /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
18:49:08         -Dtest.src=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/beans/PropertyEditor \
18:49:08         -Dtest.src.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/beans/PropertyEditor \
18:49:08         -Dtest.classes=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/beans/PropertyEditor/TestColorClassValue.d \
18:49:08         -Dtest.class.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/java/beans/PropertyEditor/TestColorClassValue.d \
18:49:08         -Dtest.vm.opts='-ea -esa -Xmx512m' \
18:49:08         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
18:49:08         -Dtest.compiler.opts= \
18:49:08         -Dtest.java.opts= \
18:49:08         -Dtest.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:49:08         -Dcompile.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:49:08         -Dtest.timeout.factor=4.0 \
18:49:08         -ea \
18:49:08         -esa \
18:49:08         -Xmx512m \
18:49:08         com.sun.javatest.regtest.agent.MainWrapper /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/java/beans/PropertyEditor/TestColorClassValue.d/main.0.jta
</pre>

**Comment by smlambert** [comment]
Could not find editor for class java.awt.Color - is this a machine configuration issue, what editor does this test expect to find?

**Comment by akolarkunnu** [comment]
It is related to #117

**Comment by akolarkunnu** [comment]
It is related to https://github.com/AdoptOpenJDK/openjdk-tests/issues/49

**Comment by smlambert** [comment]
Closing as now listed in summary issue #346
