### ISSUE TITLE
"well-known file is not secure" causing failures in numerous tests 

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/openjdk-tests#1353]
This failure seems to have come up on a number of other issues:

https://github.com/AdoptOpenJDK/openjdk-tests/issues/1267
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1259

 Just caused a failure in https://ci.adoptopenjdk.net/job/Test_openjdk13_hs_extended.system_x86-64_mac/52/console

```
19:40:13  AG  11:40:13 > Attach will be done using agent jar file: /Users/jenkins/workspace/Test_openjdk13_hs_extended.system_x86-64_mac/jvmtest/system/openjdk-systemtest/openjdk.test.debugging/bin/StringModifierAgent.jar
19:40:14  AG  stderr Exception in thread "main" java.io.IOException: well-known file /var/folders/qb/mpy9xj1x7gd4v0vpwrc6c36m0000gr/T/.java_pid89377 is not secure: file's group should be the current group (which is -1) but the group is 0
19:40:14  AG  stderr 	at jdk.attach/sun.tools.attach.VirtualMachineImpl.checkPermissions(Native Method)
19:40:14  AG  stderr 	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:108)
19:40:14  AG  stderr 	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
19:40:14  AG  stderr 	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
19:40:14  AG  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:70)
19:40:14  STF 11:40:14.255 - **FAILED** Process AG  ended with exit code (1) and not the expected exit code/s (0)
```

**Comment by smlambert** [comment]
We have seen this failure across many tests, seems specific to Mac builds/machines.  Will need to narrow down if its just on a particular machine or osx version.

**Comment by smlambert** [comment]
This instance of failure (HCRLateAttachWorkload test from the extended.system target) ran on test-macincloud-macos1014-x64-2

**Comment by sophia-guo** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/issues/1214

**Comment by M-Davies** [comment]
Dup of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1274

**Comment by smlambert** [comment]
I will close this as dup, and as its being actively worked in openjdk-infrastructure issue 1274.

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1274
