### ISSUE TITLE
Jenkins Grinder jobs using jdk_custom can no longer find tests in the test directory

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-tests#1368]
Eg.
Error: Cannot find file: /home/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/scripts/testKitGen/../../../openjdk/openjdk-jdk/java/util/Arrays/TimSortStackSize2.java

I reset some commits and found that this commit caused the problem: https://github.com/AdoptOpenJDK/openjdk-tests/commit/91c4c4b128445665860b342fd4d5357947b6856d although cannot determine the issue

Tested this on multiple tests and versions.
Eg. https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/631/

**Comment by llxia** [comment]
We updated the code. We are expected `CUSTOM_TARGET` to contain full path after `yourTestImageLocation`. For example,
```
export JDK_CUSTOM_TARGET=test/jdk/java/lang/Class/GetModuleTest.java
```

Please see the wiki https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally#run-specific-test-class-from-openjdk-tests-on-jdk11-linux-s390x-openj9-sdk

Close the issue for now. Please reopen if you still have problem.
