### ISSUE TITLE
ProblemList_openjdk14-openj9.txt does not exist

### ISSUE THREAD

**Issue by mikezhang1234567890** [AdoptOpenJDK/openjdk-tests#1374]
I was trying to run tests against jdk14, but I ran into the issue mentioned in the title, which makes sense since the OpenJDK repo hasn't branched for 14 yet.

In the OpenJ9 repo, there's https://github.com/eclipse/openj9/pull/6784 which uses a base exclude file when the exclude files for a specific version do not exist. Perhaps something similar could be done here?

**Comment by sophia-guo** [comment]
@mikezhang1234567890 please copy ProblemList_openjdk13-openj9.txt and rename to ProblemList_openjdk14-openj9.txt and push the PR if the issue block you right now.

Going forward we'd like a more flexible and less maintenance solution for this. Ideally each openjdk should have its own separate problemlist.

**Comment by smlambert** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1476
