### ISSUE TITLE
Test build are running scala_test_SE80_0, which should not.

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#138]
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_test_x86-64_linux/35/consoleFull
21:09:34 ===============================================
21:09:34 Running test scala_test_SE80_0 ...
21:09:34 ===============================================
21:09:34 test with NoOptions
21:09:34 { docker run -it --rm -v /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../..:/java -v :/scala adoptopenjdk-scala-test:latest "jvm pos neg"; } 2>&1 | tee -a TestTargetResult
21:09:34 /bin/sh: 1: docker: not found

**Comment by sophia-guo** [comment]
Still there .
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_test_x86-64_linux/86/console

**Comment by smlambert** [comment]
Closing as this was fixed with PR #211.
