### ISSUE TITLE
special.functional: error: package openj9.internal.tools.attach.target does not exist

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#1385]
Testcase fails to build: x64_linux
jdk8u232-b07_openj9-0.17.0-m2
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_linux/71/console

15:33:19      [javac] /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/functional/cmdLineTests/jvmtitests/src/com/ibm/jvmti/tests/util/attachingAgent.java:36: error: package openj9.internal.tools.attach.target does not exist
15:33:19      [javac] 			String myVmid = openj9.internal.tools.attach.target.AttachHandler.getVmId();

**Comment by smlambert** [comment]
dup of https://github.com/AdoptOpenJDK/openjdk-build/issues/1316
