### ISSUE TITLE
sanity.external_thorntail: Failed to resolve POM for io.thorntail:bom...

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#1386]
testcase gradle dependency error I think...
jdk8u232-b07_openj9-0.17.0-m2
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_thorntail-mp-tck_x86-64_linux/155/console

16:18:00  [ERROR] arquillianBeforeClass(org.eclipse.microprofile.health.tck.DelegateHealthSuccessfulTest)  Time elapsed: 7.731 s  <<< FAILURE!
16:18:00  org.jboss.arquillian.container.spi.client.container.DeploymentException: 
16:18:00  Found 1 problems while building POM model from /thorntail/testsuite/microprofile-tcks/health/pom.xml
16:18:00  1/ [ERROR] Non-resolvable import POM: Failed to resolve POM for io.thorntail:bom:2.5.1.Final-SNAPSHOT due to Could not transfer artifact io.thorntail:bom:pom:2.5.1.Final-SNAPSHOT from/to gradle (https://repo.gradle.org/gradle/libs-releases-local): Error transferring file: Server returned HTTP response code: 409 for URL: https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.5.1.Final-SNAPSHOT/bom-2.5.1.Final-SNAPSHOT.pom from https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.5.1.Final-SNAPSHOT/bom-2.5.1.Final-SNAPSHOT.pom @ io.thorntail.testsuite:thorntail-microprofile-tck-health:2.5.1.Final-SNAPSHOT, /thorntail/testsuite/microprofile-tcks/health/pom.xml
16:18:00  
16:18:00  	at org.wildfly.swarm.arquillian.adapter.WildFlySwarmContainer.deploy(WildFlySwarmContainer.java:95)

**Comment by smlambert** [comment]
this is a dup of #1161 

looks like an issue with thorntail pom (and subsequently missing artifacts at the repo it pulls from), will need to reach out to that community to fix or to get work around

**Comment by smlambert** [comment]
Identified as a dup, but did not close for some reason, closing now.
