### ISSUE TITLE
MBCS_Tests_CLDR test failures with JDK 11.0.5+10

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#1394]
Platform: linux_x86-64
Test target: special.functional

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_special.functional_x86-64_linux/2/consoleFull

12:44:15  ===============================================
12:44:15  Running test MBCS_Tests_CLDR_11_ja_JP_linux_0 ...
12:44:15  ===============================================
12:44:15  MBCS_Tests_CLDR_11_ja_JP_linux_0 Start Time: Wed Oct 16 11:44:15 2019 Epoch Time (ms): 1571226255257
12:44:15  "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
12:44:15  JVMSHRC005I No shared class caches available
12:44:15  JVMSHRC005I No shared class caches available
12:44:15  cache cleanup done
12:44:15  variation: NoOptions
12:44:15  JVM_OPTIONS: -Xcompressedrefs 
12:44:15  { itercnt=1; \
12:44:15  mkdir -p "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15712261102718/MBCS_Tests_CLDR_11_ja_JP_linux_0"; \
12:44:15  cd "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15712261102718/MBCS_Tests_CLDR_11_ja_JP_linux_0"; \
12:44:15  LANG=ja_JP.UTF-8 bash /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/test.sh; \
12:44:15  if [ $? -eq 0 ] ; then echo ""; echo "MBCS_Tests_CLDR_11_ja_JP_linux_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../..;  else echo ""; echo "MBCS_Tests_CLDR_11_ja_JP_linux_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15712261102718/TestTargetResult";
12:44:16  Running ...
12:44:16  Default ...
12:44:21  Done
12:44:21  JRE ...
12:44:22  Done
12:44:22  CLDR ...
12:44:24  Done
12:44:24  SPI ...
12:44:30  Done
12:44:30  CLDR,JRE ...
12:44:33  Done
12:44:34  1..35
12:44:34  ok 1 - DecimalFormatSymbolsTest-ja-JP-CLDR,JRE.log
12:44:34  ok 2 - diff DecimalFormatSymbolsTest-ja-JP-DEFAULT.log expected_DecimalFormatSymbolsTest-ja-JP-DEFAULT.log
12:44:34  ok 3 - diff DecimalFormatSymbolsTest-ja-JP-CLDR.log expected_DecimalFormatSymbolsTest-ja-JP-CLDR.log
12:44:34  ok 4 - diff DecimalFormatSymbolsTest-ja-JP-JRE.log expected_DecimalFormatSymbolsTest-ja-JP-JRE.log
12:44:34  ok 5 - diff DecimalFormatSymbolsTest-ja-JP-SPI.log expected_DecimalFormatSymbolsTest-ja-JP-SPI.log
12:44:34  ok 6 - DateFormatSymbolsTest-ja-JP-CLDR,JRE.log
12:44:34  ok 7 - diff DateFormatSymbolsTest-ja-JP-DEFAULT.log expected_DateFormatSymbolsTest-ja-JP-DEFAULT.log
12:44:34  ok 8 - diff DateFormatSymbolsTest-ja-JP-CLDR.log expected_DateFormatSymbolsTest-ja-JP-CLDR.log
12:44:34  ok 9 - diff DateFormatSymbolsTest-ja-JP-JRE.log expected_DateFormatSymbolsTest-ja-JP-JRE.log
12:44:34  ok 10 - diff DateFormatSymbolsTest-ja-JP-SPI.log expected_DateFormatSymbolsTest-ja-JP-SPI.log
12:44:34  ok 11 - DecimalStyleTest-ja-JP-CLDR,JRE.log
12:44:34  ok 12 - diff DecimalStyleTest-ja-JP-DEFAULT.log DecimalStyleTest-ja-JP-CLDR,JRE.log
12:44:34  ok 13 - diff DecimalStyleTest-ja-JP-CLDR.log DecimalStyleTest-ja-JP-CLDR,JRE.log
12:44:34  ok 14 - diff DecimalStyleTest-ja-JP-JRE.log DecimalStyleTest-ja-JP-CLDR,JRE.log
12:44:34  ok 15 - diff DecimalStyleTest-ja-JP-SPI.log DecimalStyleTest-ja-JP-CLDR,JRE.log
12:44:34  ok 16 - CurrencyTest-ja-JP-CLDR,JRE.log
12:44:34  ok 17 - diff CurrencyTest-ja-JP-DEFAULT.log expected_CurrencyTest-ja-JP-DEFAULT.log
12:44:34  ok 18 - diff CurrencyTest-ja-JP-CLDR.log expected_CurrencyTest-ja-JP-CLDR.log
12:44:34  ok 19 - diff CurrencyTest-ja-JP-JRE.log expected_CurrencyTest-ja-JP-JRE.log
12:44:34  ok 20 - diff CurrencyTest-ja-JP-SPI.log expected_CurrencyTest-ja-JP-SPI.log
12:44:34  ok 21 - LocaleTest-ja-JP-CLDR,JRE.log
12:44:34  ok 22 - diff LocaleTest-ja-JP-DEFAULT.log expected_LocaleTest-ja-JP-DEFAULT.log
12:44:34  ok 23 - diff LocaleTest-ja-JP-CLDR.log expected_LocaleTest-ja-JP-CLDR.log
12:44:34  ok 24 - diff LocaleTest-ja-JP-JRE.log expected_LocaleTest-ja-JP-JRE.log
12:44:34  ok 25 - diff LocaleTest-ja-JP-SPI.log expected_LocaleTest-ja-JP-SPI.log
12:44:34  ok 26 - TimeZoneTestA-ja-JP-CLDR,JRE.log
12:44:34  ok 27 - diff TimeZoneTestA-ja-JP-DEFAULT.log TimeZoneTestA-ja-JP-CLDR,JRE.log
12:44:34  ok 28 - diff TimeZoneTestA-ja-JP-JRE.log TimeZoneTestA-ja-JP-CLDR,JRE.log
12:44:34  ok 29 - diff TimeZoneTestA-ja-JP-SPI.log TimeZoneTestA-ja-JP-CLDR,JRE.log
12:44:34  not ok 30 - diff TimeZoneTestA-ja-JP-CLDR.log expected_TimeZoneTestA-ja-JP-CLDR.log
12:44:34  #   Failed test 'diff TimeZoneTestA-ja-JP-CLDR.log expected_TimeZoneTestA-ja-JP-CLDR.log'
12:44:34  #   at /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 78.
12:44:34  ok 31 - TimeZoneTestB-ja-JP-CLDR,JRE.log
12:44:34  not ok 32 - diff TimeZoneTestB-ja-JP-DEFAULT.log expected_TimeZoneTestB-ja-JP-DEFAULT.log
12:44:34  #   Failed test 'diff TimeZoneTestB-ja-JP-DEFAULT.log expected_TimeZoneTestB-ja-JP-DEFAULT.log'
12:44:34  #   at /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 86.
12:44:34  not ok 33 - diff TimeZoneTestB-ja-JP-CLDR.log expected_TimeZoneTestB-ja-JP-CLDR.log
12:44:34  #   Failed test 'diff TimeZoneTestB-ja-JP-CLDR.log expected_TimeZoneTestB-ja-JP-CLDR.log'
12:44:34  #   at /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 86.
12:44:34  not ok 34 - diff TimeZoneTestB-ja-JP-JRE.log expected_TimeZoneTestB-ja-JP-JRE.log
12:44:34  #   Failed test 'diff TimeZoneTestB-ja-JP-JRE.log expected_TimeZoneTestB-ja-JP-JRE.log'
12:44:34  #   at /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 86.
12:44:34  not ok 35 - diff TimeZoneTestB-ja-JP-SPI.log expected_TimeZoneTestB-ja-JP-SPI.log
12:44:34  #   Failed test 'diff TimeZoneTestB-ja-JP-SPI.log expected_TimeZoneTestB-ja-JP-SPI.log'
12:44:34  #   at /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 86.
12:44:34  # Looks like you failed 5 tests of 35.
12:44:34  
12:44:34  MBCS_Tests_CLDR_11_ja_JP_linux_0_FAILED
12:44:34  
12:44:34  "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
12:44:34  
12:44:34  Attempting to destroy all caches in cacheDir /home/jenkins/javasharedresources/
12:44:34  
12:44:34  JVMSHRC806I Compressed references persistent shared cache "sharedcc_jenkins" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
12:44:34  JVMSHRC005I No shared class caches available
12:44:34  cache cleanup done
12:44:34  MBCS_Tests_CLDR_11_ja_JP_linux_0 Finish Time: Wed Oct 16 11:44:34 2019 Epoch Time (ms): 1571226274534
12:44:34  
12:44:34  ===============================================
12:44:34  Running test MBCS_Tests_CLDR_11_ko_KR_linux_0 ...
12:44:34  ===============================================
12:44:34  MBCS_Tests_CLDR_11_ko_KR_linux_0 Start Time: Wed Oct 16 11:44:34 2019 Epoch Time (ms): 1571226274572
12:44:34  "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
12:44:34  JVMSHRC005I No shared class caches available
12:44:35  JVMSHRC005I No shared class caches available
12:44:35  cache cleanup done
12:44:35  variation: NoOptions
12:44:35  JVM_OPTIONS: -Xcompressedrefs 
12:44:35  { itercnt=1; \
12:44:35  mkdir -p "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15712261102718/MBCS_Tests_CLDR_11_ko_KR_linux_0"; \
12:44:35  cd "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15712261102718/MBCS_Tests_CLDR_11_ko_KR_linux_0"; \
12:44:35  LANG=ko_KR.UTF-8 bash /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/test.sh; \
12:44:35  if [ $? -eq 0 ] ; then echo ""; echo "MBCS_Tests_CLDR_11_ko_KR_linux_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../..;  else echo ""; echo "MBCS_Tests_CLDR_11_ko_KR_linux_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15712261102718/TestTargetResult";
12:44:35  Running ...
12:44:36  Default ...
12:44:41  Done
12:44:41  JRE ...
12:44:42  Done
12:44:42  CLDR ...
12:44:44  Done
12:44:44  SPI ...
12:44:50  Done
12:44:50  CLDR,JRE ...
12:44:52  Done
12:44:54  1..35
12:44:54  ok 1 - DecimalFormatSymbolsTest-ko-KR-CLDR,JRE.log
12:44:54  ok 2 - diff DecimalFormatSymbolsTest-ko-KR-DEFAULT.log expected_DecimalFormatSymbolsTest-ko-KR-DEFAULT.log
12:44:54  ok 3 - diff DecimalFormatSymbolsTest-ko-KR-CLDR.log expected_DecimalFormatSymbolsTest-ko-KR-CLDR.log
12:44:54  ok 4 - diff DecimalFormatSymbolsTest-ko-KR-JRE.log expected_DecimalFormatSymbolsTest-ko-KR-JRE.log
12:44:54  ok 5 - diff DecimalFormatSymbolsTest-ko-KR-SPI.log expected_DecimalFormatSymbolsTest-ko-KR-SPI.log
12:44:54  ok 6 - DateFormatSymbolsTest-ko-KR-CLDR,JRE.log
12:44:54  ok 7 - diff DateFormatSymbolsTest-ko-KR-DEFAULT.log expected_DateFormatSymbolsTest-ko-KR-DEFAULT.log
12:44:54  ok 8 - diff DateFormatSymbolsTest-ko-KR-CLDR.log expected_DateFormatSymbolsTest-ko-KR-CLDR.log
12:44:54  ok 9 - diff DateFormatSymbolsTest-ko-KR-JRE.log expected_DateFormatSymbolsTest-ko-KR-JRE.log
12:44:54  ok 10 - diff DateFormatSymbolsTest-ko-KR-SPI.log expected_DateFormatSymbolsTest-ko-KR-SPI.log
12:44:54  ok 11 - DecimalStyleTest-ko-KR-CLDR,JRE.log
12:44:54  ok 12 - diff DecimalStyleTest-ko-KR-DEFAULT.log DecimalStyleTest-ko-KR-CLDR,JRE.log
12:44:54  ok 13 - diff DecimalStyleTest-ko-KR-CLDR.log DecimalStyleTest-ko-KR-CLDR,JRE.log
12:44:54  ok 14 - diff DecimalStyleTest-ko-KR-JRE.log DecimalStyleTest-ko-KR-CLDR,JRE.log
12:44:54  ok 15 - diff DecimalStyleTest-ko-KR-SPI.log DecimalStyleTest-ko-KR-CLDR,JRE.log
12:44:54  ok 16 - CurrencyTest-ko-KR-CLDR,JRE.log
12:44:54  ok 17 - diff CurrencyTest-ko-KR-DEFAULT.log expected_CurrencyTest-ko-KR-DEFAULT.log
12:44:54  ok 18 - diff CurrencyTest-ko-KR-CLDR.log expected_CurrencyTest-ko-KR-CLDR.log
12:44:54  ok 19 - diff CurrencyTest-ko-KR-JRE.log expected_CurrencyTest-ko-KR-JRE.log
12:44:54  ok 20 - diff CurrencyTest-ko-KR-SPI.log expected_CurrencyTest-ko-KR-SPI.log
12:44:54  ok 21 - LocaleTest-ko-KR-CLDR,JRE.log
12:44:54  ok 22 - diff LocaleTest-ko-KR-DEFAULT.log expected_LocaleTest-ko-KR-DEFAULT.log
12:44:54  ok 23 - diff LocaleTest-ko-KR-CLDR.log expected_LocaleTest-ko-KR-CLDR.log
12:44:54  ok 24 - diff LocaleTest-ko-KR-JRE.log expected_LocaleTest-ko-KR-JRE.log
12:44:54  ok 25 - diff LocaleTest-ko-KR-SPI.log expected_LocaleTest-ko-KR-SPI.log
12:44:54  ok 26 - TimeZoneTestA-ko-KR-CLDR,JRE.log
12:44:54  ok 27 - diff TimeZoneTestA-ko-KR-DEFAULT.log TimeZoneTestA-ko-KR-CLDR,JRE.log
12:44:54  ok 28 - diff TimeZoneTestA-ko-KR-JRE.log TimeZoneTestA-ko-KR-CLDR,JRE.log
12:44:54  ok 29 - diff TimeZoneTestA-ko-KR-SPI.log TimeZoneTestA-ko-KR-CLDR,JRE.log
12:44:54  not ok 30 - diff TimeZoneTestA-ko-KR-CLDR.log expected_TimeZoneTestA-ko-KR-CLDR.log
12:44:54  #   Failed test 'diff TimeZoneTestA-ko-KR-CLDR.log expected_TimeZoneTestA-ko-KR-CLDR.log'
12:44:54  #   at /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 78.
12:44:54  ok 31 - TimeZoneTestB-ko-KR-CLDR,JRE.log
12:44:54  not ok 32 - diff TimeZoneTestB-ko-KR-DEFAULT.log expected_TimeZoneTestB-ko-KR-DEFAULT.log
12:44:54  #   Failed test 'diff TimeZoneTestB-ko-KR-DEFAULT.log expected_TimeZoneTestB-ko-KR-DEFAULT.log'
12:44:54  #   at /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 86.
12:44:54  not ok 33 - diff TimeZoneTestB-ko-KR-CLDR.log expected_TimeZoneTestB-ko-KR-CLDR.log
12:44:54  #   Failed test 'diff TimeZoneTestB-ko-KR-CLDR.log expected_TimeZoneTestB-ko-KR-CLDR.log'
12:44:54  #   at /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 86.
12:44:54  not ok 34 - diff TimeZoneTestB-ko-KR-JRE.log expected_TimeZoneTestB-ko-KR-JRE.log
12:44:54  #   Failed test 'diff TimeZoneTestB-ko-KR-JRE.log expected_TimeZoneTestB-ko-KR-JRE.log'
12:44:54  #   at /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 86.
12:44:54  not ok 35 - diff TimeZoneTestB-ko-KR-SPI.log expected_TimeZoneTestB-ko-KR-SPI.log
12:44:54  #   Failed test 'diff TimeZoneTestB-ko-KR-SPI.log expected_TimeZoneTestB-ko-KR-SPI.log'
12:44:54  #   at /home/jenkins/workspace/Test_openjdk11_j9_special.functional_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 86.
12:44:54  # Looks like you failed 5 tests of 35.
12:44:54  
12:44:54  MBCS_Tests_CLDR_11_ko_KR_linux_0_FAILED

**Comment by smlambert** [comment]
Rerun links for the 2 targets that fail (from console output):

https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=functional&JenkinsFile=openjdk_x86-64_linux&TARGET=MBCS_Tests_CLDR_11_ja_JP_linux_0

https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=functional&JenkinsFile=openjdk_x86-64_linux&TARGET=MBCS_Tests_CLDR_11_ko_KR_linux_0

**Comment by smlambert** [comment]
FYI @KKES335
