### ISSUE TITLE
sun/util/calendar/zi/TestZoneInfo310.java fails with jdk8

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1400]
sun/util/calendar/zi/TestZoneInfo310.java.TestZoneInfo310  FAILED: America/Campo_Grande    

```
Standard Error

java.lang.RuntimeException:   FAILED:  America/Campo_Grande
	at TestZoneInfo310.main(TestZoneInfo310.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)

JavaTest Message: Test threw exception: java.lang.RuntimeException
JavaTest Message: shutting down test

    
```

Failed on all platforms with upstream test, adoptopenjdk hotspot and openj9. 
https://ci.adoptopenjdk.net/view/Test_upstream/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux_upstream/21/testReport/sun_util_calendar_zi_TestZoneInfo310/java/TestZoneInfo310/

Believe this should be reported to JBS.  @jerboaa Could you please take a look at this?

**Comment by smlambert** [comment]
There are a couple open defects against this test, though none for Campo_Grande:
https://bugs.openjdk.java.net/browse/JDK-8223388
https://bugs.openjdk.java.net/browse/JDK-8227293

Also failing for upstream:
https://ci.adoptopenjdk.net/view/Test_upstream/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux_upstream/21/testReport/sun_util_calendar_zi_TestZoneInfo310/java/TestZoneInfo310/

**Comment by jerboaa** [comment]
@sophia-guo @smlambert This is:
http://mail.openjdk.java.net/pipermail/jdk8u-dev/2019-October/010445.html

**Comment by smlambert** [comment]
Closing as it has been reported/fixed upstream
