### ISSUE TITLE
Error trying to test my own openjdk binaries: Unrecognized option: -Xgcpolicy:optthrupu

### ISSUE THREAD

**Issue by klepiz** [AdoptOpenJDK/openjdk-tests#1402]
I'm trying to test my openjdk's binaries for linux64 with AdoptOpenJDK using a CentOS7 ( I downloaded  the openjdk from here: http://hg.openjdk.java.net/jdk8u/jdk8u/). 
Then  I clones [openjdk-tests](https://github.com/AdoptOpenJDK/openjdk-tests.git) and compiled the tests with those commands:
```
 - ./get.sh  -t /home/centos/work/work -p x64_linux -i hotspot -j jdk8u181-b13
 - make -f run_configure.mk && make compile
 - make _functional
```
Every time I try to test with `make _functional` I get this error:
```
Unrecognized option: -Xgcpolicy:optthruput
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
Could you please take a look at this?

**Comment by smlambert** [comment]
Looks like we've missed tagging a functional test properly (for openj9 only).  

@klepiz - can you please share the name of the test that fails with this error?

**Comment by klepiz** [comment]
```
FAILED test targets:
        testSCCMLExpireAndListALLCaches_0
        cmdLineTester_GCRegressionTests_Mode301_0
        jsr335tests_defendersupersends_SE80_0
        jsr335_interfaceStaticMethod_0
```

**Comment by smlambert** [comment]
Thanks, we'll update the tests definition so they skipped for a hotspot implementation (as those tests are using j9 specific JVM options).

**Comment by klepiz** [comment]
@smlambert  - What can i do at the moment to fix it ?. 
Thanks for the reply

**Comment by smlambert** [comment]
Fixing in this PR: https://github.com/eclipse/openj9/pull/7523

You could make those changes locally to the playlist.xml files and rerun the 'make -f run_configure.mk' (to regenerate the test targets, those targets will then be skipped for hotspot).

**Comment by smlambert** [comment]
As the fix for this is now merged, marking this as complete, verified in Grinder runs (both passing):
sanity.functional hs jdk8: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/911
extended.functional hs jdk11: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/912/
