### ISSUE TITLE
external/jenkins test error on j9 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1409]
Fails for jdk8/jdk11 j9 runs (passes on hotspot).  
in FunctionsTest.printThrowable:515->assertPrintThrowable:529 » OutOfMemory Java
- in jdk11: Tests run: 14887, Failures: 0, Errors: 1, Skipped: 15
- in jdk8: Tests run: 3715, Failures: 0, Errors: 1, Skipped: 15

Tests running weekly:
https://ci.adoptopenjdk.net/view/Test_external_weekly/job/openjdk11_j9_external_extended_jenkins_x86-64_linux
https://ci.adoptopenjdk.net/view/Test_external_weekly/job/openjdk8_j9_external_extended_jenkins_x86-64_linux

To reproduce for jdk11:
https://ci.adoptopenjdk.net//job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=external/jenkins&JenkinsFile=openjdk_x86-64_linux&TARGET=extended.external&CUSTOMIZED_SDK_URL=https://api.adoptopenjdk.net/v2/binary/nightly/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk&heap_size=normal&DOCKER_REQUIRED=true

To reproduce for jdk8:
https://ci.adoptopenjdk.net//job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=external/jenkins&JenkinsFile=openjdk_x86-64_linux&TARGET=extended.external&CUSTOMIZED_SDK_URL=https://api.adoptopenjdk.net/v2/binary/nightly/openjdk8?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk&heap_size=normal&DOCKER_REQUIRED=true

From console jdk11 j9 test run (https://ci.adoptopenjdk.net/view/Test_external_weekly/job/openjdk11_j9_external_extended_jenkins_x86-64_linux/72/console):
05:39:53  [ERROR] Tests run: 16, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 119.649 s <<< FAILURE! - in hudson.FunctionsTest
05:39:53  [ERROR] printThrowable(hudson.FunctionsTest)  Time elapsed: 49.719 s  <<< ERROR!
05:39:53  java.lang.OutOfMemoryError: Java heap space
05:39:53  	at java.base/java.util.Arrays.copyOf(Arrays.java:3776)
05:39:53  	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
05:39:53  	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:633)
05:39:53  	at java.base/java.lang.StringBuffer.append(StringBuffer.java:392)
05:39:53  	at java.base/java.io.StringWriter.write(StringWriter.java:122)
05:39:53  	at java.base/java.io.PrintWriter.write(PrintWriter.java:542)
05:39:53  	at java.base/java.io.PrintWriter.write(PrintWriter.java:559)
05:39:53  	at java.base/java.io.PrintWriter.append(PrintWriter.java:1089)
05:39:53  	at java.base/java.io.PrintWriter.append(PrintWriter.java:61)
05:39:53  	at java.base/com.ibm.oti.util.Util.appendTo(Util.java:225)
05:39:53  	at java.base/com.ibm.oti.util.Util.appendTo(Util.java:263)
05:39:53  	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:479)
05:39:53  	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:324)
05:39:53  	at hudson.FunctionsTest.assertPrintThrowable(FunctionsTest.java:529)
05:39:53  	at hudson.FunctionsTest.printThrowable(FunctionsTest.java:515)
05:39:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:39:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:39:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:39:53  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
05:39:53  	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
05:39:53  	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
05:39:53  	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
05:39:53  	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
05:39:53  	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
05:39:53  	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
05:39:53  	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
05:39:53  	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
05:39:53  	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
05:39:53  	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
05:39:53  	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
05:39:53  	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
05:39:53  	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
05:39:53  	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
05:39:53  	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
05:39:53  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
05:39:53  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
05:39:53  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
05:39:53  
05:40:12  [WARNING] Tests run: 39, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 119.798 s - in hudson.FilePathTest
05:40:12  [INFO] 
05:40:12  [INFO] Results:
05:40:12  [INFO] 
05:40:12  [ERROR] Errors: 
05:40:12  [ERROR]   FunctionsTest.printThrowable:515->assertPrintThrowable:529 » OutOfMemory Java ...
05:40:12  [INFO] 
05:40:12  [ERROR] Tests run: 14887, Failures: 0, Errors: 1, Skipped: 15
05:40:12  [INFO] 
05:40:12  [INFO] ------------------------------------------------------------------------
05:40:12  [INFO] Reactor Summary for Jenkins main module 2.201-SNAPSHOT:
05:40:12  [INFO] 
05:40:12  [INFO] Jenkins main module ................................ SUCCESS [  0.537 s]
05:40:12  [INFO] Jenkins BOM ........................................ SUCCESS [  0.039 s]
05:40:12  [INFO] Jenkins cli ........................................ SUCCESS [  3.856 s]
05:40:12  [INFO] Jenkins core ....................................... FAILURE [03:13 min]
05:40:12  [INFO] Jenkins war ........................................ SKIPPED
05:40:12  [INFO] Jenkins core tests POM ............................. SKIPPED
05:40:12  [INFO] Tests for Jenkins core ............................. SKIPPED

Same error can be seen in jdk8 run: https://ci.adoptopenjdk.net/view/Test_external_weekly/job/openjdk8_j9_external_extended_jenkins_x86-64_linux/79/console

03:16:17  [INFO] Results:
03:16:17  [INFO] 
03:16:17  [ERROR] Errors: 
03:16:17  [ERROR]   FunctionsTest.printThrowable:515->assertPrintThrowable:529 » OutOfMemory Java ...
03:16:17  [INFO] 
03:16:17  [ERROR] Tests run: 3715, Failures: 0, Errors: 1, Skipped: 15
03:16:17  [INFO] 
03:16:17  [INFO] ------------------------------------------------------------------------
03:16:17  [INFO] Reactor Summary for Jenkins main module 2.200-SNAPSHOT:
03:16:17  [INFO] 
03:16:17  [INFO] Jenkins main module ................................ SUCCESS [  0.886 s]
03:16:17  [INFO] Jenkins BOM ........................................ SUCCESS [  0.091 s]
03:16:17  [INFO] Jenkins cli ........................................ SUCCESS [  3.784 s]
03:16:17  [INFO] Jenkins core ....................................... FAILURE [06:55 min]

**Comment by ashu-mehra** [comment]
Opened https://github.com/eclipse/openj9/issues/7669

**Comment by smlambert** [comment]
Closing this as we will track all [type:external Reported upstream](https://github.com/AdoptOpenJDK/openjdk-tests/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22Reported%2FFixed+Upstream%22+label%3Atype%3Aexternal) issues via https://github.com/AdoptOpenJDK/openjdk-tests/issues/587
