### ISSUE TITLE
jdk_lang : java/lang/System/finalization/FinInterrupt.java failed with Execution failed: `main' threw exception: java.lang.AssertionError: interrupt bit was cleared

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#141]
<pre>
23:05:31 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: interrupt bit was cleared
23:05:31 REASON: User specified action: run main FinInterrupt 
23:05:31 TIME:   0.011 seconds
23:05:31 messages:
23:05:31 command: main FinInterrupt
23:05:31 reason: User specified action: run main FinInterrupt 
23:05:31 Mode: agentvm
23:05:31 Agent id: 1
23:05:31 elapsed time (seconds): 0.011
23:05:31 configuration:
23:05:31 Boot Layer
23:05:31   class path: /Users/jenkins/workspace/test_x86-64_experimental/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
23:05:31               /Users/jenkins/workspace/test_x86-64_experimental/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
23:05:31               /Users/jenkins/workspace/test_x86-64_experimental/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
23:05:31 
23:05:31 Test Layer
23:05:31   class path: /Users/jenkins/workspace/test_x86-64_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/System/finalization/FinInterrupt.d
23:05:31               /Users/jenkins/workspace/test_x86-64_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/System/finalization
23:05:31 
23:05:31 rerun:
23:05:31 HOME=/Users/jenkins \
23:05:31 PATH=/bin:/usr/bin \
23:05:31     /Users/jenkins/workspace/test_x86-64_experimental/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
23:05:31         -Dtest.class.path.prefix=/Users/jenkins/workspace/test_x86-64_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/System/finalization/FinInterrupt.d:/Users/jenkins/workspace/test_x86-64_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/System/finalization \
23:05:31         -Dtest.src=/Users/jenkins/workspace/test_x86-64_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/System/finalization \
23:05:31         -Dtest.src.path=/Users/jenkins/workspace/test_x86-64_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/System/finalization \
23:05:31         -Dtest.classes=/Users/jenkins/workspace/test_x86-64_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/System/finalization/FinInterrupt.d \
23:05:31         -Dtest.class.path=/Users/jenkins/workspace/test_x86-64_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/System/finalization/FinInterrupt.d \
23:05:31         -Dtest.vm.opts='-ea -esa -Xmx512m' \
23:05:31         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
23:05:31         -Dtest.compiler.opts= \
23:05:31         -Dtest.java.opts= \
23:05:31         -Dtest.jdk=/Users/jenkins/workspace/test_x86-64_experimental/openjdkbinary/j2sdk-image/jre/bin/../.. \
23:05:31         -Dcompile.jdk=/Users/jenkins/workspace/test_x86-64_experimental/openjdkbinary/j2sdk-image/jre/bin/../.. \
23:05:31         -Dtest.timeout.factor=4.0 \
23:05:31         -classpath /Users/jenkins/workspace/test_x86-64_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/System/finalization/FinInterrupt.d:/Users/jenkins/workspace/test_x86-64_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/System/finalization:/Users/jenkins/workspace/test_x86-64_experimental/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/Users/jenkins/workspace/test_x86-64_experimental/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/Users/jenkins/workspace/test_x86-64_experimental/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
23:05:31         FinInterrupt
23:05:31 STDERR:
23:05:31 java.lang.AssertionError: interrupt bit was cleared
23:05:31 	at FinInterrupt.main(FinInterrupt.java:38)
23:05:31 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:05:31 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:05:31 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:05:31 	at java.lang.reflect.Method.invoke(Method.java:498)
23:05:31 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
23:05:31 	at java.lang.Thread.run(Thread.java:748)
23:05:31 
23:05:31 JavaTest Message: Test threw exception: java.lang.AssertionError
23:05:31 JavaTest Message: shutting down test
23:05:31 
23:05:31 
23:05:31 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.AssertionError: interrupt bit was cleared
</pre>

**Comment by sophia-guo** [comment]
rerun on linux and mac, works fine.
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_x86-64_personal/133/ https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_x86-64_personal/132/

Will Re-enable.

**Comment by karianna** [comment]
@sophia-guo So this can be closed?
