### ISSUE TITLE
jdk_lang: Failed. Unexpected exit from test [exit code: 1] - cannot allocate memory

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#144]
<pre>
19:52:10 ACTION: junit -- Failed. Unexpected exit from test [exit code: 1]
19:52:10 REASON: User specified action: run junit/othervm/timeout=2500 -XX:+IgnoreUnrecognizedVMOptions -XX:-VerifyDependencies -esa test.java.lang.invoke.MethodHandlesTest 
19:52:10 TIME:   24.416 seconds
19:52:10 messages:
19:52:10 command: junit -XX:+IgnoreUnrecognizedVMOptions -XX:-VerifyDependencies -esa test.java.lang.invoke.MethodHandlesTest
19:52:10 reason: User specified action: run junit/othervm/timeout=2500 -XX:+IgnoreUnrecognizedVMOptions -XX:-VerifyDependencies -esa test.java.lang.invoke.MethodHandlesTest 
19:52:10 Mode: othervm [/othervm specified]
19:52:10 elapsed time (seconds): 24.416
19:52:10 configuration:
19:52:10 STDOUT:
19:52:10 #
19:52:10 # There is insufficient memory for the Java Runtime Environment to continue.
19:52:10 # Native memory allocation (mmap) failed to map 65536 bytes for committing reserved memory.
19:52:10 # An error report file with more information is saved as:
19:52:10 # /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/scratch/3/hs_err_pid30798.log
19:52:10 #
19:52:10 # Compiler replay data is saved as:
19:52:10 # /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/scratch/3/replay_pid30798.log
19:52:10 STDERR:
19:52:10 OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007ff8e54a0000, 65536, 1) failed; error='Cannot allocate memory' (errno=12)
19:52:10 rerun:
19:52:10 HOME=/home/jenkins \
19:52:10 LANG=en_US.UTF-8 \
19:52:10 PATH=/bin:/usr/bin \
19:52:10 CLASSPATH=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/invoke/MethodHandlesTest.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/invoke:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/lib/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/lib/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/lib/testlibrary/jsr292:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/lib/testlibrary/jsr292:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/junit.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
19:52:10     /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
19:52:10         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/invoke/MethodHandlesTest.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/invoke:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/lib/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/lib/testlibrary/jsr292 \
19:52:10         -Dtest.src=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/invoke \
19:52:10         -Dtest.src.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/invoke:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/lib/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/lib/testlibrary/jsr292 \
19:52:10         -Dtest.classes=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/invoke/MethodHandlesTest.d \
19:52:10         -Dtest.class.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/invoke/MethodHandlesTest.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/lib/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/lib/testlibrary/jsr292 \
19:52:10         -Dtest.vm.opts='-ea -esa -Xmx512m' \
19:52:10         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
19:52:10         -Dtest.compiler.opts= \
19:52:10         -Dtest.java.opts= \
19:52:10         -Dtest.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
19:52:10         -Dcompile.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
19:52:10         -Dtest.timeout.factor=4.0 \
19:52:10         -ea \
19:52:10         -esa \
19:52:10         -Xmx512m \
19:52:10         -XX:+IgnoreUnrecognizedVMOptions \
19:52:10         -XX:-VerifyDependencies \
19:52:10         -esa \
19:52:10         com.sun.javatest.regtest.agent.MainWrapper /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/java/lang/invoke/MethodHandlesTest.d/junit.0.jta java/lang/invoke/MethodHandlesTest.java test.java.lang.invoke.MethodHandlesTest
19:52:10 
19:52:10 TEST RESULT: Failed. Unexpected exit from test [exit code: 1]
</pre>
java/lang/invoke/LFCaching/LFMultiThreadCachingTest.java.LFMultiThreadCachingTest
java/lang/invoke/LFCaching/LFSingleThreadCachingTest.java.LFSingleThreadCachingTest
java/lang/invoke/MethodHandlesTest.java.MethodHandlesTest

**Comment by smlambert** [comment]
error='Cannot allocate memory' - is this a case of insufficient memory on test machine, is there guidance in terms of machine configuration / requirements for running this test?

**Comment by akolarkunnu** [comment]
I rerun and not able to reproduce:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/119/testReport/
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/121/testReport/

**Comment by akolarkunnu** [comment]
Re-enabled these tests by PR #230
