### ISSUE TITLE
JTReg Fail: java/util/EnumSet/BogusEnumSet.java & java/util/EnumSet/EnumSetClassSerialization.java

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1441]
Condensed these two tests together as the issue is likely the same.
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/3cc03bc6fbbab6bbd54eecb860e007f44e14656e/test/jdk/java/util/EnumSet/BogusEnumSet.java#L1 and https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/3cc03bc6fbbab6bbd54eecb860e007f44e14656e/test/jdk/java/util/EnumSet/EnumSetClassSerialization.java#L1 fail on JDK11 for openj9 and hotspot (on all generic OS's). JDK13 and 8 are unaffected.

- Category, openjdk
- Non intermittent
- Discovered on the newly restarted JDK11 nightly builds for plinux and s390x but it appears to be a generic-all failure when ran locally and in grinders. Tests have not yet been excluded.
- Probably due an incorrect `serialVersionUID` but it appears correct after a little research into the JDK Bug system 
- https://bugs.openjdk.java.net/browse/JDK-8227432 and https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8227368

```
16:33:31  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
16:33:31  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Linux amd64-64-Bit Compressed References 20191016_358 (JIT enabled, AOT enabled)
16:33:31  OpenJ9   - 77c1cf708
16:33:31  OMR      - 20db4fbc
16:33:31  JCL      - 2a7af5674b based on jdk-11.0.5+10)

16:35:51  STDERR:
16:35:51  java.io.InvalidClassException: java.util.EnumSet; local class incompatible: stream classdesc serialVersionUID = 1009687484059888093, local class serialVersionUID = -2409567991088730183
16:35:51  	at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
16:35:51  	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2009)
16:35:51  	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1878)
16:35:51  	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2009)
16:35:51  	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1878)
16:35:51  	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2166)
16:35:51  	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1700)
16:35:51  	at java.base/java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:517)
16:35:51  	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:455)
16:35:51  	at BogusEnumSet.deserialize(BogusEnumSet.java:98)
16:35:51  	at BogusEnumSet.main(BogusEnumSet.java:85)
16:35:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:35:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:35:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:35:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:35:51  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
16:35:51  	at java.base/java.lang.Thread.run(Thread.java:831)
```

Rerun Job x86_64 linux JDK11-openj9 BogusEnumSet.java: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/util/EnumSet/BogusEnumSet.java&TARGET=jdk_custom_0

**Comment by sophia-guo** [comment]
Similar to https://github.com/AdoptOpenJDK/openjdk-tests/issues/1440#issuecomment-552995766

**Comment by M-Davies** [comment]
Closing as per https://github.com/AdoptOpenJDK/openjdk-tests/issues/1440#issuecomment-553338131
