### ISSUE TITLE
Increase Perf Tests Coverage to All Platforms

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-tests#1457]
### Problem Description

Currently, all the perf tests are only tested on and enabled for xLinux. We need to expand the coverage for these tests to all platforms.

Since we just have 2 perf machines, which are both xLinux, at Adopt (https://ci.adoptopenjdk.net/label/ci.role.perf/) at the moment, we're running them on non-perf machines as functional tests for now. Hence, it's fine to do the same for other platforms as well until we get more dedicated perf machines.

### Benchmarks

- [x] Dacapo (via https://github.com/AdoptOpenJDK/openjdk-tests/pull/1458)

- [x] Renaissance (via #1494)

- [x] BumbleBench

- [ ] TBD

### Assigned Contributor

I'll get started by enabling all tests under one benchmark suite and then moving on to the next suite.

**Comment by karianna** [comment]
@d3r3kk

**Comment by smlambert** [comment]
Appears we can close this one, as TBD can be To Be Determined later... :) 

Thanks @piyush286
