### ISSUE TITLE
Add quarkus tests

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1463]
This issue is to add [quarkus java testing](https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#setup) to the external test group, and put a placeholder for the native tests (if we end up tying a graalvm build into our regularly scheduled pipelines).

**Comment by sophia-guo** [comment]
Grinder with `quarkus_java_test` ( exclude: quarkus-documentation, which either failedd or hung):
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1015/testReport/

With :quarkus-documentation 
Failed:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1004/console  

Hung:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1010/
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1011/

hung happened when doing:
Downloaded from central: https://repo.maven.apache.org/maven2/org/jruby/jruby-stdlib/9.2.6.0/jruby-stdlib-9.2.6.0.jar (11 MB at 3.6 MB/s)

or:
Downloaded from central: https://repo.maven.apache.org/maven2/org/jruby/jruby-core/9.2.6.0/jruby-core-9.2.6.0.jar (10 MB at 1.5 MB/s)

Both related with jruby

**Comment by smlambert** [comment]
Thanks pushing this forward, and for the update @sophia-guo - with this, I think we can prepare a PR, leaving the quarkus-documention piece excluded for now.

**Comment by smlambert** [comment]
Opened https://github.com/eclipse/openj9/issues/8237 to raise awareness of the LogManager initialization behavioural differences.

**Comment by sophia-guo** [comment]
Jenkins jobs have been added to https://ci.adoptopenjdk.net/view/Test_external_weekly/, which should be triggered on Jan 12. Will keep an eye on it.

**Comment by DanHeidinga** [comment]
> FYI Grinder quarkus_java_test with openjdk8-openj9 ( exclude: quarkus-documentation, which either failed or hung)

Does this only fail / hang on OpenJ9?  If so, please raise a defect for this at the OpenJ9 project and we'll investigate further

**Comment by smlambert** [comment]
Yes, quarkus-documentation fails only openj9, we will be raising an issue shortly after gathering some additional info.

**Comment by sophia-guo** [comment]
Opened hang issue on https://github.com/eclipse/openj9/issues/8303
