### ISSUE TITLE
New openj9 large heap zlinux/plinux/arm platforms don't have test scripts

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-tests#1489]
Wasn't sure where to raise this, here or infra, but the new large heap platforms that we produce don't run tests as they don't have openjdk/system jenkins jobs yet, so the pipelines just skip them. This may be intentional but thought I would raise just in case it's not. 

eg. https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9-linuxXL/

**Comment by smlambert** [comment]
Thanks Adam, yes, I had delayed generating those test jobs (and had mentioned it as an AdoptOpenJDK 'todo' in a recent openj9 community meeting) but will do so shortly.  Raising this issue was appropriate (and a good reminder).  :)

**Comment by smlambert** [comment]
Jobs have now been generated.

s390x_linux_xl:  https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/87/
ppc64le_linux_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/88/
aarch64_linux, aarch64_linux_xl: https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/89/
