### ISSUE TITLE
Add mac_os to graphSpecs list

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#15]
For use when people set SPEC= for testing (linux_x86-64 currently works for mac_os testing, but to avoid confusion, we should add it to the list.

**Comment by smlambert** [comment]
@renfeiw, can you verify that mac_os is in the list.  This is a book-keeping exercise, as we can run and do run tests on mac_os already.

**Comment by renfeiw** [comment]
Yes, it is added. But a proper name should be mac_x86-64? If the SPEC follows OSNAME_ARCH-BITS, it will help platform-requirement filter.
