### ISSUE TITLE
Failing JTReg: java/io/CharArrayReader/OverflowInRead.java

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1500]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/d24795242d614819423ba3b48f91e61c7f675a6c/test/jdk/java/io/CharArrayReader/OverflowInRead.java#L1 fails intermittently for JDK11/13 on all platforms
- Category: openjdk
- Testname: java/io/CharArrayReader/OverflowInRead.java
- Jenkins can't seem to find the test but it can find the file `OverflowInRead.java`, producing a `Test results: no tests selected` result (perhaps due to the absence of a `@Test` flag in the main method?).
- Ran locally, the test passes without issue on mac, windows and linux for JDK11 & 13 when using the "quick and dirty" method of running tests (e.g. `./java -jar jtreg.jar OverflowInRead.java) but also when running the test as per https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally. JDK versions are the same (on jenkins and local)
- Yet this test is excluded anyway (probably due to the previously mentioned Jenkins result)
Is this the appropriate place to raise this problem?

**Comment by smlambert** [comment]
Investigate the annotations at the top of the test, do we have the proper settings in our playlists?

example, this test has a @requires tag, we may need to restrict this test to machines with certain capabilities
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/d24795242d614819423ba3b48f91e61c7f675a6c/test/jdk/java/io/CharArrayReader/OverflowInRead.java#L27

**Comment by sophia-guo** [comment]
Good catch, I just googled 
@requires <expression>
Express a dependence on characteristics of the system being tested, which is supported by jtreg framework. Should not need any manual setting. 

To confirm I just run a grinder on linux with jdk_custom=test/jdk/java/io/CharArrayReader/OverflowInRead.java

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/982/console

```
03:27:49  Test results: no tests selected
```

Tried also with 'openjdk_sparcv9_solaris' as it is sun.arch unfortunately the machine has not setup correctly.
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/984/

To double check could also search another test with @requires tag asking other platforms.

**Comment by M-Davies** [comment]
That'll teach me to double check the details at the top of the test instead of diving straight into the code! Thank you both :). Seeing as we don't have any working solaris machines at hyc either, I'll try and test this locally on a solaris VM

**Comment by M-Davies** [comment]
Currently waiting for my solaris SPARC approval to go through so until then, there's not much else I can do for this. I'll comment again if I get approved
https://www.oracle.com/solaris/solaris11/downloads/solaris11-vm-templates-downloads.html

**Comment by M-Davies** [comment]
A month down the line without approval. I'll send another request.

**Comment by M-Davies** [comment]
@smlambert Does adopt distribute solaris-hotspot-jdk11 from the website? I can see a solaris jdk8 but no jdk11

**Comment by smlambert** [comment]
No, we currently do not have a jdk11 solaris build, see https://github.com/AdoptOpenJDK/openjdk-build/issues/1279

**Comment by M-Davies** [comment]
Are there any other builds at adopt that are sun.arch?

**Comment by smlambert** [comment]
agree, closing this issue now (since no jdk11 on solaris) or hardware setup for testing jdk8 build.
