### ISSUE TITLE
Add Testing for Spring Framework

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-tests#1501]
Spring is a popular application development framework for Java EE. More and more developers are using it to write extremely performant and easily testable code. Because it's getting increasingly popular, we should add some benchmarks related to it.

We can start by adding the PetClinic application (https://github.com/spring-projects/spring-petclinic). WAS team already runs this application, so we can ask them if we have any questions.

### Requirements
1) We should avoid adding a script for running the benchmark unless it's absolutely needed. If we do, it should be as simple as possible.
2) We can start with adding it for xLinux, but eventually we want it to run for all platforms.
3) Needless to say, it should follow the design of other perf tests.

### Assigned Contributors

I'll be working with my team to add this benchmark.

**Comment by smlambert** [comment]
Related to #1112

**Comment by smlambert** [comment]
Adding petclinic to #1112 and closing this issue, as we do not need 2 separate issues open.
