### ISSUE TITLE
openjdk11 j9 aarch64 test do not have -Xcompressedrefs option

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1503]
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/61/console

```
20:42:52  -agentvm -a -ea -esa -v:fail,error,time,nopass -retain:fail,error,*.dmp,javacore.*,heapdump.*,*.trc -ignore:quiet -timeoutFactor:8 -xml:verify -concurrency:96 -vmoptions:"-Xmx512m  " \
```

`-vmoptions:"-Xmx512m  " `should be `-vmoptions:"-Xmx512m  -Xcompressedrefs  "`

Same issue for system or functional test with aarch64 jdk.
JVM_OPTIONS is set without -Xcompressedrefs

https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk11_j9_sanity.system_aarch64_linux/61/
https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk11_j9_extended.system_aarch64_linux/58/

```
21:17:46  Running test MachineInfo_0 ...
21:17:46  ===============================================
21:17:46  MachineInfo_0 Start Time: Sat Oct 12 19:17:46 2019 Epoch Time (ms): 1570907866064
21:17:46  "/home/jenkins/workspace/Test_openjdk11_j9_sanity.system_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_sanity.system_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
21:17:46  
21:17:46  Attempting to destroy all caches in cacheDir /home/jenkins/javasharedresources/
21:17:46  
21:17:46  JVMSHRC806I Compressed references persistent shared cache "sharedcc_jenkins" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
21:17:46  JVMSHRC005I No shared class caches available
21:17:46  cache cleanup done
21:17:46  variation: NoOptions
21:17:46  JVM_OPTIONS:  

```

**Comment by sophia-guo** [comment]
https://github.com/AdoptOpenJDK/TKG/pull/20 should fix this. Meanwhile we use ^arch.arm to skip the test unworkable with arm in both system and functional tests. As aarch64 is enabled we need to go through the test with `<platformRequirements>...,^arch.arm... </platformRequirements>` to make sure if tests work with aarch64 or not. If not <platformRequirements> need to update with `^arch.aarch`. 

Take system DaaLoadTest_daa1_ConcurrentScavenge_0 test for example, which failed in 
https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk11_j9_sanity.system_aarch64_linux/61/

```
04:26:01  FAILED test targets:
04:26:01  	LambdaLoadTest_ConcurrentScavenge_0
04:26:01  	MathLoadTest_autosimd_ConcurrentScavenge_0
04:26:01  	MathLoadTest_bigdecimal_ConcurrentScavenge_0
04:26:01  	MauveSingleThreadLoadTest_OpenJ9_0
04:26:01  	ClassLoadingTest_ConcurrentScavenge_0
04:26:01  	DaaLoadTest_daa1_ConcurrentScavenge_0
04:26:01  	DaaLoadTest_daa2_ConcurrentScavenge_0
04:26:01  	DaaLoadTest_daa3_ConcurrentScavenge_0
04:26:01  

```

The platformRequirements is https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/system/daaLoadTest/playlist.xml#L140, which probably need to update as 
`<platformRequirements>bits.64,^arch.aarch</platformRequirements>`

**Comment by sophia-guo** [comment]
Remove tests which should not run on aarch64 will also help test jobs get more aarch64 machine time slot. 

system extended tests take 7 hours. 
https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk11_j9_extended.system_aarch64_linux/

**Comment by llxia** [comment]
There is some inconsistency in the scripts. In openjdk_aarch32_linux, `SPEC = linux_arm`

https://github.com/AdoptOpenJDK/openjdk-tests/blob/d2f0946813daaf3cc9708eae88072953579ab261/buildenv/jenkins/openjdk_aarch32_linux#L8

`SPEC=linux_aarch64_cmprssptrs` is used for openjdk_aarch64_linux
https://github.com/AdoptOpenJDK/openjdk-tests/blob/d2f0946813daaf3cc9708eae88072953579ab261/buildenv/jenkins/openjdk_aarch64_linux#L8

If we are going to update `platformRequirements ` to use `arch.aarch`, then SPEC in openjdk_aarch32_linux should update as well.

**Comment by knn-k** [comment]
OpenJ9 for AArch64 Linux supports `-Xcompressedrefs` since January.

**Comment by karianna** [comment]
@sophia-guo - Can this be closed?

**Comment by sophia-guo** [comment]
Yes, can be closed. Further update see https://github.com/eclipse/openj9/issues/9231
