### ISSUE TITLE
Topics of discussion from December AdoptOpenJDK mtg in Toronto

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1523]
This issue is to capture the main points of discussion in the in-person AdoptOpenJDK meetup in Toronto on Dec 9/10th, 2019 related to AdoptOpenJDK testing.  

Some of these items will become standalone issues in this repo to be delivered in 2020 milestones.

- https://github.com/AdoptOpenJDK/openjdk-tests/issues/1522 - next features to include in AQA v2.0 updates (expected in 1Q) 
- discussion of performance benchmarks integrated into AQA (see https://github.com/AdoptOpenJDK/openjdk-tests/issues/1112)
- discuss criteria for bare metal machines for perf (approved by TSC for 2020)

- discussion of external (3rd party application tests as form of verification, see #172)
- crowd-sourcing external testing as a way to expand that aspect of Adopt testing

- overview of TRSS and how to use it for triaging release pipelines (action to Shelley to create a short tutorial to show others)

- demo of TRSS graphical perf views (and features of highcharts 3rd party graphing tool being used under open-source license)

- centralize and update test documentation (WIP, related: https://github.com/AdoptOpenJDK/TKG/issues/1)

- monthly openjdk-tests meetings to be scheduled in 2020 (see issues labelled with AQAvit meeting label)

- adding support for smart parallelization in TKG / TRSS (#1563)

- overview of Azure Devops (and how TKG runs tests in that environment) (action to Sophia/Lan to get accounts to the Adopt public AzDo to experiment with it for future integration / envisioning a hybrid test farm in Jenkins/AzDo/other combinations where we can maximize our resources but continue to have a seamless triage experience)

- less fun tasks for 2020 include triaging all extended.openjdk tests
- switch over to use API v3 for testing https://github.com/AdoptOpenJDK/openjdk-tests/pull/1532

**Comment by smlambert** [comment]
Closing this as it was just a way to capture the discussion notes.

**Comment by d3r3kk** [comment]
> less fun tasks for 2020 include triaging all extended.openjdk tests

According to whom is this _less fun_ exactly? Hmmmm?

**Comment by smlambert** [comment]
haha, you caught me, its my opinion that it is a 'less fun' task!
