### ISSUE TITLE
Setup issue when running jdk11 openj9 pipeline tests

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-tests#1531]
```
07:00:23  + ./openjdk-tests/get.sh -s /cygdrive/c/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_windows -t /cygdrive/c/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/openjdk-tests -p -r upstream -j 11 -i openj9 --openj9_repo https://github.com/eclipse/openj9.git --openj9_branch master --tkg_repo https://github.com/AdoptOpenJDK/TKG.git --tkg_branch master
07:00:23  get jdk binary...
07:00:24  /cygdrive/c/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/openjdkbinary is not an empty directory, please empty it or specify a different SDK directory.
07:00:24  This directory is used to download SDK resources into it and the script will not overwrite its contents.
```

Running grinders using any source of sdk doesn't cause a problem so something in the pipeline is putting something in this folder before it gets the source or is failing a check. For some reason is only affecting jdk11 openj9 and I'm not sure why

Eg. https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac/118/console

**Comment by adam-thorpe** [comment]
There's a check just before the error statement which is: `"$SDK_RESOURCE" != "upstream"`
but `-r upstream` is passed in?

**Comment by adam-thorpe** [comment]
Oh I see what it is. On the job template, the parameter is still called JenkinsFile not PLATFORM, so -p is not being passed in

**Comment by llxia** [comment]
I regenerated JDK 11 openjdk openj9 tests. Close this issue. Please reopen if the problem still exists.
