### ISSUE TITLE
Test_openjdk8_hs_sanity.external_x86-64_linux is triggered twice a day

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1535]
https://ci.adoptopenjdk.net/view/Test_external/job/Test_openjdk8_hs_sanity.external_x86-64_linux/ is triggered twice daily by https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/ and 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot-jfr/, which will trigger all hotspot 8 external sanity tests job twice daily and test same docker images. Ideally test jobs should be triggered by docker images updates https://github.com/AdoptOpenJDK/openjdk-tests/issues/773

Currently we only have limited resources for external test https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1044 , which makes resources more limited.

**Comment by sophia-guo** [comment]
Would suggest if it's build job of jfr disable sanity.external test job 
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/openjdk8_pipeline.groovy#L43
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/openjdk8_pipeline.groovy#L42

**Comment by smlambert** [comment]
This will need to be raised in the openjdk-build repo.

**Comment by sophia-guo** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1087
