### ISSUE TITLE
Test machines have dependencies on non-standard tooling as default

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-tests#1538]
Spotted while testing on a new AIX machine on [a grinder job](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1649/console):
```
23:55:36  Archiving artifacts
23:55:37  Recording fingerprints
[Pipeline] sh
23:55:39  + tar -zcf openjdk_test_output.tar.gz ./openjdk-tests/TKG/test_output_15785277132074 ./openjdk-tests/TKG/test_output_15785277297854
23:55:39  tar: Not a recognized flag: z
23:55:39  Usage: tar -{c|r|t|u|x} [ -BdDEFhilmopRUsvwZ ] [ -Number ] [ -f TarFil e ]
23:55:39  	   [ -b Blocks ] [ -S [ Feet ] | [ Feet@Density ] | [ Blocksb ] ]
23:55:39  	   [ -L InputList ] [-X ExcludeFile] [ -N Blocks ] [ -C Directory ] File ...
23:55:39  Usage: tar {c|r|t|u|x} [ bBdDEfFhilLXmNopRsSUvwZ[0-9] ] ]
23:55:39  	   [ Blocks ] [ TarFile ] [ InputList ] [ ExcludeFile ] 
23:55:39  	   [ [ Feet ] | [ Feet@Density ] | [ Blocksb ] ] [-C Directory ] File ...
[Pipeline] }
[Pipeline] // timestamps
```
In general, non-OSS operating systems will use "standard" commands and not the GNU variants. We seem  to have code in the test repository that has hard dependencies on GNU-specific options including the `z` option to tar. In general, to extra a tarball `gzip -cd filename.tgz | tar xpf -` will work across platforms.

It would appear that in the past, the AIX boxes have had `/usr/bin/tar`, as supplied with the OS, replaced by a symbolic link to `/opt/freeware/bin/tar` which is the GNU version.

The options to resolve this without changing the defaults on the machine (which could mask real end-user visible issues) are:

1. If we must mandate GNU tar, invoke it as `gtar` where available
2. Modify the code to use `gzip -cd filename.tgz | tar xpf -` or if pipes are not easily doable within the XML scripts, then a  sequence of `gzip -d filename.tgz` then `tar  xpf filename.tar
3. (Least preferred as it can still mask issues!) Put `/opt/freeware/bin` into the `PATH` on AIX before running the test scripts

FYI @sej-jackson since this affects AIX machine setup

**Comment by smlambert** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1592
