### ISSUE TITLE
Issue with playlist.xml: The entity name must immediately follow the '&' in the entity reference.

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-tests#1539]
Tests job is failing on JDK13 x86-64_windows_xl
(Test_openjdk13_j9_extended.system_x86-64_windows_xl#85)

Job: https://ci.adoptopenjdk.net/job/Test_openjdk13_j9_extended.system_x86-64_windows_xl/85/console

21:24:20  Generating make file C:\Users\jenkins\workspace\Test_openjdk13_j9_extended.system_x86-64_windows_xl\openjdk-tests\TKG/../system/openj9-systemtest/openj9.build/autoGen.mk
21:24:20  [Fatal Error] playlist.xml:30:55: The entity name must immediately follow the '&' in the entity reference.
21:24:20  org.xml.sax.SAXParseException; systemId: file:/C:/Users/jenkins/workspace/Test_openjdk13_j9_extended.system_x86-64_windows_xl/openjdk-tests/TKG/../system/openj9-systemtest/openj9.build/playlist.xml; lineNumber: 30; columnNumber: 55; The entity name must immediately follow the '&' in the entity reference.
21:24:20  	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
21:24:20  	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
21:24:20  	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:206)
21:24:20  	at org.testKitGen.MkGen.processPlaylist(MkGen.java:100)
21:24:20  	at org.testKitGen.MkGen.start(MkGen.java:67)
21:24:20  	at org.testKitGen.MkTreeGen.traverse(MkTreeGen.java:78)
21:24:20  	at org.testKitGen.MkTreeGen.traverse(MkTreeGen.java:69)
21:24:20  	at org.testKitGen.MkTreeGen.traverse(MkTreeGen.java:69)
21:24:20  	at org.testKitGen.MkTreeGen.traverse(MkTreeGen.java:69)
21:24:20  	at org.testKitGen.MkTreeGen.start(MkTreeGen.java:27)
21:24:20  	at org.testKitGen.MainRunner.start(MainRunner.java:29)
21:24:20  	at org.testKitGen.MainRunner.main(MainRunner.java:23)
21:24:20  make[1]: *** [makeGen.mk:39: autogen] Error 1
21:24:20  make[1]: Leaving directory '/cygdrive/c/Users/jenkins/workspace/Test_openjdk13_j9_extended.system_x86-64_windows_xl/openjdk-tests/TKG'
21:24:20  make: *** [run_configure.mk:32: testconfig] Error 2

**Comment by sophia-guo** [comment]
https://github.com/eclipse/openj9-systemtest/issues/109
