### ISSUE TITLE
Test_openjdk8_j9_special.functional_x86-64_linux : Malformed target-specific variable definition. 

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-tests#1540]
Failure link : https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_linux/123/console
Public link to the failing test
and ideally extracting relevant info from the failed run (just enough info to run a Grinder), include:

test category, in Grinder equates to BUILD_LIST (functional, systemtest, openjdk, etc): special.functional
test target name, in Grinder equates to TARGET (testCaseName from playlist.xml, jdk_lang, jdk_net, etc):
OS/architecture, in Grinder equates to Jenkinsfile (openjdk_x86-64_linux, openjdk_x86-64_windows, etc): x86-64_linux
public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced:
Optional info
intermittent failure (yes|no):
regression or new test:
if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :
Failure output (captured from console output)
Test name : openjdk-tests/functional/JIT_Test

15:05:24 make[3]: Entering directory /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/functional/JIT_Test' 15:05:24 autoGen.mk:758: *** Malformed target-specific variable definition. Stop. 15:05:24 make[3]: Leaving directory /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/functional/JIT_Test'
15:05:24 make[2]: *** [compile-JIT_Test] Error 2
15:05:24 make[2]: Leaving directory /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/functional' 15:05:24 make[1]: *** [compile-functional] Error 2 15:05:24 make[1]: Leaving directory /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests'
15:05:24 make: *** [compile-..] Error 2

**Comment by smlambert** [comment]
As a 'workaround', so that we can run the special.functional target, I have adjusted the Jenkins job config to set BUILD_LIST=functional/MBCS since all the special test targets live in that directory, so that avoids the compilation of the the JIT_Test material, which fails to compile.  

This is not a long-term solution, we need to understand and fix the compilation issue.  Note, JIT_Test compiles fine in openj9 test jobs, not sure what the difference is.

**Comment by smlambert** [comment]
Relaunched job with workaround here:
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_j9_special.functional_x86-64_linux/125

**Comment by llxia** [comment]
This is a known issue due to the old make version on the machine. Please refer the issue in infra https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/925

**Comment by sophia-guo** [comment]
Yes, machine issue. I reran on test-godaddy-debian8-x64-1 and looks good.
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1053/

**Comment by archanaNogriya** [comment]
I will close this issue in that case

**Comment by archanaNogriya** [comment]
@sophia-guo Should we close this issue, as I understand it is not test related issue but test machine which is covered already here AdoptOpenJDK/openjdk-infrastructure#925?

**Comment by llxia** [comment]
yes, this is not test issue. Close it as the machine issue is covered in  AdoptOpenJDK/openjdk-infrastructure#925
