### ISSUE TITLE
JDK 13 : sanity.perf jobs failing in all platforms 

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-tests#1541]
Failure link : https://ci.adoptopenjdk.net/job/Test_openjdk13_j9_sanity.perf_ppc64le_linux/4/console
Public link to the failing test
and ideally extracting relevant info from the failed run (just enough info to run a Grinder), include:

test category, in Grinder equates to BUILD_LIST (functional, systemtest, openjdk, etc): sanity.perf
test target name, in Grinder equates to TARGET (testCaseName from playlist.xml, jdk_lang, jdk_net, etc): sanity.perf
OS/architecture, in Grinder equates to Jenkinsfile (openjdk_x86-64_linux, openjdk_x86-64_windows, etc): All supported Platforms
public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced:
20:50:42 Run /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdkbinary/j2sdk-image/bin/java -version
20:50:42 openjdk version "13.0.1" 2019-10-15
20:50:42 OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
20:50:42 Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0-m2, JRE 13 Linux ppc64le-64-Bit Compressed References 20200109_145 (JIT enabled, AOT enabled)
20:50:42 OpenJ9 - b8fe619
20:50:42 OMR - 7a1b0239a
20:50:42 JCL - 03236d9eee based on jdk-13.0.1+9)
Optional info
intermittent failure (yes|no):
regression or new test:
if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :
Failure output (captured from console output)
20:51:24 [javac] Compiling 8 source files to /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/perf/bumbleBench/bumblebench
20:51:24 [javac] warning: [options] bootstrap class path not set in conjunction with -source 6
20:51:24 [javac] error: Source option 6 is no longer supported. Use 7 or later.
20:51:24 [javac] error: Target option 6 is no longer supported. Use 7 or later.
20:51:24
20:51:24 BUILD FAILED
20:51:24 /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/TKG/scripts/build_test.xml:58: The following error occurred while executing this line:
20:51:24 /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/perf/build.xml:31: The following error occurred while executing this line:
20:51:24 /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/perf/bumbleBench/build.xml:59: The following error occurred while executing this line:
20:51:24 /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/perf/bumbleBench/build.xml:49: The following error occurred while executing this line:
20:51:24 /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/perf/bumbleBench/bumblebench/build.xml:47: Compile failed; see the compiler error output for details.
20:51:24
20:51:24 Total time: 3 seconds
20:51:24 1
20:51:24 makefile:79: recipe for target 'compile' failed
20:51:24 make: *** [compile] Error 1
[Pipeline] }
20:51:24 $ ssh-agent -k
20:51:24 unset SSH_AUTH_SOCK;
20:51:24 unset SSH_AGENT_PID;
20:51:24 echo Agent pid 27860 killed;
20:51:25 [ssh-agent] Stopped.
[Pipeline] // sshagent

**Comment by llxia** [comment]
I think I accidentally generated these `Test_openjdk13_j9_sanity.perf` jobs. Above is the compilation error (Source option 6 is no longer supported), so these jobs are not ready to run yet. 

@ShelleyLambert could you please delete both [Test_openjdk13_j9_sanity.perf](https://ci.adoptopenjdk.net/job/Test_openjdk13_j9_extended.perf_x86-64_linux/search/?q=Test_openjdk11_j9_sanity.perf&Jenkins-Crumb=7a563b17f56f10a696e64c1b7fbebefb59cebd009cb9fdd1c122bdfea4d03f01) and [Test_openjdk13_j9_extended.perf](https://ci.adoptopenjdk.net/job/Test_openjdk13_j9_extended.perf_x86-64_linux/search/?q=Test_openjdk13_j9_extended.perf&Jenkins-Crumb=7a563b17f56f10a696e64c1b7fbebefb59cebd009cb9fdd1c122bdfea4d03f01)? Thanks

**Comment by smlambert** [comment]
Instead of deleting them, I have updated the config with BUILD_LIST=perf/dacapo (where the main sanity targets live), so they can run without hitting the bumblebench compilation issue, https://github.com/AdoptOpenJDK/bumblebench/issues/17.  

We will need to find someone to work on fixing that bbench issue that @piyush286 raised, maybe someone from PMA team?

**Comment by piyush286** [comment]
@smlambert I'll try to have a fix for it by Monday if not today.

**Comment by smlambert** [comment]
Much appreciated @piyush286 !

**Comment by smlambert** [comment]
This has been addressed by https://github.com/AdoptOpenJDK/bumblebench/pull/20
