### ISSUE TITLE
external functional-test get compilation error with openj9

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1549]
**Describe the bug**
External functional-test get compilation error with openj9 jdk8

**To Reproduce**
Rerun link https://ci.adoptopenjdk.net//job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=external/functional-test&PLATFORM=x86-64_linux&TARGET=special&SDK_RESOURCE=nightly

```
16:55:33  compile:
16:55:33       [echo] Ant version is Apache Ant(TM) version 1.10.5 compiled on March 28 2019
16:55:33       [echo] ============COMPILER SETTINGS============
16:55:33       [echo] ===fork:                         yes
16:55:33       [echo] ===executable:                   /opt/java/openjdk/bin/javac
16:55:33       [echo] ===debug:                        on
16:55:33       [echo] ===destdir:                      /openj9/test/TKG/../../jvmtest/functional/CacheManagement
16:55:33      [javac] Compiling 4 source files to /openj9/test/functional/CacheManagement/testcodebuild
16:55:35      [javac] Compiling 4 source files to /openj9/test/functional/CacheManagement/bin
16:55:35      [javac] Compiling 98 source files to /openj9/test/functional/CacheManagement/bin
16:55:42      [javac] /openj9/test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java:232: error: cannot find symbol
16:55:42      [javac] 							if (cacheInfo.getCacheLayer() != 0) {
16:55:42      [javac] 							             ^
16:55:42      [javac]   symbol:   method getCacheLayer()
16:55:42      [javac]   location: variable cacheInfo of type SharedClassCacheInfo
16:55:42      [javac] /openj9/test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java:234: error: cannot find symbol
16:55:42      [javac] 								if ((cacheInfo.getCacheName().equals("cache3_multilayercache")) && (1 == 
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sophia-guo** [comment]
The reason is default latest openjdk8-openj9 docker version is:

```
17:21:48  System.getProperty('java.fullversion')=1.8.0_222-b10
17:21:48  JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190717_368 (JIT enabled, AOT enabled)
17:21:48  OpenJ9   - 0f66c6431
17:21:48  OMR      - ec782f26
17:21:48  JCL      - f147086df1e based on jdk8u222-b10

```

With [Support multiple shared classes caches in single JVM](https://github.com/eclipse/openj9/issues/5480) SharedClassCacheInfo.java has updated like https://github.com/eclipse/openj9/commit/1f103aa937447045e06b3ea13fd5bc1f333566cc. That is saying test code is inconsistent with jdk code.

**Comment by sophia-guo** [comment]
[Trigger Docker builds from main build pipelines](https://github.com/AdoptOpenJDK/openjdk-build/issues/1123) would be easy for test is consistent with sdk ( SHA, releast tag)

**Comment by sophia-guo** [comment]
Probably also need to figure out the frequency and plan of the docker builds as confused why the latest openjdk8-openj9 JCL is jdk8u222-b10, is that a second latest release version?

**Comment by sophia-guo** [comment]
@dinogun For external test we expect that with latest tag we should get comparatively latest openjdk docker image. Is the following result expected?

```
sophiaguos-mbp:DockerLearning sophiag$ docker run --rm -it adoptopenjdk/openjdk8-openj9:latest java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190717_368 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - f147086df1e based on jdk8u222-b10)
```
If yes, which tag should I use to get the latest image?

**Comment by sophia-guo** [comment]
According to https://github.com/AdoptOpenJDK/openjdk-docker and try nightly tag got 

```
docker run --rm -it adoptopenjdk/openjdk8-openj9:nightly java -version

sophiaguos-mbp:DockerLearning sophiag$ docker run --rm -it adoptopenjdk/openjdk8-openj9:nightly java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-202001020429-b05)
Eclipse OpenJ9 VM (build master-a873af9c2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200102_486 (JIT enabled, AOT enabled)
OpenJ9   - a873af9c2
OMR      - ce7fdb230
JCL      - fbdf154d48b based on jdk8u242-b05)
```
Current external functional and system test are target the latest jdk. Probably using nightly tag is more reasonable.

**Comment by sophia-guo** [comment]
@ShelleyLambert  as now external tests are triggered nighlty by upstream build jobs | weekly by schedule probably we should target nightly JDK docker image instead of releases (latest)  by default?

**Comment by smlambert** [comment]
Completely agree.

**Comment by smlambert** [comment]
Raised issue to ask about what 'latest' tag should return:  https://github.com/AdoptOpenJDK/openjdk-docker/issues/267
