### ISSUE TITLE
Grinder rerun link missing DOCKER_REQUIRED parameter

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1550]
**Describe the bug**
Grinder rerun link missing DOCKER_REQUIRED parameter. When original job requires docker the rerun link doesn't set parameter DOCKER_REQUIRED, which will cause external jobs run on machine without docker installed or without docker correctly installed.

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):
1. Go to https://ci.adoptopenjdk.net/job/Grinder/
2. Run any external job
3. Click the re-run link
4. Check the re-run job parameters DOCKER_REQUIRED is not set

**Expected behavior**
Re-run link should set exactly same parameters as original run.

**Additional context**
Example:
Original build: https://ci.adoptopenjdk.net/job/Grinder/1744/
rerun link: https://ci.adoptopenjdk.net//job/Grinder/parambuild/?JDK_VERSION=&JDK_IMPL=&BUILD_LIST=external/quarkus&PLATFORM=x86-64_linux&TARGET=quarkus_java_test&SDK_RESOURCE=nightly

**Comment by smlambert** [comment]
I think it also does not grab the ADOPTOPENJDK_REPO and ADOPTOPENJDK_BRANCH info.

**Comment by sophia-guo** [comment]
I guess probably for most parameters if it is different from the default value it need to be added to the re-run link.
