### ISSUE TITLE
Support for smart parallelization in TKG / TRSS

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#1563]
We would like to support for smart parallelization in TKG / TRSS, so that we can break test build into any number of smaller builds (based on test during and the number of machines) and run them in parallel. The goal is to achieve a balanced load and optimal overall testing throughput.

ToDo:

- TRSS provides API to divide tests into a number of buckets (based on test
historical duration) to get optimal throughput overall  https://github.com/AdoptOpenJDK/openjdk-test-tools/pull/146
- TKG generates makefiles on demand https://github.com/AdoptOpenJDK/TKG/issues/25
- Parse TRSS API output and run TKG with the tests
- Handle the case where TRSS is not available (#1801 )

**Comment by smlambert** [comment]
As we revise and update the test pipeline scripts to support this feature, I thought it would be good to capture any of the known specially configured test jobs (parameters different than expected defaults) in one spot, to make sure we account for them in the test pipeline revisions.  

| [platform](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_tests)\testGroup| openjdk | external | system | perf | functional | jck | NOTES |
| --- | --- | --- | --- | --- | --- | --- | --- |
| x86-64_linux |  |  |  | LABEL=ci.role.perf&& | BUILD_LIST=functional/subdir |   |  functional subdirectories was defined to avoid issue of running tests on machines with older ant versions JIT_Test dir needs new ant |
|x86-64_mac  |  |  |  |  LABEL=ci.role.perf&& |  |   |
|s390x_linux  |  |  |  |  |  |   |
| ppc64_linux |  |  |  |  |  |   |
| s390_zos |  |  |  |  |  |  EXTRA_OPTIONS=attachAPI |


Some test jobs were defined as weekly and in those cases use `@weekly` in Jenkins scheduler and so must also have default SDK_RESOURCE=nightly .  We can simplify this by updating build pipeline scripts to run sanity level testing nightly, but on weekends switch to extended level tests.  For release builds, ultimately build pipelines should run both sanity and extended levels.

**Comment by llxia** [comment]
PR https://github.com/AdoptOpenJDK/TKG/pull/67

**Comment by smlambert** [comment]
It seems like all of the related changes are in, are we ready to close this one?

**Comment by llxia** [comment]
Yes, this can be closed.
