### ISSUE TITLE
Archive core files from /cores on Mac from testing

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-tests#1564]
Mac can put core files into the /cores directory, which is different from other platforms. Any cores produced by running testing need to be archived.

Also, the /cores directory should be cleared after every test job. Otherwise once a core is created, it will be archived in every subsequent job that runs on the machine

**Comment by smlambert** [comment]
This work will likely actually be done in the TKG repo, but tracking here to have visibility.

**Comment by sophia-guo** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1682

**Comment by llxia** [comment]
@LongyuZhang Could you please take a look at this issue? Thanks
The code should be updated in TKG repo https://github.com/AdoptOpenJDK/TKG/blob/master/scripts/moveDmp.pl

**Comment by LongyuZhang** [comment]
In PR https://github.com/AdoptOpenJDK/TKG/pull/50, we have been able to archive build failure core dump from default folder to output folder on Internal Jenkins Mac machine (Internal Grinder_TKG/381), but when running the same code on Adopt Jenkins Mac machine, it cannot generate core dump (https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1249), with error message:
```
15:02:04       [java] JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/Grinder_Sandbox/openjdk-tests/functional/cmdLineTests/lockWordAlignment/core.20200408.120204.84960.0001.dmp' in response to an event
15:02:11       [java] JVMDUMP012E Error in System dump: The core file created by child process with pid = 84965 was not found. Expected to find core file with name "/cores/core.84965"
```
I checked the permission on /cores, looks like the internal and adopt Mac has different settings.
```
Adopt Mac Jenknins machine Permissions for /cores folder (https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1245/console)
15:17:35  destination /cores folder: total 0
15:17:35   drwxrwxr-t   2 root  admin   64 Sep 24  2018 .
15:17:35   drwxr-xr-x@ 31 root  wheel  992 Jul 16  2019 ..
```
```
Internal Mac Jenkins machine Permisison for /cores folder (Grinder_TKG/396)
15:25:10  destination /cores folder: total 0
15:25:10   drwxrwxr-t@  2 root  staff    68 Apr  8 15:25 .
15:25:10   drwxr-xr-x  30 root  wheel  1088 Oct  4  2019 ..
```
And while I manually set the adopt mac core dump path to /cores, I got:
```
JVMDUMP030W Cannot write dump to file /cores/core.20200408.115419.84134.0001.dmp: Permission denied
```
@jdekonin Could you check if it is related to this issue (https://github.ibm.com/runtimes/infrastructure/issues/994) and did you change the internal mac settings and get the internal worked? Really appreciate!

**Comment by jdekonin** [comment]
That internal to IBM issue, which isn't resolved as there was never an official agreement on the solution, also has details captured in this issue @ https://github.com/eclipse/openj9/issues/3791#issuecomment-447148286

This appears to be the exact same issue yes.

**Comment by LongyuZhang** [comment]
@jdekonin Thanks for clarifying the problem, and mentioning the related issue https://github.com/eclipse/openj9/issues/3791. 
In that issue, Lan has tested running GCCheck on internal Mac, the core dump is working now with your previous change of /cores user permission```chown -R root:staff /core```.
Would it be possible to do the same changes on the Adopt Mac Jenkins machine to get it work too? Thanks.

**Comment by jdekonin** [comment]
That would be a possible solution yes, but I cannot perform as I don't have access to the Adopt machines.  This might be good to raise or transfer to AdoptOpenJDK/openjdk-infrastructure
fyi @sxa

**Comment by smlambert** [comment]
I believe we have made the correct changes on the test side, so will close this.  

There remains an open issue https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1282 that would be needed for us to gather cores from Adopt mac machines, we are able to gather cores on machines that have the proper permission setting.
