### ISSUE TITLE
Ability to Set CPU Affinities for Benchmarking

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-tests#1587]
### Problem Description

Currently, we run all benchmarks without setting any CPU affinities. This can have major impact on performance for some benchmarks. 

If we don't bind threads to CPUs, then threads can be executed on any CPU rather than on some designated CPU. Using CPU affinity reduces cache issues and improves the perf results by making them more consistent. Without processor affinity, we could run into performance degradations and fluctuations because of events such as cache misses. Anyway, I won't get into the benefits of using CPU affinity any further since it's beyond the scope of this issue.

In short, we should have the capability to set affinities for some benchmarks, which require them to produce reliable results. 

### Common Scenario for Using CPU Affinity

CPU affinity is extremely useful especially when we're running multiple services just one machine rather than using different machine for different services. 

For example: In our internal perf testing, we run benchmarks such as Liberty and Spark on 2 machines:
1st machine: Server
2nd machine: Client + DB
Those machines are physically connected using the 10 Gbps network to avoid network latencies.
I believe that physically connecting machines adds complexity and other requirements (i.e. SSH keys, network connections, location) and might be going against our goal of simplifying things. Hence, if we have a machine with more cores, then we could pin threads using affinity tools. For example:
2 cores (+2 logical): Liberty
Other 4 cores (+4 logical): Client + DB

### Possible Solutions

Before running any benchmarks, we need to get the relevant info for setting CPU affinities from the machine. We can possibly use TKG (https://github.com/AdoptOpenJDK/TKG/tree/master/src/org/openj9/envInfo) as proposed in https://github.com/AdoptOpenJDK/TKG/issues/34.

Once we have the relevant info, we should dynamically generate the CPU affinity command for different CPU affinity tools such as Numactl, Taskset, Execrset and others that are used on various platforms. 

For dynamic generation of those commands, we would need to do something similar to what we did on PerfNext as part of https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/32. You can refer the relevant lines below.

https://github.com/AdoptOpenJDK/openjdk-test-tools/blob/2f3d6b8781eae736157ee953dc7eb408aa64a06b/PerfNext/public/lib/js/util.js#L544-L648

We'll need to decide on how we want to do this for openjdk-tests. I was thinking that we could have a bash script or something that requires all relevant info such as number of physical and logical CPUs to generate the affinities commands. We'll need to give this a thought. 

We should have relevant affinity tool supported by the OS installed on the machine as a prerequisite. We can create an infrastructure info after we are done discussing this issue and have a game plan.

### Related Issues

- Get Relevant Machine Info for Setting CPU Affinities (https://github.com/AdoptOpenJDK/TKG/issues/34)

### Other Relevant Snippets

https://github.com/AdoptOpenJDK/TKG/blob/84b082615e8cf443f3ce07e2eea9a334dbd8f52e/src/org/openj9/envInfo/EnvDetector.java#L75-L78

Any testCase with name `MachineInfo`. Example: https://github.com/AdoptOpenJDK/openjdk-tests/blob/31af46981e9864adb5e723eebfac0babd86f4372/system/daaLoadTest/playlist.xml#L9-L11

**Comment by piyush286** [comment]
@smlambert I would really appreciate your suggestions on this issue. Maybe we can discuss this in our meeting tmr if we have time. Otherwise, we can schedule one whenever you'll be available.

**Comment by smlambert** [comment]
Part 1: augment MachineInfo.java to include CPU affinity information - makes sense

Part 2: method for generating the affinity commands (and then presumably running them)  -  can talk about implementation details, but since requirement is to a) get the MachineInfo, b) make a calculation based on MachineInfo, then 3) execute a command.   Whether its a script or Java code, it could be run as an initial target in build.xml for test directories that will use it.

One thing to note, if a machine does not have affinity tools (Numactl, Taskset, Execrset...) installed, the approach should gracefully handle it.

**Comment by piyush286** [comment]
Has been completed in https://github.com/AdoptOpenJDK/openjdk-tests/pull/1917.
