### ISSUE TITLE
Build.xml files don't take into account jdk14 new naming convention

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-tests#1610]
New jdk14 repo for hotspot builds is at https://github.com/AdoptOpenJDK/openjdk-jdk14, not jdk14u, so `build.xml` scripts cannot find it.

Eg.
```
git clone --depth 1 -q -b dev https://github.com/AdoptOpenJDK/openjdk-jdk14u.git
```

**Comment by adam-thorpe** [comment]
I have a quick fix for this, but because you can't do integer comparisons in xml, we would have to manually check for each version past 14

**Comment by smlambert** [comment]
I am presuming you can add a check in [this block](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml#L83-L85), so that if:
`<IsLessThan  arg1="${JDK_VERSION}" arg2="14" />` then append 'u'

**Comment by karianna** [comment]
Yep we typically move to the `u` naming once the version goes GA
