### ISSUE TITLE
JTReg Fail on arm32: java/net/URL/OpenStream.java

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1637]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1548

- test category, sanity.openjdk.jdk_net_0
- OS/architecture, aarch32_linux
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: 
```
02:48:13  openjdk version "1.8.0_242"
02:48:13  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-202001150439-b06)
02:48:13  OpenJDK Client VM (AdoptOpenJDK)(build 25.242-b06, mixed mode)
```
- Created via non-JIT VM for the JDK8-hotspot-arm32 GA release (see linked issue)
- This has been [excluded](https://github.com/AdoptOpenJDK/openjdk-tests/blob/64d0564a253475df0c9c2ff04ed6a0ed74250ec4/openjdk/ProblemList_openjdk11.txt#L83) on all linux distros for JDK11+  

```
02:59:35  STDERR:
02:59:35  java.lang.RuntimeException: Expected UnknownHostException to be thrown
02:59:35  	at OpenStream.main(OpenStream.java:45)
02:59:35  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:59:35  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:59:35  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:59:35  	at java.lang.reflect.Method.invoke(Method.java:498)
02:59:35  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
02:59:35  	at java.lang.Thread.run(Thread.java:748)
```

**Comment by smlambert** [comment]
Not seeing this failure reproduce in Grinders (example: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4240) so will close.

These tests were not excluded using the correct OS-ARCH name (used linux-aarch32 instead of linux-arm), entries in problem lists will be removed as part of https://github.com/AdoptOpenJDK/openjdk-tests/pull/2018.
