### ISSUE TITLE
Rename external tests

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#1643]
In order to have the same naming convention (https://github.com/AdoptOpenJDK/openjdk-tests/issues/1553) and be able to process easily on TRSS side, I am going to rename external tests to `Test_openjdk<JDK_VERSION>_<IMPL>_<LEVEL>.<GROUP>_<PLATFORM>_<SUBDIR>_<EXTRA>`. `SUBDIR` should not contain `_`.

For example, [Test_openjdk11_j9_sanity.external_openliberty-mp-tck_x86-64_linux](https://ci.adoptopenjdk.net/view/Test_external/job/Test_openjdk11_j9_sanity.external_openliberty-mp-tck_x86-64_linux/) will be rename to `Test_openjdk11_j9_sanity.external_x86-64_linux_openliberty-mp-tck`

**Comment by llxia** [comment]
Tests under https://ci.adoptopenjdk.net/view/Test_external/ are renamed

**Comment by smlambert** [comment]
Thanks @llxia !

**Comment by smlambert** [comment]
Closing as tests are renamed now.
