### ISSUE TITLE
jdk_nio_0 in Test_openjdk8_hs_sanity.openjdk_s390x_linux takes 2 - 3 hrs to run

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1647]
**Test Info**
Test Name: jdk_nio_0
Test Duration: 2 hr 24 min 
Machine: test-marist-ubuntu1604-s390x-3
TRSS link for the test output: https://trss.adoptopenjdk.net/output/test?id=5e50405bc044422f31fd3b22

**Build Info**
Build Name: Test_openjdk8_hs_sanity.openjdk_s390x_linux
Jenkins Build start time: Feb 20 2020, 11:49 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_s390x_linux/124/
TRSS link for the build: https://trss.adoptopenjdk.net/allTestsInfo?buildId=5e503fd0c044422f31fd39b0

This test target, in particular 4 test classes within it are consistently taking a very long time to run on s390x_linux platform.

If you look at https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_s390x_linux/125/testReport/ and sort tests by Duration, you see some of the big offenders... (jdk_nio and jdk_security1 targets)
<img width="701" alt="Screen Shot 2020-02-22 at 10 26 50 AM" src="https://user-images.githubusercontent.com/2836948/75096548-9e5ed500-556e-11ea-81d2-e7467e72a2ef.png">

HS:
FindDecoderBugs 1 hr 31min
TestStringCoding 58min
FindEncoderBugs 43 min
FindOneCharEncoderBugs 15min

For comparison J9 from the same jdk8 pipeline build, https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux/118/testReport/:
FindDecoderBugs 31sec
FindEncoderBugs 18sec
FindOneCharEncoderBugs 8.1sec

Next steps:
Need to check how Upstream builds look.  
Run on all s390x machines, need to rule out if only slow on certain machines (to rule out machine issue).
Look at test code ([TestStringCoding](https://github.com/openjdk/jdk11u/blob/master/test/jdk/sun/nio/cs/TestStringCoding.java)) and [bugs listed in it](https://github.com/openjdk/jdk11u/blob/master/test/jdk/sun/nio/cs/TestStringCoding.java#L25) (and in bugs DB in event its already reported/known)

**Comment by jerboaa** [comment]
@smlambert That's expected. OpenJDK 8u on s390x is Zero (no JIT). I'd suggest to run a limited set of tests for this combination.

**Comment by smlambert** [comment]
Thanks for the clarification @jerboaa, I will update the build pipeline scripts so these test jobs are not triggered nightly.
