### ISSUE TITLE
Test_openjdk8_hs_sanity.system_x86-64_windows_upstream/openjdk-tests///..//jvmtest\system\mathLoadTest/../\openj9-systemtest: No such file or directory

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-tests#1654]
I'm seeing weird test failures for upstream sanity.system tests:

```
08:37:05  Uncaught exception from user code:
08:37:05  	C:/Users/jenkins/workspace/Test_openjdk8_hs_sanity.system_x86-64_windows_upstream/openjdk-tests///..//jvmtest\system\mathLoadTest/../\openj9-systemtest: No such file or directory at C:/Users/jenkins/workspace/Test_openjdk8_hs_sanity.system_x86-64_windows_upstream/openjdk-tests///..//jvmtest\system\mathLoadTest/../\stf\stf.core\scripts\stf.pl line 809.
08:37:05  	Cwd::_croak("C:/Users/jenkins/workspace/Test_openjdk8_hs_sanity.system_x86"...) called at C:/Strawberry/perl/lib/Cwd.pm line 505
08:37:05  	Cwd::fast_abs_path("C:/Users/jenkins/workspace/Test_openjdk8_hs_sanity.system_x86"...) called at C:/Users/jenkins/workspace/Test_openjdk8_hs_sanity.system_x86-64_windows_upstream/openjdk-tests///..//jvmtest\system\mathLoadTest/../\stf\stf.core\scripts\stf.pl line 809
08:37:05  	main::make_paths_absolute("test-root", "C:/Users/jenkins/workspace/Test_openjdk8_hs_sanity.system_x86"..., "") called at C:/Users/jenkins/workspace/Test_openjdk8_hs_sanity.system_x86-64_windows_upstream/openjdk-tests///..//jvmtest\system\mathLoadTest/../\stf\stf.core\scripts\stf.pl line 397
```

Examples:
https://ci.adoptopenjdk.net/view/Test_upstream/job/Test_openjdk8_hs_sanity.system_x86-64_windows_upstream/29/
https://ci.adoptopenjdk.net/view/Test_upstream/job/Test_openjdk8_hs_sanity.system_x86-64_linux_upstream/29/

This looks like a test setup issue to me. Thoughts?

**Comment by jerboaa** [comment]
@smlambert Any ideas?

**Comment by adam-thorpe** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/commit/f4d2bd9ca7c4f57b02ce7bd6abd1f2096433a7a9 ?

**Comment by lumpfish** [comment]
Looks like https://github.com/AdoptOpenJDK/openjdk-tests/commit/f4d2bd9ca7c4f57b02ce7bd6abd1f2096433a7a9 might have added the openj9-systemtests as a location to look for tests for hotspot builds as well as openj9 builds.  Those tests are not built when testing hotspot (the apis they test do not exist).

**Comment by smlambert** [comment]
I think https://github.com/AdoptOpenJDK/openjdk-tests/issues/1654#issuecomment-591890702 is the correct assessment 

@Mesbah-Alam can you please take a look and correct

**Comment by Mesbah-Alam** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1654#issuecomment-591890702 - is indeed the reason. I'll create a fix.
