### ISSUE TITLE
Using github action running AQA tests

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1658]
Initial 'AQA' github action, which can be used to run AQA tests similar to the tests running in AdoptOpenJDK CI. 

Initial version: https://github.com/sophia-guo/runaqa

**Comment by sophia-guo** [comment]
Tested with openjdk and functional tests on linux and mac. 
 
Windows hit the issue - can't autoset SPEC, which may be cygwin related (github hosted windows doesn't have cygwin installed) or file writing issue. Need to investigate.

**Comment by sophia-guo** [comment]
Support github hosted jdk or customized installed sdk.

**Comment by sophia-guo** [comment]
Haven't released or tagged. For trying can use sophia-guo/runaqa@master

**Comment by sophia-guo** [comment]
Released v1. Using sophia-guo/runaqa@v1

**Comment by smlambert** [comment]
@sophia-guo - the action is looking great!

we can now populate this repo with the contents of your personal one: https://github.com/AdoptOpenJDK/run-aqa

**Comment by smlambert** [comment]
I think we can close this item now and track any remaining runaqa updates in the run-aqa repo.  Thanks @sophia-guo !
