### ISSUE TITLE
AQAvit meeting - March 4, 2020 Agenda and Minutes

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1662]
AQA vit Meeting
Wednesday, Mar 4, 2020 11:30 am | 30 minutes | (UTC-05:00) Eastern Time (US & Canada)  
https://ibm.webex.com/ibm/j.php?MTID=mca68b43b418dd3280165279b4c800c14  

Join by phone  
1-844-531-0958 United States Toll Free  
Access code: 927 236 656
If asked for a password: Password: adoptQA! (23678720 from phones) 

Agenda topics:
- https://github.com/AdoptOpenJDK/openjdk-tests/pull/1660, enable the generation test Docker images for all docker image tags - @smlambert and @james-crowley  
- 'Run AQA' GitHub action update, ready for some beta testing https://github.com/AdoptOpenJDK/openjdk-tests/issues/1658 - @sophia-guo 
- TRSS, [support AzDo](https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/208) and video & [example for how to add open benchmark parsers](https://github.com/AdoptOpenJDK/openjdk-test-tools/pull/205) - @llxia 
- System test - @Mesbah-Alam 
  - Simplify playlist command lines by using command template https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/328
  - Use a common minimum Mauve load for all SDK versions and platforms https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/331
- Brief review of DevNexus - @smlambert 

Any other verification business?

**Comment by piyush286** [comment]
@smlambert Seems like a typo: `Wednesday, Mar 2`.

**Comment by smlambert** [comment]
Good catch @piyush286, thanks!

**Comment by smlambert** [comment]
Minutes from today:
- overview of how we are expanding out the external testing (demo of running external tests locally, which is then also possible in Grinder remembering to set DOCKER_REQUIRED=true and DOCKERIMAGE_TAG=[dockertag_to_base_from](https://github.com/AdoptOpenJDK/openjdk-docker#unofficial-images-docker-image-build-types-and-associated-tags))
- RunAQA github action demo, and call for people to try it (beta testers!) and and give feedback
- Show how to support a new benchmark in TRSS (demo, showing the 4 files that need updating to add a new benchmark, 2 for server-side, 2 for client-side, see https://github.com/AdoptOpenJDK/openjdk-test-tools/pull/205 for the example used)
- review of a couple of recent changes in system test material
- short re-do of DevNexus AQA talk to be recorded and shared here

Thanks all for joining, asking questions and sharing!

**Comment by smlambert** [comment]
Recording link:  https://youtu.be/JVGPdIIbA3Q
