### ISSUE TITLE
jdk14 repo is now jdk14u - update build.xml script accordingly

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1681]
As per this PR https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml#L91, we will have to ensure we are pulling test material from same.  

See https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml#L91-L94 for where a change is required.

**Comment by SwathiKalahastri** [comment]
Working on this issue

**Comment by smlambert** [comment]
hi @SwathiKalahastri - as a very short-term measure, feel free to simply add 
`<equals arg1="${JDK_VERSION}" arg2="14" />`  directly after [line 91 of the openjdk/build.xml](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml#L91) file.

Ultimately we can future-proof this by adding a few extra checks in this ant script, but I did not intend to do that extra checking as part of a PR for this issue.

**Comment by SwathiKalahastri** [comment]
PR created.
