### ISSUE TITLE
Add JaCoCo test suite to the external group

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1697]
Thanks to the request of community members who have noticed that [JaCoCo](https://github.com/jacoco/jacoco) tests find a lot of openjdk issues, so they would be a good set to include in our external test runs (original list captured in issue #172.

The instruction how to run JaCoCo builds (tests included): https://www.jacoco.org/jacoco/trunk/doc/build.html

Note: OpenJDK issues found by this suite typically have a "jacoco-found" tag: https://bugs.openjdk.java.net/secure/IssueNavigator.jspa?reset=true&jqlQuery=labels+%3D+jacoco-found

**Comment by llxia** [comment]
Thanks to @nikolamilijevic1 , JaCoCo test is added.

**Comment by smlambert** [comment]
Thanks so much for all of your wonderful contributions over your work term and SoC term @nikolamilijevic1 !!  🥇

**Comment by nikolamilijevic1** [comment]
> Thanks so much for all of your wonderful contributions over your work term and SoC term @nikolamilijevic1 !! 🥇

Thank you for your kind words Shelley! @ShelleyLambert
