### ISSUE TITLE
Add new test nodes in Jenkins

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#17]
We'd like to start testing on other platforms also, and to try out running tests in parallel.  So a couple additional linux_x86-64 nodes and some for other platform testing will be good.  Priority on adding more linux test nodes.

**Comment by karianna** [comment]
@smlambert We're still struggling with the windows build so until that's sorted we'll have to wait on that.  For the Mac build I think we have a couple of nodes so one could go to test.  Not sure on the less common variants of Linux (s390 etc).  How much CPU/RAM/Disk do you need for these you think?

**Comment by smlambert** [comment]
Tim mentioned spinning up some new Packet VM for the x86-64_linux test build.  I copied the ansible/playbooks from openjdk-builds to openjdk-tests and added test tools to the ubuntu yml file, do not know how to test it or spin up new Packet VMs, hoping someone can do it or show me how.  
More than one test machine for linux-x86-64 will allow us to test the parallel test stuff.

After that, whichever platform we get test going on next, does not matter to me which one.  Choose by excess numbers of available machines, or by urgency for testing...

**Comment by karianna** [comment]
@gdams Can you take @smlambert through provisioning machines / nodes?  We should probably write this process up as well.

**Comment by smlambert** [comment]
@sophia-guo has been learning how to configure machines via the ansible scripts (and she has written up some instructions for it, which she could likely put in a README in the openjdk-infrastructure repo).  I am going to close this item, as we will discuss upcoming machines at our Thursday calls, and track it likely through the infra repo.
