### ISSUE TITLE
Update get.sh to install all the prerequisites 

### ISSUE THREAD

**Issue by chandrams** [AdoptOpenJDK/openjdk-tests#170]
make -f run_configure.mk, make and make test fail if the below prerequisites are not installed. Update get.sh to install all the prerequisites

Install the below Prerequisites 
1) Install Text/CSV.pm 
/usr/bin/perl -MCPAN -e'install Text::CSV'

2) Install Ant
wget http://redrockdigimark.com/apachemirror//ant/binaries/apache-ant-1.10.1-bin.tar.gz

3) Download ant-contrib.jar and copy it to ant/lib directory
https://sourceforge.net/projects/ant-contrib/files/ant-contrib/

**Comment by sophia-guo** [comment]
Those are system prerequisites, which should not be done by get.sh. We are going to update readme to add "prerequisites" part.
