### ISSUE TITLE
sanity.external is unstable

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1704]
**Describe the bug**
Ref https://github.com/AdoptOpenJDK/openjdk-tests/issues/1703
sanity.external is currently failing on external/thorntail-mp-tck (thorntail_microprofile_tck_0) and external/tomee (tomee_test_0)

**To Reproduce**
Rebuild one of these two links:
https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=external/thorntail-mp-tck&PLATFORM=x86-64_linux&TARGET=thorntail_microprofile_tck_0

https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=external/tomee&PLATFORM=x86-64_linux&TARGET=tomee_test_0

**Expected behavior**
Tests pass

**Screenshots**
THORNTAIL
[throntailFailure.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4408067/throntailFailure.txt)

TOMEE
```
18:12:25  Unable to recognize DOCKER_OS from DOCKERIMAGE_TAG = --version!
18:12:25  Unable to find image 'adoptopenjdk-derby-test:8-jdk-ubuntu-openj9-full' locally
18:12:26  docker: Error response from daemon: pull access denied for adoptopenjdk-derby-test, repository does not exist or may require 'docker login'.
18:12:26  See 'docker run --help'.
18:12:26  
18:12:26  tomee_test_0_FAILED
```

**Comment by smlambert** [comment]
I need to update the test jobs to use default value for DOCKERIMAGE_TAG=ubuntu (related to us changing to generate test Dockerfiles on the fly, in the past used the ubuntu-based Dockerfiles in the openjdk-tests repo).
