### ISSUE TITLE
Add test target for StringIndexOfStringBench 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1714]
Relating to https://github.com/AdoptOpenJDK/bumblebench/pull/10, we can add an associated target for that new benchmark called StringIndexOfStringBench, adding an entry in the perf/bumbleBench/playlist.xml file, similar to the [entry for StringIndexOfBench](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/perf/bumbleBench/playlist.xml#L539-L548).

**Comment by sobirada** [comment]
I will be working on this issue
