### ISSUE TITLE
JTReg Fail on aix: com/sun/jdi/EvalArraysAsList.sh

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1718]
https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/test/com/sun/jdi/EvalArraysAsList.sh is failing on jdk8 hotspot aix runs since 31/03/2020. Fails due to a syntax error in the test. 

There is a lot of history on JBS for this bug and also some [soloutions](https://bugs.openjdk.java.net/browse/JDK-8207766) but only on jdk11+. This would need to be backported to jdk8 if this test is to pass

```
09:44:40  STDERR:
09:44:40  ShellScaffold.sh: Version
09:44:40  EvalArraysAsList.java:4: error: ')' expected
09:44:40          System.out.println("java.util.Arrays.asList(null, "a") returns: " + l);
09:44:40                                                             ^
09:44:40  EvalArraysAsList.java:4: error: not a statement
09:44:40          System.out.println("java.util.Arrays.asList(null, "a") returns: " + l);
09:44:40                                                                            ^
09:44:40  EvalArraysAsList.java:4: error: ';' expected
09:44:40          System.out.println("java.util.Arrays.asList(null, "a") returns: " + l);
09:44:40                                                                               ^
09:44:40  3 errors
```

Grinder Rebuild: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=hotspot&BUILD_LIST=openjdk&PLATFORM=ppc64_aix&CUSTOM_TARGET=jdk/test/com/sun/jdi/EvalArraysAsList.sh&TARGET=jdk_custom_0

**Comment by M-Davies** [comment]
Exclude PR while local testing is underway https://github.com/AdoptOpenJDK/openjdk-tests/pull/1719

**Comment by M-Davies** [comment]
I managed to recreate this on a local machine that failed in the exact same way. 

Because of the way that [aix uses quotes](https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/osmanagement/korn_shell_quote_chars.html), the quotation marks are not escaped at https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/baec42c5baec170b8da5a2fae4388104530b6262/jdk/test/com/sun/jdi/EvalArraysAsList.sh#L42 which leads to the syntax error. 

Adding in the changes from https://bugs.openjdk.java.net/browse/JDK-8207766 resolves the problem by adding in extra quotes to escape this semicolons. 
https://github.com/M-Davies/openjdk-jdk8u/commit/bdf787bf8212c768ee4ff47b573b69f12dd89c81

```
----------System.out:(26/1386)----------
--Compiling first version of /home/jenkins/workspace/mrgTemp/jdk8u252-b08/bin/JTwork/classes/com/sun/jdi/aa6947200/EvalArraysAsList.java with options: 
compiling  EvalArraysAsList.java

--Starting jdb, address=
Listening at address: aix72p7rt1.canlab.ibm.com:32826
--Starting debuggee
Cmd: /home/jenkins/workspace/mrgTemp/jdk8u252-b08/bin/java  -classpath /home/jenkins/workspace/mrgTemp/jdk8u252-b08/bin/JTwork/classes/com/sun/jdi/aa6947200 -DHANGINGJAVA-6947200_DEB              -Djtreg.classDir=/home/jenkins/workspace/mrgTemp/jdk8u252-b08/bin/JTwork/classes/com/sun/jdi/aa6947200             -showversion              -agentlib:jdwp=transport=dt_socket,address=32826,server=n,suspend=y              EvalArraysAsList
Set uncaught java.lang.Throwable
Set deferred uncaught java.lang.Throwable
Initializing jdb ...
> 
VM Started: No frames on the current call stack

main[1] Deferring breakpoint EvalArraysAsList:5.
It will be set after the class is loaded.
main[1] > Set deferred breakpoint EvalArraysAsList:5
java.util.Arrays.asList(null, "a") returns: [null, a]

Breakpoint hit: "thread=main", EvalArraysAsList.main(), line=5 bci=42
5            return;    // @1 breakpoint

main[1]  java.util.Arrays.asList(null, null) = "[null, null]"
main[1]  java.util.Arrays.asList(null, "a") = "[null, a]"
main[1]  java.util.Arrays.asList("a", null) = "[a, null]"
main[1] 
--Done: test passed
```

@andrew-m-leonard Could this be contributed/backported to jdk8? If so, what is the process for contributing? I'll admit I have not looked into it much but IIRC, it involves putting out an email on a mailing list somewhere?

**Comment by andrew-m-leonard** [comment]
Yes this could be contributed, see: https://openjdk.java.net/contribute/

**Comment by M-Davies** [comment]
Thanks

**Comment by M-Davies** [comment]
Haven't seen any indication of this test failing recently https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_ppc64_aix/

**Comment by sophia-guo** [comment]
Test has been excluded so no failure. Reopen it and if there is no failures when re-enabled we can close this.
