### ISSUE TITLE
jdk_jdi failures : Test_openjdk8_hs_sanity.openjdk_s390x_linux 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1731]
**Describe the bug**
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_s390x_linux/165/testReport/

The following tests have been failing for 11 days in Test_openjdk8_hs_sanity.openjdk_s390x_linux runs:

com/sun/jdi/AllLineLocations.java.AllLineLocations
com/sun/jdi/EarlyReturnTest.java.EarlyReturnTest 
com/sun/jdi/JdbMethodExitTest.sh.JdbMethodExitTest 
com/sun/jdi/MethodExitReturnValuesTest.java.MethodExitReturnValuesTest 
com/sun/jdi/NativeInstanceFilter.java.NativeInstanceFilter  
com/sun/jdi/PopAndStepTest.java.PopAndStepTest 
com/sun/jdi/PopAsynchronousTest.java.PopAsynchronousTest 
com/sun/jdi/PopSynchronousTest.java.PopSynchronousTest 
com/sun/jdi/Redefine-g.sh.Redefine-g 
com/sun/jdi/RedefineCrossStart.java.RedefineCrossStart 
com/sun/jdi/redefineMethod/RedefineTest.java.RedefineTest - FAIL: Wrong number of breakpoints encountered: 0

**To Reproduce**
https://ci.adoptopenjdk.net//job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=hotspot&BUILD_LIST=openjdk&PLATFORM=s390x_linux&TARGET=jdk_jdi&SDK_RESOURCE=upstream&SDK_RESOURCE=nightly

**Expected behavior**
All tests should pass

**Screenshots**

<img width="1110" alt="Screen Shot 2020-04-16 at 8 53 39 AM" src="https://user-images.githubusercontent.com/2836948/79458458-d65b2500-7fbf-11ea-873c-e0910bc95ede.png">

**Additional context**
JTR files:
[PopAsynchronousTest.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4487228/PopAsynchronousTest.jtr.txt)
[Redefine-g.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4487229/Redefine-g.jtr.txt)
[RedefineCrossStart.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4487230/RedefineCrossStart.jtr.txt)
[PopSynchronousTest.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4487231/PopSynchronousTest.jtr.txt)
[EarlyReturnTest.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4487232/EarlyReturnTest.jtr.txt)
[PopAndStepTest.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4487233/PopAndStepTest.jtr.txt)
[NativeInstanceFilter.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4487234/NativeInstanceFilter.jtr.txt)
[MethodExitReturnValuesTest.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4487235/MethodExitReturnValuesTest.jtr.txt)
[JdbMethodExitTest.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4487236/JdbMethodExitTest.jtr.txt)
[AllLineLocations.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4487237/AllLineLocations.jtr.txt)

FYI @gdams 
Next steps:  Need to triage further
- Using https://github.com/AdoptOpenJDK/openjdk-tests/wiki/Guidance-for-Creating-OpenJDK-Test-Defects as a guide, check if a known issue already.  
- Check if this past last release, try to determine when this failure actually started happening (really 11 days ago?  if so, what changes went in at that time).

**Comment by smlambert** [comment]
For the record, I think 11 days ago was when these tests were moved from extended.openjdk to sanity.openjdk (so they have been failing for longer than 11 days, find them failing in an August test run here: https://ci.adoptopenjdk.net/view/Test_openjdk_weekly/job/Test_openjdk8_hs_extended.openjdk_s390x_linux/5/testReport/).

**Comment by M-Davies** [comment]
This is also being worked on in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1737. I'm not sure if we should keep open 🤔

**Comment by smlambert** [comment]
I will close this as a dup of #1737 thanks for the heads up @M-Davies !
