### ISSUE TITLE
MBCS_Tests_formatter_* tests failing in jdk14 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1732]
**Describe the bug**
MBCS_Tests_formatter_ja_JP_linux
MBCS_Tests_formatter_ko_KR_linux
MBCS_Tests_formatter_zh_CN_linux
MBCS_Tests_formatter_zh_TW_linux
are failing in jdk14 x86-64_linux builds

See https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk14_hs_special.functional_x86-64_linux/21/tapResults/

**To Reproduce**
https://ci.adoptopenjdk.net//job/Grinder/parambuild/?JDK_VERSION=14&JDK_IMPL=hotspot&BUILD_LIST=functional&PLATFORM=x86-64_linux&TARGET=special.functional&SDK_RESOURCE=nightly

**Expected behaviour**
Expect those 4 test targets to pass

**Additional context**
MBCS_Tests_formatter_ja_JP_linux
MBCS_Tests_formatter_ko_KR_linux 
passed back on Mar 9th (see https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk14_hs_special.functional_x86-64_linux/21/)

The CN and TW tests were added more recently.  It is unclear when this failure first started occurring.

**Comment by smlambert** [comment]
@KKES335 - May I ask that you help address this for jdk14+ (want to make sure we can either use these failing tests for 14+ or disable them for the later subsets via the playlist files).

**Comment by KKES335** [comment]
@smlambert   Sure.  My team modified the source file to fix this issue.  Please see my PR#1901.

**Comment by smlambert** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1901
