### ISSUE TITLE
TestAllocInNewTLAB.java failure (from jdk_svc_sanity) on jdk14_hs_sanity.openjdk_x86-32_windows 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1736]
**Describe the bug**
Failing test case:
 jdk/jfr/event/compiler/TestAllocInNewTLAB.java.TestAllocInNewTLAB

**To Reproduce**
https://ci.adoptopenjdk.net//job/Grinder/parambuild/?JDK_VERSION=14&JDK_IMPL=hotspot&BUILD_LIST=openjdk&PLATFORM=x86-32_windows&TARGET=jdk_svc_sanity&SDK_RESOURCE=nightly

**Expected behavior**
Expect that test case to pass

**Screenshots**

**Additional context**
[TestAllocInNewTLAB.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/4493009/TestAllocInNewTLAB.jtr.txt)

**Comment by M-Davies** [comment]
https://bugs.openjdk.java.net/browse/JDK-8220726

Exclude PR: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1743

**Comment by karianna** [comment]
@M-Davies - FYI - you can link the PR on the right-hand side of a GitHub issue.
