### ISSUE TITLE
getJtreg curl seems flaky 

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1748]
**Describe the bug**
In the nightlies, there is a stage in `openjdk-tests/TKG/scripts/build_test.xml` that gets jtreg from our [dependencies](https://ci.adoptopenjdk.net/view/Dependencies/job/jtreg/) builds. https://github.com/AdoptOpenJDK/openjdk-tests/blob/3ac97bcb0c8ce833c3993d2fb458aca06a68f459/openjdk/build.xml#L28

However, every now and again, the curl transfer occasionally fails to pull from this link (see screenshot). Although I'm not sure if it's related or not, the upstream [jtharness](https://ci.adoptopenjdk.net/view/Dependencies/job/jtharness/) job, has been failing for a while. 

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):
1. Execute a pipeline with tests enabled at https://ci.adoptopenjdk.net/job/build-scripts/
2. Look at the downstream test jobs
3. The error is intermittent in builds (see https://github.com/AdoptOpenJDK/openjdk-build/issues/1634 for reports of this occuring) across all platforms

**Expected behavior**
jtreg is pulled from the job

**Screenshots**
```
18:44:57  getJtreg:
18:44:57      [mkdir] Created dir: /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_ppc64le_linux/jvmtest/openjdk
18:44:57       [echo] Getting Jtreg from https://ci.adoptopenjdk.net/job/jtreg/lastSuccessfulBuild/artifact/jtreg-4.2.0-tip.tar.gz
18:45:14       [exec] curl: (18) transfer closed with 1648942 bytes remaining to read
18:45:14  
18:45:14  BUILD FAILED
```

**Comment by karianna** [comment]
This should be in a retry loop for a few times

**Comment by M-Davies** [comment]
From https://curl.haxx.se/docs/manpage.html:
```
--retry <num>

If a transient error is returned when curl tries to perform a transfer, it will retry this number of times before giving up. Setting the number to 0 makes curl do no retries (which is the default). Transient error means either: a timeout, an FTP 4xx response code or an HTTP 408 or 5xx response code.

When curl is about to retry a transfer, it will first wait one second and then for all forthcoming retries it will double the waiting time until it reaches 10 minutes which then will be the delay between the rest of the retries. By using --retry-delay you disable this exponential backoff algorithm. See also --retry-max-time to limit the total time allowed for retries.

Since curl 7.66.0, curl will comply with the Retry-After: response header if one was present to know when to issue the next retry.

If this option is used several times, the last one will be used.

Added in 7.12.3.
```

@karianna Would a `transfer closed` error count as a transient error?

**Comment by karianna** [comment]
@M-Davies - yes I believe so
