### ISSUE TITLE
workflows/actionExample.yml fails every time I push to my fork

### ISSUE THREAD

**Issue by keithc-ca** [AdoptOpenJDK/openjdk-tests#1757]
`workflows/actionExample.yml` fails every time I push to my fork, even if I have actions disabled, and I get an email notifying me of that failure.

I suggest the example should at least be syntactically correct and should trivially succeed. Apparently a file with only comments doesn't qualify.

**Comment by keithc-ca** [comment]
FYI @sophia-guo

**Comment by sophia-guo** [comment]
We could move the file to other folder instead of workflows. However that means users have to do extra step. 

Will skip the action by ignore any push branch.

**Comment by smlambert** [comment]
We could also just uncomment and enable it to run a test on a real trigger (either using a trigger that is a very rare occurrence, if we do not want to run testing often, or on a push, because it will actually help test changes.
