### ISSUE TITLE
New JDK8 JTReg Fail: sun/misc/Version/Version.java

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-tests#1760]
**Describe the bug**
https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/test/sun/misc/Version/Version.java is failing on multiple platforms across the JDK nightlies.

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):
1. Execute a grinder with these params: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=hotspot&BUILD_LIST=openjdk&PLATFORM=x86-64_linux&TARGET=jdk_custom&CUSTOM_TARGET=jdk/test/sun/misc/Version/Version.java
2. See error

**Expected behavior**
test passes

**Screenshots**
```
Standard Output

jdkVersionInfo: input=1.8.0_262-202004281802-b01 output=1.8.0_262-b1
JDK version = 1.8.0_262-b1  1.8.0_6-b1
    
Standard Error

java.lang.RuntimeException: Unmatched version: 1.8.0_262-b1 vs 1.8.0_6-b1
	at Version.main(Version.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)
```

**Additional context**
- At the time of writing this, I couldn't find any recent history of this failure in JBS https://bugs.openjdk.java.net/browse/JDK-8136651?jql=text%20~%20%22sun%2Fmisc%2FVersion%2FVersion.java%22%20ORDER%20BY%20updated%20DESC
- Started failing on the 28th April 2020

**Comment by M-Davies** [comment]
Exclude PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/1763

**Comment by karianna** [comment]
I've landed the PR - safe to close this?

**Comment by smlambert** [comment]
No, I do not think we can close this based on excluding the test.  Excluding it means we no longer run the test (which should be a temporary state).  

What needs to be determined, is likely one of the following:
- does the test need fixing upstream
- is the test fixed upstream but we are using stale or mismatched test material
- does this binary actually legitimately fail the test for some reason (and needs correction)

**Comment by M-Davies** [comment]
Pulling a recent adopt nightly shows the test's `getProperty` is fine. 
```
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_262-202005021711-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.262-b01, mixed mode)
```

This is a regression failure. Prior to [this build](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-04-28-22-18/OpenJDK8U-jdk_x64_linux_hotspot_2020-04-28-22-18.tar.gz), this test passes. However from this build onwards, the test fails

Last passing https://ci.adoptopenjdk.net/job/Grinder/2969
```
13:48:04  openjdk version "1.8.0_252"
13:48:04  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-202004271724-b09)
13:48:04  OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```
First failing https://ci.adoptopenjdk.net/job/Grinder/2970
```
14:05:21  openjdk version "1.8.0_262"
14:05:21  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_262-202004281723-b01)
14:05:21  OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.262-b01, mixed mode)
```

I'm not sure where the update number (`6`) in the test output is is coming from.

**Comment by M-Davies** [comment]
The lack of any movement on JBS implies this is an "Adopt" problem and not an upstream one. Futhermore, [our test target](https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/test/sun/misc/Version/Version.java) matches the [mercurial test target](http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/f54e9b7c1036/test/sun/misc/Version/Version.java) so I don't think it is due to our test material being out of date.

**Comment by M-Davies** [comment]
However, I ran a grinder with 
```java
System.out.println(jdkMajorVersion());
System.out.println(jdkMinorVersion());
System.out.println(jdkMicroVersion());
System.out.println(jdkUpdateVersion());
```
in the test and it returned
```java
1
8
0
6
```
Ever since the April release, this test has only been pulling one number from the update version (of which, the only reference I could find to `jdkUpdateVersion()` is in a [template file](https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/classes/sun/misc/Version.java.template#L243)). The template file is not used which remains the question, where does this `jdkUpdateVersion()` method come from?

@smlambert Thoughts?

**Comment by smlambert** [comment]
This looks like it may turn into an openjdk-build issue.  

Both the jdkUpdateVersion() method and the sun/misc/Version/Version.java class that tests it live in the mirror of openjdk that we build.  

For nightly builds, we assume that the tip of the openjdk mirror (https://github.com/AdoptOpenJDK/openjdk-jdk8u) is being built, so that is where we pull test material from.  

We **need to confirm** that the tip (https://github.com/AdoptOpenJDK/openjdk-jdk8u master branch) is the one being built in our nightly build pipelines?  

- If it is not tip, then the test material will not match the JDK source that was built, and build pipelines need to pass to test pipelines the tag or SHA of the openjdk-jdk8u repo that was built, so this issue transfers to openjdk-build to make the change to set [RELEASE_TAG](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L129) to be the SHA of the openjdk mirror that was built
- If it is tip, then there is something potentially 'funky' about the JDK that was built, and this issue should transfer to openjdk-build.

**Comment by M-Davies** [comment]
@smlambert The pipeline output seems to suggest it is from whatever the default is which I believe is master
```
Fetching origin
From https://github.com/adoptopenjdk/openjdk-jdk8u
 * [new branch]            dev        -> origin/dev
HEAD is now at a537b9ba56 Merge hotspot at HEAD
Pulling latest tags and getting the latest update version using git fetch -q --tags --depth=1
NOTE: This can take quite some time!  Please be patient
From /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-hotspot/workspace/./build//src
 * branch                  HEAD       -> FETCH_HEAD
OpenJDK repo tag is jdk8u262-b01
Version: 262 
Should have the source, I'm at /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-hotspot/workspace/build/src
From /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-hotspot/workspace/./build//src
 * branch                  HEAD       -> FETCH_HEAD
OpenJDK repo tag is jdk8u262-b01
Completed configuring the version string parameter, config args are now:  --with-milestone=fcs --with-user-release-suffix=202005041729 --with-vendor-name=AdoptOpenJDK --with-update-version=262 --with-build-number=b01
```

@sxa is this correct?

**Comment by M-Davies** [comment]
The test material in the dev and master branches are identical but the dev branch is behind master by quite a few commits. 
```
This branch is 384 commits ahead, 370 commits behind master.
```
However, these are mostly tag changes and the 262 tag is in both [master](https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/.hgtags#L1003) and [dev](https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/dev/.hgtags#L1003) branches.

**Comment by M-Davies** [comment]
@smlambert Can we transfer this to build?

**Comment by sxa** [comment]
> ```java
> System.out.println(jdkMajorVersion());
> System.out.println(jdkMinorVersion());
> System.out.println(jdkMicroVersion());
> System.out.println(jdkUpdateVersion());
> ```

@M-Davies Can you confirm what those functions are since they are not standard java API functions as far as I'm aware and I can't find those values in the JVM system properties - can you provide a standalone test case?

**Comment by M-Davies** [comment]
@sxa They're pulled from https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/aa318070b27849f1fe00d14684b2a40f7b29bf79/jdk/src/share/native/sun/misc/Version.c#L118

**Comment by M-Davies** [comment]
I was about to write a whole summary on my findings but it looks like @jerboaa beat me too it upstream 😂 https://bugs.openjdk.java.net/browse/JDK-8244548

**Comment by M-Davies** [comment]
Will close this as a REPORTED UPSTREAM issue

**Comment by M-Davies** [comment]
Amend PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/1781
