### ISSUE TITLE
Quarkus quickstarts pipeline never scheduled?

### ISSUE THREAD

**Issue by DanHeidinga** [AdoptOpenJDK/openjdk-tests#1769]
**Describe the bug**
The `Pipeline Test_openjdk11_j9_sanity.external_x86-64_linux_quarkus_quickstarts` has never run.  Can we get that scheduled and extended to other platforms?

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.external_x86-64_linux_quarkus_quickstarts/

My assumption is this is intended to be scheduled but got missed along the way

**Comment by DanHeidinga** [comment]
fyi @smlambert @llxia

**Comment by smlambert** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1807

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.external_x86-64_linux_quarkus_quickstarts/ is running nightly (triggered by upstream) and it is passing.
