### ISSUE TITLE
Rename Perf Tests To Match TRSS Parser Convention

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-tests#1770]
Currently, some perf tests are not named according to the [TRSS parser convention](https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/190#issuecomment-611130337) since we hadn't decided the convention on TRSS before these tests were added.

Renaming them would allow TRSS to parse them, enabling us to monitor the results of these tests.

- [x] BumbleBench: Follows already

- [x] Dacapo: Follows already

- [ ] Idle Micro: Needs renaming

- [x] Renaissance: Needs renaming (https://github.com/AdoptOpenJDK/openjdk-tests/pull/1771)

- [x] Liberty: Needs renaming (https://github.com/AdoptOpenJDK/openjdk-tests/pull/1829)

**Comment by smlambert** [comment]
Changing to enhancement, as we are still able to run these tests with current naming, but if we update the naming, we can start to use TRSS and have graphical/historical views of perf data.

**Comment by smlambert** [comment]
It is unlikely we will add parser for the idle microbenchmark, so I am marking this as complete.
