### ISSUE TITLE
get.sh Customized auto-download of test/debug-images does not check if they exist

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#1791]
**Describe the bug**
get.sh assumes if you supply only one customized URL, it auto-downloads the test-images/debug-image, but makes no attempt to check they exist. So if one of them doesn't, eg.on zOS there is no debug-image, it always fails...

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):
1. Run an OpenJ9 Grinder using "Customized" with only one URL, which is a build that does not have a debug-image.tar.gz

**Expected behavior**
get.sh should not try to download the debug-image if one does not exist

**Screenshots**

**Additional context**

**Comment by andrew-m-leonard** [comment]
I would say "auto-download" should default to "false" maybe? and add a checkbox to enable if needed

**Comment by smlambert** [comment]
We decided to default to true based on the need for test images by testing, the request by developers to always fetch debug images, and the fact that most of the places we pull from in automation (Adopt v3 API and various artifactory servers) host all three images.  If you are running a Grinder and pulling from a location that does not have all 3, then you can deselect test_images_required and/or debug_images_required independently.

<img width="788" alt="Screen Shot 2020-05-15 at 8 27 08 AM" src="https://user-images.githubusercontent.com/2836948/82050829-cdc14180-9686-11ea-8c25-11e9a7f4ea2c.png">

**Comment by smlambert** [comment]
For reference, related PR: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1692 (also discussed in March 31st AQAvit meeting).
