### ISSUE TITLE
Re-generate external test jobs to use PARALLEL=Subdir

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#1795]
We are going to re-generate external test jobs to use `PARALLEL=Subdir`. We will take the graduated approach:

- enable xlinux extended.external
- enable all extended.external
- enable all sanity.external
- enable all special.external

**Comment by llxia** [comment]
FYI @ShelleyLambert

**Comment by smlambert** [comment]
I would like to change these jobs, that get triggered by the build pipelines (not the docker image builds), to take the EXTRA_DOCKER_ARGS param (set to the jdk that was just downloaded),  
EXTRA_DOCKER_ARGS="-v $TEST_JDK_HOME:/opt/java/openjdk" 

Related to https://github.com/AdoptOpenJDK/openjdk-tests/issues/773 - these sanity.external and extended.external can be for verifying those apps run well on the jdk under test.  

Related to https://github.com/AdoptOpenJDK/openjdk-tests/issues/1700 - special.external will be used to verify the docker images (so for those, we will not pass in EXTRA_DOCKER_ARGS for those jobs)

**Comment by smlambert** [comment]
Related to this, I am going to disable the old style testing (parent: https://ci.adoptopenjdk.net/view/Test_external_weekly/job/openjdk_externaltest_extended_weekly/ and all subsequent jobs that follow the old naming convention and were triggered by this parent).

**Comment by llxia** [comment]
external.extended on xlinux:
|folder|result| issue|
|--|--|--|
|camel|PASSES||
|camel|PASSES||
|camel|PASSES||
|camel|PASSES||
|camel|PASSES||

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/job/openjdk_externaltest_extended_weekly/ is updated to trigger new extended.external tests using PARALLEL=Subdir

**Comment by llxia** [comment]
|target|impl|platform|auto gen job|Comment|
|--|--|--|--|--|
|sanity.external|j9|x86-64_linux|[Test_Job_Auto_Gen/181/](https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/181/)|maunally set PARALLEL=Subdir|
|sanity.external|hs|x86-64_linux|[Test_Job_Auto_Gen/182/](https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/182/)|maunally set PARALLEL=Subdir|
|special.external|j9|x86-64_linux,s390x_linux|[Test_Job_Auto_Gen/180/](https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/180/)||
|special.external|hs|x86-64_linux,s390x_linux|[Test_Job_Auto_Gen/179/](https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/179/)||
|extended.external|hs|x86-64_linux|[Test_Job_Auto_Gen/178/](https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/178/)|[Parent build](https://ci.adoptopenjdk.net/job/openjdk_externaltest_extended_weekly/) set PARALLEL=Subdir|
|extended.external|j9|x86-64_linux|[Test_Job_Auto_Gen/177/](https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/177/)|[Parent build](https://ci.adoptopenjdk.net/job/openjdk_externaltest_extended_weekly/) set PARALLEL=Subdir|

**Comment by smlambert** [comment]
thanks for all your efforts on this @llxia - your dedication and thorough approach is truly stunning!

**Comment by llxia** [comment]
Renamed [openjdk_externaltest_extended_weekly](https://ci.adoptopenjdk.net/job/openjdk_externaltest_extended_weekly/) to [openjdk_extended.external_weekly](https://ci.adoptopenjdk.net/job/openjdk_extended.external_weekly/).

It is scheduled weekly and triggers `extended.external` for JDK8, 11, 14 on xlinux and plinux.
Due to the limited machine on s390 (only one machine with docker installed), it is disabled at the moment.
