### ISSUE TITLE
Add new AdoptOpenJDK test builds (per platform)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#18]
Want to populate the 'AdoptOpenJDK tests' tab (https://ci.adoptopenjdk.net/view/OpenJDK%20tests/) with test builds that mirror the 'AdoptOpenJDK builds', one per platform (openjdk_test_arm32_linux, openjdk_test_x86-64_linux, etc).  

Can leave the existing build as an experimental one (could rename openjdk_test_x86-64_linux_experimental).

**Comment by karianna** [comment]
@gdams - Am I missing a trick here?  I tried finding to find a way to upgrade @smlambert but couldn't see an option under Manage Jenkins or People...

**Comment by smlambert** [comment]
I have permissions now to add new builds.  Thanks!
