### ISSUE TITLE
Add system directory and playlist 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#180]
We will add a system directory to include the running of system tests via testkitgen, so that we can have a common way to add, tag, categorize, exclude and view results.  Where the system test materials is fetched from the various github repos where it resides (openjdk-stf, openjdk-systemtest and eclipse/openj9-systemtest)

system
   build.xml
   playlist.xml

**Comment by lumpfish** [comment]
Is the proposal that the build.xml file invokes the build for each of the three repositories mentioned (actually just building openj9-systemtest will build the other repositories as they are prereqs)?
What will be in the playlist.xml file?  The makefile targets to run the JCK are included in the openjdk-systemtest repository.  Is this work item proposing to include the command lines to run the JCK in this system/playlist.xml or a different playlist?

**Comment by Mesbah-Alam** [comment]
I was not aware of an issue already created for this task, and had created a separate issue for the same work:
https://github.ibm.com/rushton/openj9_svt_issues/issues/114

**Comment by Mesbah-Alam** [comment]
@lumpfish - Hi Simon, 
The build.xml that I am working on under openjdk-tests/systemtest is cloning openjdk-systemtest, stf and systemtest prereqs and building them, e.g.: https://github.com/Mesbah-Alam/openjdk-tests/blob/Reorganize_systemtest_jenkins_builds/systemtest/build.xml. I'd include building openj9-systemtest in it soon. 

The playlist.xml file contains full command lines to invoke systemtests, e.g.: https://github.com/Mesbah-Alam/openjdk-tests/blob/Reorganize_systemtest_jenkins_builds/systemtest/playlist.xml

**Comment by Mesbah-Alam** [comment]
@sophia-guo @smlambert - I have created a new pull request to add systemtest directory and playlist in adopt; please review: https://github.com/AdoptOpenJDK/openjdk-tests/pull/182

**Comment by smlambert** [comment]
As per a verbal discussion, this work is also to be co-ordinated with the upcoming work related to #183
