### ISSUE TITLE
Wrap all curl fetch operations in build.xml files with retry

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1818]
As done in #1817 we should wade through all of the build.xml files and put a retry on them, to make the compile step 'sturdier' against network flakiness.

There are a few other examples where we use curl to fetch things, example:
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/perf/renaissance/build.xml#L29

Have not seen any of the cases where we 'git clone' to fetch materials has failed, so leave those targets out of this initiative.

**Comment by llxia** [comment]
FYI @nikolamilijevic1

**Comment by nikolamilijevic1** [comment]
with the updates in #1829, I believe there are no more instances of curl fetch operations without a retry so this issue could be closed
