### ISSUE TITLE
Trigger special.external test builds using Scanner Tool

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#1843]
With [Scanner Tool](https://github.com/AdoptOpenJDK/openjdk-docker/pull/345), we can scan all images AdoptOpenJDK produces and identify any problematic Docker images. We will use it to identify what images are changed, and trigger our `special.external` test builds with the parameters.

Details:
- [DockerScannerTool](https://ci.adoptopenjdk.net/view/Docker%20Images/job/DockerScannerTool/) - runs scanner tool with `--verify all --json --filter-bad-manifests --delta-hours 24 --log-path /tmp/` in docker and archives `adoptopenjdk_scanner.log`. Once it is successful, it will trigger [openjdk_special.external](https://ci.adoptopenjdk.net/job/openjdk_special.external/)

- [openjdk_special.external](https://ci.adoptopenjdk.net/job/openjdk_special.external/) - copies `adoptopenjdk_scanner.log`, parses it to get JSON output, and archives JSON output file `scanner_output.json`. Then, it triggers `special.external` based on the info in JSON file. `special.external` test builds runs with `PARALLEL=Subdir`

FYI @ShelleyLambert @james-crowley

**Comment by llxia** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1795

**Comment by llxia** [comment]
Example run: https://ci.adoptopenjdk.net/job/DockerScannerTool/28/

**Comment by smlambert** [comment]
Since related PRs have been merged, can this issue be closed?

**Comment by karianna** [comment]
@llxia ^^ :-)

**Comment by llxia** [comment]
yes, this is completed. Close the issue.
