### ISSUE TITLE
AQAvit Meeting June 24, 2020

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1844]
AQAvit Meeting June 24, 2020
Wednesday, June 24 ⋅11:30am – 12:00pm (GMT-04:00)
Description: Bi-weekly meeting to discuss AdoptOpenJDK Quality Assurance (AQA) topics.

Join with Google Meet
meet.google.com/ejp-yjon-vec

Join by phone
PIN: ‪754 815 097‬#

Proposed Agenda:

- Overview of TRSS features  (includes background of this tool and some over-arching goals/design principles) @llxia @smlambert 

- quick update on external tests changes

We will not have time to dive into all the future features/enhancements we envision in this tool, but will talk about some immediate term stuff.  If need be, we can schedule a follow-up session that dives a bit deeper.

**Comment by sxa** [comment]
Just a note - the subject date and the text above says 23rd of June where it should be 24th :-)

**Comment by karianna** [comment]
I'm unlikely to make it but can we add the topic of test clean up auditing?  We seem to be getting lots of artifacts or java processes leftover from TKG et al and I wonder if we can do a better job in cleaning up and warning us if that fails.

**Comment by sxa** [comment]
@karianna How many instances of that have you seen?

**Comment by karianna** [comment]
anecdotally 3-4 - I think Will tends to clean up the workspace/box quickly :-)

**Comment by sxa** [comment]
@karianna See also related discussion and linked TKG issue in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1165#issuecomment-648478507

**Comment by smlambert** [comment]
The test cleanup item is this one and is being picked up next:  
https://github.com/AdoptOpenJDK/TKG/issues/45

**Comment by smlambert** [comment]
Minutes:
- an overview of TRSS by @llxia 

[Link to recording](https://drive.google.com/file/d/10c-9Ym3umfmm4wLUUCej6qPuGTmsqKF3/view?usp=sharing) of AQAvit meeting
