### ISSUE TITLE
Address Jenkins warnings about RUNTIME_NAME

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1849]
**👾 Description of the issue**

This issue is to remove the [RUNTIME_NAME parameter](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L275-L277) from [JenkinsfileBase file](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase) as it is currently unused and generates unwanted warnings during a test run in Jenkins.

example:
```
2020-06-25 02:48:40.350+0000 [id=3429187]       WARNING hudson.model.ParametersAction#filter: Skipped parameter `RUNTIME_NAME` as it is undefined on `Test_openjdk11_j9_sanity.external_x86-64_linux_tomcat`. Set `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` to allow undefined parameters to be injected as environment variables or `-Dhudson.model.ParametersAction.safeParameters=[comma-separated list]` to whitelist specific parameter names, even though it represents a security breach or `-Dhudson.model.ParametersAction.keepUndefinedParameters=false` to no longer show this message.
```

Once it is removed, the change can be tested by running a Grinder job that runs with PARALLEL=Dynamic.  The person reviewing this fix can trigger a Grinder job in Jenkins to verify.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing pieces or a problem they will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by llxia** [comment]
The RUNTIME_NAME parameter was introduced to trigger the same Jenkins job multiple times (in iterations). Since our code is updated to trigger jobs with a suffix, I think RUNTIME_NAME can be removed.

**Comment by avishreekh** [comment]
Hi! I am an Outreachy applicant and would like to contribute to this issue.

**Comment by avishreekh** [comment]
Please review the change and let me know if anything else is required @ShelleyLambert
