### ISSUE TITLE
FinalizeOverride Test runs despite being excluded

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#1852]
**Describe the bug**
FinalizeOverride is in the ProblemList exclude file for this release+jvm, but it is still being run.
See [here](https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.openjdk_ppc64le_linux/123/) for test run.
See [here](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk14-openj9.txt) for the relevant problem list.

**To Reproduce**
Run nightly sanity.openjdk job like the one here:
https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.openjdk_ppc64le_linux/123/

**Expected behavior**
This test is not meant to run at all.

**Additional context**
The test has been excluded for 2 days, and yet it is still being run.

**Comment by smlambert** [comment]
Excluding the test, and then continuing to run the test in a separate target ([jdk_lang_ref_FinalizeOverride_j9](https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.openjdk_ppc64le_linux/123/tapResults/)) with different options (see https://github.com/AdoptOpenJDK/openjdk-tests/pull/1845) was purposefully done by @pshipton 

We can repurpose this issue as jdk_lang_ref_FinalizeOverride_j9 fails issue, @pshipton we would normally exclude non-green tests, is this one intermittent and you are trying to gather data, or shall we also disable jdk_lang_ref_FinalizeOverride_j9 ?

**Comment by pshipton** [comment]
It's a trade off. Although the test fails intermittently, it could still catch another real problem if it started failing more frequently or always. Although it shouldn't, excluding might have the side affect of de-prioritizing the work to fix it.

**Comment by sophia-guo** [comment]
Maybe we could move it to special category? So it could run daily and not block the sanity?

**Comment by smlambert** [comment]
good plan @sophia-guo - let's do that!

**Comment by smlambert** [comment]
Closing this as it is intended to continue to run the test and it has been moved to special.openjdk via https://github.com/AdoptOpenJDK/openjdk-tests/pull/1863
