### ISSUE TITLE
jdk14u aarch64 64k builds show an error while testing on 4k machines

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#1864]
**Platform: arm64**

**Architecture: aarch64**

The problem is that if you build jdk14u on an aarch64 machine with 64k pages, and then use it on a machine with 4k pages (and possibly the reverse too), you get this non-fatal error right before the -version output:

```
[0.011s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 65536 actual: 4096
```
This was originally reported [here](https://github.com/AdoptOpenJDK/openjdk14-binaries/issues/1).

However, the fix was not backported to 14, nor does the fix appear to be an actual resolution of the issue (but rather something to let the build process tolerate the error).

Since jdk14 is about to go out of service, I'm not convinced that backporting is a good use of anyone's time, however [these test failures](https://ci.adoptopenjdk.net/job/Test_openjdk14_hs_sanity.openjdk_aarch64_linux/129/consoleFull) still need to be resolved for jdk14+ test runs on aarch64.

If the accepted solution for the build issue was to ignore the error message, it seems like the correct action here is to modify the tests to do the same via an OpenJDK bug.

Notes: 
64k machine - build-osuosl-aix71-ppc64-2
4k machine - test-aws-ubuntu1804-armv8-1
[Useful facts](http://openjdk.5641.n7.nabble.com/APPCDS-JDK-8236847-JDK-built-on-machine-with-4K-pages-refused-to-start-on-machine-with-64k-pages-td398927.html#a399101)

**Comment by adamfarley** [comment]
Correction: [This fix](https://bugs.openjdk.java.net/browse/JDK-8243392) appears to claim that this issue is resolved on jdk15, so the tests shouldn't have to be fixed.

It seems a more prudent use of time to simply exclude the tests (from jdk14 - aarch) while we wait for jdk14 to expire. If we see the problem on jdk15, then we can spend time on a fix.

**Comment by austin0** [comment]
PR to exclude failing tests here: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1905

**Comment by adamfarley** [comment]
Closing this for now. If the issue returns on jdk15, we can re-open.

**Comment by superusercode** [comment]
This is an error I am currently having with the latest adoptopenjdk build for aarch64 PCs (https://adoptopenjdk.jfrog.io/artifactory/rpm/centos/7/aarch64/Packages/adoptopenjdk-16-hotspot-16.0.1+9-3.aarch64.rpm). How do I go about reopening and documenting this? The server in question is a free tier machine on oracle cloud, where I install this rpm manually onto a oracle linux OS.
