### ISSUE TITLE
Proposal: Reduce Jenkinsfilebase params by combining repo/branch names into 1 string

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1873]
For each of the REPO and BRANCH parameter pairs we have, we can reduce the 2 parameters to a single string, this would not only reduce the number of parameters, but also allow for cut'n'paste when launching Grinders during review.

(repo:branch is typically listed at the top right in Github PR, which could then be cut'n'pasted into the Grinder fields when running Grinders during review)

In Jenkinsfilebase (or TKG if we want to do this at the lower layer), logic to parse the single string into REPO and BRANCH.  One caveat is if we proceed with https://github.com/AdoptOpenJDK/openjdk-tests/issues/1872 then parsing logic would also have to look at other information, example vendor info, to avoid making assumptions about repo location 

Reduces 14 params down to 7 (if you count in JDK_REPO/BRANCH from proposal #1872):

<img width="621" alt="Screen Shot 2020-07-08 at 2 32 47 PM" src="https://user-images.githubusercontent.com/2836948/86957047-20b7f200-c128-11ea-9140-341928802811.png">
<img width="683" alt="Screen Shot 2020-07-08 at 2 33 07 PM" src="https://user-images.githubusercontent.com/2836948/86957076-2c0b1d80-c128-11ea-9dfc-0812c19e326e.png">
<img width="702" alt="Screen Shot 2020-07-08 at 2 33 35 PM" src="https://user-images.githubusercontent.com/2836948/86957090-30cfd180-c128-11ea-81a4-19dc73dba0bf.png">

**Comment by smlambert** [comment]
I like the explicit nature of the 2 separate params, but definitely think the Grinder job config would be nicer to use by collapsing the params.  Let's use this issue to discuss pros/cons.

**Comment by llxia** [comment]
I really like the idea. This will make Grinder so much easy to use. No more typing! I can see this been used for most of our repo and branch parameters, but I am not sure about `ADOPTOPENJDK_REPO ` and `ADOPTOPENJDK_BRANCH `. 

Currently, we use them in job configure, so the job can check out specific `ADOPTOPENJDK_REPO` and `ADOPTOPENJDK_BRANCH`.

<img src="https://user-images.githubusercontent.com/19273206/86973353-74373980-c142-11ea-92d4-6a95416da52c.png" width="500">

If we change `ADOPTOPENJDK_REPO ` and `ADOPTOPENJDK_BRANCH ` into one parameter, I am not sure how to use it in the job configure.

**Comment by smlambert** [comment]
Ah good call, so maybe ADOPTOPENJDK_REPO and ADOPTOPENJDK_BRANCH keep their current status of unique individual parameters, since they represent the seed/base/starter repo, and other tangential repos shift to the collapsed single parameter, not quite as clean, but it still reduction.


If ADOPTOPENJDK_REPO_BRANCH = "AdoptOpenJDK:master"
Doubt its possible to change the Repository URL
and Branch specifier to contain groovy code or if they only allow for variables
but if it were possible, perhaps could parse and fill with some string methods...
where ADOPTOPENJDK_BRANCH is substring(${ADOPTOPENJDK_REPO_BRANCH}.indexOf(‘:’))

**Comment by llxia** [comment]
Thanks Shelley. I will give it a try.

**Comment by llxia** [comment]
PR #1940 and PR #1941 combined repo/branch names for TKG, stf, openjdk-systemtest and openj9-systemtest.

Remaining repos:
- OPENJ9_REPO and OPENJ9_BRANCH (as the parameters are set in [upstream](https://github.com/eclipse/openj9/blob/e0ba42d26fa27a0cd24639ab6de1512b43c9b071/buildenv/jenkins/common/pipeline-functions.groovy#L442). It needs to change the upstream script in openj9 as well)
- ADOPTOPENJDK_REPO and ADOPTOPENJDK_BRANCH (the parameters are needed in the job configure. Cannot use code in job configure parameter)
- JDK_REPO and JDK_BRANCH

**Comment by smlambert** [comment]
I think the remaining 3 repos are not easily collapsed into a single param (as there are variants and/or reasons that make it impossible to assume defaults), given this, we can likely mark this issue as closed.  Do you agree @llxia ?

**Comment by llxia** [comment]
yes, close this issue.
