### ISSUE TITLE
LockingLoadTest_0 FAILED in Test_openjdk14_hs_extended.system_aarch64_linux

### ISSUE THREAD

**Issue by d3r3kk** [AdoptOpenJDK/openjdk-tests#1892]
**Test Info**
Test Name: LockingLoadTest_0
Test Duration: 13 sec
Machine: test-aws-ubuntu1804-armv8-1
TRSS link for the test output: https://trss.adoptopenjdk.net/output/test?id=5f0edf557eaab3443ca848c3

**Build Info**
Build Name: Test_openjdk14_hs_extended.system_aarch64_linux
Jenkins Build start time: Jul 15 2020, 02:39 am
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk14_hs_extended.system_aarch64_linux/140/
TRSS link for the build: https://trss.adoptopenjdk.net/allTestsInfo?buildId=5f0eded87eaab3443ca8477b

**Java Version**
[0.009s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 65536 actual: 4096
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode)

**This test has been failed 19 times since Jun 25 2020, 01:45 pm**
**Java Version when the issue first seen**
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7-202006252018)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7-202006252018, mixed mode, sharing)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk14_hs_extended.system_aarch64_linux/122/

The test failed on machine test-aws-ubuntu1804-armv8-1 1 times 
The test failed on machine test-aws-rhel76-armv8-3 3 times 
The test failed on machine test-aws-rhel76-armv8-4 3 times 
The test failed on machine test-packet-ubuntu1604-armv8-1 4 times 
The test failed on machine test-aws-rhel76-armv8-2 2 times 
The test failed on machine test-packet-ubuntu1604-armv8-2 2 times 
The test failed on machine test-aws-rhel76-armv8-6 2 times 
The test failed on machine test-aws-rhel76-armv8-1 1 times 
The test failed on machine test-aws-rhel76-armv8-5 1 times

**Comment by lumpfish** [comment]
The exact symptoms of the failures reported here are no longer available, but the LockingLoadTest is now passing on all platforms and releases as a result of the recently merged PR https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/378.

**Comment by smlambert** [comment]
Closing as resolved, if it resurfaces we can capture details in a new issue.
