### ISSUE TITLE
JTReg download fails and does not retry

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#1894]
**Describe the bug**
JTReg tar.gz file download terminates before the file completes the download.

**To Reproduce**
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.openjdk_ppc64le_linux/177/console

**Expected behavior**
The file should download completely and successfully. If this fails, curl is instructed to retry. We do not appear to retry.

**Additional context**
```
16:18:27  getJtreg:
16:18:27      [mkdir] Created dir: /home/jenkins/workspace/Test_openjdk8_j9_special.openjdk_ppc64le_linux/jvmtest/openjdk
16:18:27       [echo] Getting Jtreg from https://ci.adoptopenjdk.net/job/jtreg/lastSuccessfulBuild/artifact/jtreg-4.2.0-tip.tar.gz
16:19:08       [exec] curl: (18) transfer closed with 4544003 bytes remaining to read
16:19:08  
16:19:08  BUILD FAILED
16:19:08  /home/jenkins/workspace/Test_openjdk8_j9_special.openjdk_ppc64le_linux/openjdk-tests/TKG/scripts/build_test.xml:58: The following error occurred while executing this line:
16:19:08  /home/jenkins/workspace/Test_openjdk8_j9_special.openjdk_ppc64le_linux/openjdk-tests/openjdk/build.xml:197: The following error occurred while executing this line:
16:19:08  /home/jenkins/workspace/Test_openjdk8_j9_special.openjdk_ppc64le_linux/openjdk-tests/openjdk/build.xml:42: exec returned: 18
```

P.S. The "exec returned: 18" at the end seems to refer to the aforementioned curl command. This translates as:
```
CURLE_PARTIAL_FILE (18)

A file transfer was shorter or larger than expected. This happens when the server first reports an expected transfer size, and then delivers data that doesn't match the previously given size. 
```
(as per https://curl.haxx.se/libcurl/c/libcurl-errors.html)
Which just repeats what we already knew.

**Comment by adamfarley** [comment]
The option we use to get curl to retry is "--retry 5"

It seems retry only retries when you get a "transient" error. "Partial file download" does not appear to be one.

One option is to use "retry-all-errors", but the manpage advises against that.

Will see if there's a way to include rc18 as a transient error.

**Comment by smlambert** [comment]
There is a retry as per https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml#L43

Though I have not seen this issue prior to this week, where its now been reported twice, I am going to presume that the Jenkins server that serves up the artifacts from the jtreg job is now deciding to be laggy.  

https://github.com/eclipse/openj9/issues/10166#issuecomment-658490512

**Comment by adamfarley** [comment]
@smlambert - I identified the retry option. I'm saying it's not working.

As mentioned above, partial file download doesn't appear to be "transient" enough for --retry to consider simply restarting the download.

**Comment by adamfarley** [comment]
We could simply use [retry-all-errors](https://curl.haxx.se/docs/manpage.html#--retry-all-errors), though the website says that's not necessarily wise.

**Comment by smlambert** [comment]
https://github.com/eclipse/openj9/issues/10166#issuecomment-658490512

**Comment by adamfarley** [comment]
Yup. I saw. I didn't think you were offering a solution there, as if it's the chunked encoding that allows us to know if there's still parts of the file left to download, then it seems like the absence of this in a HTTP1.0 request would cause us to simply "not know" if the download is a partial. 

Do let me know if I've misunderstood you there. If I have, the docs imply that the ant "Get" task appears to do this, so it could be a simple change.

I also looked into the ant retry block, as [this](https://stackoverflow.com/questions/52625873/retry-task-on-exec-task-in-ant-gives-incorrect-resultproperty) appears to indicate we can retry a failed task even if failonerror is set (as it is here).

However, this brings its own challenges (immutable return value, as noted there), so if we're going to do the unconditional retry, we may as well use retry-all-errors. Time will tell if this causes more headaches than it solves.

**Comment by smlambert** [comment]
I am curious why this is suddenly showing up now after years of not being an issue, also interested in why it's only seen on plinux runs.  (another instance here: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.openjdk_ppc64le_linux/177/console)

**Comment by adamfarley** [comment]
I've set this up to attempt to reproduce the issue in a job. It uses a build.xml with an rc-sensitive fix, which attempts to resume the download if rc 18 is detected.
https://ci.adoptopenjdk.net/job/AdamF_grinder_tempjob/

It uses the fix defined here:
https://github.com/AdoptOpenJDK/openjdk-tests/compare/master...adamfarley:fix_rc_18_bug_for_jtreg_download

(Note that the adamfarley line is meant to ensure we're using the right build.xml, and will not be included in the PR).

Will review the results tomorrow to ensure it's working correctly, and will leave it running over the weekend to try and reproduce the failure.

This job will be deleted once we have the data, so the job shouldn't take more than (5mins * 6runs * 3 =) 1.5hrs of machine time total over the entire weekend.

**Comment by adamfarley** [comment]
Ok, the new job didn't work, so that's deleted.

However, a "parallel grinders" [run](https://ci.adoptopenjdk.net/job/grinder_sandbox_iteration_16/1/console) *did* work.

The good news is that my build.xml changes successfully identified and retried a jtreg download.

The bad news is that the retry failed as well.

Will tweak and re-attempt.

**Comment by adamfarley** [comment]
Fix now correctly identifies when a partial download has occurred.

Instead of resuming the download after 10 minutes (the method we used in the comment above), we now delete the partial download and start afresh after 20 minutes.

In the two cases where I was able to reproduce the issue, this fix resolved the problem.

https://ci.adoptopenjdk.net/job/grinder_sandbox_iteration_5/2/console
https://ci.adoptopenjdk.net/job/grinder_sandbox_iteration_9/2/console

```
21:21:30  getJtreg:
21:21:30      [mkdir] Created dir: /home/jenkins/workspace/grinder_sandbox_iteration_9/jvmtest/openjdk
21:21:30       [echo] Getting Jtreg from https://ci.adoptopenjdk.net/job/jtreg/lastSuccessfulBuild/artifact/jtreg-4.2.0-tip.tar.gz
21:21:30       [echo] If you are reading this, then you are using the adamfarley repo.
21:22:59       [exec] Result: 18
21:22:59     [delete] Deleting: /home/jenkins/workspace/grinder_sandbox_iteration_9/openjdk-tests/openjdk/${curl.download.tmp.jtreg.output}
21:22:59       [echo] Jtreg download failed after partial download. Will attempt to retry after a 20 minute pause.
21:42:59     [delete] Deleting: /home/jenkins/workspace/grinder_sandbox_iteration_9/openjdk-tests/openjdk/jtreg-4.2.0-tip.tar.gz
```

Note that after the last delete, we retry the download. I'll add an echo message to make that clear.

Will create a PR for this.

**Comment by adamfarley** [comment]
Ok, the issue has yet to be reproduced after the echo messages were modified. Several restarts, no instances of the issue this change fixes.

We know the core of the change works as per [these](https://ci.adoptopenjdk.net/job/grinder_sandbox_iteration_5/2/console) [two](https://ci.adoptopenjdk.net/job/grinder_sandbox_iteration_9/2/console) results, so I assert that since the addition of the echo messages didn't cause any of the [test runs](https://ci.adoptopenjdk.net/job/grinder_sandbox/56/) to fail, the change is good to merge.

[PR created.](https://github.com/AdoptOpenJDK/openjdk-tests/pull/1918)

**Comment by adamfarley** [comment]
Shelley points out that this issue appears to have gone away, and that there are other options if it comes back.

Closing.
