### ISSUE TITLE
Stop archiving duplicate perf test artifacts in Jenkins

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1911]
Looks like we are currently archiving and keeping 2 copies of test artifacts for perf tests in the event that the perf tests fail (benchmark_test_output.tar.gz and perf_test_output.tar.gz), though one artifact contains slightly more than the other.  This is because we always want to keep the benchmark results (so we archive benchmark_test_output [here](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L648)) but on failure we also archive results in perf_test_output for all types of tests.

<img width="473" alt="Screen Shot 2020-07-23 at 9 01 18 AM" src="https://user-images.githubusercontent.com/2836948/88290139-49152400-ccc4-11ea-9a1f-c6d93c074054.png">

We should verify the difference in content between the 2 artifacts and stop keeping both because its redundant and eats space on Jenkins or in Artifactory.

**Comment by patkarns** [comment]
I investigated the benchmark and perf files and they seem identical. The only difference is that the perf output is inside another tar file: 
- benchmark_test_output.tar.gz\.\openjdk-tests\... [the rest is the same]
- perf_test_output.tar.gz\perf_test_output.tar\.\openjdk-tests\... [the rest is the same]

**Comment by smlambert** [comment]
Closed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/2378
