### ISSUE TITLE
HCRLateAttachWorkload_0 test fails with NullPointerException

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#1915]
**Describe the bug**
Hot Code Replace test fails with this error:

```
[2020-07-23T18:10:41.389Z] LT  stderr Caused by: java.lang.NullPointerException
[2020-07-23T18:10:41.389Z] LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:67)
```

**To Reproduce**
[Test_openjdk8_hs_extended.system_ppc64le_linux #268](https://trss.adoptopenjdk.net/output/test?id=5f19d98b0bec7975aef877fc)
[Test_openjdk8_hs_extended.system_s390x_linux #256](https://trss.adoptopenjdk.net/output/test?id=5f1a07cc0bec7975aef8acec)

**Expected behavior**
I expected the test to pass.

**Additional context**
I'm I'm the person who wrote this test, I'm probably best positioned to resolve it. Will investigate.

**Comment by smlambert** [comment]
Closing as dup ofhttps://github.com/AdoptOpenJDK/openjdk-tests/issues/1882

Can use TRSS Possible issues button to see if an issues already been raised that may be same or related.

Possible issues button:
<img width="1067" alt="Screen Shot 2020-07-24 at 9 27 59 AM" src="https://user-images.githubusercontent.com/2836948/88396119-189abc00-cd90-11ea-8b42-2bd27e037403.png">

Possible issues list:
<img width="777" alt="Screen Shot 2020-07-24 at 9 26 22 AM" src="https://user-images.githubusercontent.com/2836948/88396134-1df80680-cd90-11ea-9044-be4c0c7de11c.png">
