### ISSUE TITLE
Set java/foreign/TestNative.java as a separate test case

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1920]
java/foreign/TestNative.java depends on the testImages. For cases there is no testimages available it should be labeled as <type>native</type>.

**Comment by sophia-guo** [comment]
Another one in java_lang: java/lang/ProcessBuilder/checkHandles/CheckHandles.java

**Comment by smlambert** [comment]
Right, I see your draft PR, if we can create a single jdk_lang_native target with multiple single classes in the list to execute, that will be ideal.  👍

**Comment by sophia-guo** [comment]
Those tests are scattered everywhere. The first one belongs to java_foreign and second one belongs to jdk_lang. If we'd like to use a single target to exclude those classes the easiest way should be set the target at openjdk hg :-(.

I'm using this issue as the permanent exclude references due to the same reason.

**Comment by sophia-guo** [comment]
JDK15+ in jdk_lang: jdk/internal/loader/NativeLibraries/Main.java jdk15+

**Comment by sophia-guo** [comment]
JDK15+ in jdk_lang: jdk/internal/loader/NativeLibraries/Main.java

**Comment by SehrishHussain** [comment]
Another test fail:
**java/lang/ProcessBuilder/Basic.java**
Jenkins Link: https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.openjdk_ppc64_aix/16/testReport/junit/java_lang_ProcessBuilder_Basic/java_id0/Basic_id0/
TRSS Link: https://trss.adoptium.net/allTestsInfo?buildId=616d7be7c6182d02177fff67&limit=5&hasChildren=false
