### ISSUE TITLE
Unable to Run Bash Script from Playlist.xml on Windows

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-tests#1928]
**Describe the bug**

We aren't able to run a bash script from playlist.xml on Windows, while we can do so on all other platforms. I noticed this issue while working on adding affinity support for perf tests in https://github.com/AdoptOpenJDK/openjdk-tests/pull/1917. 

More details here: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1917#issuecomment-663788319

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):
1. Comment out `<platformRequirements>^os.win</platformRequirements>` in https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/perf/renaissance/playlist.xml for any test that has it (i.e. test using `run_with_affinity.sh`)
2. Run that test on any Windows machine.

**Expected behavior**

We are able to run bash script on Windows just like on any other platform.

**Comment by smlambert** [comment]
@sxa - wondering if this should be moved to openjdk-infrastructure repo, what are your thoughts?  The expectation is that machines with cygwin installed would behave similarly to linux machines.

**Comment by piyush286** [comment]
Apologies! I investigated this issue further to realize that this didn't happen due to some cygwin issue but rather due to a bug in the affinity tool, which would be fixed in https://github.com/AdoptOpenJDK/openjdk-tests/pull/2034. Sorry for the confusion!
