### ISSUE TITLE
jdk_lang_native | jdk_lang_native_j9 failed on all platforms except windows due to 'no tests selected'

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1930]
jdk_lang_native_j9 testcase was recently added as a native type test, which includes the single test jdk/java/lang/ProcessBuilder/checkHandles/CheckHandles.java moved from jdk_lang subset. The test is limited to windows by JTReg framework. 

No test running will by default set as failed by TKG.

https://ci.adoptopenjdk.net/view/Test_openjdk/ openjdk11
```
20:40:09  Test results: no tests selected
20:40:19  Report written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
20:40:19  Results written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_15965006633918/jdk_lang_native_j9_0/work
20:40:19  
20:40:19  jdk_lang_native_j9_0_FAILED
```

**Comment by smlambert** [comment]
ah, so if we spin it off into its own target in playlist, the `< platformRequirements>` will need to be updated for it to also restrict to what the underlying test framework restricts to
