### ISSUE TITLE
Request: GraalVM or OpenJ9 Port for android

### ISSUE THREAD

**Issue by Malaska678** [AdoptOpenJDK/openjdk-tests#1945]

**Comment by aahlenst** [comment]
You're in the wrong place. This project is about testing AdoptOpenJDK. For Graal, please contact the [Graal project](https://www.graalvm.org/), for OpenJ9 the [OpenJ9 project](https://www.eclipse.org/openj9/).

**Comment by Malaska678** [comment]
Ok
