### ISSUE TITLE
Update to support unicode 13 in MBCS test material

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1957]
Seems that OpenJDK is updated to support unicode 13.0: https://bugs.openjdk.java.net/browse/JDK-8239383. But the test material https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/functional/MBCS_Tests/unicode/data is still using the 12.0.1 version of NormalizationTest.txt. May need to update test material to use the 13.0 version https://www.unicode.org/Public/13.0.0/ucd/NormalizationTest.txt

_Originally posted by @hangshao0 in https://github.com/eclipse/openj9/issues/10590#issuecomment-692263656_

FYI @KKES335 @takiguc - could one of you take a look at this?

**Comment by hangshao0** [comment]
I see there is an existing issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/1938 talking about the same thing.

**Comment by smlambert** [comment]
Close as dup of https://github.com/AdoptOpenJDK/openjdk-tests/issues/1938
