### ISSUE TITLE
Support + in rerun link

### ISSUE THREAD

**Issue by liqunl** [AdoptOpenJDK/openjdk-tests#1962]
Rerun a grinder https://ci.adoptopenjdk.net/job/Grinder/3875/ changed the `CUSTOMIZED_SDK_URL` from
https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15+36_openj9-0.22.0-m2/OpenJDK15U-jdk_x64_linux_openj9_15_36_openj9-0.22.0-m2.tar.gz
to
https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15 36_openj9-0.22.0-m2/OpenJDK15U-jdk_x64_linux_openj9_15_36_openj9-0.22.0-m2.tar.gz

`+` is not correctly handled.

**Comment by liqunl** [comment]
@ShelleyLambert @llxia

**Comment by smlambert** [comment]
Looking up on https://www.rapidtables.com/code/text/unicode-characters.html, we can handle this special character in the same way we need to handle other special chars (see [handling of &](https://github.com/AdoptOpenJDK/openjdk-tests/pull/1943/files#diff-9da4c7b7710fb521a3c011d52316f1f9R791))
`&#43;` is the html code
`U+002B` unicode
`\u002B` escape sequence

**Comment by llxia** [comment]
yes, we can use `URLEncoder.encode()`. I will create PR soon.
