### ISSUE TITLE
Jtreg: JDK11 native tests failing on z/OS as there is no nativepath

### ISSUE THREAD

**Issue by psoujany** [AdoptOpenJDK/openjdk-tests#1964]
**Describe the bug**
JDK11 native related tests are failing due to missing natives path to jtreg.

-nativepath is being excluded on z/OS
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/openjdk.mk#L123

**To Reproduce**
Re-run the below jtreg test on z/OS with JDK11
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/9934/testReport/compiler_floatingpoint_TestFloatJNIArgs/java/TestFloatJNIArgs/

**Expected behavior**
Jni tests should pick -nativepath location to execute native related tests.

**Comment by llxia** [comment]
@LongyuZhang Could you please take a look? Thanks

**Comment by smlambert** [comment]
Believe this is resolved via https://github.com/AdoptOpenJDK/openjdk-tests/pull/2000

**Comment by llxia** [comment]
yes, this issue can be closed. 
Just for the record, there are two parts to the problems. One is the path which is fixed by #2000. The other one is that there is no native test image built on zos. Thanks to @LongyuZhang This issue is already opened in the openj9 zos extension repo.

**Comment by LongyuZhang** [comment]
The new issue link is repo openj9-openjdk-jdk11-zos 448. Thanks.

**Comment by smlambert** [comment]
Wonderful, thanks for clarifying!
