### ISSUE TITLE
Support extracting pax.Z file

### ISSUE THREAD

**Issue by narkedi** [AdoptOpenJDK/openjdk-tests#1973]
This request is specific to z/OS platform on JDK11, we are changing the file extension from pax to pax.Z. This is required for z/OS as the pax.Z going forward will be a input to the packaging teams to generate the z/OS Installers (SMP/E). 

Once we have the file format changed to pax.Z, the tests also should handle extracting this file should have no impact on testing. 

Request you to handle the pax.Z and once confirmed, we can start creating pax.Z files instead of pax files. 

**Expected behavior**
Tests should extract pax.Z and shouldn't break the test execution.

**Additional context**
Refer runtimes/backlog/issues/382 for more details.

**Comment by pshipton** [comment]
Note the existing .pax files are already compressed, only the file extension is changing.

**Comment by smlambert** [comment]
@llxia has noted that this will be a one character change in [get.sh](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/get.sh#L338) `$jar_name == *pax` -> `$jar_name == *pax*`

**Comment by llxia** [comment]
I got SDK with pax.Z by using PR https://github.com/eclipse/openj9/pull/10642. I will have a PR soon.
