### ISSUE TITLE
Enhance PARALLEL=Iteration mode

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#1985]
Currently, our PARALLEL modes are the following:

- None // run test(s) in serial
- Dynamic // dynamically divides tests according to NUM_MACHINES and runs them in parallel.
- Iteration // run the same test(s) in parallel according to ITERATIONS number.
- Subdir // run tests in parallel according to subdir. This is mainly for external tests.

The `Iteration` mode only allows users to run in parallel based on ITERATIONS number and each parallel will only run this test once. Due to the lack of machine resources and overhead test setup time, we may want to run tests multiple times in parallel. For example, run a test in parallel on 5 machines and run this test 10 times in a loop in each parallel run.

We can enhance `Iteration` mode to achieve this. I think we should rename `Iteration` mode to a generic name, maybe call it `Regular` mode. Below is the detail:
If `PARALLEL` is set to `Regular` mode, users need to provide `NUM_MACHINES`. The script will parallel based on `NUM_MACHINES`. The default limitation should still apply (i.e., cannot run parallel if NUM_MACHINES > 20). The Dynamic parallel should not be invoked. All other parameters should be set into child jobs, including user-specified `ITERATIONS`. In this way, we can support to run the test in x parallel runs with y iterations in each run.

FYI @pshipton @smlambert

**Comment by smlambert** [comment]
I like the plan, and will suggest to use a more descriptive name than `Regular` as it doesn't indicate anything about what it means.  

PARALLEL = NodesByIterations 
(and if NUM_MACHINES and ITERATIONS empty, both default to 1 so in the case both empty, PARALLEL=NodesByIterations behaves like PARALLEL=none)

**Comment by pshipton** [comment]
Thanks for the proposal Lan. Whatever the naming, this will address the concern I had for being able to get the most out of the available machines to repeat a failure.
