### ISSUE TITLE
jdk8 sanity.external s390x_linux_openliberty-mp-tck and x86-64_linux_tomee taking a considerable amout of time on zLinux

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#1993]
**Describe the bug**
jdk8 sanity.external testsuites s390x_linux_openliberty-mp-tck and x86-64_linux_tomee are taking a considerable amount of time to run. This greatly impacts zLinux especially due to limited machine resource.

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_s390x_linux_openliberty-mp-tck/
https://ci.adoptopenjdk.net/view/Test_external/job/Test_openjdk8_hs_sanity.external_x86-64_linux_tomee

s390x_linux_openliberty-mp-tck : avg = 5hrs
x86-64_linux_tomee : avg = 9hrs38mins (typically Aborts)

**Comment by andrew-m-leonard** [comment]
on xLinux:
```
16:32:12  Preparing all bnd projects in the workspace (this can take a while)
16:33:50  All bnd projects in the workspace have been prepared
```
on zLinux:
```
05:51:19  Preparing all bnd projects in the workspace (this can take a while)
06:23:00  All bnd projects in the workspace have been prepared
```
So on xLinux this step takes 1min38sec, on zLinux it takes 31min41sec, so roughly 20x slower, **why?**

**Comment by andrew-m-leonard** [comment]
OpenLiberty package build time:
zLinux 5+hours (gets aborted before completion)
xLinux 1.5 hours

**Comment by andrew-m-leonard** [comment]
Comparing jdk11 zLinux build time for a given openliberty module:
jdk11 : 2 mins
jdk8: nearly 2hours!

**Comment by andrew-m-leonard** [comment]
This is probably it! **"Zero VM"**
```
07:39:18  =JAVA VERSION OUTPUT BEGIN=
07:39:18  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
07:39:18  openjdk version "1.8.0_272"
07:39:18  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-202010051720-b09)
07:39:18  OpenJDK 64-Bit Zero VM (AdoptOpenJDK)(build 25.272-b09, interpreted mode)
07:39:18  =JAVA VERSION OUTPUT END=
```

**Comment by aahlenst** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/issues/2038 might be related.

**Comment by andrew-m-leonard** [comment]
Updated issue to address just the zLinux problem.
Raised separate issue for tomee on xLinux problem: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1997

**Comment by smlambert** [comment]
Close in favour of epic #2057
