### ISSUE TITLE
need slave machines to set up build

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#2]
We need labeled machine to set up build to run test. For now we can at least get one machine labeled with linux&&x64&&test to run the build

**Comment by gdams** [comment]
@sophia-guo I can give you access to a test machine, let me take a look at the pool tonight

**Comment by gdams** [comment]
okay I have provisioned https://ci.adoptopenjdk.net/computer/test-packet-x64-ubuntu-16.04-1/, let me know what you need on the machine please

**Comment by gdams** [comment]
Okay so here is the list of dependencies I have so far:
- git
- jq
- make
- gcc
- g++
- `/usr/bin/perl -MCPAN -e'install Text::CSV'`

**Comment by sophia-guo** [comment]
Thanks George, double checked please also install ant-contrib

**Comment by gdams** [comment]
@sophia-guo installed

**Comment by helenmasters** [comment]
Just as an fyi when you come to work out dependencies across all of the platform types I had to 
`brew install wget ` on macOS as it wasn't installed by default.

**Comment by karianna** [comment]
Reopening in that case :-)

**Comment by smlambert** [comment]
Closing as duplicate of issue 17.
