### ISSUE TITLE
Add build triggers to tie openjdk_test_xxxx builds to image builds

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#20]
Ideally using pipelineTriggers in the Jenkinsfile, but acceptable to edit in the Jenkins configure view directly, to trigger openjdk_test_platformxxxx build to successful completion of openjdk_build_platformxxxx build.

**Comment by sophia-guo** [comment]
Using openjdk_test_x86-64_linux as upstream project tried build triggers in Jenkins configure works fine. 
Trying pipelineTriggers:   
 		pipelineTriggers(
    			[
    				upstream(
    					threshold: <object of type hudson.model.Result>, 
    					upstreamProjects: 'openjdk_test_x86-64_linux'
    				)
    			]
    		)
Doesn't work. Investigating.

**Comment by sophia-guo** [comment]
Declarative Pipeline use triggers directive defines the automated ways in which the Pipeline should be re-triggered. Currently the only two available triggers are cron and pollSCM. 
https://jenkins.io/doc/book/pipeline/syntax/#triggers

Properties pipelineTriggers support build trigger, however it is for Scripted pipeline.

Besides we are using pipeline script from SCM, which means before builder is triggered jenkins job can not get any information about the job configuration from jenkinsfile. 

So I would say using webhooks-based integration may be good for us? @smlambert what's your suggestion?

**Comment by sophia-guo** [comment]
"Besides we are using pipeline script from SCM, which means before builder is triggered jenkins job can not get any information about the job configuration from jenkinsfile. " 
--This is not true.Using script from SCM, once the build has been run once, either parameter build or trigger whatever have been set in jenkinsfile will be stored in build configuration.

**Comment by smlambert** [comment]
Does that mean you don't need me to answer yes to webhooks?  Because I am happy to proceed with any approach that gives us the behaviour we want, which is to launch a test build from either a MR or a successful completion of a regular build (depending on the circumstance).

**Comment by sophia-guo** [comment]
openjdk_test_x86-64_linux has been set as trigger by openjdk_build_x86-64_linux. 
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/6/console

Working on PR trigger.

**Comment by sophia-guo** [comment]
Triggered by PR with specified comment : https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux_experimental/46/consoleFull

Also see : https://github.com/AdoptOpenJDK/openjdk-tests/pull/28

Comment should be made by authors in white-listed. ( Admins )
Any updated commit with new comment will trigger build again and override the former trigger result.

**Comment by sophia-guo** [comment]
It was resolved.
