### ISSUE TITLE
Unable to launch Grinder for arm32

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#2002]
Found the following issues trying to launch a Grinder against the latest nightly hotspot arm32 jdk11 build (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/build?delay=0sec).

1. The help text for the `PLATFORM` build parameter lists `arm_linux`, but the job actually seems to need the value `aarch32_linux`
2. Using `PLATFORM: aarch32_linux` and selecting `SDK_RESOURCE: Nightly` for the build type causes the job to attempt to download from
```
 https://api.adoptopenjdk.net/v3/binary/latest/11/ea/linux/aarch32/jdk/hotspot/normal/adoptopenjdk
```
but the url should be
```
https://api.adoptopenjdk.net/v3/binary/latest/11/ea/linux/arm/jdk/hotspot/normal/adoptopenjdk
```

The job ran successfully when `PLATFORM; aarch32_linux`,  `SDK_RESOURCE: Customized` and `CUSTOMIZED_SDK_URL: https://api.adoptopenjdk.net/v3/binary/latest/11/ea/linux/arm/jdk/hotspot/normal/adoptopenjdk` were specified.

**Comment by sophia-guo** [comment]
run against jdk 11:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4134/
run against jdk8:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4133/

Both no issues. Platform has been updated from aarch32_linux to arm_linux to be consistent with other repos. Correspondingly updated related logic in openjdk-tests repo.

**Comment by smlambert** [comment]
Help text was updated purposefully as part of https://github.com/AdoptOpenJDK/openjdk-tests/pull/1970#issuecomment-698355475, and Grinder links from @sophia-guo show examples of Grinders working, so will close this one.

**Comment by lumpfish** [comment]
Looks like I was missing https://github.com/AdoptOpenJDK/openjdk-tests/pull/1970 in my openjdk-tests fork branch.
