### ISSUE TITLE
OpenJDK tests ignore RELEASE_TAG value

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#2006]
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/62/rebuild/parameterized has RELEASE_TAG=openj9-0.23.0 passed in, but we git clone `openj9` branch

```
git clone --depth 1 -q -b openj9 https://github.com/ibmruntimes/openj9-openjdk-jdk8 openjdktemp
```
It looks like instead of using `RELEASE_TAG`  value, we are using `JDK_IMPL` value.

Suspect there is a bug in https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml

**Comment by llxia** [comment]
As suggested in https://github.com/AdoptOpenJDK/openjdk-tests/pull/2007#issuecomment-705778591, we are going to set JDK_REPO and JDK_BRANCH explicitly in upstream jobs and remove RELEASE_TAG in the test script.

**Comment by smlambert** [comment]
Marking this as complete.
