### ISSUE TITLE
Jenkins continues regardless of the test compilation and test execution results

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#2068]
The recent PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/2059 changes the exit code of maketest.sh. As a result, Jenkins continues regardless of the test compilation and test execution results.

In our recent zos test build, the test compilation failed, but the build continued to run all the tests.

Maybe PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/2059 code should be in Post stage https://github.com/AdoptOpenJDK/openjdk-tests/blob/13d113e63e13b21860f453372b97327f6fa440c0/buildenv/jenkins/JenkinsfileBase#L572

**Comment by sophia-guo** [comment]
Or can just store the $MAKE command exit code. 

```
make_exit_code=$?
'window clean up code'
exit $make_exit_code
```

**Comment by llxia** [comment]
yes, we can. But if the build crashes, the Post stage will execute regardless.

**Comment by smlambert** [comment]
Note: the process clean up (#2059) added to maketest.sh is meant to be 'temporary', as in, waiting for PR for https://github.com/AdoptOpenJDK/TKG/issues/45 to land, so that then this check can be moved to TKG setup phase.

**Comment by smlambert** [comment]
Not sure what the ETA for PR for TKG/45 is, if its going to be a while, we can/should take one of the solutions proposed in this issue.

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/2121 addresses this, closing this now.
