### ISSUE TITLE
JDK16 XL test jobs for ppc64le, s390x, and aarch64

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#2069]
JDK16 recently acquired a set of six build jobs for the production of XL builds.

When the "Test_Job_Auto_Gen" was run, three of these XL platforms gained some test jobs.

However, these did not: ppc64le_linux_xl, s390x_linux_xl, aarch64_linux_xl

I see 2 tasks here:

1) To rerun Test_Job_Auto_Gen to produce test jobs for the platforms listed above.
and
2) To add the same three platforms to a list of platforms for 15+ builds in the param text for ARCH_OS_LIST in Test_Job_Auto_Gen, so this doesn't happen again.

@smlambert - Can I ask you to take a look at item 1 while I make a PR for item 2, please?

**Comment by smlambert** [comment]
Both tasks done.   Missing jobs generated [here](https://ci.adoptopenjdk.net/job/Test_Job_Auto_Gen/222/).

**Comment by adamfarley** [comment]
Thanks Shelley.
