### ISSUE TITLE
openjdk-test PR test build gets triggered without any code change

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#2072]
Currently, if PR changes status (even without any code change), the PR test build will get triggered.
For example,  PR is merged; PR changes status to Ready for Review.

<img src="https://user-images.githubusercontent.com/19273206/100371544-ed420b00-2fd5-11eb-83a8-904b826b238c.png" width=600 />
<img src="https://user-images.githubusercontent.com/19273206/100372183-e36cd780-2fd6-11eb-9e4a-287de86774dd.png" width=600 />

Link to trigger PR test builds: https://github.com/AdoptOpenJDK/openjdk-tests/actions?query=workflow%3A%22openjdk-test+CI+for+PUSH+or+PR+test+build%22

Is this expected behavior? Ideally, if there is no code change, PR test build should not get triggered. I think we should limit when PR test build should be triggered to use the resource efficiently.

**Comment by smlambert** [comment]
Agreed.  As noted in a recent discussion, we all prefer to have some form of "change-based' testing in play here.  Thanks for raising the issue so it's not lost beyond a conversation of all the ways we should improve our processes.  :)

**Comment by llxia** [comment]
Code that needs to be updated: https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/.github/workflows/PushOrPRtestbuild.yml#L15

Link to the doc:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request

**Comment by patkarns** [comment]
I'll be working on this!
