### ISSUE TITLE
extended.external fails due to parallel SubDir childJobNum exceeds 20

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#2117]
Extended.external uses parallel=SubDir, but this now fails as the number of sub dirs exceeds 20:
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_hs_extended.external_x86-64_linux/31/console

This limited and asserts the job here: https://github.com/AdoptOpenJDK/openjdk-tests/blob/1be48796f2a31912cd53cc55a6f27978445bd050/buildenv/jenkins/JenkinsfileBase#L202

**Comment by smlambert** [comment]
An update to that childJobNum will land when https://github.com/AdoptOpenJDK/openjdk-tests/pull/2093 is merged.

**Comment by smlambert** [comment]
This issue is now addressed via #2093
