### ISSUE TITLE
Add dacapo tests in TRSS

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#2122]
Jenkins link: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.perf_x86-64_linux/426/consoleFull

https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/perf/dacapo/playlist.xml

Similar to PR https://github.com/AdoptOpenJDK/openjdk-test-tools/pull/205/

**Comment by smlambert** [comment]
I think the initial widget is now in place.  

It will be good to add the j9 extended.perf and the hs sanity.perf and extended.perf as well (since they all contain dacapo benchmarks).  I have not looked too closely in the TRSS code, but we should probably separate the impls into their own widgets.

**Comment by llxia** [comment]
The changes are delivered in TRSS repo. Any future issues should track in TRSS repo as well.
