### ISSUE TITLE
date -R option unsupported on some mac machines 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2127]
**Describe the bug**
PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/2121 merged a change in Jenkinsfile base that has introduced an issue on some mac machines

22:13:49  + date -R
22:13:49  date: illegal option -- R
22:13:49  usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
22:13:49              [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

-R option does not work on some mac machines, unable to run test jobs on these machines (though not all machines), not sure if there is another option that can be used that is more globally accepted or not, needs investigation.

see https://github.com/eclipse/openj9/issues/11502

**Comment by smlambert** [comment]
From man page of date function:
-R      Use RFC 2822 date and time output format. This is equivalent to use ``%a, %d %b %Y %T %z'' as output_fmt while LC_TIME is set to the ``C'' locale .

Since its not always present as an option, perhaps can use the uglier equivalent...

**Comment by smlambert** [comment]
This was reported on mac10_11, we have no machines of that vintage, but do have 10_10, running a [Grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5563/) on test-macincloud-macos1010-x64-1

**Comment by smlambert** [comment]
FYI @andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
Fixed by #2128

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/2128 is now merged.
