### ISSUE TITLE
jdk8 draginwell sanity.perf: No such property: activeNodeTimeoutString

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#2131]
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk8_dragonwell_sanity.perf_x86-64_linux/114/console
```
LABEL: ci.role.perf&&hw.arch.x86&&sw.os.linux
[Pipeline] stage
[Pipeline] { (Queue)
[Pipeline] nodesByLabel
Could not find any nodes with 'ci.role.perf&&hw.arch.x86&&sw.os.linux' label
[Pipeline] echo
Cannot find an active node matching this label: ci.role.perf&&hw.arch.x86&&sw.os.linux
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: activeNodeTimeoutString for class: WorkflowScript
```

**Comment by smlambert** [comment]
I've re-auto-generated Test_openjdk8_dragonwell_sanity.perf_x86-64_linux job configuration [here](https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/230/) (which previously had ci.role.perf in the LABEL field, and was missing the active node timeout parameter value, which will resolve this issue.

**Comment by andrew-m-leonard** [comment]
same issue with jdk11 last night, i've run a testAutoGen for jdk11 as well: https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/231/
