### ISSUE TITLE
sanity/extended.system won't run on macos10.15

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#2133]
I looks like these tests fail on macos10.15 with:
```
17:47:47       [exec] ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd' for architecture x86_64
17:47:47       [exec] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk8_j9_extended.system_x86-64_mac_xl/431/console
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_j9_extended.system_x86-64_mac/431/console

**Comment by andrew-m-leonard** [comment]
Node's ld version:
```
test-macstadium-macos1015-x64-1:~ jenkins$ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-450.3
BUILD 18:16:53 Apr  5 2019
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 10.0.1, (clang-1001.0.46.4) (static support for 22, runtime is 22)
TAPI support using: Apple TAPI version 10.0.1 (tapi-1001.0.4.1)
```

**Comment by andrew-m-leonard** [comment]
@smlambert can we remove the ci.role.test from this node until this is resolved?

**Comment by smlambert** [comment]
There are 2 infra issues (https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1777  and  https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1673) and 2 test issues (this one and #2096) tracking the same problem, I will close the test issues as it is specifically an infra issue on a single machine.
