### ISSUE TITLE
Comment triggered PR builds

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2199]
Comment triggered PR builds (related to AdoptOpenJDK/TKG#109)
-- Trigger PR testing manually using comment in the git PR
-- Allow users to specify SDK (default is nightly). Users can specify releases/nightly
-- Allow users to specify test targets (sanity.system, extended.openjdk, etc)
-- Allow other values to be specified. For example:
```
action nightly sanity.functional xlinuxlargeheap jdk11
action releases testA,testB xlinux,osx jdk8,jdk11 hotspot,openj9
```

**Comment by smlambert** [comment]
@patkarns @icohedron @yanshan24 @xfxcwynlc @xichen1

**Comment by smlambert** [comment]
In our call, we referenced an example of comment triggered workflow ([autoTestPR.yml](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/.github/workflows/autoTestPR.yml) which ends up calling some [python code](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/.github/workflows/autoTestPR.yml#L33) in the [TKG repo](https://github.com/AdoptOpenJDK/TKG/blob/master/scripts/testBot/disable.py))

In a similar fashion, can we trigger some PR tests (like (PushOrPRtestbuild.yml)[https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/.github/workflows/PushOrPRtestbuild.yml] from a comment trigger instead of on [push](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/.github/workflows/PushOrPRtestbuild.yml#L4) or [pull_request](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/.github/workflows/PushOrPRtestbuild.yml#L14) trigger.

**Comment by patkarns** [comment]
Update: we got the arguments using a python script.

Next up, we'll trigger the PR test and check for invalid parameters (like versions).

@Icohedron

**Comment by Icohedron** [comment]
GitHub Workflow implementation for comment triggered PR builds should be complete in PR #2222
