### ISSUE TITLE
Certain test directories/files change trigger for PR testing

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2200]
Investigate and trial a github workflow that determines which openjdk-tests dir was changed, and then based on a defined mapping, takes different types of action. 

Start by looking at top-level directories and doing something basic like, if something changed in:
perf -> run sanity.perf test target
system -> run sanity.system test target
functional -> run sanity.functional test target
openjdk -> run sanity.openjdk test target

This approach could then be tuned to look at which test targets in a playlist changed and run the target or the level its contained within.  For now, we will ignore changes to doc, external and jck directories.

We can investigate what action to take if the buildenv dir changes in https://github.com/AdoptOpenJDK/openjdk-tests/issues/2204.  

If both test dirs and buildenv, dir changes, can a Grinder be triggered with targets from the playlists within the test dirs.

Essentially, this in combination with comment triggered PR testing (see https://github.com/AdoptOpenJDK/openjdk-tests/issues/2199) can allow us to reduce the amount of testing that happens as part of PR testing.  

A prototype workflow would output a result, which is a change-based test target, or a comma-separated list of test targets to be ingested by run-aqa github action to run a build with specific test target to run against changes in test category or trigger specific jenkins build to test jenkins changes.

**Comment by sophia-guo** [comment]
Related with #2292 
Probably we need to confirm:

> If buildenv dir changed, investigate how to trigger a Jenkins job in a github workflow to trigger a Grinder (via https://github.com/marketplace/actions/trigger-jenkins-job or similar)

Current #2292 is trying the grinder with default parameters. Should we set the grinder with platform which is not supported on github runner?

`If both test dirs and buildenv, dir changes, can a Grinder be triggered with targets from the playlists within the test dirs.`
Similar to the former one, Should we set the grinder with platform which is not supported on github runner?

**Comment by smlambert** [comment]
re: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2200#issuecomment-785426288

We can pick a platform where we have lots of machines attached to Jenkins, the purpose here is to check that changes to the Jenkins scripts are not broken.  

yes, I think if both buildenv and some test group dir changes, like system, the target/build_list could be matched up... that can be done as an iterative improvement to this initial contribution.

Another enhancement relating to the comment triggered workflow would be if someone typed "run aqa --platform=SomeNonGithubRunnerPlatform"... would be to trigger a Grinder on that platform, but for now lets leave it simple...

**Comment by smlambert** [comment]
Closing this as completed.
