### ISSUE TITLE
Workflow job triggered by a change to the buildenv directory

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2204]
Similar to #2200 this issue is to Investigate and trial a github workflow that determines if openjdk-tests/buildenv dir was changed, and then take a certain type of action. 

If buildenv dir changed, investigate how to trigger a Jenkins job in a github workflow to trigger a Grinder (via https://github.com/marketplace/actions/trigger-jenkins-job or similar) . 

If both test dirs and buildenv, dir changes, can a Grinder be triggered with targets from the playlists within the test dirs.

Essentially, this in combination with comment triggered PR testing (see https://github.com/AdoptOpenJDK/openjdk-tests/issues/2199) can allow us to reduce the amount of testing that happens as part of PR testing.  

A prototype workflow would trigger a Jenkins Grinder to test Jenkins changes.

**Comment by patkarns** [comment]
Update: formatted and passed targets from changed test dirs (output of Xichen's code #2200 ) as parameters into Grinder_Simple

- See: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/209/ (added empty files to the functional and system folders)

Going from here:

- [ ] Add test dir target(s) to the parameters only when **both** test dirs and buildenv dir changes (right now the targets are added to the parameters regardless of whether buildenv changes, also handle the case where test dirs is unchanged)
- [ ] Using sanity for efficiency/speed right now, will have to change or make the test groups dynamic later
- [ ] Change from yanan's username to a general user

**Comment by smlambert** [comment]
Closing as won't pursue at this time.
