### ISSUE TITLE
Re-enable code coverage testing

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2205]
This is related to #2186 

First part of this is to read up on jcov (FAQ, user guide and build instructions at: https://wiki.openjdk.java.net/display/CodeTools/jcov) 

Re-enable code coverage testing (from jcov work). This involves an instrumented build of the jdk repo (openjdk/jdk using jcov, see related issues [list](https://github.com/AdoptOpenJDK/openjdk-tests/issues?q=is%3Aissue++code+coverage+)). 

Note other coverage tools can be used for certain types of tests, but we will start with OpenJDK test material (and jcov for the coverage info). 

This item can be broken down and approached in several ways:
- try to revive the actual [openjdk9_jcov job](https://ci.adoptopenjdk.net/view/work-in-progress/job/openjdk8_jcov/)
- See if we can we leverage [build-jdk](https://github.com/AdoptOpenJDK/build-jdk) (and later [build-openj9](https://github.com/eclipse/build-openj9)) github action? (adding the build args to instrument and create jcov output). 
- In either approach above (running jcov in Jenkins or in github workflow, create an artifact that can be archived and pulled into in a 'next step'...

**Comment by sophia-guo** [comment]
[openjdk8_jcov](https://ci.adoptopenjdk.net/view/work-in-progress/job/openjdk8_jcov/) use the jtreg functions in openjdk-builds repo, which has been removed from the repo. To re-enable the build we can directly grab the nightly jdk or any interested jdk and run jtreg tests against the JDK by command like:

```
 java -jar jtreg.jar -jdk:$JDK -w:$JDK_WS -r:rep -avm -jcov/classes:$JDK/jre/lib/rt.jar -jcov/source:$JDK/src.zip -jcov/include:java.math.* /test/*
```

**Comment by sophia-guo** [comment]
[openjdk8_jcov](https://ci.adoptopenjdk.net/view/work-in-progress/job/openjdk8_jcov/) reenabled by removing the build jdk step and grab a jdk binary directly.
