### ISSUE TITLE
Temporarily exclude java/foreign/TestNative for jdk16+ J9 (all platforms)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2218]
Related to:
https://github.com/eclipse/openj9/issues/11760

**Comment by smlambert** [comment]
auto exclude test jdk_foreign_native impl=openj9 ver=16+

**Comment by karianna** [comment]
@smlambert can this be closed?

**Comment by smlambert** [comment]
Not really, not without me updating the URL [here](https://github.com/AdoptOpenJDK/openjdk-tests/pull/2219/files#diff-d2ae1ce824e94cb07603a5a77c2d8ab3c5b00617153e8d66e54a78a3ccfb4f1dR966): to point at the openj9 issue, because we will eventually automate the reinclusion of disabled tests by first checking if the issue is closed, grinding the test to see if it passes, then reincluding.

**Comment by smlambert** [comment]
Need to update the exclude to point at the openj9 issue so that this can be closed.
