### ISSUE TITLE
functional.extended target TestJstack_SE80_0 hangs on 32bit Windows

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#2220]
**Describe the bug**
functional.extended target TestJstack_SE80_0 hangs on 32bit Windows

I've determined it's a hang because a passing run takes 6 seconds, and the "hanging" run runs for over 9 hours before being killed.

https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_x86-32_windows/77/console

**To Reproduce**
https://ci.adoptopenjdk.net/job/Grinder/parambuild/?TARGET=TestJstack_SE80_0&SDK_RESOURCE=upstream&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&EXTRA_DOCKER_ARGS=&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&PLATFORM=x86-32_windows&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&LABEL=build-alibaba-win2012r2-x64-2&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&JDK_VERSION=8&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x86-32-openj9&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&TKG_SHA=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&NUM_MACHINES=&OPENJDK_SHA=&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=833&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None

**Expected behavior**
Test is expected to pass in 6 seconds, and not hang around for 9 hours.

**Screenshots**
```
21:25:57  [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is C:/Users/Jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-32_windows/openjdk-tests/\\TestConfig\\resources\\excludes\\latest_exclude_8.txt
21:25:57  ...
21:25:57  ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
21:25:57  ...
21:25:57  
Cancelling nested steps due to timeout
06:26:21  Sending interrupt signal to process
06:26:34  
06:26:34  TestJstack_SE80_0_FAILED
```

**Additional context**
Failed on build-alibaba-win2012r2-x64-2

**Comment by smlambert** [comment]
As per [Triage doc](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/doc/Triage.md#test-triage-at-adoptopenjdk), there is more investigation needed / Questions to be answered:

- is the failure specific to 1 or a set of machines
- diffing output on a clean run are there any other eye-catchers
- has it been seen/reported elsewhere or on any other platforms 
- this [TestJstack_SE80](https://github.com/eclipse/openj9/blob/master/test/functional/Java8andUp/playlist.xml#L543-L565) target is currently only run against openj9, if it proves not to be a machine issue, this issue should live in the openj9 repo
- it's a test that uses AttachAPI, are the settings being used appropriate: 
         -Dcom.ibm.tools.attach.enable=yes \
	-Djdk.attach.allowAttachSelf=true \
	-Dcom.ibm.tools.attach.timeout=15000

**Comment by smlambert** [comment]
From the console output of the failing test job:

```
16:25:51  
16:25:51  FAILED CONFIGURATION: @BeforeMethod setUp(public void org.openj9.test.attachAPI.TestAttachErrorHandling.testAttachWithCorruptAdvertisementFile())
16:25:51  java.lang.AssertionError: main process did not initialize attach API
16:25:51  	at org.testng.Assert.fail(Assert.java:96)
16:25:51  	at org.openj9.test.attachAPI.TestAttachErrorHandling.setUp(TestAttachErrorHandling.java:65)
16:25:51  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:25:51  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:25:51  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:25:51  	at java.lang.reflect.Method.invoke(Method.java:498)
16:25:51  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
16:25:51  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
16:25:51  	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
16:25:51  	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
16:25:51  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
16:25:51  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
16:25:51  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
16:25:51  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
16:25:51  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
16:25:51  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
16:25:51  	at org.testng.TestRunner.run(TestRunner.java:505)
16:25:51  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
16:25:51  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
16:25:51  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
16:25:51  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
16:25:51  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
16:25:51  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
16:25:51  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
16:25:51  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
16:25:51  	at org.testng.TestNG.runSuites(TestNG.java:1049)
16:25:51  	at org.testng.TestNG.run(TestNG.java:1017)
16:25:51  	at org.testng.TestNG.privateMain(TestNG.java:1354)
16:25:51  	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by smlambert** [comment]
My suspicion is that there is something different about how https://ci.adoptopenjdk.net/computer/build-alibaba-win2012r2-x64-2/ is configured that messes with the ability of attachAPI to initialize as the alibaba machines have had some differences in their config as compared to others.

Rerun on build-alibaba-win2012r2-x64-2 to confirm it consistently has initialization problems on that machine:
https://ci.adoptopenjdk.net/job/Grinder/6270

**Comment by adamfarley** [comment]
Triage doc - Good point, I didn't do that. Will track down that info now, and make extra sure to use the doc in the future.

Attach Options:

Comparing [this failing run](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_x86-32_windows/77/console) with [this passing run](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_x86-32_windows/79/consoleFull) shows that there is no difference in the commands or options used, so I don't think it's an attach options thing.

Specific machine:

As the passing run mentioned above passed on test-ibmcloud-win2012r2-x64-2, and that machine also seemed to lack the "main process did not initialize attach API" errors in the other tests within the same job, this evidence supports your theory of a config issue in build-alibaba-win2012r2-x64-2.

**Comment by smlambert** [comment]
Note: I also see AttachAPISanity_SE80 failing consistently on build-alibaba-win2012r2-x64-2

Deep history:
https://trss.adoptopenjdk.net/deepHistory?testId=6018c487ddf93e76e9fb9057

**Comment by adamfarley** [comment]
I think we should keep this issue open to make it easier for people to find, but another should be raised in the infra repository for further investigation.

**Comment by smlambert** [comment]
Out of curiosity, what is -Dcom.ibm.tools.attach.timeout=15000 (15 seconds) used for, if test hangs for 9hrs, does that timeout get applied per test class in the set of test classes that make up the TestJstack_SE80 target, but even then, doesn't account for a 9 hr hang.

**Comment by adamfarley** [comment]
I don't know.

I do know that "main process did not initialize attach API" was presumed caused by a machine issue in [this issue](https://github.com/eclipse/openj9/issues/1454), and that deleting a specific file resolved the issue.

**Comment by adamfarley** [comment]
To verify, let's re-run your grinder with  -Dcom.ibm.tools.attach.logging=yes on the test command line.

**Comment by smlambert** [comment]
I'll leave you to it

For reference (re: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2220#issuecomment-771805961): https://www.eclipse.org/openj9/docs/dcomibmtoolsattachtimeout/

**Comment by adamfarley** [comment]
Cancelling Shelley's grinder so we can get the debug output.

Since a passing TestJstack_SE80_0 run takes between 4 and 6 seconds, and it's already been 3 minutes, I think it's safe to assume we've got all the information we're liable to get out of it until it times out in 9 hours time.

**Comment by adamfarley** [comment]
Doesn't seem to have produced the desired logging output. To rule out the option simply being in the wrong place, here's a run with it hard-coded into the right place: https://ci.adoptopenjdk.net/job/Grinder/6295/console

If that doesn't work, and the digging I'm doing now doesn't produce results, will reach out to pdbain (who used the option initially).

**Comment by smlambert** [comment]
pdbain is retired, but I am sure you can ask in the openj9 channel and someone can help

**Comment by adamfarley** [comment]
Just found the log file the debug option creates.

Here's the problem:

[Attach API initializer]: AttachHandler initialized
[Attach API initializer]: IPC Directory=C:\cygwin\tmp\.com_ibm_tools_attach
[Attach API initializer]: The common directory already exists at C:\cygwin\tmp\.com_ibm_tools_attach
[Attach API initializer]: non-blocking locking file C:\cygwin\tmp\.com_ibm_tools_attach\_controller
[Attach API initializer]: locking file C:\cygwin\tmp\.com_ibm_tools_attach\_controller
[Attach API initializer]: lock failed, trying blocking lock
[Attach API initializer]: AttachHandler obtained controller lock
[Attach API initializer]: unlocking file C:\cygwin\tmp\.com_ibm_tools_attach\_attachlock
[Attach API initializer]: unlocking file C:\cygwin\tmp\.com_ibm_tools_attach\_controller
[Attach API initializer]: AttachHandler IOException while creating files: C:\cygwin\tmp\.com_ibm_tools_attach\10300
[Attach API initializer]: AttachHandler terminate: Attach API is being shut down, currentAttachThread = Thread[Attach API initializer,5,main]
[Attach API initializer]: AttachHandler terminate removing directory : C:\cygwin\tmp\.com_ibm_tools_attach
[Attach API initializer]: deleting my directory 
[Attach API initializer]: deleting my files
[Attach API initializer]: Exception in FilelockTimer.cancel: java.lang.InterruptedException:null
[Attach API initializer]: non-blocking locking file C:\cygwin\tmp\.com_ibm_tools_attach\_controller
[Attach API initializer]: VM already notified for termination, abandoning controller lock
[Attach API initializer]: AttachHandler tryObtainControllerLock failed
[Attach API initializer]: ERROR: failed to initialize

According to the [OpenJ9 issue](https://github.com/eclipse/openj9/issues/1454), deleting .com_ibm_tools_attach solved the issue.

Raising an infra ticket.

**Comment by adamfarley** [comment]
Tasks remaining:
- [ ] Monitor and help resolve [this infra ticket](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1887).
- [ ] Test that TestJstack_SE80_0 doesn't hang on that machine anymore.
- [ ] Add the "ci.role.test" label to build-alibaba-win2012r2-x64-2

**Comment by Haroon-Khel** [comment]
Job rerunning on build-alibaba-win2012r2-x64-2 at https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_extended.functional_x86-64_windows_xl/22/console

**Comment by adamfarley** [comment]
Verified fixed.
