### ISSUE TITLE
Utilize Jenkins Parameter Separator plugin to make test jobs more understandable

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2238]
To make it easier for people to understand all the various parameters that one can pass to the test pipeline, we can utilize the Jenkins Parameter Separator plugin.

We can divide the different parameters into logical groups and add extra information to aid understanding.  This can then be added into the [testJobTemplate](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate) so that any time we generate test jobs, they are presented in the same groups and order in (any) Jenkins server.

Proposed groups can be seen in the prototype:
https://ci.adoptopenjdk.net/view/work-in-progress/job/Grinder_ParamsSeparate/build?delay=0sec

-----------------

**Test Repositories Parameters**
Repositories where we pull test material from. Unless you are testing test code, these do not need to be changed.

**Non-AQA Test Repositories**
Additional test repositories that can be overlayed onto existing AQA test material for extra testing.

**Platform and Machine Selection Parameters**
Choose which platform to run tests on, and optionally specify machine label to send the test job to a certain machine is desired.

**JDK Selection Parameters**
Specify where to pick up JDK from and provide extra details if taking from upstream or customized.

**Test Selection Parameters**
Provide parameters for which test material to build and which test targets to run.

**Test Options Parameters**
Additional test parameters if you want to append or replace options, or repeat the test for more than 1 iteration.

**Test Parallelization Parameters**
Additional test options if you wish to run in various parallel modes

**Post Run Parameters**
Parameters to determine what to do with post run artifacts.

-----------------

The order of the groups in the Jenkins config should reflect which groups are REQUIRED (or often used) to go near the top, and those seldom used further down.  Some groups are closely related so should be near each other.  

Another note is that for various Grinders we have created, we do not even present certain groups of parameters, in order to keep the config simple, and example is [Grinder_Simple](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/build?delay=0sec) (which runs with many of the parameters prepopulated with default settings and therefore does not even present them in the config view).

**Comment by smlambert** [comment]
Additional notes:

- testJobTemplate is a [job DSL](https://plugins.jenkins.io/job-dsl/) script that we use to generate all test jobs in Jenkins, if we update it with extra information to separate and group the parameters used in test jobs, it will make all test jobs more readable and standardized
- read the Jenkins Parameter Separator plugin doc here: https://plugins.jenkins.io/parameter-separator/
- especially the section entitled "Example usage in scripted pipeline, with advanced custom styling" in order to accomplish a configuration that is shown in the example [Grinder_ParamsSeparate](https://ci.adoptopenjdk.net/view/work-in-progress/job/Grinder_ParamsSeparate/build?delay=0sec) job

**Comment by patkarns** [comment]
I investigated the benchmark and perf files and they seem identical. The only difference is that the perf tar file is inside another tar file like so: 
- benchmark_test_output.tar.gz\.\openjdk-tests\
- perf_test_output.tar.gz**\perf_test_output.tar**\.\openjdk-tests\

**Comment by smlambert** [comment]
@patkarns - we had to revert your PR #2375 because one of the servers that use this code did not have the plugin installed, it has now been installed (via https://github.com/eclipse-cbi/jiro/pull/156), so I think we can try again to bring your changes in.

**Comment by smlambert** [comment]
Closing as completed via https://github.com/AdoptOpenJDK/openjdk-tests/pull/2464, thanks @patkarns !
