### ISSUE TITLE
Request for the generation of test jobs for JDK8, 11, and 16

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#2260]
**Describe the bug**
89 test jobs appear to be missing from Jenkins.

**Expected behavior**
The upstream build jobs appear to try to find and launch these jobs as part of the weekend runs on j9 and hs jdk8, 11, and 16.

**Additional context**
Here is the list. Note that, since the majority are sanity.external (which may not be a priority "add"), I've separated the list into two lists: 33 non-sanity.external, and 56 sanity.external. Further groupings are by jdk version, then vm, and then platform.

Test_openjdk8_j9_sanity.perf_ppc64le_linux_xl
Test_openjdk8_j9_sanity.functional_ppc64le_linux_xl
Test_openjdk8_j9_extended.functional_ppc64le_linux_xl
Test_openjdk8_j9_extended.perf_ppc64le_linux_xl
Test_openjdk8_j9_special.functional_ppc64le_linux_xl
Test_openjdk8_j9_sanity.functional_s390x_linux_xl
Test_openjdk8_j9_extended.functional_s390x_linux_xl
Test_openjdk8_j9_special.functional_s390x_linux_xl
Test_openjdk8_hs_sanity.perf_s390x_linux
Test_openjdk8_hs_sanity.system_arm_linux
Test_openjdk8_hs_extended.system_arm_linux
Test_openjdk8_hs_sanity.perf_arm_linux
Test_openjdk8_hs_sanity.functional_arm_linux
Test_openjdk8_hs_extended.functional_arm_linux
Test_openjdk8_hs_extended.openjdk_arm_linux
Test_openjdk8_hs_extended.perf_arm_linux
Test_openjdk8_hs_special.functional_arm_linux
Test_openjdk11_hs_extended.openjdk_arm_linux
Test_openjdk11_hs_special.functional_arm_linux
Test_openjdk11_j9_sanity.functional_s390x_linux_xl
Test_openjdk11_j9_extended.functional_s390x_linux_xl
Test_openjdk11_j9_special.functional_s390x_linux_xl
Test_openjdk11_j9_sanity.perf_ppc64le_linux_xl
Test_openjdk11_j9_sanity.functional_ppc64le_linux_xl
Test_openjdk11_j9_extended.functional_ppc64le_linux_xl
Test_openjdk11_j9_extended.perf_ppc64le_linux_xl
Test_openjdk11_j9_special.functional_ppc64le_linux_xl
Test_openjdk11_j9_sanity.perf_aarch64_linux_xl
Test_openjdk11_j9_sanity.functional_aarch64_linux_xl
Test_openjdk11_j9_extended.functional_aarch64_linux_xl
Test_openjdk11_j9_extended.perf_aarch64_linux_xl
Test_openjdk11_j9_special.functional_aarch64_linux_xl
Test_openjdk16_hs_special.functional_arm_linux

Test_openjdk8_j9_sanity.external_ppc64le_linux
Test_openjdk8_j9_sanity.external_x86-64_windows
Test_openjdk8_j9_sanity.external_x86-64_linux_xl
Test_openjdk8_j9_sanity.external_ppc64_aix
Test_openjdk8_j9_sanity.external_x86-32_windows
Test_openjdk8_j9_sanity.external_x86-64_windows_xl
Test_openjdk8_j9_sanity.external_x86-64_mac_xl
Test_openjdk8_j9_sanity.external_aarch64_linux
Test_openjdk8_j9_sanity.external_ppc64le_linux_xl
Test_openjdk8_j9_sanity.external_s390x_linux_xl
Test_openjdk8_j9_sanity.external_x86-64_mac
Test_openjdk8_hs_sanity.external_aarch64_linux
Test_openjdk8_hs_sanity.external_x86-64_mac
Test_openjdk8_hs_sanity.external_arm_linux
Test_openjdk8_hs_sanity.external_ppc64_aix
Test_openjdk8_hs_sanity.external_x86-32_windows
Test_openjdk8_hs_sanity.external_x86-64_windows
Test_openjdk8_hs_sanity.external_ppc64le_linux
Test_openjdk11_hs_sanity.external_x86-64_mac
Test_openjdk11_hs_sanity.external_x86-32_windows
Test_openjdk11_hs_sanity.external_aarch64_linux
Test_openjdk11_hs_sanity.external_ppc64le_linux
Test_openjdk11_hs_sanity.external_x86-64_windows
Test_openjdk11_hs_sanity.external_ppc64_aix
Test_openjdk11_hs_sanity.external_arm_linux
Test_openjdk11_j9_sanity.external_x86-64_mac
Test_openjdk11_j9_sanity.external_ppc64le_linux
Test_openjdk11_j9_sanity.external_x86-64_mac_xl
Test_openjdk11_j9_sanity.external_s390x_linux_xl
Test_openjdk11_j9_sanity.external_x86-64_windows
Test_openjdk11_j9_sanity.external_ppc64le_linux_xl
Test_openjdk11_j9_sanity.external_x86-64_linux_xl
Test_openjdk11_j9_sanity.external_aarch64_linux
Test_openjdk11_j9_sanity.external_aarch64_linux_xl
Test_openjdk11_j9_sanity.external_x86-64_windows_xl
Test_openjdk11_j9_sanity.external_ppc64_aix
Test_openjdk16_hs_sanity.external_x86-64_windows
Test_openjdk16_hs_sanity.external_aarch64_linux
Test_openjdk16_hs_sanity.external_x86-64_linux
Test_openjdk16_hs_sanity.external_arm_linux
Test_openjdk16_hs_sanity.external_s390x_linux
Test_openjdk16_hs_sanity.external_x86-64_mac
Test_openjdk16_hs_sanity.external_ppc64_aix
Test_openjdk16_hs_sanity.external_ppc64le_linux
Test_openjdk16_hs_sanity.external_x86-32_windows
Test_openjdk16_j9_sanity.external_x86-64_mac
Test_openjdk16_j9_sanity.external_ppc64_aix
Test_openjdk16_j9_sanity.external_ppc64le_linux
Test_openjdk16_j9_sanity.external_x86-64_windows_xl
Test_openjdk16_j9_sanity.external_ppc64le_linux_xl
Test_openjdk16_j9_sanity.external_x86-64_linux
Test_openjdk16_j9_sanity.external_x86-64_windows
Test_openjdk16_j9_sanity.external_x86-64_linux_xl
Test_openjdk16_j9_sanity.external_s390x_linux
Test_openjdk16_j9_sanity.external_aarch64_linux
Test_openjdk16_j9_sanity.external_x86-64_mac_xl

**Comment by smlambert** [comment]
> Test_openjdk8_j9_sanity.perf_ppc64le_linux_xl
> Test_openjdk8_j9_sanity.functional_ppc64le_linux_xl
> Test_openjdk8_j9_extended.functional_ppc64le_linux_xl
> Test_openjdk8_j9_extended.perf_ppc64le_linux_xl
> Test_openjdk8_j9_special.functional_ppc64le_linux_xl
> Test_openjdk8_j9_sanity.functional_s390x_linux_xl
> Test_openjdk8_j9_extended.functional_s390x_linux_xl
> Test_openjdk8_j9_special.functional_s390x_linux_xl

Generated via https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/244/


> Test_openjdk11_j9_sanity.functional_s390x_linux_xl
> Test_openjdk11_j9_extended.functional_s390x_linux_xl
> Test_openjdk11_j9_special.functional_s390x_linux_xl
> Test_openjdk11_j9_sanity.perf_ppc64le_linux_xl
> Test_openjdk11_j9_sanity.functional_ppc64le_linux_xl
> Test_openjdk11_j9_extended.functional_ppc64le_linux_xl
> Test_openjdk11_j9_extended.perf_ppc64le_linux_xl
> Test_openjdk11_j9_special.functional_ppc64le_linux_xl
> Test_openjdk11_j9_sanity.perf_aarch64_linux_xl
> Test_openjdk11_j9_sanity.functional_aarch64_linux_xl
> Test_openjdk11_j9_extended.functional_aarch64_linux_xl
> Test_openjdk11_j9_extended.perf_aarch64_linux_xl
> Test_openjdk11_j9_special.functional_aarch64_linux_xl

Generated via https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/245/

**Comment by smlambert** [comment]
> Test_openjdk8_hs_sanity.system_arm_linux
> Test_openjdk8_hs_extended.system_arm_linux
> Test_openjdk8_hs_sanity.perf_arm_linux
> Test_openjdk8_hs_sanity.functional_arm_linux
> Test_openjdk8_hs_extended.functional_arm_linux
> Test_openjdk8_hs_extended.openjdk_arm_linux
> Test_openjdk8_hs_extended.perf_arm_linux
> Test_openjdk8_hs_special.functional_arm_linux
> Test_openjdk11_hs_extended.openjdk_arm_linux
> Test_openjdk11_hs_special.functional_arm_linux
> Test_openjdk16_hs_special.functional_arm_linux

Generated via https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/246/

**Comment by smlambert** [comment]
> Test_openjdk8_j9_sanity.external_ppc64le_linux
> Test_openjdk8_j9_sanity.external_x86-64_linux_xl
> Test_openjdk8_j9_sanity.external_ppc64le_linux_xl
> Test_openjdk8_j9_sanity.external_s390x_linux_xl

> Test_openjdk11_j9_sanity.external_ppc64le_linux
> Test_openjdk11_j9_sanity.external_s390x_linux_xl
> Test_openjdk11_j9_sanity.external_ppc64le_linux_xl
> Test_openjdk11_j9_sanity.external_x86-64_linux_xl


Generated via https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/247/

external group should only be running on test machines with the sw.tool.docker label (https://ci.adoptopenjdk.net/label/ci.role.test&&sw.tool.docker/), so if build pipelines are trying to run tests on other platforms where we do not have machines with Docker installed, they will fail (not finding any machines to run on)...  I have marked them below with a * and will not generate them.  Build pipeline code will have to be updated if its trying to run external tests on those platforms.

> Test_openjdk8_j9_sanity.external_x86-64_windows*
> Test_openjdk8_j9_sanity.external_ppc64_aix*
> Test_openjdk8_j9_sanity.external_x86-32_windows*
> Test_openjdk8_j9_sanity.external_x86-64_windows_xl*
> Test_openjdk8_j9_sanity.external_x86-64_mac_xl*
> Test_openjdk8_j9_sanity.external_x86-64_mac*
> Test_openjdk11_j9_sanity.external_x86-64_mac* 
> Test_openjdk11_j9_sanity.external_x86-64_mac_xl*
> Test_openjdk11_j9_sanity.external_x86-64_windows*
> Test_openjdk11_j9_sanity.external_x86-64_windows_xl*
> Test_openjdk11_j9_sanity.external_ppc64_aix*
> Test_openjdk8_j9_sanity.external_aarch64_linux*
> Test_openjdk11_j9_sanity.external_aarch64_linux*
> Test_openjdk11_j9_sanity.external_aarch64_linux_xl

**Comment by smlambert** [comment]
> Test_openjdk16_j9_sanity.external_ppc64le_linux
> Test_openjdk16_j9_sanity.external_ppc64le_linux_xl
> Test_openjdk16_j9_sanity.external_x86-64_linux
> Test_openjdk16_j9_sanity.external_x86-64_linux_xl
> Test_openjdk16_j9_sanity.external_s390x_linux

Generated via https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/248/

* Platforms below do not have Docker installed and should not have sanity.external test jobs triggered on them.

> Test_openjdk16_j9_sanity.external_x86-64_mac*
> Test_openjdk16_j9_sanity.external_ppc64_aix*
> Test_openjdk16_j9_sanity.external_x86-64_windows_xl*
> Test_openjdk16_j9_sanity.external_x86-64_windows*
> Test_openjdk16_j9_sanity.external_aarch64_linux*
> Test_openjdk16_j9_sanity.external_x86-64_mac_xl*

**Comment by smlambert** [comment]
> Test_openjdk8_hs_sanity.external_ppc64le_linux
> Test_openjdk11_hs_sanity.external_ppc64le_linux
> Test_openjdk16_hs_sanity.external_x86-64_linux
> Test_openjdk16_hs_sanity.external_s390x_linux
> Test_openjdk16_hs_sanity.external_ppc64le_linux

Generated via https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/251/


The ones* below should not be generated and run, as there are no machines to match the sw.tool.docker tag that external tests currently require.

> Test_openjdk8_hs_sanity.external_aarch64_linux*
> Test_openjdk8_hs_sanity.external_x86-64_mac*
> Test_openjdk8_hs_sanity.external_arm_linux*
> Test_openjdk8_hs_sanity.external_ppc64_aix*
> Test_openjdk8_hs_sanity.external_x86-32_windows*
> Test_openjdk8_hs_sanity.external_x86-64_windows*
> Test_openjdk11_hs_sanity.external_x86-64_mac*
> Test_openjdk11_hs_sanity.external_x86-32_windows*
> Test_openjdk11_hs_sanity.external_aarch64_linux*
> Test_openjdk11_hs_sanity.external_x86-64_windows*
> Test_openjdk11_hs_sanity.external_ppc64_aix*
> Test_openjdk11_hs_sanity.external_arm_linux*
> Test_openjdk16_hs_sanity.external_x86-64_windows*
> Test_openjdk16_hs_sanity.external_aarch64_linux*
> Test_openjdk16_hs_sanity.external_arm_linux*
> Test_openjdk16_hs_sanity.external_x86-64_mac*
> Test_openjdk16_hs_sanity.external_ppc64_aix*
> Test_openjdk16_hs_sanity.external_x86-32_windows*

**Comment by smlambert** [comment]
I believe all the jobs that should be generated now have been.  For the jobs marked with * in above comments that are trying to run but should not, we will have to clean those up from the build pipelines.  Can create a PR soon for that.

**Comment by adamfarley** [comment]
Thanks Shelley :)
