### ISSUE TITLE
Test Post-Parallel should not be limited to run on $LABEL node

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-tests#2262]
After the children from a parallel test run finish, a `node("$LABEL")` is grabbed in order to copy and archive the artifacts to the parent test pipeline. In my opinion this shouldn't be limited to a node that matches the test node defined by `LABEL`. I often see this step stalled while a node becomes available. It could run on any machine. I would propose it could run on any `ci.role.test`. I don't like hardcoding so I'm open to other ideas.

The only caveat _may_ be z/OS due to encoding. We'd have to test it.

https://github.com/AdoptOpenJDK/openjdk-tests/blob/2305ce2c3c3cdb4fd5d1b29d1b3d15fe9376fceb/buildenv/jenkins/JenkinsfileBase#L872

**Comment by AdamBrousseau** [comment]
@llxia I don't really like any of these options, but we could
1. Add an optional parameter for SETUP_LABEL which would be substituted for LABEL at this step.
2. Remove the LABEL from the node block so any machine is picked.
3. Hardcode it to `ci.role.test`. This might be the least bad option.

**Comment by llxia** [comment]
Options 2 may be the easiest as we should be able to use any node for copying files (assuming this works on zos). I will do some tests for this.
