### ISSUE TITLE
Enable Java10 testing in Jenkins 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#228]
As there is a Java10 build available to test, we should enable the openjdk_regression and systemtest suites at minimum.

**Comment by karianna** [comment]
Please note that the Java 10 is an old build, see https://github.com/AdoptOpenJDK/openjdk-build/pull/209 which needs to land first before we can sanely test.

**Comment by sophia-guo** [comment]
Will "openjdk-jdk10" in "https://github.com/AdoptOpenJDK/openjdk-jdk10" be changed to openjdk-jdk?

**Comment by smlambert** [comment]
We will need to update the openjdk_regression/playlist file for a few tests that require additional commandline option to point to location of native tests for Java10 testing (see below, and https://download.java.net/openjdk/testresults/10/docs/howtoruntests.html for details).

-nativepath:{location of the jdk test native library}: This has to be generated at build time of the test jdk by invoking "make test-image". These libraries are located in the build directory under "images/test/jdk/jtreg/native/"

**Comment by sophia-guo** [comment]
Will the OpenjdkBuild build test-image or test build do it?

**Comment by smlambert** [comment]
I presume it makes sense to have the native test libs be built alongside the JVM (as they have been done for Java8 and Java9), so if they are not currently being built as part of the Java10 builds, we should open an issue on the openjdk-build repo.

**Comment by sophia-guo** [comment]
I have double check no test image is built in Java10 builds. Will open an issue in build repo.

**Comment by sophia-guo** [comment]
Open an issue https://github.com/AdoptOpenJDK/openjdk-build/issues/248

**Comment by smlambert** [comment]
Closing as now listed in summary issue #346
