### ISSUE TITLE
Reduce verbosity of parseComment job in runAqa.yml workflow 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2289]
For cases where parseComment finds there is nothing to do, the bot does not need create a comment.  In fact it is preferable to only comment if there is an action that has happened (be quiet when skipped).

(But excited to see this workflow in place, yay!)

**Comment by Icohedron** [comment]
@smlambert Could you give an example of when parseComment should not create a comment?

**Comment by Icohedron** [comment]
oh that is very odd

**Comment by Icohedron** [comment]
Working on fixing this ASAP

**Comment by sophia-guo** [comment]
Might be this line https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/.github/workflows/runAqa.yml#L130
