### ISSUE TITLE
Update Renaissance suite to latest release v0.11.0

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2298]
We are currently using Renaissance v0.9.0 and should update to latest release (https://github.com/renaissance-benchmarks/renaissance/releases/tag/v0.11.0) - update can be made in perf/renaissance/[build.xml_L37](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/perf/renaissance/build.xml#L37) file.

We should then check if this addresses any of the renaissance benchmark failures reported under
- https://github.com/AdoptOpenJDK/openjdk-tests/issues/1932
- https://github.com/AdoptOpenJDK/openjdk-tests/issues/1994
- https://github.com/AdoptOpenJDK/openjdk-tests/issues/2159
- https://github.com/AdoptOpenJDK/openjdk-tests/issues/2183
- https://github.com/AdoptOpenJDK/openjdk-tests/issues/2253
- https://github.com/AdoptOpenJDK/openjdk-tests/issues/2254
- https://github.com/AdoptOpenJDK/openjdk-tests/issues/2255

**Comment by sophia-guo** [comment]
Renaissance's releases provides binary file formats which means we can get the latest releases by auto script. 

`curl -s https://api.github.com/repos/renaissance-benchmarks/renaissance/releases/latest`
`curl -s https://api.github.com/repos/renaissance-benchmarks/renaissance/releases/latest | grep "browser_download_url"`

**Comment by smlambert** [comment]
Ah, sorry @sophia-guo - I did not see your comment before merging the PR related to this issue.

**Comment by sophia-guo** [comment]
That's ok. I've related this with #1971 we can close this.
