### ISSUE TITLE
Update playlist to use new disable feature

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#2361]
**👾 Description of the issue**

We should update the openjdk/playlist.xml file to use the new disable feature which uses explicit tags in the xml file to indicate which tests are disabled.  The old way was to put a comment in the xml file (often starting with `<!-- temporarily disable....`
see here for an example: https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/playlist.xml#L89

which should be changed to 
```
  <disabled>
    <comment>https://github.com/eclipse/openj9/issues/10757</comment>
    <impl>openj9</impl>
  </disabled>
```

There are many occurrences to fix in the playlist file, best to start with a search for `<!-- temp` but also good to look carefully through the playlist file for any comment that may reference that a test has been disabled.

Please refer to the readme for how to use the new disable feature:
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/doc/userGuide.md#manually-exclude-a-test-target

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by jwnmoon** [comment]
I will work on this one.

**Comment by smlambert** [comment]
Great! @jwnmoon - if you have any questions, you can post them as comments in this issue.  :)

**Comment by jwnmoon** [comment]
Hi, if I'm understanding the line above correctly it's excluding the debug interface for openj9, so it could be written using the new disable feature. Is this something that should be changed?

**Comment by smlambert** [comment]
That is correct @jwnmoon !  That is one of several examples in this file that should be updated.

It indicates that the jdk_jdi test has been disabled for openj9 impl:

so the test defined at `https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/playlist.xml#L857-L885` should be updated from 

```
	<test>
		<testCaseName>jdk_jdi</testCaseName>
		<variations>
			<variation>Mode150</variation>
			<variation>Mode650</variation>
			<variation>Mode1000</variation>
		</variations>
	...
		<impls>
			<impl>hotspot</impl>
		</impls>
	</test>
```

to 

```
	<test>
		<testCaseName>jdk_jdi</testCaseName>
                 <disabled>
                     <comment>https://github.com/AdoptOpenJDK/openjdk-tests/issues/1071</comment>
                     <impl>openj9</impl>
                  </disabled>
		<variations>
			<variation>Mode150</variation>
			<variation>Mode650</variation>
			<variation>Mode1000</variation>
		</variations>
...
	</test>
```

Where the new `<disabled>` tag is used, and the `<impl>` tag no longer needs to be defined, noting that if the impl tag is defined, it means to restrict the test to whatever implementation is listed there.  If the impl tag is not defined, it means the test applies to all implementations (which is true, we just need to temporarily exclude it for the openj9 impl).

**Comment by jwnmoon** [comment]
Do the lines about hotspot implementations need to be deleted on other tests as well? I assume the tests would apply to all implementations so they wouldn't have to be defined, but I'm not feeling too sure.

**Comment by jwnmoon** [comment]
I just created a pull request! I would appreciate it if you could review what I have.
