### ISSUE TITLE
Add documentation to run system_custom 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#2390]
We need to add a documentation somewhere to run `system_custom`. 

The basic content of this documentation is available here: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2234

**Comment by Mesbah-Alam** [comment]
@llxia - I remember we spoke about this earlier. Do you have. suggestion as to where this documentation could be added?

**Comment by llxia** [comment]
A couple of places:
- https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins
- add as the parameter description in the test job template

**Comment by Mesbah-Alam** [comment]
Added documentation in the wiki: https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins

**Comment by llxia** [comment]
Another place to update: https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally#system-tests

**Comment by karianna** [comment]
@Mesbah-Alam can this be closed now?

**Comment by Mesbah-Alam** [comment]
Please keep it open. I need to run some testing to see if we can automate a step we had mentioned in the documentation.

**Comment by llxia** [comment]
@patkarns Once https://github.com/AdoptOpenJDK/openjdk-tests/pull/2375 is merged, we can update the test job template to show `system_custom` example.

**Comment by Mesbah-Alam** [comment]
Removed note about having to add `-add-opens..` option from wiki  https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins. 

We are doing it automatically now, ref: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2413

**Comment by Mesbah-Alam** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/2413 has been delivered. This issue can now be closed.

**Comment by llxia** [comment]
Reopen as we need to add the example https://github.com/AdoptOpenJDK/openjdk-tests/issues/2390#issuecomment-805827188
