### ISSUE TITLE
Add Logstash tests

### ISSUE THREAD

**Issue by smithwil** [AdoptOpenJDK/openjdk-tests#243]
This request comes from a Java support case, where a developer was getting unexpected errors running Logstash, on Java 8 and the critical part was the platform: Power9 Linux PPCLE. The errors did not happen on Power8.

I don't know when AdoptOpenJDK will get Power9 hardware to test on, but maybe that doesn't matter. Perhaps any test material set up here can be reused by whatever project does get Power9 test hardware.

The errors below came from jruby (running Logstash). The LoadError happened once and the SyntaxError was reported at many points in the jruby script:

LoadError: library 'jruby' could not be loaded: java.lang.NullPointerException

SyntaxError: class/module name must be CONSTANT

Here are the details I could get, of the test set up that found
errors.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
1. download the application from https://artifacts.elastic.co/downloads/logstash/logstash-5.4.2.tar.gz
2. extract the jruby application
3. export JAVA_HOME environment
4. create a simple configuration file named index.conf in the folder logstash-5.4.2 with below content

input {
beats {
port => "5045"
congestion_threshold => 60
}
}

filter {
}

output {

}

5. start the application with command line:

bin/logstash -f index.conf

then you will see the exception and programme terminated. [Only Power9 platform only].
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Reference PMR 02048,001,866 from Zhan Wei Wang

**Comment by smlambert** [comment]
Plan to address this issue:
thirdparty_containers/startup directory for a set of tests that just starts up applications (doesn't run a suite of tests), as a quick sniff.  These tests can/should be run on actual machines, vs in Docker containers if needed.

**Comment by smlambert** [comment]
Closing this issue (now added to the list in #172).
