### ISSUE TITLE
Related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/186

### ISSUE THREAD

**Issue by ecoarqtec** [AdoptOpenJDK/openjdk-tests#2459]
Related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/186

_Originally posted by @smlambert in https://github.com/AdoptOpenJDK/openjdk-tests/issues/965#issuecomment-471765796_

**Comment by smlambert** [comment]
@ecoarqtec - this appears to be an autogenerated bug report.  Given there are no details or context, I will close it.  Feel free to reopen it if there is some specific request that you can clarify in the description.
