### ISSUE TITLE
Investigate license requirements for several MBCS data files

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2528]
AIX_ko_KR.IBM-eucKR.txt
AIX_KO_KR.UTF-8.txt
Linux_ko_KR.UTF-8.txt
BreakIteratorTest.out
win_ko.txt

Contain the following license/copyright statement:

IMdkit&#47484; &#51228;&#50808;&#54620; &#48512;&#48516;&#51008;
&#54889;&#52824;&#45909;&#50640;&#44172; &#51200;&#51089;&#44428;&#51060;
&#51080;&#51004;&#47728; &#51060;&#51032; &#49324;&#50857;&#51008;
GPL&#50640; &#46384;&#46972;&#50556;&#54633;&#45768;&#45796;. COPYING
&#54028;&#51068; &#52280;&#51312;

which translates as:

All parts except IMdkit are copyrighted by Hwang Chi-deok, and its use is
It must be in accordance with the GPL. COPYING file reference

Question:
can we remove and/or replace these files with more permissive licenses (GPL is not permissive enough) in order to transition them as part of this repository to the Eclipse foundation (under the Adoptium github organization).

FYI @KKES335 @takiguc - your input is requested.

**Comment by takiguc** [comment]
@smlambert 
Thank you for your notification.
These are data files for BreakIterator testcase on Korean locale.
I'll check them with my co-workers and get back to you.

**Comment by takiguc** [comment]
@smlambert 
We created new Korean data files against i18n.
Also we found regex testcase had same kind of issue.
So we created new Korean data files against regex.

**Comment by smlambert** [comment]
Thank you for your quick response @takiguc !  We will intend to merge #2534 once we unfreeze this repo after our release activities are complete.
