### ISSUE TITLE
getBinaryOpenjdk in get.sh need to be updated to avoid folder name collision

### ISSUE THREAD

**Issue by TianyuZuo** [AdoptOpenJDK/openjdk-tests#262]
in the get.sh file, the last three cmds in the function
```
getBinaryOpenjdk()
{
...
        jarDir=`ls -d */`
	dirName=${jarDir%?}
	mv $dirName j2sdk-image
}
```
will cause rename collision when the unzipped folder is also named as j2sdk-image. The error message would be:
`$ mv j2sdk-image/ j2sdk-image/
mv: rename j2sdk-image/ to j2sdk-image/j2sdk-image/: Invalid argument`

Since the `j2sdk-image` is a common name for some JDK's unzipped folder, My first thought is to change the target folder name ` j2sdk-image` to `testSDK` or other more meaningful names to avoid folder name collision. 

Did a search and found that `j2sdk-image` is used in JenkinsBase, windows and personal Jenkinsfiles, so changing `j2sdk-image` to other names also need to change these Jenkinsfiles.

**Comment by TianyuZuo** [comment]
Hi @sophia-guo  @Mesbah-Alam  Do you have any comments or suggestions?

**Comment by sophia-guo** [comment]
j2sdk-image is a common image name in openjdk. There is a decision about the sdk folder name in adoptopenjdk. Like jdk8u172-b03, which should not get collision. Could you first confirm which sdk you are using? Even if there is collision we can do like:

```
if dirName!='j2sdk-image'
  mv $dirName j2sdk-image
fi
```

**Comment by TianyuZuo** [comment]
The JDK is openj9-java8 compiled internally, which is different from the one compiled i adopt ci. I will add the check to the get.sh script.

**Comment by Mesbah-Alam** [comment]
@TianyuZuo - please update `get.sh` with the check.
