### ISSUE TITLE
runtime/RedefineTests/RedefineInterfaceCall.java got Error. Can't find library: /test/lib

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#267]
18:56:41 TEST: runtime/RedefineTests/RedefineInterfaceCall.java
18:56:41 TEST JDK: /home/jenkins/workspace/openjdk8_hs_openjdktest_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../..
18:56:41 
18:56:41 TEST RESULT: Error. Can't find library: /test/lib

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_linux/35/consoleFull

This is a new test, which is running at Feb 19. Checked https://github.com/AdoptOpenJDK/openjdk-jdk8u there is a merge 5 days ago. 

This is a jre test and need extra lib. Believe extra settings are needed. @akolarkunnu Any idea?

**Comment by sophia-guo** [comment]
I have run a personal build issue stays 
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/330/testReport/junit/runtime_RedefineTests_RedefineInterfaceCall/java/RedefineInterfaceCall/

Probably it is not in adopt jdk8u repo yet: https://github.com/AdoptOpenJDK/openjdk-jdk8u

Not sure how adopt jdk8u repo get sync with jdk8u hotspot.

**Comment by smlambert** [comment]
This is actually a good point to remind for openjdk_regression failures to follow this guidance for raising defects: 
https://github.com/AdoptOpenJDK/openjdk-tests/wiki/Guidance-for-Creating-Test-Defects

**Comment by akolarkunnu** [comment]
The changeset http://hg.openjdk.java.net/jdk8u/jdk8u-dev/hotspot/rev/de8045923ad2 is there in adopt repo also: https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/hotspot/test/runtime/RedefineTests/RedefineInterfaceCall.java.
@sophia-guo: Can you please confirm personal runs take test cases from repo https://github.com/AdoptOpenJDK/openjdk-jdk8u?

**Comment by sophia-guo** [comment]
Yes, the link in former comment is using adopt repo  https://github.com/AdoptOpenJDK/openjdk-jdk8u.

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/330/testReport/junit/runtime_RedefineTests_RedefineInterfaceCall/java/RedefineInterfaceCall/

**Comment by akolarkunnu** [comment]
I beleive something is wrong in the personal run, I downloaded latest code from https://github.com/AdoptOpenJDK/openjdk-jdk8u, latest build from https://ci.adoptopenjdk.net/job/openjdk8_build_x86-64_linux/lastSuccessfulBuild/artifact/OpenJDK8_x64_Linux_201805031700.tar.gz and tested locally and it executed successfully.

But in adopt personal run still it fails: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/356/#showFailuresLink

**Comment by sophia-guo** [comment]
@akolarkunnu When you run tests locally did you have extras settings? I suspect we need to extra settings?

**Comment by smlambert** [comment]
@akolarkunnu - can you give specifics on the steps you are following to 'run locally'.  
Also, if you are free tomorrow for a 10amEST hangout, lets speak directly, to get rid of any gap in understanding on this one.

**Comment by akolarkunnu** [comment]
Steps I followed:
1) Download or clone test base from https://github.com/AdoptOpenJDK/openjdk-jdk8u
2) Download latest JDK8 from https://ci.adoptopenjdk.net/job/openjdk8_build_x86-64_linux/
3) Download jtreg from https://ci.adoptopenjdk.net/view/Dependencies/job/jtreg/
4) Run the following jtreg command.
 ./jtreg-adopt/bin/jtreg -verbose:all -jdk:./jdk8u172-b03-adopt/ -dir:./adopt-jdk8u/hotspot/test runtime/RedefineTests/RedefineInterfaceCall.java

But with latest jtreg I see different issue, https://github.com/AdoptOpenJDK/openjdk-tests/issues/300.
I was testing with a bit old jtreg, jtreg-4.2-b11, it is working fine with that jtreg version.

**Comment by sophia-guo** [comment]
Thanks @akolarkunnu . And I believe this is the same steps testing com/sun/jdi/RedefineCrossEvent.java on MAC? In my local I did the exact same steps. Confused I got different result.

**Comment by akolarkunnu** [comment]
Yes, it is same.

**Comment by smlambert** [comment]
Closing as now listed in summary issue #345
