### ISSUE TITLE
Scala tests failing because fail to download instrumented.jar file

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#270]
From https://ci.adoptopenjdk.net/view/External%20tests/job/openjdk8_hs_externaltest_x86-64_linux/33/console

18:48:13         [0m[[33mwarn[0m] [0m==== local: tried[0m
18:48:13         [0m[[33mwarn[0m] [0m  /root/.ivy2/local/org.scala-lang.scala-sha-bootstrap.test.files.speclib/instrumented/1b11ac773055c1e942c6b5eb4aabdf02292a7194/jars/instrumented.jar[0m
18:48:13         [0m[[33mwarn[0m] [0m  https://repo.lightbend.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/1b11ac773055c1e942c6b5eb4aabdf02292a7194/test/files/speclib/instrumented.jar[0m
18:48:13         [0m[[33mwarn[0m] [0m	::::::::::::::::::::::::::::::::::::::::::::::[0m
18:48:13         [0m[[33mwarn[0m] [0m	::              FAILED DOWNLOADS            ::[0m
18:48:13         [0m[[33mwarn[0m] [0m	:: ^ see resolution messages for details  ^ ::[0m
18:48:13         [0m[[33mwarn[0m] [0m	::::::::::::::::::::::::::::::::::::::::::::::[0m

**Comment by sophia-guo** [comment]
We do have machine issue when running thirdparty container tests. This failure happened on test-packet-x64-ubuntu-16.04-1

comment in https://github.com/AdoptOpenJDK/openjdk-tests/pull/225

Docker Image fails on test-packet-x64-ubuntu-16.04-1, passed on test-scaleway-x64-ubuntu-16.04-1. Not sure the difference between those two machines. Remember recent system compiling failed on on one machine and passed on the other one. So are those machines set by playbooks from scratch? @gdams ?

Failure one:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox/54/consoleFull
Good one:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox/53/consoleFull

**Comment by smlambert** [comment]
I am closing this as it was a result of some machine config change which allowed 2 jenkins executors to run on the machine at the same time.  We should only allow 1.  The infra team has corrected this, and I have not seen further issues of this kind.

Have opened a different one #303 for the fact that we have docker on 4/6 xlinux machines (where it used to be on all 2/2 machines we had, so we just used the linux tag to find machines to run on.
