### ISSUE TITLE
 Test Build failed for "sh: 1: Cannot fork "

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#274]
Test build exit and failed unexpected with following message:

22:26:50 --------------------------------------------------
**22:27:05 sh: 1: Cannot fork**
**22:27:15 Cannot contact test-scaleway-ubuntu1604-x64-1: java.lang.InterruptedException**
22:27:25 [2018-02-23 21:27:10,836] Agent[2]: stderr: OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f1ec3a00000, 262144, 0) failed; error='Cannot allocate memory' (errno=12)
22:27:25 [2018-02-23 21:27:10,836] Agent[2]: stdout: #
22:27:25 [2018-02-23 21:27:24,946] Agent[2]: stdout: # There is insufficient memory for the Java Runtime Environment to continue.
22:27:25 [2018-02-23 21:27:24,947] Agent[2]: stdout: # Native memory allocation (mmap) failed to map 262144 bytes for committing reserved memory.
22:27:25 [2018-02-23 21:27:24,947] Agent[2]: stdout: # An error report file with more information is saved as:
22:27:25 [2018-02-23 21:27:24,947] Agent[2]: stdout: # /home/jenkins/workspace/openjdk8_hs_openjdktest_x86-64_linux/jvmtest/openjdk_regression/work/scratch/0/hs_err_pid18473.log
22:27:25 [2018-02-23 21:27:25,188] Agent[2]: stdout: [thread 139770111723264 also had an error]
22:27:25 [2018-02-23 21:27:25,188] Agent[2]: stdout: #
22:27:25 [2018-02-23 21:27:25,188] Agent[2]: stdout: # Compiler replay data is saved as:
22:27:25 [2018-02-23 21:27:25,189] Agent[2]: stdout: # /home/jenkins/workspace[Pipeline] End of 

Pipeline
ERROR: script returned exit code -1
Finished: FAILURE

This happened twice:
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_linux/36/consoleFull

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_j9_openjdktest_x86-64_linux/24/consoleFull

By now both happened on test-scaleway-ubuntu1604-x64-1.

Suspect jenkins setup or master-slave network issue?

**Comment by smlambert** [comment]
@sophia-guo - if you suspect this is a machine issue, please raise a related issue at openjdk-infrastructure

**Comment by sophia-guo** [comment]
Yes, I created a issue at infrasturcutre https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/235

**Comment by sophia-guo** [comment]
Didn't see the issue again ever since Feb 27. Close it. Details refer to  AdoptOpenJDK/openjdk-infrastructure#235.
