### ISSUE TITLE
openjdk10_hs_openjdktest_x86-64_linux got "Error: Group spec does not specify a valid test suite:"

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#284]
Build openjdk10_hs_openjdktest_x86-64_linux didn't run any tests due to error"Error: Group spec does not specify a valid test suite: "

Looking at code structure openjdk10 has changed code structure,  which separate source code and test code from each component. All test code has been moved to test folder. Where can we find those changes document or how can we be notified when those changes happens?

**Comment by smlambert** [comment]
Is this related to what Muneer had mentioned through the Slack channel?  Also implying that a new commandline option is required for test groups that contain native tests?  

https://github.com/AdoptOpenJDK/openjdk-tests/issues/228#issuecomment-367892659

I presume both the restructuring of openjdk tests and the new requirement to point to where native test images live indicate that the openjdk repo underwent some reorganization.  

We would likely have to monitor the activities on that repo, or depend on Muneer and others who are monitoring, if we were to know of this in advance.
