### ISSUE TITLE
All openj9 test build fails : Error: failed to get JDK properties for /home/jenkins/workspace/openjdk8_j9_openjdktest_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -ea -esa -Xmx512m -Xnocompressedrefs; exit code 255

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#292]
All openj9 test build fails : Error: failed to get JDK properties for /home/jenkins/workspace/openjdk8_j9_openjdktest_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -ea -esa -Xmx512m -Xnocompressedrefs; exit code 255

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_j9_openjdktest_x86-64_linux/35/console

**Comment by sophia-guo** [comment]
Recent testkitgen changes for j9. If it's non compressed sdk -Xnocompressedrefs is added as default jvm options. If it's compressed sdk -Xcompressedrefs is added as default jvm options. 

In adoptopenjdk comrpessedrefs is default. There is no nocompressedrefs or compressedrefs sdk.

**Comment by smlambert** [comment]
is this not covered by env variable SPEC, and are we using the correct one at Adopt?

**Comment by sophia-guo** [comment]
Refer to #294
