### ISSUE TITLE
Test build unexpected exit for test failure

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#301]
Latest openjdk9 test build failed for unexpected exit when there is test failure

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_hs_openjdktest_x86-64_linux/

**Comment by akolarkunnu** [comment]
java.io.IOException: No space left on device
14:58:35 	at java.base/sun.nio.ch.FileDispatcherImpl.allocate0(Native Method)
14:58:35 	at java.base/sun.nio.ch.FileDispatcherImpl.allocate(FileDispatcherImpl.java:80)
14:58:35 	at java.base/sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:918)
14:58:35 	at Size.testLargeFile(Size.java:73)
14:58:35 	at Size.main(Size.java:45)
14:58:35 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:58:35 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:58:35 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:58:35 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
14:58:35 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
14:58:35 	at java.base/java.lang.Thread.run(Thread.java:844)
14:58:35 
14:58:35 JavaTest Message: Test threw exception: java.io.IOException: No space left on device
14:58:35 JavaTest Message: shutting down test

**Comment by sophia-guo** [comment]
Happened to MAC test-macincloud-macos1010-2
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_macos/42/consoleFull
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk10_hs_openjdktest_x86-64_macos/4/consoleFull

**Comment by sophia-guo** [comment]
Some of them don't have message "No space left on device"

All have message "Error: Some tests failed or other problems occurred"
We do have build on same day with test failures, which do not exit unexpected.

**Comment by sophia-guo** [comment]
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_macos/44/consoleFull

Seems it only happened on MAC. And only happened when jdk_nio sub group got failure either as "Error: Some tests failed or other problems occurred." or as "Unexpected exit from test [exit code: 143]"

**Comment by sophia-guo** [comment]
The failure started two weeks ago, seems related with PR :Update the count mechanism for testKitGen @renfeiw

**Comment by renfeiw** [comment]
I have a PR: https://github.com/eclipse/openj9/pull/1443 to replace the error prone echo -e. Hope the PR will resolve this issue.

**Comment by smlambert** [comment]
We should have now picked up fix openj9/#1443, so should confirm if this problem is resolved, and if issue can be closed.

**Comment by sophia-guo** [comment]
I can confirm that builds from Mar 16 do not have  line " -e " with the openj9/#1443. However this is a intermittent failure with unexpected exit will run a few other personal build and see if it goes way.

**Comment by smlambert** [comment]
I've not seen this issue recur, will close now.
