### ISSUE TITLE
Need to use sw.tool.docker label for external tests

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#303]
We have docker on 4/6 xlinux machines (the ubuntu playbook),  where it used to be on all 2/2 machines we had, so we used to just use the linux tag to find machines to run on.

More correctly we should use the docker label and create a jenkins data file for the docker based testing.

**Comment by Mesbah-Alam** [comment]
The issue is resolved in the following PR: https://github.com/AdoptOpenJDK/openjdk-tests/pull/304
