### ISSUE TITLE
Test build on test-softlayer-rhel74-x64-1 got different ant issue

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#307]
Test build running on test-softlayer-rhel74-x64-1 got "Problem: failed to create task or type if"

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_j9_openjdktest_x86-64_linux/41/console

Suspect "ant-contrib" is not installed or installed with problem.

https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/269

**Comment by sophia-guo** [comment]
Fixed:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox/172/console

**Comment by sophia-guo** [comment]
A different ant issue on same machine:
15:51:32 Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
15:51:32 Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.launch.Launcher
15:51:32 make: *** [compile] Error 1

https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_x86-64_linux/26/console

https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_x86-64_linux/26/console

Updated in infra repo issues.

**Comment by sophia-guo** [comment]
again: 
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk10_sap_openjdktest_x86-64_linux/12/console

**Comment by smlambert** [comment]
Did this get resolved, last I saw in the infra issue, they were asking for a basic test...

**Comment by sophia-guo** [comment]
No, this can be reproduced with personal build. I will respond to that comment.

**Comment by smlambert** [comment]
Closing as now listed in summary issue #346
