### ISSUE TITLE
Confirm test plan executed against openjdk8-openj9 release 0.8 candidate build

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#309]
Artifacts for the candidate build for:

x64_linux: 
https://github.com/AdoptOpenJDK/openjdk8-openj9-nightly/releases/download/jdk8u162-b12-20180103/OpenJDK8-OPENJ9_x64_Linux_20180103.tar.gz

Tests to be run against x64_linux candidate/platform:

- [x] openjdk_regression (subset)

- [x] system

- [x] jck (8b) automated

- [x] jck (8b) manual/interactive
--------------------
ppc64le_linux:
https://github.com/AdoptOpenJDK/openjdk8-openj9-nightly/releases/download/jdk8u162-b12-20180803/OpenJDK8-OPENJ9_ppc64le_Linux_20180803.tar.gz

Tests to be run against ppc64le_linux candidate/platform:

- [x] openjdk_regression (subset)

- [x] system

- [x] jck (8b) automated

- [x] jck (8b) manual/interactive
--------------------
s390x_linux:
https://github.com/AdoptOpenJDK/openjdk8-openj9-nightly/releases/download/jdk8u162-b12-20180803/OpenJDK8-OPENJ9_s390x_Linux_20180803.tar.gz

Tests to be run against s390x_linux candidate/platform:

- [x] openjdk_regression (subset) 

- [x] system 

- [x] jck (8b) automated

- [x] jck (8b) manual/interactive

**Comment by sxa555** [comment]
Initial x64 JCK run is covered in the private repository but has been completed successfully against https://github.com/AdoptOpenJDK/openjdk8-openj9-nightly/releases/download/jdk8u162-b12-20180103/OpenJDK8-OPENJ9_x64_Linux_20180103.tar.gz but is being re-run after the fix to https://github.com/AdoptOpenJDK/openjdk-build/issues/244 (which was purely a cosmetic change)

**Comment by smlambert** [comment]
[openjdk8-j9_ppc64le_openjdktest_release0.8results.zip](https://github.com/AdoptOpenJDK/openjdk-tests/files/1795527/openjdk8-j9_ppc64le_openjdktest_release0.8results.zip)

[openjdk8-j9_x64linux_openjdktest_release0.8results.zip](https://github.com/AdoptOpenJDK/openjdk-tests/files/1795528/openjdk8-j9_x64linux_openjdktest_release0.8results.zip)

[openjdk8-j9_ppc64le_systemtest_release0.8_results.tap.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/1795531/openjdk8-j9_ppc64le_systemtest_release0.8_results.tap.txt)

[openjdk8-j9_x64_linux_systemtest_release0.8_results.tap.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/1797326/openjdk8-j9_x64_linux_systemtest_release0.8_results.tap.txt)

**Comment by sxa555** [comment]
JCK execution details are in https://github.com/AdoptOpenJDK/JCK8/issues/36 (automated) and https://github.com/AdoptOpenJDK/JCK8/issues/38 (interactive/manual) - restricted to those with access to those repositories.

**Comment by smlambert** [comment]
Closing this one, as all categories of tests have been run/checked off.
