### ISSUE TITLE
Wipe out or cleanup workspace at the end of jenkins jobs 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#314]
Currently we are doing the wiping out workspace at the beginning of each build. That is saying all build material (including all test results) of each build stays in disk, which is helpful for debugging if build fails.

However we are getting hit more with out of space errors than times we needed workspace to be present. Suggestion is cleaning up the workspace at the end of jenkins jobs.

**Comment by smlambert** [comment]
Agreed, especially now that we have added all the new test jobs (and a few more to come).
