### ISSUE TITLE
Enable openjdk_regression tests with openjdk8 with hotspot  on s390x got jvm crashed

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#319]
Using nightly build get failures:
20:29:49 #
20:29:49 # A fatal error has been detected by the Java Runtime Environment:
20:29:49 #
20:29:49 #  Internal Error (os_linux_zero.cpp:254), pid=51868, tid=0x000003ff874ff910
20:29:49 #  fatal error: caught unhandled signal 11
20:29:49 #
20:29:49 # JRE version:  (8.0) (build )
20:29:49 # Java VM: OpenJDK 64-Bit Zero VM (25.71-b00 interpreted mode linux-s390x )
20:29:49 # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
20:29:49 #
20:29:49 # An error report file with more information is saved as:
20:29:49 # /data/jenkins/workspace/openjdk8_hs_openjdktest_s390x_linux/openjdk-tests/TestConfig/hs_err_pid51868.log
20:29:49 #
20:29:49 # If you would like to submit a bug report, please visit:
20:29:49 #   http://bugreport.java.com/bugreport/crash.jsp
20:29:49 #
20:29:49 makefile:82: recipe for target 'compile' failed
20:29:49 make: *** [compile] Aborted (core dumped)

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_hs_openjdktest_s390x_linux/1/console

Using release version got:
21:54:41 ant -f scripts/build_test.xml -DTEST_ROOT=/data/jenkins/workspace/openjdk8_hs_openjdktest_s390x_linux/openjdk-tests/TestConfig/.. -DBUILD_ROOT=/data/jenkins/workspace/openjdk8_hs_openjdktest_s390x_linux/openjdk-tests/TestConfig/../../jvmtest -DJAVA_BIN=/data/jenkins/workspace/openjdk8_hs_openjdktest_s390x_linux/openjdkbinary/j2sdk-image/jre/bin -DJAVA_VERSION=SE80 -DJCL_VERSION=current -DBUILD_LIST=openjdk_regression -DRESOURCES_DIR=/data/jenkins/workspace/openjdk8_hs_openjdktest_s390x_linux/openjdk-tests/TestConfig/../../jvmtest/TestConfig/resources -DJCK_ROOT= -DJVM_VERSION=openjdk8
21:54:41 Error: dl failure on line 893
21:54:41 Error: failed /data/jenkins/workspace/openjdk8_hs_openjdktest_s390x_linux/openjdkbinary/j2sdk-image/jre/lib/s390x/server/libjvm.so, because libffi.so.4: cannot open shared object file: No such file or directory
21:54:41 makefile:82: recipe for target 'compile' failed
21:54:41 make: *** [compile] Error 6
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_hs_openjdktest_s390x_linux/2/console

Running java version locally got same behavior:
jenkins@build-marist-ubuntu1604-s390x-1:~/test/jdk8u172-b03/jre/bin$ ./java -version
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (os_linux_zero.cpp:254), pid=64869, tid=0x000003ffb2bff910
#  fatal error: caught unhandled signal 11
#
# JRE version:  (8.0) (build )
# Java VM: OpenJDK 64-Bit Zero VM (25.71-b00 interpreted mode linux-s390x )
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /data/home/jenkins/test/jdk8u172-b03/jre/bin/hs_err_pid64869.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

**Comment by sophia-guo** [comment]
Open build issue:
https://github.com/AdoptOpenJDK/openjdk-build/issues/257

**Comment by sophia-guo** [comment]
SDK build itself failed
https://ci.adoptopenjdk.net/job/openjdk8_build_s390x_linux/159/console

Wondered if build fails why it can still be accessed by https://github.com/AdoptOpenJDK/openjdk-api

**Comment by smlambert** [comment]
Closing as now listed in summary issue #346
