### ISSUE TITLE
jdk9 with hotspot: jdk_net test -- java/net/InetAddress/IPv4Formats.java failed

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#325]
Test category: openjdk
Testsuite name: jdk_net
Test name(s): java/net/InetAddress/IPv4Formats.java
Product(s) tested: jdk-9+181
OS/architecture: Ubuntu16.04 x64
Platform specific: yes

Reproducibility: always
Reproducible on machine: test-softlayer-ubuntu1604-x64-1
Regression: yes, introduced in JDK 9 181

Exception/Error from Log:
some output from log file
Error log file (if available): https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_hs_openjdktest_x86-64_linux/11/artifact/jvmtest/openjdk_regression/work/java/net/InetAddress/IPv4Formats.jtr/*view*/

Steps to reproduce:

- Re-include test. (Search the Test class name in ProblemList_openjdk9.txt find the exclude line and comment the line
    java/net/InetAddress/IPv4Formats.java 325 linux-x86_64

- make jdk_net_0 (assuming you are running with the test material already setup, if not follow openjdk-tests/README.md instructions to set up test material first, then run the make target).

**Comment by smlambert** [comment]
[IPv4Formats.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/1812932/IPv4Formats.jtr.txt)

**Comment by smlambert** [comment]
There was an older issue: https://bugs.openjdk.java.net/browse/JDK-8058932 that was corrected with this fix: http://hg.openjdk.java.net/jdk9/jdk9/jdk/rev/76cf3d7e0a8a 

Suspect that "java.lang.RuntimeException: invalidhost.invalid should throw UnknownHostException!" is similar problem (should check if pingable from test machine).

**Comment by smlambert** [comment]
I am closing all jdk9 issues, we have 2 or more other issues to capture java/nio issues in jdk8 and jdk11
