### ISSUE TITLE
Rewrite all ansible playbooks - standardize/Nagios/slack notifications

### ISSUE THREAD

**Issue by bblondin** [AdoptOpenJDK/openjdk-tests#33]
- Cleanup and standardize playbooks 
- Alphabetize package list
- Include Nagios plugin deployment
- Add slack notifications for ansible (pass/fail)

**Comment by karianna** [comment]
@bblondin I'm wondering about the split we have between openjdk-build and openjdk-test for some of this stuff and whether there should be a common base for any of it....

**Comment by tellison** [comment]
I agree with @karianna , there will be common set-up for all machines we manage.  We can probably describe the various machine 'roles' that Ansible can manage for us, then call a set of these scripts for a specific machine. 

Roles may include:
- machine managed by the project (requires admin account, ntp, etc)
- configured for test 
- configured for build
- configured as a Jenkins | semaphore | whatever node

Since we use the Ansible scripts to configure Docker images, and want people to be able to use them locally, we won't want to couple the roles like test & project config (for example).

**Comment by bblondin** [comment]
Playbooks for ubuntu_14_16_x86.yml and rhel_7_x86.yml are now ready

**Comment by bblondin** [comment]
@karianna @tellison 
I like the idea of a command base.
Is there anything different about a build machine vs a test machine?
Comparing the playbooks from build to test I don't see anything that is different.

**Comment by gdams** [comment]
I think there are a few extra dependencies for the test machines but there is no harm in just installing them on the build machines too

**Comment by smlambert** [comment]
The only playbook that got updated for test is the ubuntu_14_16_x86.yml file 

    - name: Install Test tools
      apt: name={{item}} state=installed
      with_items:    
        - ant
        - ant-contrib
        - git
        - jq
        - perl
        - wget

The remaining playbooks in the openjdk-tests repo have only been copied over from openjdk-build, but not updated (saw that @bblondin was working on ansible files), so left the rest alone.

**Comment by bblondin** [comment]
@smlambert and rhel_7_x86.yml https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/Build/ansible/playbooks/rhel_7_x86.yml

Sophia items were already addressed.
We don't have a Windows ansible playbook at this time, but we will.

**Comment by bblondin** [comment]
Windows playbook is ready: https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/Build/ansible/playbooks/Windows.yml

**Comment by gdams** [comment]
@bblondin nice work with the windows playbook. The only thing I would say is that we should ideally have java 7 installed instead of java 8

**Comment by bblondin** [comment]
Updates windows playbook
- Added Java 6 and 7
- Set Java 7 as default JAVA_HOME

**Comment by bblondin** [comment]
Closing... addition work on playbooks will be addressed in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/6

**Comment by gdams** [comment]
so we should move all playbooks to https://github.com/AdoptOpenJDK/openjdk-infrastructure I think

**Comment by bblondin** [comment]
I agree

**Comment by bblondin** [comment]
Also... 
- Java needs to be updated in all playbooks to version 8
- configure time servers

**Comment by bblondin** [comment]
playbooks 
- Java has been updated to 8
- ntp time server added
- playbooks moved into https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible/playbooks

Closing... addition work on playbooks will be addressed in
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/6
