### ISSUE TITLE
Add 'java -version' test to the build pipelines

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#333]
Create a quick test that just runs 'java -version'.

The build pipelines will follow this pattern:

build   test   deploy 
         ^
     insert quick 'java -version' test here

This will avoid launching a whole bunch of testing if the build really isn't sane.

**Comment by sophia-guo** [comment]
Quick search of openjdk-build/sbin/build.sh there is 'java -version' check:
```
printJavaVersionString()
{
  # shellcheck disable=SC2086
  PRODUCT_HOME=$(ls -d $OPENJDK_DIR/build/*/images/${JDK_PATH})
  if [[ -d "$PRODUCT_HOME" ]]; then
     echo "${good}'$PRODUCT_HOME' found${normal}"
     # shellcheck disable=SC2154
     echo "${info}"
     "$PRODUCT_HOME"/bin/java -version || (echo "${error} Error executing 'java' does not exist in '$PRODUCT_HOME'.${normal}" && exit -1)
     echo "${normal}"
     echo ""
  else
     echo "${error}'$PRODUCT_HOME' does not exist, build might have not been successful or not produced the expected JDK image at this location.${normal}"
     exit -1
  fi
}

```

Looking at build: the https://ci.adoptopenjdk.net/job/openjdk8_build_s390x_linux/160/console
111
'/data/jenkins/workspace/openjdk8_build_s390x_linux/openjdk/build/linux-s390x-normal-zero-release/images/j2sdk-image' found

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (os_linux_zero.cpp:254), pid=12395, tid=0x000003ffbaa7f910
#  fatal error: caught unhandled signal 11
#
# JRE version:  (8.0) (build )
# Java VM: OpenJDK 64-Bit Zero VM (25.71-b00 interpreted mode linux-s390x )
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /data/jenkins/workspace/openjdk8_build_s390x_linux/openjdk/hs_err_pid12395.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
/data/jenkins/workspace/openjdk8_build_s390x_linux/sbin/build.sh: line 291: 12395 Aborted                 (core dumped) "$PRODUCT_HOME"/bin/java -version
 Error executing 'java' does not exist in '/data/jenkins/workspace/openjdk8_build_s390x_linux/openjdk/build/linux-s390x-normal-zero-release/images/j2sdk-image'.


Removing unnecessary files now...
```

So the problem is when there is error build.sh exit -1, which doesn't consumed by jenkins build to tag build as failure.

**Comment by sophia-guo** [comment]
Probably should do ' exit 1'  instead of 'exit -1' in  printJavaVersionString() of openjdk-build/sbin/build.sh.

**Comment by smlambert** [comment]
@sophia-guo - please open an openjdk-build issue to change the exit code in printJavaVersionString() of the build script as with that in place, the build job should have failed and caught this issue before it triggered testing (reference this one for details, which we can close).

**Comment by sophia-guo** [comment]
Yes, will do. There probably is another problem hidden. Will update.

**Comment by sophia-guo** [comment]
Opened an issue https://github.com/AdoptOpenJDK/openjdk-build/issues/264, different behavior on different bash version.
