### ISSUE TITLE
jdk9 with hotspot: jdk_nio test --java/nio/file/attribute/BasicFileAttributeView/UnixSocketFile.java failed

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#334]
Test category: openjdk
Testsuite name: jdk_nio
Test name(s): java/nio/file/attribute/BasicFileAttributeView/UnixSocketFile.java
Product(s) tested: jdk-9+181
OS/architecture: Ubuntu16.04 x64
Platform specific: yes

Reproducibility: always
Reproducible on machine: test-softlayer-ubuntu1604-x64-1
Regression: yes, introduced in JDK 9 181

Exception/Error from Log:
some output from log file
Error log file (if available): https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_hs_openjdktest_x86-64_linux/11/artifact/jvmtest/openjdk_regression/work/java/nio/file/attribute/BasicFileAttributeView/UnixSocketFile.jtr/*view*/

Steps to reproduce:
1) Re-include test.  (Search the Test class name in ProblemList_openjdk9.txt find the exclude line and comment the line
java/nio/file/attribute/BasicFileAttributeView/UnixSocketFile.java  334 linux-x86_64
2) make jdk_nio  (assuming you are running with the test material already setup, if not follow openjdk-tests/README.md instructions to set up test material first, then run the make target).

[UnixSocketFile.jtr.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/1820391/UnixSocketFile.jtr.txt)

**Comment by smlambert** [comment]
Link to jtr file indicates that the test passed:
JavaTest Message:  Test complete.
result: Passed. Execution successful
test result: Passed. Execution successful

Attached jtr file indicates:
Error. Agent error: java.lang.Exception: Agent 0 timed out

**Comment by smlambert** [comment]
I am closing all jdk9 issues, we have 2 or more other issues to capture java/nio issues in jdk8 and jdk11
