### ISSUE TITLE
udpate JCK build.xml to download jck test materials from GitHub repos.

### ISSUE THREAD

**Issue by TianyuZuo** [AdoptOpenJDK/openjdk-tests#335]
To run JCK test, JCK materials need to be staged manually to current system and set variable to point to the jck materials location. This process is not convenient for automation testing process or user local testing process.

The way to update it is to add another process in the jck build.xml to clone and stage jck test materials automatically. This process will be triggered by the conditions of environment variables `env.JCK_ROOT`, `env.JCK_VERSION` and `env.JCK_GIT_REPO`.

The logic would be 

if  env.JCK_ROOT.isNotEmpty        // assume user staged JCK materials manually
    Build STF
else
    if env.JCK_GIT_REPO.isNotEmpty
       Git clone JCK materials
       Unzip JCK materials to env.JCK_VERSION folder
       Build STF
    else
        Fail the build process

Pros:
1. This new build process will not crash current running JCK tests, which gives time to update the JCK test automation process on Jenkins. 
2. This process also give user flexibility to use manually staged JCK materials or use automated staged JCK materials.

Cons:
1. For single user who wants to run jck test locally, the local machine need to have access to the JCK GitHub repo. This may become a block to run TKG+STF JCK test in Docker images (which need to set ssh every time).
2. Every Jenkins machine which runs JCK tests needs to have access to JCK GitHub repo.

**Comment by TianyuZuo** [comment]
fyi @smlambert  and @llxia

**Comment by smlambert** [comment]
Your cons list isn't very generous.  In both cons listed, this approach still supports the manual pre-setting up of JCK materials.  If the node/machine does not have access to a repo containing JCK materials, the person setting up the node needs to manually pre-install them.  I do not believe we need to worry about those edge cases (as for our purpose, only people with access to JCK material run JCKs).

**Comment by TianyuZuo** [comment]
Private jck repos seems only accept connection from access token or ssh
```
root$  git clone https://github.private.com/jck.git
Cloning into 'jck'...
Username for 'https://github.private.com/': xxxxxx
Password for 'https://github.private.com/': xxxxxxx
remote: Password authentication is not available for Git operations.
remote: You must use a personal access token or SSH key.
remote: See https://github.ibm.com/settings/tokens or https://github.ibm.com/settings/ssh
fatal: unable to access 'https://github.ibm.com/tianyu/containertests.git/': The requested URL returned error: 403
root$ 
```

I will leave the build.xml to clone from jck repos directly, assuming the jck test machines have ssh or token access to private jck repos.
