### ISSUE TITLE
Test java/util/concurrent/LinkedTransferQueue/WhiteBox.java in OpenJDK9 cannot be excluded using exclude file option

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#349]
Test java/util/concurrent/LinkedTransferQueue/WhiteBox.java in OpenJDK9 cannot be excluded using exclude file option both in our build story or locally.

Test java/util/concurrent/LinkedTransferQueue/WhiteBox.java has been excluded in ProblemList_openjdk9-openj9.txt, however it is not excluded in all openjdk9_j9_openjdktest_{arch}_{OS} test jobs.

To reproduce locally using openjdk9 exclude story:

1.  Download or clone test base from https://github.com/AdoptOpenJDK/openjdk-jdk9
2. Download latest JDK9 from https://ci.adoptopenjdk.net/job/openjdk9_build_x86-64_linux/
3. Download jtreg from https://ci.adoptopenjdk.net/job/jtreg/lastSuccessfulBuild/artifact/jtreg-4.2.0-tip.tar.gz
4. Add java/util/concurrent/LinkedTransferQueue/WhiteBox.java		https://github.com/eclipse/openj9/issues/1434	generic-all in openjdk9-jdk9/jdk/tet/ProblemList.txt

Run the following jtreg command.
./jtreg/jtreg/bin/jtreg -verbose:all -jdk:**/openjdk9binary/j2sdk-image/ -exclude:"***/openjdk9/openjdk-jdk9/jdk/test/ProblemList.txt" /Users/sophiag/adoptjdktest/openjdk9/openjdk-jdk9/jdk/test/java/util/concurrent
./jtreg/jtreg/bin/jtreg -verbose:all -jdk:**/openjdk9binary/j2sdk-image/ -exclude:"***/openjdk9/openjdk-jdk9/jdk/test/ProblemList.txt" /Users/sophiag/adoptjdktest/openjdk9/openjdk-jdk9/jdk/test:jdk_util
Test will not be excluded.

Note: 
1. Running specified the testcase, it will be excluded:
./jtreg/jtreg/bin/jtreg -verbose:all -jdk:**/openjdk9binary/j2sdk-image/ -exclude:"***/openjdk9/openjdk-jdk9/jdk/test/ProblemList.txt" /Users/sophiag/adoptjdktest/openjdk9/openjdk-jdk9/jdk/test/java/util/concurrent/LinkedTransferQueue/WhiteBox.java

2. If exclude another concurrent whitebox.java at the same time:
java/util/concurrent/ArrayBlockingQueue/WhiteBox.java	https://github.com/eclipse/openj9/issues/1434	generic-all
java/util/concurrent/LinkedTransferQueue/WhiteBox.java		https://github.com/eclipse/openj9/issues/1434	generic-all

Both test will be excluded, which looks like those tests case are not written dependently? Probably there are some other similar cases?

**Comment by smlambert** [comment]
Based on some queries from @ben-walsh (thanks Ben!), we now know that the inability to properly exclude certain tests stems to this [openjdk/jreg defect](https://bugs.openjdk.java.net/browse/CODETOOLS-7902067).  

Response on queries: "The bug is that the content of the test description (the /* @test */) comment is identical for this test and some other tests. If you need a short term workaround, add some unique text, such as a @summary or @bug info into the test you are trying to exclude."

2 options: 
1) wait for a fix, which was told is coming soon, but with no actual date
2) temporary workaround, add a step just after copying test material to edit the comment section of the tests in question prior to running the test

**Comment by smlambert** [comment]
Sure, we can do that (option 3!), though are some of those tests actually passing?  If so, we should make a comment in the issue under which we exclude them.

**Comment by sophia-guo** [comment]
Yes, those three are passing tests. Agree we need to put a comment in the exclude issue and also refer to https://bugs.openjdk.java.net/browse/CODETOOLS-7902067

**Comment by sophia-guo** [comment]
Looks like the fix is in  https://urldefense.proofpoint.com/v2/url?u=http-3A__hg.openjdk.java.net_code-2Dtools_jtreg_rev_7265713552da&d=DwIBAg&c=jf_iaSHvJObTbx-siA1ZOg&r=0yESvVeO2xHyvCbHqew0S5OPRA6T6qWI6hcf_aOJlVw&m=pzcRLa2mVoYRl85DhAzGAgGYqRPNxiia06RZXF5zBKs&s=9xNpBUgC3xHjpXFe1wZydRPsjfqehkzL3L3Coz1iygc&e=

When the changes is in https://ci.adoptopenjdk.net/job/jtreg/ the problem should be fixed.

**Comment by smlambert** [comment]
Can we check if this has been resolved, so we can reinclude tests and close the issue?

**Comment by sophia-guo** [comment]
A couple of grinders https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/554/  - https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/559/ show this has been fixed. Tests with same name under different package | path could be excluded. Close this issue. 

Leave excluded test as is. There is specific issue opened for its unexpected behavior. 


Reinclude tests depend on the test
