### ISSUE TITLE
Add openjdk-tests build in openjdk build pipeline story

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#354]
Add openjdk-tests build in openjdk build pipeline story)https://github.com/AdoptOpenJDK/openjdk-build/tree/master/pipelines)
1)  add a testing stage  (still as non-blocking a.k.a. propagate : false)
2)  then we will introduce variables to avoid as much duplication (do as separate PR since that is a bigger change)
3) I will update the actual Pipeline builds in Jenkins to refer to the ones in github (will do this one platform at a time, during less trafficked times to avoid catastrophic disruption in the event unforeseen problems)
4) when happy that all is working as expected, we can start switching testing to blocking/gating deploy stage

**Comment by smlambert** [comment]
This was fixed by [openjdk-build/279](https://github.com/AdoptOpenJDK/openjdk-build/pull/279)
