### ISSUE TITLE
Test personal build requires duplicate information

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#356]
[Test personal build](https://ci.adoptopenjdk.net/view/all/job/test_personal/) requires user to provide duplicate information. For example, 
- SPEC, PLATFORM and MACHINE_LABEL
- JAVA_IMPL and JVM_VERSION

We should ask user for common information that is needed by TestKitGen (i.e., SPEC and JAVA_IMPL). If other variable is needed, our Jenkins script should have the ability to map it. We need to clean up the script and ask user for the minimal information.

![image](https://user-images.githubusercontent.com/19273206/37980657-9b118076-31b9-11e8-868a-6b20a067e4f3.png)

**Comment by smlambert** [comment]
I started addressing this here: https://github.com/smlambert/openjdk-tests/blob/grinder/buildenv/jenkins/Jenkinsfile_personal, as I am also trying to introduce a "grinder" feature, but haven't gotten a final working version yet.  

If someone else is picking up and running with this, that will be great...

**Comment by Mesbah-Alam** [comment]
I can pick it up if noone else has already done so!

**Comment by sophia-guo** [comment]
Mesbah, I've had a PR for this https://github.com/AdoptOpenJDK/openjdk-tests/pull/358

**Comment by Mesbah-Alam** [comment]
@sophia-guo - Sure, if you have already done some part of the work, I should let you continue. I will not duplicate the work. But please do let me know if you need any help in finishing the work.

**Comment by llxia** [comment]
Close this issue as #358 is merged.
