### ISSUE TITLE
TAP plugin fails with parse error when tests fail

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#36]
some tests fail will cause  TAP plugin fails with parse error 
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/13/
01:24:31         Error: Some tests failed or other problems occurred.
01:24:31 ]: special characters are not allowed
01:24:31 	at org.tap4j.parser.Tap13Parser.parseDiagnostics(Tap13Parser.java:435)
01:24:31 	at org.tap4j.parser.Tap13Parser.parseLine(Tap13Parser.java:262)
01:24:31 	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:224)
01:24:31 	... 15 more
01:24:31 Caused by: unacceptable character '' (0x7) special characters are not allowed
01:24:31 in "'string'", position 447721
01:24:31 	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67)
01:24:31 	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47)
01:24:31 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
01:24:31 	at org.tap4j.parser.Tap13Parser.parseDiagnostics(Tap13Parser.java:430)
01:24:31 	... 17 more
01:24:31 TAP parse errors found in the build. Marking build as UNSTABLE
01:24:31 TAP Reports Processing: FINISH

**Comment by smlambert** [comment]
You may want to temporarily comment out that part of the deploy stage until this can be fixed (I suspect some jtreg output is not to tap4j's liking).

**Comment by sophia-guo** [comment]
Will try my fix first. If not works I will comment out the deploy stage, however, that means no taps tests result :_(. Or we could temporarily comment out the failure output( still have the tap results, change back to no failure output details )?

**Comment by smlambert** [comment]
As we have moved towards using other plugins to represent the test output, I think we can close this issue altogether.
