### ISSUE TITLE
Functional tests need playlists before compile stage

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#365]
Functional tests are in openj9 repo. We set up all material in compile stage(build.xml)
https://github.com/AdoptOpenJDK/openjdk-tests/pull/364

If we expect to run functional tests from adopt we need all tests playlists staged when generate make files. That is before compile stage.

**Comment by sophia-guo** [comment]
Or functional tests need one more extra make configure step.

**Comment by llxia** [comment]
Close this as it is addressed in #394
