### ISSUE TITLE
use CopyArtifact instep of wget to stage test binaries in parallel test execution

### ISSUE THREAD

**Issue by TianyuZuo** [AdoptOpenJDK/openjdk-tests#370]
current JenkinsfileBase is using 
```
	sh "wget -q --no-check-certificate --header 'Cookie: allow-download=1' ${env.BUILD_URL}artifact/test-binaries.tar.gz " 
	sh "tar -xzf test-binaries.tar.gz"
```
to get compiled test binaries, we may want to use Jenkins plugin `CopyArtifact` to get the artifacts.

Open this issue to track the progress.

**Comment by smlambert** [comment]
Think this issue no longer applicable, parallel test setup has been changed.
