### ISSUE TITLE
Get latest sdk per platfom doesn't work any more

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#380]
With updated sdk deployment story( deploy per platform) openjdk-api query about latest sdk per platform will fail.

https://api.adoptopenjdk.net/$JVMVERSION/$SDK_RESOURCE/$PLATFORM/latest/binary

The reason is some platform may not have latest binary.
For example: 
openjdk8 only have 4 platform available for latest ( April 9 for now: linux, ppcle, aix, windows)
https://api.adoptopenjdk.net/openjdk8/nightly

In that case if we want get latest mac sdk, which latest version is Mar 8, wget will fail as there is no sdk available. 
wget https://api.adoptopenjdk.net/openjdk8/nightly/x64_mac/latest/binary

**Comment by sophia-guo** [comment]
Refer to https://github.com/AdoptOpenJDK/openjdk-api/issues/52

**Comment by smlambert** [comment]
This has now been fixed by a set of PRs in the website/website-backend/build repos.
