### ISSUE TITLE
 No rule to make target `jckjni.c', needed by `libjckjni.so'

### ISSUE THREAD

**Issue by wefine** [AdoptOpenJDK/openjdk-tests#386]
Dear all, PLEASE HELP... How can I resolve the `jckjni.c` problem, I googled and find out nothing useful.

## Problem
```
dist:
     [copy] Copying 5957 files to /opt/openjdk/openjdk-tests/jck/build/jck
     [copy] Copied 903 empty directories to 4 empty directories under /opt/openjdk/openjdk-tests/jck/build/jck
     [echo] start compiling jck natives

compile_jck:
     [echo] jck_short_version is 8b
     [echo] platform_short_name is x64_linux
     [echo] /opt/openjdk/openjdk-tests/jck/../systemtest/openjdk-systemtest/openjdk.test.jck/src/native/makefile
     [echo] PLATFORM=x64_linux
     [echo] SRCDIR=/opt/openjdk/openjdk-tests/jck/jck8b/JCK-runtime-8b
     [echo] OUTDIR=/opt/openjdk/openjdk-tests/jck/jck8b/natives
     [echo] JAVA_HOME=${JDK_HOME}
     [exec] mkdir -p /opt/openjdk/openjdk-tests/jck/jck8b/natives/x64_linux/
     [exec] /opt/openjdk/openjdk-tests/jck/../systemtest/openjdk-systemtest/openjdk.test.jck/src/native/makefile:41: Using /opt/openjdk/j2sdk-image/bin/ from PATH to create jar files
     [exec] make: *** No rule to make target `jckjni.c', needed by `libjckjni.so'.  Stop.

BUILD FAILED
/opt/openjdk/openjdk-tests/jck/build.xml:214: The following error occurred while executing this line:
/opt/openjdk/openjdk-tests/jck/build.xml:75: exec returned: 2
```

I checked the SRCDIR, it's not existed?

## My Env
```
os: Ubuntu 14.04.5 LTS 
PLATFORM="x64_linux"
JVMVERSION="openjdk8"
```

**Comment by smlambert** [comment]
hi @wefine, can you answer a couple more questions:
1) did you review https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/jck/README.md ?
2) do you have your own JCK test material (as per the jck/README.md)?
3) did you export the JCK_ROOT, JCK_VERSION and JAVA_HOME vars (as per jck/README)?

If you did not export JCK_ROOT, we should have not tried to compile the jck natives, and that is a bug against us.

FYI @TianyuZuo

**Comment by TianyuZuo** [comment]
Hi @wefine 

Thanks for using our JCK automation tool and providing feedbacks.
I went through the error output and found something which may need your help to give more info.

1.
In the output, I saw the `[echo] SRCDIR=/opt/openjdk/openjdk-tests/jck/jck8b/JCK-runtime-8b`, so I assume you have did the environment setup for JCK_ROOT and JCK_VERSION as `export JCK_ROOT=/opt/openjdk/openjdk-tests/jck` and `export JCK_VERSION=jck8b`. 

Could you also provide the structure in `/opt/openjdk/openjdk-tests/jck/jck8b/JCK-runtime-8b` and `/opt/openjdk/openjdk-tests/jck/jck8b`? Reason for asking this is that I was wondering if JCK materials are correctly staged in the `JCK_ROOT`

2.
In the outoput, it said `[echo] JAVA_HOME=${JDK_HOME}`, this `JDK_HOME` should have been passed into the Ant script  by the top level makefile. Did you run this Ant script directly or from the top level makefile?

**Comment by sxa555** [comment]
@wefine Can you clarify the above please? Assuming you have access to and have the JCK material (separate repository from the STF / openjdk-systemtest automation) extracted you should have that source file.

**Comment by wefine** [comment]
Sorry, I donot get jck material, I have to skip it.
