### ISSUE TITLE
Running test jobs on windows get "ERROR: sha1 sum check error."

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#393]
Currently test compile target depends on target getdependency, which downloads dependent jars for functional tests.

The download jobs check jars sha1 sum and fails on Windows

20:40:59 downloading dependent third party jars to C:/Users/jenkins/workspace/openjdk_test_x86-64_windows/openjdk-tests/\\TestConfig\\lib 
20:40:59 downloading http://central.maven.org/maven2/org/ow2/asm/asm-all/6.0_BETA/asm-all-6.0_BETA.jar 
20:40:59 ERROR: sha1 sum check error. 
20:40:59 --> file downloaded to C:/Users/jenkins/workspace/openjdk_test_x86-64_windows/openjdk-tests/\\TestConfig\\lib\asm-all.jar 
20:40:59 Expected sha1 is: 535f141f6c8fc65986a3469839a852a3266d1025, 
20:40:59 Actual sha1 is  : f2f8bdd51f1a5280c7874af519fdf6425431cecd. 

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk_test_x86-64_windows/300/console

Tried ignore this asm-all.jar and got same failures for other jars.

**Comment by smlambert** [comment]
jkingdon saw that error yesterday (in rt-j9-test channel).  He said it went away when he recloned a fresh copy of the tests repo... but you may already have tried that

**Comment by sophia-guo** [comment]
Double checked his error is different, which may be network issue as download didn't get the file:
```
/home/jkingdon/tests/openj9/test/TestConfig/../TestConfig/lib 
downloading http://central.maven.org/maven2/org/ow2/asm/asm-all/6.0_BETA/asm-all-6.0_BETA.jar
Use of uninitialized value $output in print at scripts/tools/getDependencies.pl line 132.
Can't delete '/home/jkingdon/tests/openj9/test/TestConfig/../TestConfig/lib/asm-all.jar': No such file or directory 
makefile:76: recipe for target 'getdependency' failed
make: *** [getdependency] Error 2
```

**Comment by sophia-guo** [comment]
Refer to https://github.com/eclipse/openj9/issues/1736

**Comment by sophia-guo** [comment]
Closed as upstream issue closed
