### ISSUE TITLE
Setup code coverage analysis for test builds

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#4]
Investigate and setup jcov for gathering code coverage information.

**Comment by neomatrix369** [comment]
@ShelleyLambert Already implemented in one of our scripts, see https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/jtreg.sh#L66

**Comment by smlambert** [comment]
Closing this issue as its already implemented.  If we want to leverage the code cov info for different views or triggers, we can open another issue.
