### ISSUE TITLE
Issues related with tests setting up on Windows

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#407]
[enable tests on windows](https://github.com/AdoptOpenJDK/openjdk-tests/pull/406)

In this PR we are actually using  batch to trigger batch file in jenkins,  which means we have to separate  windows story from other platforms. 

With build story getting complicated it is a kind of pain to maintain different stories. There are examples of build jenkins jobs on windows with cygwin, which could  align the windows story with the other platforms [openj9 tests](https://ci.eclipse.org/openj9/view/Test/)     [adoptopenjdk windows build ](https://ci.adoptopenjdk.net/)     

Not sure the exact jenkins build environment difference between our test windows machine and the machines mentioned before.  However default command line is not cygwin, probably extra setting are needed either in jenkins setting up or in jenkins build file. Looking are adopt build story may help.

**Comment by sophia-guo** [comment]
To running some regression tests we need cygwin environment. [Eclipse openj9](https://github.com/eclipse/openj9/blob/master/buildenv/Build_Instructions_V8.md) require cygwin as prerequisites. [adopt jdk build use shell script to trigger build](https://ci.adoptopenjdk.net/job/openjdk10_build_x86-64_windows/configure) . Some regression tests are shell script, which also need cygwin on windows https://ci.adoptopenjdk.net/view/all/job/Grinder/39/console.

**Comment by llxia** [comment]
Further tested this by running `get.sh` on wins machine in OpenJ9 Jenkins and the test runs fine with minor change.
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK8-win_x86-64_cmprssptrs/29/
https://github.com/AdoptOpenJDK/openjdk-tests/pull/460

This issue is blocking us to switch to use AdoptOpenJDK test pipeline on wins in OpenJ9 Jenkins. https://github.com/eclipse/openj9/blob/5e482173e62fc430ddcfadcbe57c0b6df04e8202/buildenv/jenkins/common/pipeline-functions#L171

**Comment by smlambert** [comment]
@llxia - we need to raise machine configuration requests as issues in the openjdk-infrastructure repo, I raised this one: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/378  - you may want to add a note or query to it to raise the priority.

**Comment by sophia-guo** [comment]
Configuration of win2012r2-x64-1 works well. Close this one, issue is tracked in AdoptOpenJDK/openjdk-infrastructure#378

**Comment by gdams** [comment]
@sophia-guo https://ci.adoptopenjdk.net/computer/test-packet-x64-windows-2012r2-1/ is still offline. Can it be brought back online?

**Comment by sophia-guo** [comment]
@gdams Looks like the issue in AdoptOpenJDK/openjdk-infrastructure#378 is not updated so I don't think we can bring the machine back online.
