### ISSUE TITLE
Re-enable tests on AIX

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-tests#411]
Currently we do not have dedicated test machines for AIX. Since this is taking quite a while to resolve I am proposing using one of the two build boxes to attempt to run the tests on so we at least have some coverage. It may be that we have to run them only once a week, but this issue will cover the "tactical fix" until we get more machines available

**Comment by smlambert** [comment]
Sure, I can schedule them on the weekend when I do not believe any builds are currently being run.  I can start with the 'sanity' set, and see how long it takes for those to complete.

@sxa555 - preference to a particular Java version, or I can run a subset of tests on all versions and see how it goes time-wise.

**Comment by sxa555** [comment]
Have now put ant on the machine (symlinked into `/usr/bin` so it's on the default PATH) and added in an `ant-contrib` jar file. Not sure if I've done that properly but I'll see how far it gets on the new run ([#14](https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/14/console))

**Comment by sxa555** [comment]
. o O (That's odd)
```
18:00:11 gmake: ant: Command not found
```

**Comment by sophia-guo** [comment]
As Shelley's PR has not been merged you probably need to pass in parameters:  
repo: smlambert
Branch: grinder

**Comment by smlambert** [comment]
I am running tests on AIX successfully (https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/15/).

I will be merging my PR tomorrow (that allows for the 'Grinder' job to exist and work with AIX), and will create some 'weekly test builds that will run on the weekend for regular AIX testing.

**Comment by smlambert** [comment]
https://ci.adoptopenjdk.net/view/Weekly%20Tests/job/openjdk8_j9_openjdktest_ppc64_aix_weekly/lastCompletedBuild/ - the 'sanity' set (jdk_io, jdk_lang, jdk_net, jdk_rmi, jdk_nio) completed in just over 2hrs, with 57/2258 failures.  jdk_math, run separately passes.

I'll create the other weekly jobs (for other versions and impls) and they'll be scheduled to run Sat/Sun (the sanity groups for now).

**Comment by sxa555** [comment]
Sounds good. I've opened https://github.com/AdoptOpenJDK/openjdk-build/issues/324 with the list of failures on the AO8/J9 run. I'm hoping quite a few of them will be setup issues and the like as opposed to real problems in the JVM :-)

**Comment by smlambert** [comment]
Added some weekly testing for versions 8/9/10 impl hs/j9 here: https://ci.adoptopenjdk.net/view/Weekly%20Tests/

When we get another AIX machine, we can add testing into the build pipelines as other platforms.
