### ISSUE TITLE
Add openjdk9 and openjdk10 builds on both j9 and hs for External tests 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#413]
Add openjdk9 and openjdk10 builds on both j9 and hs for External tests.

**Comment by Mesbah-Alam** [comment]
PR for the Jenkins templates : https://github.com/AdoptOpenJDK/openjdk-tests/pull/402

**Comment by Mesbah-Alam** [comment]
Build pipelines for Java 9 and Java 10 have been added under External Tests tab at Adopt: https://ci.adoptopenjdk.net/view/External%20tests/

**Comment by Mesbah-Alam** [comment]
PR for adding build triggers: https://github.com/AdoptOpenJDK/openjdk-build/pull/329

**Comment by smlambert** [comment]
Fixed by [openjdk-build/329](https://github.com/AdoptOpenJDK/openjdk-build/pull/329)
