### ISSUE TITLE
Support the fact that builds will produce JRE builds as well as JDK

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-tests#417]
There is a PR open against the build repo which will cause the builds to produce both JRE and full JDK artefacts. Any jobs that copy from this will need to tolerate this (and probably allow for picking up either version).

The PR is https://github.com/AdoptOpenJDK/openjdk-build/pull/331 (naming convention will be discussed in that PR so I'm not going to specify it here in case it goes out of date)

This build has been modified to build from the code in my PR so can be seen as an example: https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/

**Comment by smlambert** [comment]
@sophia-guo, you opened #437, is it the same as this issue?  

@sxa555 - when I go to the openjdk8_openj9_build_x86-64_linux, I no longer see the JRE artifacts (though I recall they were there at least for a while).  Can you guide me on how to revive?

**Comment by sophia-guo** [comment]
yes, same one.

There was JRE artifacts when this issue was opened. At that time`Source Code Management` was pointed to @sxa555 personal `create_jre` branch, which has not be delivered.
