### ISSUE TITLE
Jenkins unable to delete windows workspace due to busy git pack file

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#42]
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_windows/65/console

This is a known bug : https://issues.jenkins-ci.org/browse/JENKINS-19994?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

Temporary workaround is manually kill the process and restart the jenkins services.

**Comment by karianna** [comment]
@sophia-guo I've upgraded Jenkins which should have that fix.  LMK if it works for you!

**Comment by sophia-guo** [comment]
It is an intermittent failure. Will close it for now. If happens later reopen. @karianna Can you please let me know the upgraded Jenkins version? Thanks.

**Comment by karianna** [comment]
Jenkins is at 2.46.3

**Comment by sophia-guo** [comment]
Still get:
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_windows/100/console
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_windows/99/console

**Comment by sophia-guo** [comment]
Close this. Windows issue refers to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/23
