### ISSUE TITLE
Add Akka into open source packages testing 

### ISSUE THREAD

**Issue by mamatha-jv** [AdoptOpenJDK/openjdk-tests#422]
This issue is opened to track the process of adding Akka into open source packages testing at https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/thirdparty_containers

Refer issue #172 for more details.

**Comment by mamatha-jv** [comment]
Seeing OutOfMemory issue with hotspot build so I have to run tests again with increased heap

**Comment by smlambert** [comment]
Is this work in a branch somewhere?  If so, please document here.  If not, I will suggest we close it (leaving the app in the list at #172), until someone is actually working on it.

**Comment by smlambert** [comment]
Closing this as stale, its in the list in #172 should we wish to address.
