### ISSUE TITLE
Remove systemtest build step from the process of JCK compilation with STF

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#427]
Currently JCKs use STF, and at the moment you can't get/compile STF without getting and compiling systemtests, however JCKs don't need systemtests to be built. This dependency needs to be removed.

**Comment by smlambert** [comment]
I recognize we inherited this dependency to run JCKs under STF, but I think it would be good to see how to correct it.  As we analyze this, we can/should also consider the pros/cons of not using STF for running JCKs under STF, but rather, run them directly to remove layers of indirection to the actual executable being run.

**Comment by smlambert** [comment]
@Mesbah-Alam perhaps this issue may more appropriately live either in the systemtest or stf repo (wherever the change needs to happen)

**Comment by Mesbah-Alam** [comment]
@ShelleyLambert Agreed. I opened an equivalent issue in openjdk-systemtest repo: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/142. 

Closing this issue.

**Comment by lumpfish** [comment]
Regarding _"I recognize we inherited this dependency to run JCKs under STF, but I think it would be good to see how to correct it."_  There is simply some automation to setup the environment for running the JCK, execute it and check the output from the run.  The automation works - what is it you want to "correct"?  You may prefer the autoamtion to be implemented in a different way, but that it is different issue.
The statement in this issue about not being able to compile stf without compiling openjdk-systemtest is not true.  See AdoptOpenJDK/openjdk-systemtest#142.
