### ISSUE TITLE
Test Pipeline should run and provide code coverage stats where it can

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-tests#428]
Builds should run test/test-coverage see https://github.com/AdoptOpenJDK/openjdk-build/issues/7

**Comment by sophia-guo** [comment]
@neomatrix369 I have checked the build under https://adopt-openjdk.ci.cloudbees.com/view/OpenJDK/

jcov results for project-shenandoah-jdk8 are empty. I have run a build in adopt and got empty results too, which says `[jcov:instr] WARNING : Path '/jdk/classes' doesn't exist - skipped`.  https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_jcov/9/consoleFull
I have a fix for this : https://github.com/AdoptOpenJDK/openjdk-build/pull/374/files.
Then got:
```
[jcov:instr] WARNING : java.lang.Object can't be statically instrumented and was excluded
[jcov:instr] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
[jcov:instr] 	at java.util.Arrays.copyOf(Arrays.java:3236)
[jcov:instr] 	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
[jcov:instr] 	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
[jcov:instr] 	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
[jcov:instr] 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
...
[jcov:instr] 	at com.sun.tdk.jcov.instrument.ClassMorph.saveData(ClassMorph.java:658)
[jcov:grabber] Execution error: Bad template: /data/home/jenkins/workspace/openjdk8_jcov/openjdk/build/linux-x86_64-normal-server-release/testoutput/jdk_core/JTwork/jcov/template.xml
...
```

Any idea about this?

**Comment by smlambert** [comment]
Noting the extra complication of gathering code coverage per test pipeline run, where we will not be running all tests sequentially, but rather splitting them up into small groups to run in individual pipelines (smart parallelism to improve overall execution time), which means coverage per child pipeline would have to be successfully pieced together to give an overall view.

**Comment by smlambert** [comment]
will close this in favour of #2205
