### ISSUE TITLE
Grinders result

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#430]
When doing grinder we have separate tap result for each running. Better to provide a separate  grinder result summary especially for console output. Say grinder 10 times summary like:
running 10 times, 3 passed, 7 failed
It would be easy for debug es

<img width="1038" alt="screen shot 2018-05-31 at 9 34 13 am" src="https://user-images.githubusercontent.com/18030625/40785202-df23dfbe-64b5-11e8-96ac-2b19ca75c454.png">
<img width="1083" alt="screen shot 2018-05-31 at 9 33 34 am" src="https://user-images.githubusercontent.com/18030625/40785204-df3ef984-64b5-11e8-9b7c-242078880fab.png">

**Comment by llxia** [comment]
Do we have TAP result for grinder?

**Comment by llxia** [comment]
TAP result provides information if there are failed tests.

![screen shot 2018-05-31 at 10 07 31 am](https://user-images.githubusercontent.com/19273206/40786998-7ff788d8-64ba-11e8-922a-ab50b625e0b9.png)

**Comment by smlambert** [comment]
We have TAP result for grinders (and it creates a new result for each run), which is good.  For tests that produce xUnit style results, they get overwritten so only the last run is visible.

Ultimately, we maybe should improve this story, but for now, given the differences between the different result formats for the different types of tests we wish to grind, TAP is the lowest common denominator that we have.  

In the case of "openjdk" style testing, perhaps we re-introduce the failure output to the TAP comment field for Grinders, so they get printed in that view?

**Comment by smlambert** [comment]
Am closing this as wont fix, TAP results show individual runs, which is sufficient for now.
