### ISSUE TITLE
Update TestConfig scripts that download third party jars to use cURL when on z/OS

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#431]
Background: https://github.ibm.com/runtimes/infra-can/issues/117#issuecomment-6359814

In TestConfig perl scripts where `wget` is used to download third party jars, we need to use `cURL` instead, when on z/OS. 

wget doesn't work on z/OS, as evident in the following job: https://urv-jenkins.canlab.ibm.com:9095/view/SV_Tests/job/ibmjava8_systemtest_s390x_zos/32/console

cURL example : 
```
cd target/path
curl -o ${download_url}
```

**Comment by sophia-guo** [comment]
When using curl we need also update Document to add curl as a prerequisite eventually.

**Comment by smlambert** [comment]
options to consider:
1) switch over to curl for all platforms and remove the dependency on wget, to keep the prereqs 'simple'
2) have scripts check for presence of curl, use it if there, fall back to try using wget if not
3) just use curl for zos, as suggested, leaving other platforms as is for now

**Comment by smlambert** [comment]
I didn't see @renfeiw PR already :)  happy to go option 3 for now, think about if we want go further with it later.

**Comment by renfeiw** [comment]
I have PR for option 3, and am testing it now. I agree, we keep it for now and we can extend it later on.

**Comment by Mesbah-Alam** [comment]
@renfeiw - thanks for adding the curl option. I tested the PR you posted off of your branch, and it ```00:01:17.198 downloaded dependent third party jars successfully```. Please check the z/OS job. 
(It however, fails now for a different reason; will discuss about it offline).

**Comment by smlambert** [comment]
Closing this issue as PR has been delivered.  (in future, we can/should try to use 'Fixes' keyword in PR comment to auto-close issues they address).

**Comment by AdamBrousseau** [comment]
>2. have scripts check for presence of curl, use it if there, fall back to try using wget if not

+1
