### ISSUE TITLE
Add node description in test build

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#434]
I would like to add node description in test build, so it is easier for user to figure out which machine this test is running on.

We already have this set up in OpenJ9:

![screen shot 2018-06-04 at 2 09 01 pm](https://user-images.githubusercontent.com/19273206/40933870-e7780b9c-6800-11e8-92ab-9468f6a857a6.png)

**Comment by llxia** [comment]
Tested in personal build, but it does not render the html properly. https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox2/228/

![screen shot 2018-06-04 at 3 10 25 pm](https://user-images.githubusercontent.com/19273206/40936477-765363ea-6809-11e8-9c0f-c3f835426f7b.png)


It looks like we need to set `Safe HTML` in `Markup Formatter` in `Configure Global Security`
https://stackoverflow.com/questions/33821217/html-in-jenkins-job-descriptions?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

@ShelleyLambert could you enable the settings? Thanks.

**Comment by smlambert** [comment]
I've updated Jenkins global security config to use 'Safe HTML' vs Plain text.

**Comment by smlambert** [comment]
<img width="296" alt="nodedescfortests" src="https://user-images.githubusercontent.com/2836948/40937390-759484ea-680c-11e8-8b57-0beebbb3d284.png">

Looks good!
