### ISSUE TITLE
Perf build failed due to missing test package from perffarm 

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#457]
Perf build failed due to missing test package from perffarm

```
23:30:28 getBenchmarkPackage:
23:30:28      [echo] /home/jenkins/workspace/openjdk8_hs_perftest_x86-64_linux/../benchmarks/ilog_wodm881_Package.zip
23:30:28      [echo] wget -q --http-user=${env.PERF_USERNAME} --http-password=XXX --no-check-certificate http://perffarm.hursley.ibm.com/packages/ilog_wodm881_Package.zip
```

perffarm.hursley.ibm.com is an internal server. Test material should be pre-staged on the machine.

Disable the builds until this is fixed: https://ci.adoptopenjdk.net/view/Perf%20tests/

**Comment by llxia** [comment]
Could we have some machine labeled for perf testing (i.e. `ci.role.perf`), so I do not need to stage perf test material on all test machine? @ShelleyLambert

**Comment by llxia** [comment]
Can we label two linux machines for now? Thanks
https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-2/
https://ci.adoptopenjdk.net/computer/test-softlayer-ubuntu1604-x64-1/

**Comment by smlambert** [comment]
Those 2 machines now labeled with ci.role.perf

**Comment by llxia** [comment]
Test material is staged on both machines under `/home/jenkins/workspace/benchmarks`

Test cannot run properly due to missing `numactl`
https://ci.adoptopenjdk.net/view/Perf%20tests/job/openjdk8_j9_perftest_x86-64_linux/108/console
```
21:07:14 =======================
21:07:14 = Running ILOG_WODM =
21:07:14 =======================
21:07:14 Error: verbosegc.280618-190714.log does not exist
21:07:14 Error: Headless GCMV cannot operate without a verbosegclog
21:07:14 *** Error: No New Trace/Logs found
21:07:14 *** No New Dumps found
```

**Comment by llxia** [comment]
```
jenkins@test-packet-ubuntu1604-x64-2:~$ numactl
-bash: numactl: command not found
```

```
jenkins@test-softlayer-ubuntu1604-x64-1:~$ numactl
The program 'numactl' is currently not installed. To run 'numactl' please ask your administrator to install the package 'numactl'
```
I do not have the rights to install `numactl`. @gdams Could you help us to install `numactl` on the following two machines? Thanks.
https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-2/
https://ci.adoptopenjdk.net/computer/test-softlayer-ubuntu1604-x64-1/

**Comment by smlambert** [comment]
You can raise an openjdk-infrastructure issue for that request.

**Comment by llxia** [comment]
This issue is not valid anymore.
