### ISSUE TITLE
Put test workshop docs in AdoptOpenJDK test repo

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#465]
We would like to put test workshop docs in AdoptOpenJDK test repo, so more people can benefit from it. Test workshop docs contain detailed instructions of 
- how to run tests (i.e., functional, system, openjdk regression test, etc) in docker image.
- how to use our Jenkins based grinder

**Comment by smlambert** [comment]
We have a bit of this info in open wikis:
https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally
https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins

Should look to see what is missing and augment the open docs.

**Comment by llxia** [comment]
As mentioned above, we have wikis and readme in AdoptOpenJDK and OpenJ9. They contain instructions on how to run tests using Grinder and locally.
Close this issue.
