### ISSUE TITLE
External test builds break at result zipping state due to permission issue in lucene-solr syserr file

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#470]
External test builds break at result zipping state due to permission issue in lucene-solr syserr file

Output: 
```
22:06:47 tar: /home/jenkins/workspace/openjdk8_hs_externaltest_x86-64_linux/openjdk-tests/TestConfig/test_output_15309132846972/lucene_solr_nightly_smoketest_0/junitreports/lucene-solr/temp/junit4-J1-20180706_224308_2273935128120677245681.syserr
```

This was introduced by the PR delivered to map output junit xml files of lucene-solr tests onto the host machine. That step copies over the sysrerr file in question too - which seem to not have read permission.

**Comment by Mesbah-Alam** [comment]
@smlambert - agreed. I submitted a build to test a fix in which I have done exactly what you suggested. Will ask for review once the test passes.

**Comment by sophia-guo** [comment]
Can this be closed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/515?

**Comment by Mesbah-Alam** [comment]
Yes, Thanks for reminding.
