### ISSUE TITLE
Pipeline shell step aborts prematurely with ERROR: script returned exit code -1

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#474]
Pipeline shell step aborts prematurely with ERROR: script returned exit code -1, which suggests
```
23:40:22 TEST RESULT: Passed. Execution successful
23:40:22 --------------------------------------------------
23:41:22 wrapper script does not seem to be touching the log file in /home/jenkins/workspace/openjdk10_j9_openjdktest_ppc64le_linux@tmp/durable-6e1ee46e
23:41:22 (JENKINS-48300: if on a laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=300)
```
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk10_j9_openjdktest_ppc64le_linux/52/consoleFull

This issues happened intermittently. It seemed if there is no log information for a period of time pipeline will prematurely aborts and return with exit code -1. That means if some tests take longer without output may get this issue?
```
23:41:22 wrapper script does not seem to be touching the log file in /home/jenkins/workspace/openjdk10_j9_openjdktest_ppc64le_linux@tmp/durable-6e1ee46e
```

According to the message, Set master JVM with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=300 may help.

**Comment by smlambert** [comment]
@sophia-guo - Do you mean a possible solution is to add the HEARTBEAT_CHECK_INTERVAL as a commandline option to the JVM that runs the Jenkins agents?

**Comment by sophia-guo** [comment]
@smlambert yes,  though I don't have permission to try.

**Comment by smlambert** [comment]
I believe I do, so I can add it to the JVM_OPTIONS for the agent for all test machines.  (Likely won't do this until later tonight).

**Comment by smlambert** [comment]
Added to the 2 ppcle test machines that seem to be lagging, and where we see this issue most.  We can see if this will resolve the problem.  If other machines also end up having this issue, we will also want to update them.

**Comment by Mesbah-Alam** [comment]
Seen this error on x86-64_linux too:  https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/117/console.

```4:36:10 wrapper script does not seem to be touching the log file in /home/jenkins/workspace/Grinder@tmp/durable-1fd851bf
14:36:10 (JENKINS-48300: if on a laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=300)```

**Comment by smlambert** [comment]
@sxa555 or @karianna , if you have permissions to Jenkins master, can you add the HEARTBEAT_INTERVAL option as noted above?  Thanks!

**Comment by karianna** [comment]
This has been added to master jenkins and it's been restarted

**Comment by karianna** [comment]
I'll let you close if the issue is resolved

**Comment by sophia-guo** [comment]
It happened again on windows. So probably we need to double check if the option is set on master or if the setting was reset by some master update?
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_windows/2/console

**Comment by sophia-guo** [comment]
Didn't see this issue for a long time. Assume it's solved by adding the options.

**Comment by dfoley84** [comment]
Currently Facing the Above issue.. I have added the following into the Pipeline 
`script {
            System.setProperty("org.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL", "86400");`

**Comment by kerthcet** [comment]
> Currently Facing the Above issue.. I have added the following into the Pipeline
> `script { System.setProperty("org.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL", "86400");`

have you solve the problem?

**Comment by yudiz-vinayak** [comment]
I'm getting same issue @sophia-guo please help me how to fix this issue 

```
wrapper script does not seem to be touching the log file in $PWD@tmp/durable-48d0a171
(JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
```

**Comment by smlambert** [comment]
@yudiz-vinayak - see the note in https://github.com/adoptium/aqa-tests/issues/474#issuecomment-409014691 about setting the -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=300 (https://issues.jenkins-ci.org/browse/JENKINS-48300?focusedCommentId=330383&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-330383) - in the init script of the Jenkins server you are using.
