### ISSUE TITLE
Enable jdk_awt tests and x11 DISPLAY env var set properly

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#49]
There are currently a large number of failures in the jdk_awt group related to the x11 display not being set properly, in order to run those tests.  Expect the bulk of awt failures to go away after setting correctly.

23:42:59 ACTION: main -- Failed. Execution failed: `main' threw exception: java.awt.HeadlessException: No X11 DISPLAY variable was set, but this program performed an operation which requires it.

**Comment by sophia-guo** [comment]
Double checked this failure only happens to linux(Windows is fine. In Windows, there is always a display).

For Linux we need set the DISPLAY environment variable to the address of X11 server and export that. What is the address of X11 server @gdams @bblondin

**Comment by allandequeiroz** [comment]
Hello, I've been trying to reproduce it using a VM, I went to console mode only on linux and looked for the X server address.

![screen shot 2017-06-08 at 19 51 38](https://user-images.githubusercontent.com/629076/26945696-7d87f924-4c84-11e7-92d2-05268aaff240.png)

Then doing ```make test DISPLAY=:0``` apparently worked fine.

![screen shot 2017-06-08 at 19 48 30](https://user-images.githubusercontent.com/629076/26945734-9f9f1736-4c84-11e7-9484-da8a63f6e676.png)

What do you think if I try to get this address dynamically and set to DISPLAY env var?

**Comment by sophia-guo** [comment]
Not sure if X11 forwarding is enabled on test machine? If yes we can either update jdk_awt test command to

<command>**export DISPLAY=localhost:0.0;**$(JAVA_COMMAND) -Xmx512m -jar $(Q)$(JTREG_DIR)$(D)lib$(D)jtreg.jar$(Q) \
	$(JTREG_BASIC_OPTIONS)  -vmoptions:$(Q)-Xmx512m $(JVM_OPTIONS)$(Q) \
	-w $(Q)$(TEST_RESROOT)$(D)work$(Q) \
	-r $(Q)$(TEST_RESROOT)$(D)report$(Q) \
	-jdk:$(Q)$(JDK_HOME)$(Q) \
	-exclude:$(Q)$(JTREG_TEST_DIR)$(D)ProblemList.txt$(Q) \
	$(Q)$(JTREG_TEST_DIR):jdk_awt$(Q); \
	$(TEST_STATUS)</command>
	
or export in Makefile should be ok.

**Comment by allandequeiroz** [comment]
Sounds good @sophia-guo. Who has access to check there?

**Comment by tellison** [comment]
@allandequeiroz best bet is to jump onto Slack and pose the question in the #infrastructure channel.  We can either fix it there, or give you access to the box to go in and see what's happening.

**Comment by stooart-mon** [comment]
You run your tests under Jenkins. In ci.linaro.org we run with the Xvfb plugin: 
    https://wiki.jenkins.io/display/JENKINS/Xvfb+Plugin
Disconnections between the Jenkins slave and master can cause issues with Xvfb left behind - that is true for other daemons (jstatd) fired off by JTreg.

**Comment by tellison** [comment]
After some discussion on Slack, we'd like to consider the following approach:

- simplify the Ansible script to add `Xvfb` as a required package (add to the list here https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/Build/ansible/playbooks/ubuntu_14_16_x86.yml#L138), and remove the X11 set-up code (remove lines 148-169)
- Change the testing code to use the `DISPLAY` env var, rather than hard-coding a specific value (https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/OpenJDK_Playlist/playlist.xml#L257 and anywhere else likewise)
- Testing jobs in Jenkins requiring a UI are set-up to use the Xvfb plugin to define and start a useful display for their executor.
- We need a nagios check / regular clean-up script to look for growing number of Xvfb processes that need killing off.

**Comment by smlambert** [comment]
Fixing this issue depends on updates to test machines: 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/184

**Comment by smlambert** [comment]
Closing as now listed in summary issue #346

**Comment by smlambert** [comment]
This was inadvertantly closed when I deleted a branch with a potential fix.  Renaming/reoopening this issue at higher priority, as there seems a great need to get jdk_awt tests running based on recent issues raised in Slack channels over font issues seen.

**Comment by smlambert** [comment]
related: https://github.com/AdoptOpenJDK/openjdk-build/issues/682

**Comment by sophia-guo** [comment]
I have tried running start-Xvfb.sh before testing with https://github.com/sophia-guo/openjdk-tests/tree/awt and got `18:10:03 Error: /opt/sfw/bin/fvwm2 not found`. [grinder console output](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/743/console) 

According to the shell script there is no `/usr/bin/X11/fvwm2` nor `/opt/sfw/bin/fvwm2`. So we need fvvm installed before we can run this script.

**Comment by smlambert** [comment]
@sxa555 - you asked in meeting this morning, the utility is fvwm2 - we have to figure out if we need to use that approach or if the Jenkins xvfb plugin is sufficient.

**Comment by sophia-guo** [comment]
Enabled on limited Platform in #789 

Windows does not need xvfb plugin, however most jdk_awt failed with message 'TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Failed. Drag exit was not called'
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder_Sandbox/164/consoleFull

ppcle run xvfb plugin well, however most jdk_awt failed with msg 'java.lang.UnsatisfiedLinkError: /home/jenkins/workspace/Grinder_Sandbox/openjdkbinary/j2sdk-image/jre/lib/ppc64le/libfontmanager.so: libpng15.so.15: cannot open shared object file: No such file or directory'

[Test results: passed: 72; failed: 427; error: 4](https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/96/consoleFull)

Common failure is timeout, however increase timeout factor from 8 to 10 didn't resolve the problem. Looks like elapsed time increased too with increased timeout time.

**Comment by smlambert** [comment]
By the look of some failures, some relate to not finding/loading some libs:

java.lang.UnsatisfiedLinkError: /home/jenkins/workspace/Grinder_Sandbox/openjdkbinary/j2sdk-image/jre/lib/ppc64le/libfontmanager.so: libpng15.so.15: cannot open shared object file: No such file or directory

from:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/96/testReport/java_awt_Choice_RemoveAllShrinkTest_RemoveAllShrinkTest/java/RemoveAllShrinkTest/

**Comment by smlambert** [comment]
#789 and #797 are sufficient for now to mark this as closed.
