### ISSUE TITLE
Accept user credentials for getting jdk binary

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#495]
In some cases, user credential is needed for downloading jdk binary (i.e., jdk is in artifactory db). Our script needs to be updated, so that if user credential is provided for downloading jdk binary (Jenkins scheduled build, personal build and local runs), it should be used.

**Comment by geraintwjones** [comment]
Can we also consider using SSH keys too?

**Comment by llxia** [comment]
What is the use case? Is the SSH keys needed for local run? If so, you should be able to manually download the jdk.

**Comment by llxia** [comment]
reassign this to @jdekonin as he is working on upstream build script to pass in the artifactory credentials.

**Comment by smlambert** [comment]
There is a potential internal use case for ssh keys.  And given a recent request in openjdk-build repo to handle proxies better for someone using scripts within their lab, I think we should add support if possible.

**Comment by llxia** [comment]
Thanks for clarification, Shelley. Yes, we may want to address this in a separate issue.

**Comment by AdamBrousseau** [comment]
I think ssh is a valid use case if it's needed. But I think it requires slightly different code (ssh agent vs user/pass passed on cmd line). Therefore I think adding user/pass cred style for the short term, then adding ssh option later is desirable. We need this feature as soon as possible as we are moving our binaries on one of our Jenkins to a different server which requires auth.

**Comment by llxia** [comment]
This issue may want to wait until https://github.com/AdoptOpenJDK/openjdk-tests/issues/490 is delivered. We are going to remove wget, use only curl and merge multiple if statements into one.

**Comment by smlambert** [comment]
Also note that there is a case where we are already using [credentials for perf testing](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L157), that can/should be generalized.

**Comment by jdekonin** [comment]
I was attempting to get the testing working with an artifactory sdk url which requires user/passwd; I was using `withCredentials([usernamePassword...` to obtain this in other jobs.  

The rework performed under #506 by @llxia and the enablement of sshkey access on the artifactory user id resolves that use case.

**Comment by smlambert** [comment]
fixed by #512
