### ISSUE TITLE
RMI tests rmid process hang if failed for "TEST FAILED: rmid not destroyed in: 60000 milliseconds "

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#497]
Test category: openjdk
Testsuite name: jdk_rmi
Test name(s): 
java/rmi/activation/Activatable/downloadParameterClass/DownloadParameterClass.java
java/rmi/activation/Activatable/extLoadedImpl/ext.sh
java/rmi/activation/Activatable/forceLogSnapshot/ForceLogSnapshot.java.ForceLogSnapshot
java/rmi/activation/Activatable/inactiveGroup/InactiveGroup.java.InactiveGroup
java/rmi/activation/Activatable/restartCrashedService/RestartCrashedService.java.RestartCrashedService
java/rmi/activation/Activatable/restartLatecomer/RestartLatecomer.java.RestartLatecomer
java/rmi/activation/Activatable/restartService/RestartService.java.RestartService
java/rmi/activation/ActivateFailedException/activateFails/ActivateFails.java.ActivateFails
java/rmi/activation/ActivationSystem/modifyDescriptor/ModifyDescriptor.java.ModifyDescriptor

Product(s) tested: JDK 8u144 b01
OS/architecture: general
Platform specific: no

Reproducibility: always
Reproducible on machine: 
Regression: yes, introduced in jdk8u181-b13

Exception/Error from Log:
```
14:59:00 ACTION: main -- Failed. Execution failed: `main' threw exception: TestFailedException: TEST FAILED: rmid not destroyed in: 60000 milliseconds
14:59:00 REASON: User specified action: run main/othervm/policy=security.policy/timeout=240 DownloadParameterClass 
14:59:00 TIME:   69.804 seconds
14:59:00 messages:
14:59:00 command: main DownloadParameterClass
14:59:00 reason: User specified action: run main/othervm/policy=security.policy/timeout=240 DownloadParameterClass 
14:59:00 Mode: othervm [/othervm specified]
14:59:00 elapsed time (seconds): 69.804

```

**The hidden/main issue is after 600m test stopping trying to destroy the process and leave process hang around. RAM could be run out of.**

  
Steps to reproduce:
1) Re-include test.  (Search the Test class name in ProblemList_openjdk8-openj9.txt find the exclude line and comment the line)
2) make jdk_rmi

**Comment by sophia-guo** [comment]
Lost my bug system's profile passwd, when I got the passwd reset email will open the issue in buy system.

**Comment by sophia-guo** [comment]
Actually I don't have a JBS account to report/open an issue.

**Comment by karianna** [comment]
You need to be an OpenJDK committer of at least Author status IIRC.

**Comment by karianna** [comment]
Hmm, Actually it's worth raising this on the core-libs openjdk mailing list first

**Comment by sophia-guo** [comment]
Close this as a dup #819. Seemed #819 have more information.
