### ISSUE TITLE
Add missing generic Jenkins file per platform

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#504]
We need to add following generic Jenkins files:
- openjdk_x86-64_linux_largeHeap

**Comment by sophia-guo** [comment]
I believe win32 is java8 only. So no need for generic one. 
Large heap will be needed for 11 as well as it's LTS. 9 & 10 can be skipped as they are either out of support or go out in Sept. A generic one should be good.

**Comment by llxia** [comment]
Thanks. Updated the description.

**Comment by llxia** [comment]
PR is delivered. Close this issue.
