### ISSUE TITLE
Jenkins build on Windows get java.nio.file.AccessDeniedException when wiping out the workspace

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#51]
java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\openjdk_test_x86-64_windows\openjdk-test\OpenJDK_Playlist\openjdk-jdk8u\jdk\test\sun\management\windows\revokeall.exe

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_windows/146/console

Suspect revokeall.exe is running? @bblondin Could you help to check this?

**Comment by bblondin** [comment]
Rebooted to clear application holding onto the process
