### ISSUE TITLE
Execute openjdk_regression & systemtests for OpenJDK 11 build on armv5tejl

### ISSUE THREAD

**Issue by jabrena** [AdoptOpenJDK/openjdk-tests#520]
# Goal:
It is necessary certificate the build OpenJDK 11 for armv5tejl (Lego Mindstorms EV3) so it is necessary to run all tests from `openjdk_regression` and `systemtest`.

## Step 1: Validate build against the openjdk_regression test suite:

`openjdk_regression` are organized in the following areas:
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk_regression/playlist.xml

### Stable test Settings:

```
#export JAVA_IMPL=hotspot
export BUILD_LIST=openjdk_regression
export JAVA_BIN=/opt/jdktest/jdk/bin
export SPEC=linux-arm
export JAVA_VERSION=SE110
```

### Execution:

- [ ] make jdk_math
- [ ] make jdk_lang
- [ ] make jdk_io
- [ ] make jdk_beans (`All tests failed`)
- [ ] make jdk_other 
- [ ] make jdk_net
- [ ] make jdk_nio
- [ ] make jdk_security1
- [ ] make jdk_security2
- [ ] make jdk_security3 (Pending to exclude `sun/security/rsa/SignedObjectChain.java`)
- [ ] make jdk_text
- [ ] make jdk_util
- [ ] make jdk_time
- [ ] make jdk_management
- [ ] make jdk_jmx
- [ ] make jdk_rmi
- [ ] make jdk_sound (Disabled)
- [ ] make jdk_tools
- [ ] make jdk_jdi
- [ ] make jdk_jfr
- [ ] make jdk_awt (Disabled)
- [ ] make jdk_swing (Disabled)

### Dev notes:

All test exclusion are stored in this feature branch:
https://github.com/ev3dev-lang-java/openjdk-tests/blob/feature/ev3dev/openjdk_regression/ProblemList_openjdk11-openj9.txt

## Step 2: Validate the build against the system tests

https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/systemtest/playlist.xml

### Stable test Settings:

```
export JAVA_IMPL=hotspot
export BUILD_LIST=systemtest
export JAVA_BIN=/opt/jdktest/jdk/bin
export SPEC=linux-arm
export JAVA_VERSION=SE110
```

### Execution:

- [x]  make DirectByteBufferLoadTest
- [x]  make LangLoadTest
- [x]  make LockingLoadTest
- [x]  make MathLoadTest_all
- [x]  make MathLoadTest_autosimd
- [x]  make MathLoadTest_bigdecimal
- [x]  make MauveSingleThreadLoadTest
- [x]  make MauveSingleInvocationLoadTest
- [x]  make MauveMultiThreadLoadTest
- [x]  make NioLoadTest
- [x]  make UtilLoadTest
- [x]  make HCRLateAttachWorkload
- [x]  make JdiTest
- [x]  make DaaLoadTest_daa1
- [x]  make DaaLoadTest_daa2
- [x]  make DaaLoadTest_daa3
- [x]  make DaaLoadTest_all
- [x]  make HeapHogLoadTest
- [x]  make ObjectTreeLoadTest
- [x]  make CpMpTest_CpMp
- [x]  make CpMpTest_MP
- [x]  make CpMpTest2
- [x]  make CpMpTest3
- [x]  make CpMpModularJarTest
- [x]  make CpMpModularJarTest2
- [x]  make CpMpModularJarTest3
- [x]  make JDKInternalAPIsTest
- [x]  make AutomaticModulesTest1
- [x]  make AutomaticModulesTest2
- [x]  make AutomaticModulesTest_ImpliedReadabilityTest1
- [x]  make AutomaticModulesTest_ImpliedReadabilityTest2
- [x]  make AutomaticModulesTest_ImpliedReadabilityTest3
- [x]  make ExplicitModulesTest
- [x]  make ServiceLoadersTest
- [x]  make PatchModuleTest_PlatformModPatchModule
- [x]  make PatchModuleTest_AppModPatchModule
- [x]  make PatchModuleTest_UnexportedTypePatchModule
- [x]  make PatchModuleTest_AdvancedPatchModule
- [x]  make PatchModuleImageTest_PlatformModPatchModule
- [x]  make PatchModuleImageTest_AppModPatchModule
- [x]  make PatchModuleImageTest_UnexportedTypePatchModule
- [x]  make PatchModuleImageTest_AdvancedPatchModule
- [x]  make UpgradeModPathTest_ExpDirModUpgrade
- [x]  make UpgradeModPathTest_ExpDirModUpgradeCRImage
- [x]  make UpgradeModPathTest_JarredModUpgrade
- [x]  make UpgradeModPathTest_JarredModUpgradeCRImage
- [x]  make JlinkTest_RequiredMod
- [x]  make JlinkTest_AddModLimitMod
- [x]  make CpMpJlinkTest
- [x]  make JlinkPluginOptionsTest_GeneralOptionsTest
- [x]  make LayersTest
- [x]  make CLTest
- [x]  make CLTestImage
- [x]  make CLLoadTest
- [x]  make CLStressWithLayers
- [x]  make CLStressWithLayersCRI

It is necessary to execute all tests and if exist any execution error then report in this issue directly.

Related issue:
https://github.com/AdoptOpenJDK/openjdk-tests/issues/440

**Comment by smlambert** [comment]
@jabrena - I believe we can mark this as closed, can you confirm?

**Comment by jabrena** [comment]
Yes, I am going to close it

**Comment by jabrena** [comment]
I am going to review with Yakub, the testing process for next release OpenJDK13.
I will upgrade this issue, this weekend.

Juan Antonio

**Comment by jabrena** [comment]
For OpenJDK11, we didn´t finish completely but we didn´t receive any bad feedback from the community, so we are going to close it.

For OpenJDK13, we are going to review the testing support.
https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk13_build_ev3_linux_native/

Next week, me & @JakubVanek will review current build to do a clean process of old builds.
https://ci.adoptopenjdk.net/view/ev3dev/
