### ISSUE TITLE
Remove build parameter JVM_VERSION

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#521]
Originally JVM_VERSION( openjdk8, openjdk8-openj9, etc.) is a main path option of openjdk-api binary query https://github.com/AdoptOpenJDK/openjdk-api/blob/master/README.v1. Corresponding setting JVM_VERSION as a build parameter is reasonable. Now V2 api updated to use use openjdk version and openjdk_impl instead. 

In the TestKitGen openjdk version and openjdk_impl (namely java_versio, impl) are required variables, while JVM_VERSION is a generated variable based on java_version and impl.

To make the story simple and consistent I'd like to remove this parameter and corresponding set openjdk version and impl as required build parameters. Besides we are in the process of using generic jenkinsfile (not individual ones for different openjdk version 8,9,10)(https://github.com/AdoptOpenJDK/openjdk-tests/pull/483), which also request openjdk version is a required build parameter.

**Comment by sophia-guo** [comment]
Personal build is an example https://github.com/AdoptOpenJDK/openjdk-tests/pull/522  https://github.com/AdoptOpenJDK/openjdk-tests/pull/519

**Comment by sophia-guo** [comment]
just notice https://github.com/AdoptOpenJDK/openjdk-tests/pull/483 is using JVM_VERSION to get java version.

**Comment by llxia** [comment]
getJavaVersionFromJvmVersion() is not used.
Currently, user needs to provide JAVA_VERSION for running generic jenkinsfile.

**Comment by sophia-guo** [comment]
JAVA_VERSION is set per openjdk version Jenkinsfile. Current job will need to provide JAVA_IMPL. However if we plan to use generic jenkinsfile job will also need to provide JAVA_VERSION. Both will need to update jenkinsjob parameters I'd like to do it at once. 

@ShelleyLambert #483 planed to use JVM_VERSION to get java version though it's not used now. What's your opinion about add JAVA_VERSION and JAVA_IMPL as build parameters?

**Comment by smlambert** [comment]
Fixed by #522 and #523
