### ISSUE TITLE
"unable to establish ssl connectios" i run this scripe 'wget  --no-check-certificate http://www.example.com/download/111' on metasploitable 2 and i have error like this

### ISSUE THREAD

**Issue by phonemyatnaing** [AdoptOpenJDK/openjdk-tests#527]
wget --no-check-certificate http://www.example.com/download/1111
--15:17:44--  http://www.example.com/download/1111
           => `1111'
Resolving www.example.co... 192.182.119.1
Connecting to www.example.com| 192.182.119.1|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.exanple.com/download/1111 [following]
--15:17:44--  https://www.example.com/download/1111
           => `1111'
Connecting to www.example.com| 192.182.119.1|:443... connected.
Unable to establish SSL connection.

**Comment by smlambert** [comment]
Can you provide more context?  What test category are you trying to run?  

Please share the entire output of the test suite prior to failure.  Thanks!

**Comment by smlambert** [comment]
@phonemyatnaing - are you able to share some details on what tests you were trying to run?

**Comment by phonemyatnaing** [comment]
Upload an icon on the virtual dictator metasploitable 2 onto I bufferoverflow method and test entered its terminal I've a script file to download with wget such error o
Sorry For Late

**Comment by smlambert** [comment]
Closing as wont fix, not enough info.
