### ISSUE TITLE
Add TomEE Eclipse MicroProfile TCK to external test build

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#535]
We will enable the [Apache TomEE](http://tomee.apache.org/) Eclipse MicroProfile TCK tests to external test build. 

TomEE comes with a set of [MicroProfile TCK tests](https://github.com/apache/tomee/tree/master/tck/microprofile-tck) that we should be able to run.

**Comment by smlambert** [comment]
Potentially related: https://github.com/AdoptOpenJDK/openjdk-build/issues/245

There has been discussion about jfx builds at Adopt in the build slack channel, though far enough back that there is no archive of it.   Worth finding out where that effort is at.

**Comment by Mesbah-Alam** [comment]
@smlambert - thanks for the info. I'll keep an eye on that issue. Meanwhile I'm trying find out whether TomEE really does have a dependency on JavaFX via interaction with the TomEE community-- one answer I have received so far is "no". I need more info.

**Comment by smlambert** [comment]
This can be closed via https://github.com/AdoptOpenJDK/openjdk-tests/pull/1118
