### ISSUE TITLE
Add geode into open source packages testing

### ISSUE THREAD

**Issue by mamatha-jv** [AdoptOpenJDK/openjdk-tests#543]
This issue is opened to track the process of adding **geode** into open source packages testing at https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/thirdparty_containers

Refer issue #172 for more details.

**Comment by Mesbah-Alam** [comment]
@mamatha-jv : Just an fyi, we should make the same change for this PR as was made in the `Jenkins` test -- which is adding a `docker cp` step in the command line to copy the junit xml reports out of the docker container & into the host machine's workspace. This allows the Jenkins reporting plugin to generate test reports at the end of the test build. Here's the PR for the Jenkins test change that can be taken as example: https://github.com/AdoptOpenJDK/openjdk-tests/pull/537/files. 

So, When you run the geocode tests in your local, find out where it generates the xml junit reports and use that path in the `docker cp` command in playlist.xml. (Tip, when you create the Jenkins scripts for hbsase, start off by making a copy of the "jenkins" folder - which already has the change - and add your updates  on top.)

**Comment by smlambert** [comment]
Is this issue being worked?  If not, I will suggest we close it (leaving the app in the list at #172), until someone is actually working on it.

**Comment by smlambert** [comment]
I will close for now and keep geode in the #172 list.
