### ISSUE TITLE
Define common variable for jck tests to reduce duplication

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#548]
The only difference between all jck testcases is `-test-args`. Apply some DRY in existing jck.mk to avoid bunch of duplication.

The benefit is #477 would be one variable change in jck.m instead of updating all testcases with the commandline args `concurrency=cpus`

**Comment by smlambert** [comment]
FYI @Mesbah-Alam may be worth doing, if not we should consider closing this as won't fix.

**Comment by Mesbah-Alam** [comment]
I'll give this a try.

**Comment by Mesbah-Alam** [comment]
We may factor out the common portion of the JCK command line into a template and use that inn the playlist. Tried it wit hone target and it seems to be working. 

https://github.com/AdoptOpenJDK/openjdk-tests/compare/master...Mesbah-Alam:apply-DRY-technique-in-jck-playlist?expand=1

Test_grinder/job/Grinder/6228/console

(Change to jck/build.xml is just for fast debugging-- it won't be included in the final PR).
