### ISSUE TITLE
Exclude and re-enable OpenJDK 10 tests due to native test image not available to test build yet

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#549]
Some tests of test/jdk and test/hotspot need jdk test native library, which has to be generated at build time of the test jdk by invoking "make test-image"

Due to the missing test-image from build we have to disable those tests first and when  AdoptOpenJDK/openjdk-build#248 resolved to re-enable those tests. When re-enable it we need to update the command with extra option `-nativepath:{location of the jdk test native library}`

- [x] exclude tests https://github.com/AdoptOpenJDK/openjdk-tests/pull/551

**Comment by smlambert** [comment]
@sophia-guo, can you please link to the build issue that will resolve this (or raise one if there is not an open one yet)?

**Comment by sophia-guo** [comment]
Yes, related with https://github.com/AdoptOpenJDK/openjdk-build/issues/248

**Comment by sophia-guo** [comment]
Close as it's fixed in https://github.com/AdoptOpenJDK/openjdk-build/issues/248
