### ISSUE TITLE
system test on openjdk10 hotspot macos get compiling error.

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#554]
/Users/jenkins/workspace/openjdk10_hs_systemtest_x86-64_macos/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:486: Execute failed: java.io.IOException: Cannot run program "${java8_bindir}/java" (in directory "/Users/jenkins/workspace/openjdk10_hs_systemtest_x86-64_macos/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build"): error=2, No such file or directory

https://ci.adoptopenjdk.net/view/Test_system/job/openjdk10_hs_systemtest_x86-64_macos/120/console

**Comment by Mesbah-Alam** [comment]
`java8_bindir` gets set fine on macos when it is JDK08 : https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_x86-64_macos/122/consoleFull  

It is failing on JDK10.

**Comment by Mesbah-Alam** [comment]
The issue is caused because of the fact that the JDK used in the job is not a full SDK but only a 'jre' that doesn't contain `javac` executable. 

Logging into `macos1010-x64-2`, I see: 

```
/Users/jenkins/workspace/openjdk10_hs_systemtest_x86-64_macos/openjdkbinary/j2sdk-image/bin
DXU773:bin jenkins$ ls
appletviewer    java            jrunscript      orbd            rmid            servertool      unpack200
idlj            jjs             keytool         pack200         rmiregistry     tnameserv
```

@sophia-guo  - any idea why the job is using a macos Java 10 jre and not the full sdk?

**Comment by smlambert** [comment]
Does systemtest still use whatever is set for JAVA_HOME ? Or do we use the JDK under test to compile test material?

All the machines should have a variety of jdks available for use, but if a jdk10 one is not present, you should check if there is already an openjdk-infrastructure issue for it ([boot jdk issues](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues?utf8=%E2%9C%93&q=is%3Aissue+boot+jdk)), if not create one.

**Comment by Mesbah-Alam** [comment]
Systemtest still uses JAVA_HOME, so it expects it to point to the JDK under test. For this failing case, it seems that we are downloading the macos java 10 jre, instead of the full SDK, and placing it under the the location where we'd normally place the SDK under test, e.g. `/Users/jenkins/workspace/openjdk10_hs_systemtest_x86-64_macos/openjdkbinary/`.

**Comment by sophia-guo** [comment]
All the build consume both jre and jdk .

15:15:17 unzip file: OpenJDK10U-jre_x64_mac_hotspot_2018-09-12-06-01.tar.gz ...
15:15:18 unzip file: OpenJDK10U_x64_mac_hotspot_2018-09-12-06-01.tar.gz ...

**Comment by sophia-guo** [comment]
I did see both jars are under the workspace, however didn't see the unjarred folder.

**Comment by sophia-guo** [comment]
yes, created an issue in build https://github.com/AdoptOpenJDK/openjdk-build/issues/504

**Comment by johnoliver** [comment]
I assume the logic for extracting the tars is at:

https://github.com/AdoptOpenJDK/openjdk-tests/blob/fe6eea372cadfbf92c8c054ff829474c20705535/get.sh#L175

It does look like this code could be quite brittle as its way of relocating the jdk/jre is to list all of the files in the current directory (`./openjdkbinary/`) and move them based on their name (if I am interpreting that script correctly).

Note on your failed run you got:

```
14:15:17 get jdk binary...
14:15:17 mkdir: openjdkbinary: File exists
```

So that directory was not empty before you started, so anything that was already in there will get listed and moved again.

Does that dir get wiped out between runs? My guess, is there was stuff already there and you are seeing a dir structure that has been built up by multiple runs listing and relocating that dir

**Comment by Mesbah-Alam** [comment]
I am not sure what exactly `openjdkbinary: File exists` message entails, but it does not prove no workspace clean up was done prior to build start. 

The last [openjdk10_hs_systemtest_x86-64_macos](https://ci.adoptopenjdk.net/view/Test_system/job/openjdk10_hs_systemtest_x86-64_macos/) build was run today, on `Sep 13, 2018 3:11 PM` . And it was run on the same machine as the [previous build](https://ci.adoptopenjdk.net/view/Test_system/job/openjdk10_hs_systemtest_x86-64_macos/120/) --  `macos1010-x64-2: {ip: 74.80.250.173, user: admin} `

Looking inside the workspace, the openjdkbinary directory for the latest build was indeed created on the day that build was run, Sept 13th - 

```
/Users/jenkins/workspace/openjdk10_hs_systemtest_x86-64_macos
DXU773:openjdk10_hs_systemtest_x86-64_macos jenkins$ ls -la
total 0
drwxr-xr-x   5 jenkins  staff  170 Sep 13 06:14 .
drwxr-xr-x  24 jenkins  staff  816 Sep 13 07:21 ..
drwxr-xr-x   5 jenkins  staff  170 Sep 13 06:14 jvmtest
drwxr-xr-x  21 jenkins  staff  714 Sep 13 06:14 openjdk-tests
drwxr-xr-x   5 jenkins  staff  170 **Sep 13 06:14** openjdkbinary
```

This suggests the workspace clean up is happening as expected after all.

**Comment by sophia-guo** [comment]
I believe we have talked about the naming convention about the jre image @sxa555  https://github.com/AdoptOpenJDK/openjdk-tests/issues/417

https://github.com/AdoptOpenJDK/openjdk-build/pull/331. Tests assume that jre will be named as `jre*version*`. Now seems jre image naming is updated to `jdk-*<version>*-jre`.  If that's the case we will need to update test script to support this change. @karianna Could you please confirm this?

**Comment by karianna** [comment]
Paging @johnoliver

**Comment by sophia-guo** [comment]
Workspace is cleaned up for each build is running. The dir openjdkbinary is created when we grab the sdk from upstream. The message`openjdkbinary: File exists` should not affect following steps, which I will move it to the correct step to stop the confusion.

**Comment by johnoliver** [comment]
I would try not to be dependent on that the name of the dir inside the tar is, i.e use:

```
tar xpzf - --strip-components=2 -C "$JDK_DIR"
```
An example being:
```
wget -q -O - "https://api.adoptopenjdk.net/v2/binary/releases/openjdk10?os=linux&release=latest&arch=x64" | tar xpzf - --strip-components=2 -C "./a-jdk-dir"
```

**Comment by sophia-guo** [comment]
@johnoliver Do you happen to know if unzip have similar option? Or I can google :) thanks.

**Comment by johnoliver** [comment]
you also have the unzip that may be harder as it does not have strip support. I have tested:

```
dest=TargetJDKDir; 
zipFile=../foo.zip;

rm -rf "./$dest"; 
mkdir -p "$dest"; 
unzip -d "$dest" $zipFile && f=("$dest"/*) && mv "$dest"/*/* "$dest" && rmdir "${f[@]}"
```

Shamelessly stolen from: https://superuser.com/questions/518347/equivalent-to-tars-strip-components-1-in-unzip

**Comment by sophia-guo** [comment]
Though the naming convention would be requested to jdk/jre/test tar name as we need to unpack different tar to specific folder.

**Comment by Mesbah-Alam** [comment]
Do we need to download the JRE? Is it possible to download only the full SDK?

**Comment by sophia-guo** [comment]
Yes, we do. We would support smoke tests for JRE.
