### ISSUE TITLE
Improve the logic of support different Images from different resources

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#557]
The current logic of supporting different images is quite brittle, which relocates the jdk/jre/test by the tar directory name. It could fail whenever the image tar/zip creation changes or the image has different naming convention.

**Comment by sophia-guo** [comment]
Suggested by @johnoliver instead of dependent on the name of the dir inside the jar we can use strip option to untar the image to specific location. The problem is we need to support jdk/jre/test images at same time and support wherever those image resources are from(adopt build image, openj9 build image, IBM internal build image, developer personal build images, etc. ). If we'd like to un-tar different images to specific location we have to either depending on the dir name or tar file name to differentiate those images. Specific to IBM internal SDK jar there is no jdk or jre information in its name.

**Comment by smlambert** [comment]
Is this issue still valid @sophia-guo ?

**Comment by sophia-guo** [comment]
We are still using the same suppose but naming convention is established. So this should not be an issue any more. Close it.
