### ISSUE TITLE
openjdk11_j9_openjdktest_s390x_linux build failed for incompleted SDK download

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#561]
openjdk11_j9_openjdktest_s390x_linux build failed for incomplete SDK download. Test machine is test-marist-ubuntu1604-s390x-1. Downloading the JDK from [build job artifacts](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11/job/jdk11-linux-s390x-openj9/) or  [pipeline job](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/) on this machine always failed.

**Comment by sophia-guo** [comment]
Note downloading on my local machine works fine.

**Comment by sxa555** [comment]
Latest build 9 looks ok  to me at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11/job/jdk11-linux-s390x-openj9/

**Comment by sxa555** [comment]
Failing log: https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_s390x_linux/
```
15:13:43 get jdk binary...
15:13:43 curl -OLJks  https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11/job/jdk11-linux-s390x-openj9/6/artifact/workspace/target/OpenJDK11_s390x_linux_openj9_2018-09-15-14-31.tar.gz
15:14:46 $ ssh-agent -k
15:14:46 unset SSH_AUTH_SOCK;
15:14:46 unset SSH_AGENT_PID;
15:14:46 echo Agent pid 52028 killed;
15:14:46 Failed to retrieve https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11/job/jdk11-linux-s390x-openj9/6/artifact/workspace/target/OpenJDK11_s390x_linux_openj9_2018-09-15-14-31.tar.gz, exiting
``

**Comment by sophia-guo** [comment]
Didn't see again assuming it's fixed. Close it.
