### ISSUE TITLE
Update JAVA_VERSION to JDK_VERSION

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#563]
Update JAVA_VERSION to JDK_VERSION, which is in plan

- [x] update compile jobs https://github.com/AdoptOpenJDK/openjdk-tests/pull/564

- [x] update playlists

- [x] update jenkinsfile

- [x] update test job passing in parameters (this may not necessary if we later use javabin to get jdk_version

**Comment by sophia-guo** [comment]
Test build jobs failed for upstream update JAVA_VERSION to JDK_VERSION
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/28/console

**Comment by smlambert** [comment]
I believe this has been completed, @sophia-guo can you confirm?

**Comment by smlambert** [comment]
#869 is it a dup of this?

**Comment by llxia** [comment]
> #869 is it a dup of this?

yes, it is a dup. There is still some cleanup to do. For example:
https://github.com/AdoptOpenJDK/openjdk-tests/blob/a98dd20ccd3bf6dcc9af00b4e0b0123435909cdb/buildenv/jenkins/JenkinsfileBase#L45

**Comment by sophia-guo** [comment]
@llxia will close #869. We'll keep this to track the leftover cleanup jobs.

**Comment by llxia** [comment]
@LongyuZhang Could you help on this issue if you have time? Thanks

**Comment by llxia** [comment]
Pending on https://github.com/eclipse/openj9/pull/6707

**Comment by sophia-guo** [comment]
Done.
