### ISSUE TITLE
Update hotspot jtreg tests for openjdk10 and up

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#565]
Hotspot jtreg tests have different subset group and jtreg tests structure. Need to update this to work for openjdk10 and up.

- [x]  update JDK10 and above hotspot jtreg tests root folders #568 

- [ ] update related hotspot jtreg subset tests

**Comment by smlambert** [comment]
@sophia-guo - is this issue now completed?

**Comment by sophia-guo** [comment]
Not yet. Due to the big difference between https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/test/hotspot/jtreg/TEST.groups and https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/hotspot/test/TEST.groups we will need developers' help to define which group would be sanity or extended. A comprehensive run will be needed to see which tests will need native library( as native library are not available, need to be excluded). A recent search also shows running tests with native library have changed. Need to double check what's the new method to run those tests(https://download.java.net/openjdk/testresults/10/docs/howtoruntests.html doesn't work any more, not sure if it keeps the same way as  -nativepath:{location of the jdk test native library}) .

**Comment by karianna** [comment]
> Not yet. Due to the big difference between https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/test/hotspot/jtreg/TEST.groups and https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/hotspot/test/TEST.groups we will need developers' help to define which group would be sanity or extended. A comprehensive run will be needed to see which tests will need native library( as native library are not available, need to be excluded). A recent search also shows running tests with native library have changed. Need to double check what's the new method to run those tests(https://download.java.net/openjdk/testresults/10/docs/howtoruntests.html doesn't work any more, not sure if it keeps the same way as -nativepath:{location of the jdk test native library}) .

The quality-discuss mailing list over on OpenJDK will be a good place to start.

**Comment by smlambert** [comment]
I had some conversations last week at the OJDK workshop, will try to revisit this shortly.

**Comment by smlambert** [comment]
I believe this has been addressed by the move to make tier1 == sanity.openjdk, so closing.
