### ISSUE TITLE
Enable JDK11 test build

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#566]
adding build tests on different platforms for openj9
- [x] linux x86-64
- [x] ppc64le
- [x] s390x
- [x] windows failed for #474 
- [x] linuxXL

**Comment by sophia-guo** [comment]
Should we also enable test build for hotspot, which is helpful to compare openj9's failures. The only concern is machine resources. I will setup all builds and only enable one on linux86_64, which helps triage.

**Comment by karianna** [comment]
@sophia-guo Absolutely!
