### ISSUE TITLE
Support uploading test logs onto artifactory

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#569]
We should update Jenkins file to support uploading test logs onto artifactory if the flag is set. In some Jenkins, disk space is limited and we do not have enough space to keep all test logs on the master.

**Comment by karianna** [comment]
Is artifactory a good searchable data source?

**Comment by llxia** [comment]
Test logs (or test output) are in gz format. It cannot be searched directly.
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk10_hs_openjdktest_ppc64le_linux/lastSuccessfulBuild/artifact/openjdk_regression_test_output.tar.gz

We can use Artifactory to store the binary data. https://jfrog.com/artifactory/

This issue is opened to provide an extra option to use Artifactory. By default, Artifactory is not used. Nothing in AdoptOpenJDK Jenkins test builds will change.

**Comment by llxia** [comment]
Artifactory seems to have powerful search feature: https://www.jfrog.com/confluence/display/RTF/Searching+for+Artifacts
