### ISSUE TITLE
Add step in Kafka tests to copy junit report xml to host machine for jenkins reporting 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#574]
Currently failures in Kafka tests do not show up in the list of failures in the external test build https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_externaltest_x86-64_linux/179/testReport/

We need to add a step in Kafka tests to copy junit report xml to host machine for jenkins reporting. 

**Details**: 

We should make the same change for  Kafka tests as was made in the Jenkins test -- which is adding a `docker cp` step in the command line to copy the junit xml reports out of the docker container & into the host machine's workspace. This allows the Jenkins reporting plugin to generate test reports at the end of the test build. 

Here's the PR for the Jenkins test change that can be taken as example: https://github.com/AdoptOpenJDK/openjdk-tests/pull/537/files.

So, we need to run Kafka tests in a local machine, find out where it generates the xml junit reports and use that path in the `docker cp` command in playlist.xml.

**Comment by Mesbah-Alam** [comment]
@suman-mitra - since you added the Kafka tests originally, I'm assigning this issue to you. Please let me know if you have any question.

**Comment by smlambert** [comment]
Closing this in favour of https://github.com/AdoptOpenJDK/openjdk-tests/issues/976
