### ISSUE TITLE
Add step in Tomcat tests to copy junit report xml to host machine for jenkins reporting

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#578]
Currently failures in Tomcat tests do not show up in the list of failures in the external test build https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_externaltest_x86-64_linux/179/testReport/

We need to add a step in Tomcat tests to copy junit report xml to host machine for jenkins reporting. 

**Details**: 

We should make the same change for Tomcat tests as was made in the Jenkins test -- which is adding a `docker cp` step in the command line to copy the junit xml reports out of the docker container & into the host machine's workspace. This allows the Jenkins reporting plugin to generate test reports at the end of the test build. 

Here's the PR for the Jenkins test change that can be taken as example: https://github.com/AdoptOpenJDK/openjdk-tests/pull/537/files.

So, we need to run Tomcat tests in a local machine, find out where it generates the xml junit reports and use that path in the `docker cp` command in playlist.xml.

**Comment by Mesbah-Alam** [comment]
@chandrams - since you added the Kafka tests originally, I'm assigning this issue to you. Could you please take care of it?

**Comment by karianna** [comment]
@Mesbah-Alam You may find creating a task list in a single issue will save you some virtual paperwork :-)

**Comment by smlambert** [comment]
Closing this in favour of https://github.com/AdoptOpenJDK/openjdk-tests/issues/976
