### ISSUE TITLE
Grinder job failed to download the nightly build and extract it

### ISSUE THREAD

**Issue by chandrams** [AdoptOpenJDK/openjdk-tests#581]
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/159/console

12:24:42 curl -OLJks  https://api.adoptopenjdk.net/v2/binary/nightly/openjdk8?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk
12:24:42 unzip file: openjdk8?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk ...
12:24:42 
12:24:42 gzip: openjdk8?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk: not in gzip format
12:24:42 tar: This does not look like a tar archive
12:24:42 tar: Exiting with failure status due to previous errors
12:24:42 ls: cannot access '*/': No such file or directory
12:24:42 chmod: cannot access 'j2sdk-image': No such file or directory

**Comment by sophia-guo** [comment]
There is no jdk available. Error message should be updated. see #582 .  However we have talked about the API should always refer the latest to be latest available( not only limited to the query date as latest). We have an issue opened for this and resolved. Need to double check.

**Comment by smlambert** [comment]
Yes, I asked @chandrams to raise an issue.  If we raised an openjdk-api issue then good.  I see several comments from others about wanting 'latest' sdk.  @sophia-guo, if you find the issue that was opened, please share the link in this issue.  Thanks!

**Comment by johnoliver** [comment]
The error message returned by the api is:

```
Multiple binaries match request: 

[
   {
      "checksum_link" : "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2018-09-24-14-37/OpenJDK8U_x64_linux_openj9_2018-09-24-14-37.tar.gz.sha256.txt",
      "binary_type" : "jdk",
      "os" : "linux",
      "architecture" : "x64",
      "binary_link" : "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2018-09-24-14-37/OpenJDK8U_x64_linux_openj9_2018-09-24-14-37.tar.gz",
      "version" : "8",
      "openjdk_impl" : "openj9",
      "binary_name" : "OpenJDK8U_x64_linux_openj9_2018-09-24-14-37.tar.gz",
      "binary_size" : 88643601
   },
   {
      "architecture" : "x64",
      "os" : "linux",
      "checksum_link" : "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2018-09-24-14-37/OpenJDK8U_x64_linux_openj9_linuxXL_2018-09-24-14-37.tar.gz.sha256.txt",
      "binary_type" : "jdk",
      "binary_size" : 88622324,
      "binary_name" : "OpenJDK8U_x64_linux_openj9_linuxXL_2018-09-24-14-37.tar.gz",
      "openjdk_impl" : "openj9",
      "version" : "8",
      "binary_link" : "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2018-09-24-14-37/OpenJDK8U_x64_linux_openj9_linuxXL_2018-09-24-14-37.tar.gz"
   }
]
```

So the issue is it does not know what to redirect you to as there are multiple binaries that match the query.  The real issue is that the api does not have any way to tell the difference between `linuxXL` and regular builds. This is actually: https://github.com/AdoptOpenJDK/openjdk-api/issues/74

**Comment by johnoliver** [comment]
hopefully you can fix this now by adding `heap_size=normal` (or large if you want a xl build) to your api query

**Comment by smlambert** [comment]
Yes, so minimally, we will need an update to the test script ( fyi @sophia-guo / @llxia ), https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/get.sh#L145 (and to add logic to translate the SPEC parameter to build the correct download_url).

**Comment by llxia** [comment]
PR #599 added heap_size to nightly url

**Comment by smlambert** [comment]
thanks @llxia !

@chandrams - this should correct the issue you encountered, please confirm when you get the chance  :)

**Comment by llxia** [comment]
@chandrams  Sorry for the late reply, I was on vacation. Do you still encounter any issue with Grinder?

**Comment by chandrams** [comment]
@llxia No problem. I spoke to Mesbah and understood that personal build is replaced with grinder now. Resolving this issue. Thanks for the fix.
