### ISSUE TITLE
Include system test in thirdparty containers

### ISSUE THREAD

**Issue by chandrams** [AdoptOpenJDK/openjdk-tests#583]
Include system test in third party container testing
- Include dockerfile and script to clone stf, adopt/openjdk-systemtest and eclipse/openj9-systemtest
- Build.xml and playlist.xml
- Ensure results are copied to host
- Results use TAP format, this might have an implication on overall report for external tests as most of them use junit

**Comment by chandrams** [comment]
Tried running the mauve tests but they fail, will create a separate issue to fix this. 

LT  Test failed:
LT  java.lang.ClassNotFoundException: gnu.testlet.java.util.AbstractCollection.AcuniaAbstractCollectionTest
LT      at java.lang.Class.forNameImpl(Native Method)
LT      at java.lang.Class.forName(Class.java:339)
LT      at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:50)
LT      at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
LT      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT      at java.lang.Thread.run(Thread.java:813)
LT  <<<
LT
LT  07:35:33.242 - Test failed. Details recorded in execution log.
LT  07:35:33.565 - Test failed. Details recorded in execution log.
LT  07:35:34.694 - Thread completed. Suite=0 thread=0
LT  07:35:34.781 - Load test completed
LT  07:35:34.782 -   Ran     : 3864
LT  07:35:34.782 -   Passed  : 3861
LT  07:35:34.782 -   Failed  : 3

Include NioLoadTest to test my changes submitted a personal build

**Comment by Mesbah-Alam** [comment]
Copy-pasting from slack for records.. 

The issue that was causing failure in compilation in systemtestes inside your docker container has been fixed  (https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/186)). See this Grinder for a successful run of docker based system test:  https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/351/console

**Comment by chandrams** [comment]
Closing this issues as the initial set of system tests to run in docker containers has been added.
