### ISSUE TITLE
Elasticsearch test 'hangs' and gets terminated by timeout 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#586]
Elasticsearch test seems to get stuck for a long time and subsequently causes the external test build to be terminated by timeout. 

We should revisit the set of Elasticsearch tests we are running and either find out why the test is getting stuck or run a separate set of tests which are more stable. 

**JDK version**
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-201809230328-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```
**Build link**
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_externaltest_x86-64_linux/182/console
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_externaltest_x86-64_linux/183/console
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_externaltest_x86-64_linux/184/console

**Comment by suman-mitra** [comment]
will take a look

**Comment by suman-mitra** [comment]
I tried to run with  below OpenJDK  version:-

openjdk version "1.8.0-adoptopenjdk"
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_08_24_11_23-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Steps :-
git clone https://github.com/elastic/elasticsearch.git
cd elasticsearch
git checkout v6.1.3
gradle assemble
./gradlew test --> Test failed with "java.net.BindException: Address already in use"

This could be a machine issue. I will try with a different machine and the build mentioned by you

**Comment by suman-mitra** [comment]
I tried with below OpenJDK-Hotspot build and executed the same steps mentioned in the above command manually. Everything worked fine for me.

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-201809250329-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)


Elasticsearch Build and  test both were successful.

> Task :distribution:tools:plugin-cli:test
==> Test Info: seed=B8FCE87DB416FBDC; jvms=4; suites=4
==> Test Summary: 4 suites, 228 tests, 8 ignored (8 assumptions)

BUILD SUCCESSFUL in 39m 56s
307 actionable tasks: 307 executed

**Comment by Mesbah-Alam** [comment]
The "hang" is not reproducible using grinder: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/188/consoleFull 

Grinder ran on `test-packet-ubuntu1604-x64-2` 

All 3 builds in which the hang was detected ran on `test-packet-ubuntu1604-x64-1` . 

It could be a machine issue. I'm gonna run the grinder again on `test-packet-ubuntu1604-x64-1` to see if I can reproduce the hang there.

**Comment by smlambert** [comment]
I have not seen this lately, so will close for now.  Am raising a new issue for the elasticsearch failures that are happening now.
