### ISSUE TITLE
jdk_tools: sun/jvmstat/monitor/MonitoredVm/CR6672135.java fails (process not found)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#59]
This test may be trying to attach to a process it can not find,  java.lang.IllegalArgumentException: Process not found, output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull: 

21:32:19 HOME=/home/jenkins \
21:32:19 LANG=en_US.UTF-8 \
21:32:19 PATH=/bin:/usr/bin \
21:32:19     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/javac \
21:32:19         -J-ea \
21:32:19         -J-esa \
21:32:19         -J-Xmx512m \
21:32:19         -J-Dtest.class.path.prefix=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/sun/jvmstat/monitor/MonitoredVm:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -J-Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -J-Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -J-Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -J-Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -J-Dtest.vm.opts='-ea -esa -Xmx512m' \
21:32:19         -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
21:32:19         -J-Dtest.compiler.opts= \
21:32:19         -J-Dtest.java.opts= \
21:32:19         -J-Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
21:32:19         -J-Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
21:32:19         -J-Dtest.timeout.factor=4.0 \
21:32:19         -d /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -sourcepath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/jvmstat/monitor/MonitoredVm:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/sun/jvmstat/monitor/MonitoredVm:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar \
21:32:19         -XDignore.symbol.file=true /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/jvmstat/monitor/MonitoredVm/CR6672135.java
21:32:19 
21:32:19 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Error: Test failed
21:32:19 REASON: User specified action: run main/othervm -XX:+UsePerfData CR6672135 
21:32:19 TIME:   0.859 seconds
21:32:19 messages:
21:32:19 command: main -XX:+UsePerfData CR6672135
21:32:19 reason: User specified action: run main/othervm -XX:+UsePerfData CR6672135 
21:32:19 Mode: othervm [/othervm specified]
21:32:19 elapsed time (seconds): 0.859
21:32:19 configuration:
21:32:19 STDOUT:
21:32:19 STDERR:
21:32:19 java.lang.Error: Test failed
21:32:19 	at CR6672135.main(CR6672135.java:60)
21:32:19 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:32:19 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:32:19 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:32:19 	at java.lang.reflect.Method.invoke(Method.java:498)
21:32:19 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
21:32:19 	at java.lang.Thread.run(Thread.java:748)
21:32:19 Caused by: sun.jvmstat.monitor.MonitorException: 20864 not found
21:32:19 	at sun.jvmstat.perfdata.monitor.protocol.local.PerfDataBuffer.<init>(PerfDataBuffer.java:84)
21:32:19 	at sun.jvmstat.perfdata.monitor.protocol.local.LocalMonitoredVm.<init>(LocalMonitoredVm.java:68)
21:32:19 	at sun.jvmstat.perfdata.monitor.protocol.local.MonitoredHostProvider.getMonitoredVm(MonitoredHostProvider.java:77)
21:32:19 	at sun.jvmstat.perfdata.monitor.protocol.local.MonitoredHostProvider.getMonitoredVm(MonitoredHostProvider.java:67)
21:32:19 	at CR6672135.main(CR6672135.java:53)
21:32:19 	... 6 more
21:32:19 Caused by: java.lang.IllegalArgumentException: Process not found
21:32:19 	at sun.misc.Perf.attach(Native Method)
21:32:19 	at sun.misc.Perf.attachImpl(Perf.java:270)
21:32:19 	at sun.misc.Perf.attach(Perf.java:200)
21:32:19 	at sun.jvmstat.perfdata.monitor.protocol.local.PerfDataBuffer.<init>(PerfDataBuffer.java:64)
21:32:19 	... 10 more
21:32:19 
21:32:19 JavaTest Message: Test threw exception: java.lang.Error: Test failed
21:32:19 JavaTest Message: shutting down test
21:32:19 
21:32:19 STATUS:Failed.`main' threw exception: java.lang.Error: Test failed
21:32:19 rerun:
21:32:19 HOME=/home/jenkins \
21:32:19 LANG=en_US.UTF-8 \
21:32:19 PATH=/bin:/usr/bin \
21:32:19 CLASSPATH=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/sun/jvmstat/monitor/MonitoredVm:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/jvmstat/monitor/MonitoredVm:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
21:32:19     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
21:32:19         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/sun/jvmstat/monitor/MonitoredVm:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/sun/jvmstat/monitor/MonitoredVm \
21:32:19         -Dtest.vm.opts='-ea -esa -Xmx512m' \
21:32:19         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
21:32:19         -Dtest.compiler.opts= \
21:32:19         -Dtest.java.opts= \
21:32:19         -Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
21:32:19         -Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
21:32:19         -Dtest.timeout.factor=4.0 \
21:32:19         -ea \
21:32:19         -esa \
21:32:19         -Xmx512m \
21:32:19         -XX:+UsePerfData \
21:32:19         com.sun.javatest.regtest.agent.MainWrapper /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/sun/jvmstat/monitor/MonitoredVm/CR6672135.d/main.0.jta
21:32:19 
21:32:19 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Error: Test failed

**Comment by akolarkunnu** [comment]
It is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8062938.

**Comment by smlambert** [comment]
Closing as now listed in summary issue #345
