### ISSUE TITLE
Fix mauve system test CNFE failures

### ISSUE THREAD

**Issue by chandrams** [AdoptOpenJDK/openjdk-tests#607]
From issue #583
Some of the mauve tests failed. Found below issue, yet to look at the complete logs for all the failures. 

LT Test failed:
LT java.lang.ClassNotFoundException: gnu.testlet.java.util.AbstractCollection.AcuniaAbstractCollectionTest
LT at java.lang.Class.forNameImpl(Native Method)
LT at java.lang.Class.forName(Class.java:339)
LT at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:50)
LT at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
LT at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT at java.lang.Thread.run(Thread.java:813)
LT <<<
LT
LT 07:35:33.242 - Test failed. Details recorded in execution log.
LT 07:35:33.565 - Test failed. Details recorded in execution log.
LT 07:35:34.694 - Thread completed. Suite=0 thread=0
LT 07:35:34.781 - Load test completed
LT 07:35:34.782 - Ran : 3864
LT 07:35:34.782 - Passed : 3861
LT 07:35:34.782 - Failed : 3

Had a quick look and found that we are removing some of the class files (and the failure above is related to one such class file that has been removed) will need to remove this from the mauve inventory test list to fix this.

**Comment by chandrams** [comment]
@Mesbah-Alam - As discussed yest over slack, some of the class files that were intended to be removed for JDK11 have got removed for JDK8 too, resulting in CNFEs in Mauve tests.  Could you please fix this. Thanks.

**Comment by chandrams** [comment]
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/241/consoleFull

**Comment by Mesbah-Alam** [comment]
@chandrams - thanks for finding this issue. I am investigating. 

In your case, the JDK_VERSION=8, so the check in systemtest/build.xml should not delete the corba related files, yet it seems it is being removed for some reasons. I'll find out why.

**Comment by Mesbah-Alam** [comment]
**Note: I could not reproduce the issue running the mauve test directly (without Docker) : https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/256/console**

In the case above, the `delete-corba-files` target rightly ignores deleting the corba releated files when `JDK_VERSION=8`. Something seems not right in Chandrakala's case. More investigation needed.

**Comment by Mesbah-Alam** [comment]
CORBA related mauve tests have been removed. This issue should now be resolved. Note: We do have an open PR for mauve test failure on jdk11:  https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/97
