### ISSUE TITLE
Grinder build fails due to broken link for asm-7.0-beta-SNAPSHOT  

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#608]
```
04:22:33 downloading https://repository.ow2.org/nexus/content/repositories/snapshots/org/ow2/asm/asm/7.0-beta-SNAPSHOT/asm-7.0-beta-20180918.180157-14.jar
04:22:34 ERROR: downloading https://repository.ow2.org/nexus/content/repositories/snapshots/org/ow2/asm/asm/7.0-beta-SNAPSHOT/asm-7.0-beta-20180918.180157-14.jar failed, return code: 2048
04:22:34 makefile:76: recipe for target 'getdependency' failed
04:22:34 make: *** [getdependency] Error 8
```

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/209/console

**Comment by Mesbah-Alam** [comment]
This was recently fixed here: https://github.com/eclipse/openj9/issues/2995. It looks like it broke again. 

FYI... @renfeiw @sophia-guo

**Comment by smlambert** [comment]
Lan has done the change to merge our 2 Jenkinsfiles into 1, we have updated the internal Grinder job to use Jenkinsfilebase, but we need to update the Adopt Grinder / test_personal config itself to use it.

**Comment by Mesbah-Alam** [comment]
@ShelleyLambert : Yes, I just created a new [Grinder ](https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder2/) at Adopt where I mimicked the work done in the internal Grinder. I'll test it first before replacing the old Grinder with the new one:

**Comment by Mesbah-Alam** [comment]
@sophia-guo : One problem I see is that in the new grinder (internal) we do not have a field for `SPEC`. In this case, how do we specify values like `SPEC=linux_arm` in the new grinder?

**Comment by smlambert** [comment]
you do not need spec anymore, because you have JenkinsFile param

**Comment by sophia-guo** [comment]
yes,  by adding an extra parameter $jenkinsFilename SPEC will not be needed.

**Comment by Mesbah-Alam** [comment]
I understand. So, for case of `SPEC=linux_arm`, we simply pick `jenkinsFile=openjdk_aarch64_linux` for the grinder parameter.

**Comment by smlambert** [comment]
Yes you can look in the Jenkinsfile to be sure... as SPEC is defined in those files.
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_aarch64_linux#L14

**Comment by Mesbah-Alam** [comment]
witched `Grinder` at Adopt to using JenkinsfileBase: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/210/console

**Comment by smlambert** [comment]
Thanks Mesbah!

**Comment by Mesbah-Alam** [comment]
@ShelleyLambert - Welcome! 

Could you please delete the temp job called Grinder2 ? https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder2/

**Comment by smlambert** [comment]
will do
