### ISSUE TITLE
jdk_rmi: java/rmi/Naming/legalRegistryNames/LegalRegistryNames.java fails (MalformedURLException)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#61]
java/rmi/Naming/legalRegistryNames/LegalRegistryNames.java fails testing form: //test-packet-x64-ubuntu-16.04-1/MyName
with java.net.MalformedURLException: invalid authority: //test-packet-x64-ubuntu-16.04-1/MyName
20:34:18 	at java.rmi.Naming.intParseURL(Naming.java:330), output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

20:34:18 TEST: java/rmi/Naming/legalRegistryNames/LegalRegistryNames.java#id0
20:34:18 TEST JDK: /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../..
20:34:18 
20:34:18 ACTION: build -- Passed. All files up to date
20:34:18 REASON: User specified action: run build TestLibrary Legal LegalRegistryNames_Stub 
20:34:18 TIME:   0.0 seconds
20:34:18 messages:
20:34:18 command: build TestLibrary Legal LegalRegistryNames_Stub
20:34:18 reason: User specified action: run build TestLibrary Legal LegalRegistryNames_Stub 
20:34:18 elapsed time (seconds): 0.0
20:34:18 
20:34:18 ACTION: build -- Passed. All files up to date
20:34:18 REASON: Named class compiled on demand
20:34:18 TIME:   0.001 seconds
20:34:18 messages:
20:34:18 command: build LegalRegistryNames
20:34:18 reason: Named class compiled on demand
20:34:18 elapsed time (seconds): 0.001
20:34:18 
20:34:18 ACTION: main -- Failed. Execution failed: `main' threw exception: TestFailedException: TEST FAILED: Test failed
20:34:18 REASON: User specified action: run main LegalRegistryNames 
20:34:18 TIME:   1.109 seconds
20:34:18 messages:
20:34:18 command: main LegalRegistryNames
20:34:18 reason: User specified action: run main LegalRegistryNames 
20:34:18 Mode: othervm
20:34:18 elapsed time (seconds): 1.109
20:34:18 configuration:
20:34:18 STDOUT:
20:34:18 STDERR:
20:34:18 
20:34:18 Regression test for bug/rfe 4254808
20:34:18 
20:34:18 Starting registry on default port
20:34:18 
20:34:18 testing form: ///MyName
20:34:18 	form ///MyName OK
20:34:18 
20:34:18 testing form: //:1099/MyName
20:34:18 	form //:1099/MyName OK
20:34:18 
20:34:18 testing form: //127.0.0.1/MyName
20:34:18 	form //127.0.0.1/MyName OK
20:34:18 
20:34:18 testing form: //127.0.0.1:1099/MyName
20:34:18 	form //127.0.0.1:1099/MyName OK
20:34:18 
20:34:18 testing form: //localhost/MyName
20:34:18 	form //localhost/MyName OK
20:34:18 
20:34:18 testing form: //localhost:1099/MyName
20:34:18 	form //localhost:1099/MyName OK
20:34:18 
20:34:18 testing form: //test-packet-x64-ubuntu-16.04-1/MyName
20:34:18 java.net.MalformedURLException: invalid authority: //test-packet-x64-ubuntu-16.04-1/MyName
20:34:18 	at java.rmi.Naming.intParseURL(Naming.java:330)
20:34:18 	at java.rmi.Naming.parseURL(Naming.java:237)
20:34:18 	at java.rmi.Naming.rebind(Naming.java:171)
20:34:18 	at LegalRegistryNames.main(LegalRegistryNames.java:89)
20:34:18 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:34:18 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:34:18 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:34:18 	at java.lang.reflect.Method.invoke(Method.java:498)
20:34:18 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
20:34:18 	at java.lang.Thread.run(Thread.java:748)
20:34:18 	unexpected lookup or unbind exception for form: //test-packet-x64-ubuntu-16.04-1/MyNameinvalid authority: //test-packet-x64-ubuntu-16.04-1/MyName
20:34:18 
20:34:18 testing form: //test-packet-x64-ubuntu-16.04-1:1099/MyName
20:34:18 java.net.MalformedURLException: invalid authority: //test-packet-x64-ubuntu-16.04-1:1099/MyName
20:34:18 	at java.rmi.Naming.intParseURL(Naming.java:330)
20:34:18 	at java.rmi.Naming.parseURL(Naming.java:237)
20:34:18 	at java.rmi.Naming.rebind(Naming.java:171)
20:34:18 	at LegalRegistryNames.main(LegalRegistryNames.java:89)
20:34:18 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:34:18 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:34:18 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:34:18 	at java.lang.reflect.Method.invoke(Method.java:498)
20:34:18 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
20:34:18 	at java.lang.Thread.run(Thread.java:748)
20:34:18 	unexpected lookup or unbind exception for form: //test-packet-x64-ubuntu-16.04-1:1099/MyNameinvalid authority: //test-packet-x64-ubuntu-16.04-1:1099/MyName
20:34:18 
20:34:18 testing form: MyName
20:34:18 	form MyName OK
20:34:18 
20:34:18 testing form: /MyName
20:34:18 	form /MyName OK
20:34:18 
20:34:18 testing form: rmi:///MyName
20:34:18 	form rmi:///MyName OK
20:34:18 
20:34:18 testing form: rmi://:1099/MyName
20:34:18 	form rmi://:1099/MyName OK
20:34:18 
20:34:18 testing form: rmi://127.0.0.1/MyName
20:34:18 	form rmi://127.0.0.1/MyName OK
20:34:18 
20:34:18 testing form: rmi://127.0.0.1:1099/MyName
20:34:18 	form rmi://127.0.0.1:1099/MyName OK
20:34:18 
20:34:18 testing form: rmi://localhost/MyName
20:34:18 	form rmi://localhost/MyName OK
20:34:18 
20:34:18 testing form: rmi://localhost:1099/MyName
20:34:18 	form rmi://localhost:1099/MyName OK
20:34:18 
20:34:18 testing form: rmi://test-packet-x64-ubuntu-16.04-1/MyName
20:34:18 java.net.MalformedURLException: invalid authority: rmi://test-packet-x64-ubuntu-16.04-1/MyName
20:34:18 	at java.rmi.Naming.intParseURL(Naming.java:330)
20:34:18 	at java.rmi.Naming.parseURL(Naming.java:237)
20:34:18 	at java.rmi.Naming.rebind(Naming.java:171)
20:34:18 	at LegalRegistryNames.main(LegalRegistryNames.java:89)
20:34:18 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:34:18 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:34:18 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:34:18 	at java.lang.reflect.Method.invoke(Method.java:498)
20:34:18 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
20:34:18 	at java.lang.Thread.run(Thread.java:748)
20:34:18 	unexpected lookup or unbind exception for form: rmi://test-packet-x64-ubuntu-16.04-1/MyNameinvalid authority: rmi://test-packet-x64-ubuntu-16.04-1/MyName
20:34:18 
20:34:18 testing form: rmi://test-packet-x64-ubuntu-16.04-1:1099/MyName
20:34:18 java.net.MalformedURLException: invalid authority: rmi://test-packet-x64-ubuntu-16.04-1:1099/MyName
20:34:18 	at java.rmi.Naming.intParseURL(Naming.java:330)
20:34:18 	at java.rmi.Naming.parseURL(Naming.java:237)
20:34:18 	at java.rmi.Naming.rebind(Naming.java:171)
20:34:18 	at LegalRegistryNames.main(LegalRegistryNames.java:89)
20:34:18 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:34:18 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:34:18 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:34:18 	at java.lang.reflect.Method.invoke(Method.java:498)
20:34:18 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
20:34:18 	at java.lang.Thread.run(Thread.java:748)
20:34:18 	unexpected lookup or unbind exception for form: rmi://test-packet-x64-ubuntu-16.04-1:1099/MyNameinvalid authority: rmi://test-packet-x64-ubuntu-16.04-1:1099/MyName
20:34:18 TEST FAILED: Test failed
20:34:18 TestFailedException: TEST FAILED: Test failed
20:34:18 	at TestLibrary.bomb(TestLibrary.java:121)
20:34:18 	at TestLibrary.bomb(TestLibrary.java:124)
20:34:18 	at LegalRegistryNames.main(LegalRegistryNames.java:115)
20:34:18 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:34:18 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:34:18 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:34:18 	at java.lang.reflect.Method.invoke(Method.java:498)
20:34:18 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
20:34:18 	at java.lang.Thread.run(Thread.java:748)
20:34:18 
20:34:18 JavaTest Message: Test threw exception: TestFailedException: TEST FAILED: Test failed
20:34:18 JavaTest Message: shutting down test
20:34:18 
20:34:18 STATUS:Failed.`main' threw exception: TestFailedException: TEST FAILED: Test failed

**Comment by sophia-guo** [comment]
java/rmi/Naming/legalRegistryNames/LegalRegistryNames.java 61	linux-all
java/rmi/registry/serialFilter/RegistryFilterTest.java 61 macosx-all

Excluded.

**Comment by sabkrish** [comment]
I was trying to reproduce the LegalRegistryNames failure on linux. But no luck. I tried on a "Ubuntu 16.04.2 LTS \n \l" linux amd box. Test passed for me in this box multiple times.

**Comment by sophia-guo** [comment]
Did you comment out the test in ProblemList.txt?

**Comment by sabkrish** [comment]
@sophia-guo - Yes. I had removed them from the ProblemList.txt.

**Comment by karianna** [comment]
@sabkrish So can this be closed now? :-)

**Comment by sabkrish** [comment]
I'm yet to create a PR with the test java/rmi/Naming/legalRegistryNames/LegalRegistryNames.java removed from the ProblemList.txt. Can i go ahead with it?

**Comment by karianna** [comment]
@sabkrish Yes please!  I'll also invite you to this team so you can assign this to yourself.

**Comment by sabkrish** [comment]
@sophia-guo - RegistryFilterTest.java test is also excluded as part of issue 61 on all platforms in the current ProblemList.txt. I see it's working on Linux amd. Do you want to exclude it on macos alone? I'm not able to trace to a history on why it's excluded on all platforms.

**Comment by sophia-guo** [comment]
I believe we had this issue on both Linux and Mac. If you couldn't reproduce it on Linux you can exclude it on Macos alone. We have a personal build for you to test it. https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/build?delay=0sec .

**Comment by smlambert** [comment]
This test is being re-excluded (see #179), as its failing 50% of the time.  

Appears to:
Fail on: test-packet-x64-ubuntu-16.04-1
Pass on: test-scaleway-x64-ubuntu-16.04-1

**Comment by karianna** [comment]
@smlambert Side Q - are we tracking the tests we need to fix kind of via ProblemsList as well as here?

**Comment by smlambert** [comment]
Yes, as we wanted to "get green", these issues typically have matching entries in ProblemList.txt
(where the format contains 3 pieces of information per line in the file: test name  issueNumber  platform)

**Comment by karianna** [comment]
I assume we should get to the stage where we match Oracle's ProblemList (for Hotpsot versions).  Is that something you and Muneer have exchanged yet?

**Comment by smlambert** [comment]
Not yet, will try to connect with Muneer this week to talk about known problems/fixes.

**Comment by akolarkunnu** [comment]
It is duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8005619.

**Comment by smlambert** [comment]
Closing as now listed in summary issue #345
