### ISSUE TITLE
New teardown step fails on AIX

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#621]
18:33:31 + make -f ./openjdk-tests/TestConfig/testEnv.mk testEnvTeardown
18:33:31 "./openjdk-tests/TestConfig/testEnv.mk", line 27: make: 1254-055 Dependency line needs colon or double colon operator.
18:33:31 "./openjdk-tests/TestConfig/testEnv.mk", line 33: make: 1254-055 Dependency line needs colon or double colon operator.
18:33:31 make: 1254-058 Fatal errors encountered -- cannot continue.

**Comment by smlambert** [comment]
FYI @renfeiw

**Comment by renfeiw** [comment]
On AIX, we need to use gmake instead of make. I will add a conditional check for AIX before calling the teardown target.

**Comment by sophia-guo** [comment]
In maketest.sh we do have the check for AIX

```if [ `uname` = AIX ]; then
  MAKE=gmake
else
  MAKE=make
fi
```

**Comment by renfeiw** [comment]
Yes, but when we call teardown we don't use maketest.sh. I will have the same piece of code before teardown target.
