### ISSUE TITLE
jdk_rmi: sun/rmi/transport/proxy/EagerHttpFallback.java fails (ConnectException)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#63]
sun/rmi/transport/proxy/EagerHttpFallback.java fails with ConnectException 
(call on registry stub with port 45852did not successfully perform HTTP fallback to 36799, java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
java.net.ConnectException: Connection refused (Connection refused), output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

20:38:25 HOME=/home/jenkins \
20:38:25 LANG=en_US.UTF-8 \
20:38:25 PATH=/bin:/usr/bin \
20:38:25     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/javac \
20:38:25         -J-ea \
20:38:25         -J-esa \
20:38:25         -J-Xmx512m \
20:38:25         -J-Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/rmi/transport/proxy \
20:38:25         -J-Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/rmi/transport/proxy:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/rmi/testlibrary \
20:38:25         -J-Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/3/sun/rmi/transport/proxy \
20:38:25         -J-Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/3/sun/rmi/transport/proxy:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/3/java/rmi/testlibrary \
20:38:25         -J-Dtest.vm.opts='-ea -esa -Xmx512m' \
20:38:25         -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
20:38:25         -J-Dtest.compiler.opts= \
20:38:25         -J-Dtest.java.opts= \
20:38:25         -J-Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:38:25         -J-Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:38:25         -J-Dtest.timeout.factor=4.0 \
20:38:25         -d /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/3/sun/rmi/transport/proxy \
20:38:25         -sourcepath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/rmi/transport/proxy:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/rmi/testlibrary \
20:38:25         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/rmi/transport/proxy:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/3/sun/rmi/transport/proxy:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/3/java/rmi/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar \
20:38:25         -XDignore.symbol.file=true /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/rmi/transport/proxy/EagerHttpFallback.java
20:38:25 STDOUT:
20:38:25 STDERR:
20:38:25 
20:38:25 ACTION: main -- Failed. Execution failed: `main' threw exception: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: java.net.ConnectException: Connection refused (Connection refused)
20:38:25 REASON: User specified action: run main/othervm EagerHttpFallback 
20:38:25 TIME:   1.12 seconds
20:38:25 messages:
20:38:25 command: main EagerHttpFallback
20:38:25 reason: User specified action: run main/othervm EagerHttpFallback 
20:38:25 Mode: othervm [/othervm specified]
20:38:25 elapsed time (seconds): 1.12
20:38:25 configuration:
20:38:25 STDOUT:
20:38:25 STDERR:
20:38:25 call on registry stub with port 45852did not successfully perform HTTP fallback to 36799
20:38:25 java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
20:38:25 	java.net.ConnectException: Connection refused (Connection refused)
20:38:25 	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
20:38:25 	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
20:38:25 	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
20:38:25 	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342)
20:38:25 	at sun.rmi.registry.RegistryImpl_Stub.list(Unknown Source)
20:38:25 	at EagerHttpFallback.main(EagerHttpFallback.java:60)
20:38:25 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:38:25 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:38:25 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:38:25 	at java.lang.reflect.Method.invoke(Method.java:498)
20:38:25 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
20:38:25 	at java.lang.Thread.run(Thread.java:748)
20:38:25 Caused by: java.net.ConnectException: Connection refused (Connection refused)
20:38:25 	at java.net.PlainSocketImpl.socketConnect(Native Method)
20:38:25 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
20:38:25 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
20:38:25 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
20:38:25 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
20:38:25 	at java.net.Socket.connect(Socket.java:589)
20:38:25 	at java.net.Socket.connect(Socket.java:538)
20:38:25 	at java.net.Socket.<init>(Socket.java:434)
20:38:25 	at java.net.Socket.<init>(Socket.java:211)
20:38:25 	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
20:38:25 	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
20:38:25 	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
20:38:25 	... 11 more
20:38:25 
20:38:25 JavaTest Message: Test threw exception: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
20:38:25 	java.net.ConnectException: Connection refused (Connection refused)
20:38:25 JavaTest Message: shutting down test
20:38:25 
20:38:25 STATUS:Failed.`main' threw exception: java.rmi.ConnectException: Connection refused to host: 127.0.0.1

**Comment by akolarkunnu** [comment]
It is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-7195095. And this test case already there in openjdk problem list http://hg.openjdk.java.net/jdk8u/jdk8u-dev/jdk/file/1c47ee06c207/test/ProblemList.txt.

So it can be closed and removed from adopt problem list.

**Comment by smlambert** [comment]
Closing as now listed in summary issue #345
