### ISSUE TITLE
External test builds have stopped showing junit test output

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#636]
External test builds have stopped displaying external test output
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_externaltest_x86-64_linux/192/

It was showing in the previous builds; e.g.: 
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_externaltest_x86-64_linux/189/

This may be related to https://github.com/AdoptOpenJDK/openjdk-tests/issues/620

We need to investigate if any recent changes to `JenkinsfileBase` may be causing this.

**Comment by Mesbah-Alam** [comment]
@sophia-guo Fyi..

**Comment by sophia-guo** [comment]
It says
 ```
11:50:54 Recording test results
11:50:54 None of the test reports contained any result
```
so if there is no file under `**/external_test_reports/**/*.xml` you will not get junit output.

**Comment by Mesbah-Alam** [comment]
The tests that generated output junit xml reports haven't been touched lately. Only new ones have been added. So, for example, in the build which worked (link above), for example, the 'jenkins test' job was copying over junit xmls from docker onto the external test reports directory-- and as a result they will show in the build output. 

Nothing changed in the `docker cp` command in the test itself. However, it seems that the XML report files, after they are being copied over into the results directory, are being deleted by some command in the build -- which will explain no test report being displayed -- even after the `docker copy` step works fine.

**Comment by Mesbah-Alam** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/638 - should fix this PR as well. Will confirm with the next build run.

**Comment by Mesbah-Alam** [comment]
Test results have started to show : https://ci.adoptopenjdk.net/view/Test_external/job/openjdk11_hs_externaltest_extended_x86-64_linux/47/testReport/
