### ISSUE TITLE
jdk_security1: java/security/KeyStore/PKCS12/StoreTrustedCertKeytool.java fails (key pair not generated)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#64]
java/security/KeyStore/PKCS12/StoreTrustedCertKeytool.java fails as the keytool fails with java.lang.Exception: Key pair not generated, alias <testkey_stckey> already exists, 

output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

20:39:34 HOME=/home/jenkins \
20:39:34 LANG=en_US.UTF-8 \
20:39:34 PATH=/bin:/usr/bin \
20:39:34     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
20:39:34         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/KeyStore/PKCS12:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/security/KeyStore/PKCS12:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/lib/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/KeyStore \
20:39:34         -Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/security/KeyStore/PKCS12 \
20:39:34         -Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/security/KeyStore/PKCS12:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/lib/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/security/KeyStore \
20:39:34         -Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/KeyStore/PKCS12 \
20:39:34         -Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/KeyStore/PKCS12:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/lib/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/KeyStore \
20:39:34         -Dtest.vm.opts='-ea -esa -Xmx512m' \
20:39:34         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
20:39:34         -Dtest.compiler.opts= \
20:39:34         -Dtest.java.opts= \
20:39:34         -Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:39:34         -Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:39:34         -Dtest.timeout.factor=4.0 \
20:39:34         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/KeyStore/PKCS12:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/security/KeyStore/PKCS12:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/lib/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/lib/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/KeyStore:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/security/KeyStore:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
20:39:34         StoreTrustedCertKeytool
20:39:34 STDOUT:
20:39:34 Command line: [/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/keytool -debug -genkeypair -alias testkey_stckey -keystore /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/KeyStore/PKCS12/ks.pkcs12 -dname CN=TestKey, T=FuncTestCertKey, O=Oracle, OU=JDKSQE, C=US -storepass passwd -keypass passwd -validity 7300 -keyalg rsa -storetype pkcs12]
20:39:34 --- ProcessLog ---
20:39:34 cmd: /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/keytool -debug -genkeypair -alias testkey_stckey -keystore /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/KeyStore/PKCS12/ks.pkcs12 -dname CN=TestKey, T=FuncTestCertKey, O=Oracle, OU=JDKSQE, C=US -storepass passwd -keypass passwd -validity 7300 -keyalg rsa -storetype pkcs12
20:39:34 exitvalue: 1
20:39:34 stderr: Exception in thread "main" java.lang.Exception: Key pair not generated, alias <testkey_stckey> already exists
20:39:34 	at sun.security.tools.keytool.Main.doGenKeyPair(Main.java:1597)
20:39:34 	at sun.security.tools.keytool.Main.doCommands(Main.java:966)
20:39:34 	at sun.security.tools.keytool.Main.run(Main.java:343)
20:39:34 	at sun.security.tools.keytool.Main.main(Main.java:336)
20:39:34 
20:39:34 stdout: keytool error: java.lang.Exception: Key pair not generated, alias <testkey_stckey> already exists
20:39:34 
20:39:34 
20:39:34 keytool error: java.lang.Exception: Key pair not generated, alias <testkey_stckey> already exists
20:39:34 Exception in thread "main" java.lang.Exception: Key pair not generated, alias <testkey_stckey> already exists
20:39:34 	at sun.security.tools.keytool.Main.doGenKeyPair(Main.java:1597)
20:39:34 	at sun.security.tools.keytool.Main.doCommands(Main.java:966)
20:39:34 	at sun.security.tools.keytool.Main.run(Main.java:343)
20:39:34 	at sun.security.tools.keytool.Main.main(Main.java:336)
20:39:34 
20:39:34 STDERR:
20:39:34  stdout: [keytool error: java.lang.Exception: Key pair not generated, alias <testkey_stckey> already exists
20:39:34 ];
20:39:34  stderr: [Exception in thread "main" java.lang.Exception: Key pair not generated, alias <testkey_stckey> already exists
20:39:34 	at sun.security.tools.keytool.Main.doGenKeyPair(Main.java:1597)
20:39:34 	at sun.security.tools.keytool.Main.doCommands(Main.java:966)
20:39:34 	at sun.security.tools.keytool.Main.run(Main.java:343)
20:39:34 	at sun.security.tools.keytool.Main.main(Main.java:336)
20:39:34 ]
20:39:34  exitValue = 1
20:39:34 
20:39:34 java.lang.RuntimeException: Expected to get exit value of [0]
20:39:34 
20:39:34 	at jdk.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:361)
20:39:34 	at Utils.executeKeytoolCommand(Utils.java:68)
20:39:34 	at Utils.createKeyStore(Utils.java:108)
20:39:34 	at Utils.createKeyStore(Utils.java:87)
20:39:34 	at Utils.createKeyStore(Utils.java:81)
20:39:34 	at StoreTrustedCertKeytool.setUp(StoreTrustedCertKeytool.java:123)
20:39:34 	at StoreTrustedCertKeytool.run(StoreTrustedCertKeytool.java:58)
20:39:34 	at StoreTrustedCertKeytool.main(StoreTrustedCertKeytool.java:118)
20:39:34 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:39:34 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:39:34 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:39:34 	at java.lang.reflect.Method.invoke(Method.java:498)
20:39:34 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
20:39:34 	at java.lang.Thread.run(Thread.java:748)
20:39:34 java.lang.RuntimeException: Keytool Command execution failed : [/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/keytool, -debug, -genkeypair, -alias, testkey_stckey, -keystore, /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/KeyStore/PKCS12/ks.pkcs12, -dname, CN=TestKey, T=FuncTestCertKey, O=Oracle, OU=JDKSQE, C=US, -storepass, passwd, -keypass, passwd, -validity, 7300, -keyalg, rsa, -storetype, pkcs12]
20:39:34 	at Utils.executeKeytoolCommand(Utils.java:74)
20:39:34 	at Utils.createKeyStore(Utils.java:108)
20:39:34 	at Utils.createKeyStore(Utils.java:87)
20:39:34 	at Utils.createKeyStore(Utils.java:81)
20:39:34 	at StoreTrustedCertKeytool.setUp(StoreTrustedCertKeytool.java:123)
20:39:34 	at StoreTrustedCertKeytool.run(StoreTrustedCertKeytool.java:58)
20:39:34 	at StoreTrustedCertKeytool.main(StoreTrustedCertKeytool.java:118)
20:39:34 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:39:34 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:39:34 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:39:34 	at java.lang.reflect.Method.invoke(Method.java:498)
20:39:34 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
20:39:34 	at java.lang.Thread.run(Thread.java:748)
20:39:34 Caused by: java.lang.RuntimeException: Expected to get exit value of [0]
20:39:34 
20:39:34 	at jdk.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:361)
20:39:34 	at Utils.executeKeytoolCommand(Utils.java:68)
20:39:34 	... 12 more
20:39:34 
20:39:34 JavaTest Message: Test threw exception: java.lang.RuntimeException
20:39:34 JavaTest Message: shutting down test

**Comment by akolarkunnu** [comment]
This test is not listed in ProblemList_openjdk8.txt, also it is passing in linux and mac ci:
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_linux/7/testReport/java_security_KeyStore_PKCS12_StoreTrustedCertKeytool/java/StoreTrustedCertKeytool/
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_macos/5/testReport/java_security_KeyStore_PKCS12_StoreTrustedCertKeytool/java/StoreTrustedCertKeytool/

So closing this bug.
