### ISSUE TITLE
openjdk_regression testcases failing due to Jenkins agent console EOF

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#644]
Some openjdk_regression tests fail due to testcase console issues, most likely due to the amount of output and how Jenkins agent reads that, eg:
```
Agent communication error: java.io.EOFException; check console log for any additional details
```

Testcases requiring exclusion for this reason:
java/nio/Buffer/Basic.java.Basic

**Comment by adam-thorpe** [comment]
Known defect with JTReg. Test has been un-excluded and this issue can be closed

**Comment by smlambert** [comment]
For completeness and to aid future searches, is there a reference to the known defect with jtreg that can be added here.

**Comment by adam-thorpe** [comment]
From what I can tell, this occurs when JTReg experiences a crash when trying to read/execute a test and is completely independent of the actual test itself. However, it does seem to occur on the same set of tests at a very low frequency, which makes me think it might have something to do with how the test sets up the environment of the test (eg. agent vm modes). I don't have an official source to back this up but this is the conclusion I have come to after reading multiple sources from jbs or just other people googling the same thing.

**Comment by smlambert** [comment]
Ok, thanks for the clarification @adam-thorpe .  I will close this, though it is an interesting side problem, as we will soon enough be breaking out the high level test targets, like sanity.openjdk into smaller groups of test targets (based on number of machines available to run on), so suspect this may happen even less often at that point.  Closing as per your suggestion above.
