### ISSUE TITLE
jdk_security1: java/security/Signature/NoProvider.java fails (NullPointerException)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#65]
Test fails with java.lang.NullPointerException
at java.security.Signature.initVerify(Signature.java:462)
at NoProvider.main(NoProvider.java:97), output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

20:40:19 TEST: java/security/Signature/NoProvider.java
20:40:19 TEST JDK: /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../..
20:40:19 
20:40:19 ACTION: build -- Passed. All files up to date
20:40:19 REASON: Named class compiled on demand
20:40:19 TIME:   0.0 seconds
20:40:19 messages:
20:40:19 command: build NoProvider
20:40:19 reason: Named class compiled on demand
20:40:19 elapsed time (seconds): 0.0
20:40:19 
20:40:19 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.NullPointerException
20:40:19 REASON: User specified action: run main/othervm -Djava.security.debug=provider NoProvider 
20:40:19 TIME:   0.515 seconds
20:40:19 messages:
20:40:19 command: main -Djava.security.debug=provider NoProvider
20:40:19 reason: User specified action: run main/othervm -Djava.security.debug=provider NoProvider 
20:40:19 Mode: othervm [/othervm specified]
20:40:19 elapsed time (seconds): 0.515
20:40:19 configuration:
20:40:19 STDOUT:
20:40:19 STDERR:
20:40:19 java.lang.NullPointerException
20:40:19 	at java.security.Signature.initVerify(Signature.java:462)
20:40:19 	at NoProvider.main(NoProvider.java:97)
20:40:19 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:40:19 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:40:19 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:40:19 	at java.lang.reflect.Method.invoke(Method.java:498)
20:40:19 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
20:40:19 	at java.lang.Thread.run(Thread.java:748)
20:40:19 
20:40:19 JavaTest Message: Test threw exception: java.lang.NullPointerException
20:40:19 JavaTest Message: shutting down test

**Comment by akolarkunnu** [comment]
This test is not listed in ProblemList_openjdk8.txt, also it is passing in linux and mac ci:
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_linux/7/testReport/java_security_Signature_NoProvider/java/NoProvider/
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_macos/5/testReport/java_security_Signature_NoProvider/java/NoProvider/

So closing this bug.
