### ISSUE TITLE
jdk_security3: sun/security/pkcs11/ec/TestECDH|TestECDSA.java fails (InvalidKeySpecException)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#66]
Both sun/security/pkcs11/ec/TestECDH.java and sun/security/pkcs11/ec/TestECDSA.java fails with  java.security.spec.InvalidKeySpecException: Could not create EC [public|private] key (libsoftokn3 version not found, set to 0.0: /usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so), output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

20:43:31 HOME=/home/jenkins \
20:43:31 LANG=en_US.UTF-8 \
20:43:31 PATH=/bin:/usr/bin \
20:43:31     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
20:43:31         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:31         -Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/ec \
20:43:31         -Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/security/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11 \
20:43:31         -Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/ec \
20:43:31         -Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:31         -Dtest.vm.opts='-ea -esa -Xmx512m' \
20:43:31         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
20:43:31         -Dtest.compiler.opts= \
20:43:31         -Dtest.java.opts= \
20:43:31         -Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:31         -Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:31         -Dtest.timeout.factor=4.0 \
20:43:31         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/security/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/security/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
20:43:31         TestECDH
20:43:31 STDOUT:
20:43:31 Beginning test run TestECDH...
20:43:31 Running test with provider SunPKCS11-NSS...
20:43:31 libsoftokn3 version not found, set to 0.0: /usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so
20:43:31 STDERR:
20:43:31 java.security.spec.InvalidKeySpecException: Could not create EC public key
20:43:31 	at sun.security.pkcs11.P11ECKeyFactory.engineGeneratePublic(P11ECKeyFactory.java:173)
20:43:31 	at java.security.KeyFactory.generatePublic(KeyFactory.java:328)
20:43:31 	at TestECDH.test(TestECDH.java:94)
20:43:31 	at TestECDH.main(TestECDH.java:86)
20:43:31 	at PKCS11Test.premain(PKCS11Test.java:88)
20:43:31 	at PKCS11Test.testNSS(PKCS11Test.java:403)
20:43:31 	at PKCS11Test.main(PKCS11Test.java:98)
20:43:31 	at TestECDH.main(TestECDH.java:124)
20:43:31 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:43:31 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:43:31 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:43:31 	at java.lang.reflect.Method.invoke(Method.java:498)
20:43:31 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
20:43:31 	at java.lang.Thread.run(Thread.java:748)
20:43:31 Caused by: java.security.InvalidKeyException: Could not create EC public key
20:43:31 	at sun.security.pkcs11.P11ECKeyFactory.implTranslatePublicKey(P11ECKeyFactory.java:130)
20:43:31 	at sun.security.pkcs11.P11ECKeyFactory.engineGeneratePublic(P11ECKeyFactory.java:171)
20:43:31 	... 13 more
20:43:31 Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
20:43:31 	at sun.security.pkcs11.wrapper.PKCS11.C_CreateObject(Native Method)
20:43:31 	at sun.security.pkcs11.P11ECKeyFactory.generatePublic(P11ECKeyFactory.java:254)
20:43:31 	at sun.security.pkcs11.P11ECKeyFactory.implTranslatePublicKey(P11ECKeyFactory.java:110)
20:43:31 	... 14 more
20:43:31 
20:43:31 JavaTest Message: Test threw exception: java.security.spec.InvalidKeySpecException
20:43:31 JavaTest Message: shutting down test
20:43:31 
20:43:31 
20:43:31 TEST RESULT: Failed. Execution failed: `main' threw exception: java.security.spec.InvalidKeySpecException: Could not create EC public key

**Comment by sophia-guo** [comment]
Duplicate of #125
