### ISSUE TITLE
Grinder job fails to access some JDK builds 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#663]
Not sure if we are hitting a timeout, an access issue or file too large issue, error message not helpful.

From https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/331/console : 

16:21:08 Failed to retrieve https://ci.eclipse.org/openj9/view/Build/job/Build-JDK10-linux_x86-64/460/artifact/OpenJ9-JDK10-linux_x86-64-20181019-003221.tar.gz, exiting. This is what we received of the file and MD5 sum:
16:21:08 ls: cannot access 'https://ci.eclipse.org/openj9/view/Build/job/Build-JDK10-linux_x86-64/460/artifact/OpenJ9-JDK10-linux_x86-64-20181019-003221.tar.gz': No such file or directory
16:21:08 md5sum: 'https://ci.eclipse.org/openj9/view/Build/job/Build-JDK10-linux_x86-64/460/artifact/OpenJ9-JDK10-linux_x86-64-20181019-003221.tar.gz': No such file or directory
[Pipeline] }

**Comment by karianna** [comment]
Are you supposed to be pulling from Eclipse or from AdoptOpenJDK?

**Comment by smlambert** [comment]
The point of the Grinder job is to be able to pull builds from any publicly available server.

**Comment by ben-walsh** [comment]
I discussed this with @sxa555 couple of days back, as we are seeing similar occasionally in our Jenkins jobs when utilising the AOJDK "download server". Would it be possible to get some / additional logging added to the "download server" so that further PD can be performed when this next happens ?

**Comment by smlambert** [comment]
Closing this as wont fix, have not seen this issue in a while, and its a matter of manually retrying to proceed if problem arises.
