### ISSUE TITLE
jdk_security3: sun/security/pkcs11/ec/TestECGenSpec|TestKeyFactory.java fail (InvalidAlgorithmParameterException)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#67]
sun/security/pkcs11/ec/TestECGenSpec.java and sun/security/pkcs11/ec/TestKeyFactory.java fail with java.security.InvalidAlgorithmParameterException: EC key must be at least 256 bits. The specific key size 192 is not supported, output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

20:43:33 HOME=/home/jenkins \
20:43:33 LANG=en_US.UTF-8 \
20:43:33 PATH=/bin:/usr/bin \
20:43:33     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/javac \
20:43:33         -J-ea \
20:43:33         -J-esa \
20:43:33         -J-Xmx512m \
20:43:33         -J-Dtest.class.path.prefix=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:33         -J-Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/ec \
20:43:33         -J-Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11 \
20:43:33         -J-Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/ec \
20:43:33         -J-Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:33         -J-Dtest.vm.opts='-ea -esa -Xmx512m' \
20:43:33         -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
20:43:33         -J-Dtest.compiler.opts= \
20:43:33         -J-Dtest.java.opts= \
20:43:33         -J-Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:33         -J-Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:33         -J-Dtest.timeout.factor=4.0 \
20:43:33         -d /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/ec \
20:43:33         -sourcepath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11 \
20:43:33         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/ec:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar \
20:43:33         -XDignore.symbol.file=true /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/ec/TestECGenSpec.java
20:43:33 
20:43:33 ACTION: main -- Failed. Execution failed: `main' threw exception: java.security.InvalidAlgorithmParameterException: EC key must be at least 256 bits. The specific key size 192 is not supported
20:43:33 REASON: Assumed action based on file name: run main TestECGenSpec 
20:43:33 TIME:   0.235 seconds
20:43:33 messages:
20:43:33 command: main TestECGenSpec
20:43:33 reason: Assumed action based on file name: run main TestECGenSpec 
20:43:33 Mode: agentvm
20:43:33 Agent id: 1
20:43:33 elapsed time (seconds): 0.235
20:43:33 configuration:
20:43:33 Boot Layer
20:43:33   class path: /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
20:43:33               /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
20:43:33               /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
20:43:33 
20:43:33 Test Layer
20:43:33   class path: /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/ec
20:43:33               /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/ec
20:43:33               /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11
20:43:33               /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11

**Comment by sophia-guo** [comment]
Duplicate of #125
