### ISSUE TITLE
JTReg test failures - java/util/Currency/CurrencyTest.java.CurrencyTest and java/util/Currency/ValidateISO4217.java

### ISSUE THREAD

**Issue by ben-walsh** [AdoptOpenJDK/openjdk-tests#678]
Both these tests are currently failing because, in the current AOJDK infrastructure, they contain code that is outdated compared to the product code. The test code must be at or later than revision https://hg.openjdk.java.net/jdk-updates/jdk11u/rev/c65b05b53a26.
Discussing with @sxa555, they are outdated because the Jenkins job responsible for keeping the relevant OpenJDK Mercurial forests and AOJDK github repos in sync is failing.

For now, with the goal of obtaining green dashboards in mind, I'm going to exclude both these tests using the relevant problem list, referencing this issue, with the intention that they should be de-excluded as soon as the relevant Jenkins job is fixed.

FAO : @ShelleyLambert @sophia-guo

**Comment by sophia-guo** [comment]
I just noticed that in Adopt we do have a updated jdk11 repo https://github.com/AdoptOpenJDK/openjdk-jdk11u, which seems the sync one with Mercurial forests. @karianna Please advise openjdk-jdk11u one is the updated one and https://github.com/AdoptOpenJDK/openjdk-jdk11 should be disabled?

**Comment by karianna** [comment]
You're correct, https://github.com/AdoptOpenJDK/openjdk-jdk11u should be used going forward.  We hadn't quite informed everyone and deprecated yet until we had a successful 11.0.1 release.  But for this purpose go ahead and change

**Comment by sophia-guo** [comment]
@ben-walsh I had a PR to update jdk11u, which should have updated test code. Those tests should be ok.

**Comment by smlambert** [comment]
So changing to use jdk11u for nightly testing is correct.  

We have an additional task that needs to be done I believe, which is for release builds, where a particular tag is used, we should be pulling openjdk test material from that tagged version.  Implication, updates to test scripts to take the tag as a parameter, and update release build pipelines to pass tag to tests.

**Comment by sophia-guo** [comment]
With passed in the release tag from build pipeline we can update openjdk_regression/build.xml to git clone specific release branch (for example :https://github.com/AdoptOpenJDK/openjdk-jdk8u/tree/jdk8u172-b11). 

Note passing in parameter to openjdk_regression/build.xml will also need to update https://github.com/eclipse/openj9/blob/master/test/TestConfig/makefile#L82

**Comment by sophia-guo** [comment]
I guess for jdk11u we need to update per tag (say 11.0.1+13 tag on the jdk11u ) as JDK11 is not a long term support version?

**Comment by karianna** [comment]
I'd argue yes

**Comment by smlambert** [comment]
Fixed by #694 and https://github.com/AdoptOpenJDK/openjdk-build/pull/764
