### ISSUE TITLE
jdk_security3: sun/security/pkcs11/rsa/TestCACerts.java fails (SignatureException SHA256withRSA)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#68]
sun/security/pkcs11/rsa/TestCACerts.java and sun/security/rsa/TestCACerts.java fails with 
java.security.SignatureException: Signature does not match.  (Signature algorithm: SHA256withRSA), output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/rsa/TestCACerts.java
20:43:39 
20:43:39 ACTION: main -- Failed. Execution failed: `main' threw exception: java.security.SignatureException: Signature does not match.
20:43:39 REASON: Assumed action based on file name: run main TestCACerts 
20:43:39 TIME:   0.813 seconds
20:43:39 messages:
20:43:39 command: main TestCACerts
20:43:39 reason: Assumed action based on file name: run main TestCACerts 
20:43:39 Mode: agentvm
20:43:39 Agent id: 1
20:43:39 elapsed time (seconds): 0.813
20:43:39 configuration:
20:43:39 Boot Layer
20:43:39   class path: /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
20:43:39               /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
20:43:39               /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
20:43:39 
20:43:39 Test Layer
20:43:39   class path: /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/rsa
20:43:39               /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/rsa
20:43:39               /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11
20:43:39               /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11
20:43:39 
20:43:39 rerun:
20:43:39 HOME=/home/jenkins \
20:43:39 LANG=en_US.UTF-8 \
20:43:39 PATH=/bin:/usr/bin \
20:43:39     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
20:43:39         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/rsa:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/rsa:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:39         -Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/rsa \
20:43:39         -Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/rsa:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11 \
20:43:39         -Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/rsa \
20:43:39         -Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/rsa:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:39         -Dtest.vm.opts='-ea -esa -Xmx512m' \
20:43:39         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
20:43:39         -Dtest.compiler.opts= \
20:43:39         -Dtest.java.opts= \
20:43:39         -Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:39         -Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:39         -Dtest.timeout.factor=4.0 \
20:43:39         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/rsa:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/rsa:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
20:43:39         TestCACerts
20:43:39 STDOUT:
20:43:39 Beginning test run TestCACerts...
20:43:39 Running test with provider SunPKCS11-NSS...
20:43:39 * Testing cn=t-telesec globalroot class 3,ou=t-systems trust center,o=t-systems enterprise services gmbh,c=de...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=digicert high assurance ev root ca,ou=www.digicert.com,o=digicert inc,c=us...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=ca wosign ecc root,o=wosign ca limited,c=cn...
20:43:39 Skipping cert with key: EC
20:43:39 * Testing cn=china internet network information center ev certificates root,o=china internet network information center,c=cn...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=teliasonera root ca v1,o=teliasonera...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing ou=trustis fps root ca,o=trustis limited,c=gb...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=secure global ca,o=securetrust corporation,c=us...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=entrust root certification authority - ec1,ou=(c) 2012 entrust\, inc. - for authorized use only,ou=see www.entrust.net/legal-terms,o=entrust\, inc.,c=us...
20:43:39 Skipping cert with key: EC
20:43:39 * Testing cn=digicert assured id root g3,ou=www.digicert.com,o=digicert inc,c=us...
20:43:39 Skipping cert with key: EC
20:43:39 * Testing ou=security communication rootca1,o=secom trust.net,c=jp...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=microsec e-szigno root ca,ou=e-szigno ca,o=microsec ltd.,l=budapest,c=hu...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=twca root certification authority,ou=root ca,o=taiwan-ca,c=tw...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=d-trust root class 3 ca 2 ev 2009,o=d-trust gmbh,c=de...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=sonera class2 ca,o=sonera,c=fi...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=entrust root certification authority - g2,ou=(c) 2009 entrust\, inc. - for authorized use only,ou=see www.entrust.net/legal-terms,o=entrust\, inc.,c=us...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=opentrust root ca g1,o=opentrust,c=fr...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=securesign rootca11,o=japan certification services\, inc.,c=jp...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=globalsign root ca,ou=root ca,o=globalsign nv-sa,c=be...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=entrust root certification authority,ou=(c) 2006 entrust\, inc.,ou=www.entrust.net/cps is incorporated by reference,o=entrust\, inc.,c=us...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=secure certificate services,o=comodo ca limited,l=salford,st=greater manchester,c=gb...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing ou=starfield class 2 certification authority,o=starfield technologies\, inc.,c=us...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=addtrust class 1 ca root,ou=addtrust ttp network,o=addtrust ab,c=se...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=verisign class 3 public primary certification authority - g5,ou=(c) 2006 verisign\, inc. - for authorized use only,ou=verisign trust network,o=verisign\, inc.,c=us...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=comodo certification authority,o=comodo ca limited,l=salford,st=greater manchester,c=gb...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=visa ecommerce root,ou=visa international service association,o=visa,c=us...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing ou=epki root certification authority,o=chunghwa telecom co.\, ltd.,c=tw...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=twca global root ca,ou=root ca,o=taiwan-ca,c=tw...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing ou=certsign root ca,o=certsign,c=ro...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=ca disig root r2,o=disig a.s.,l=bratislava,c=sk...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=entrust.net certification authority (2048),ou=(c) 1999 entrust.net limited,ou=www.entrust.net/cps_2048 incorp. by ref. (limits liab.),o=entrust.net...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=identrust public sector root ca 1,o=identrust,c=us...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=ca disig root r1,o=disig a.s.,l=bratislava,c=sk...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=quovadis root ca 2 g3,o=quovadis limited,c=bm...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing c=es,o=accv,ou=pkiaccv,cn=accvraiz1...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=affirmtrust premium,o=affirmtrust,c=us...
20:43:39 Signature algorithm: SHA384withRSA
20:43:39 * Testing cn=geotrust primary certification authority - g2,ou=(c) 2007 geotrust inc. - for authorized use only,o=geotrust inc.,c=us...
20:43:39 Skipping cert with key: EC
20:43:39 * Testing cn=opentrust root ca g2,o=opentrust,c=fr...
20:43:39 Signature algorithm: SHA512withRSA
20:43:39 * Testing cn=affirmtrust premium ecc,o=affirmtrust,c=us...
20:43:39 Skipping cert with key: EC
20:43:39 * Testing cn=amazon root ca 2,o=amazon,c=us...
20:43:39 Signature algorithm: SHA384withRSA
20:43:39 * Testing cn=certification authority of wosign g2,o=wosign ca limited,c=cn...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=staat der nederlanden root ca - g3,o=staat der nederlanden,c=nl...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=xramp global certification authority,o=xramp security services inc,ou=www.xrampsecurity.com,c=us...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=starfield root certificate authority - g2,o=starfield technologies\, inc.,l=scottsdale,st=arizona,c=us...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=global chambersign root,ou=http://www.chambersign.org,o=ac camerfirma sa cif a82743287,c=eu...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=usertrust rsa certification authority,o=the usertrust network,l=jersey city,st=new jersey,c=us...
20:43:39 Signature algorithm: SHA384withRSA
20:43:39 * Testing cn=opentrust root ca g3,o=opentrust,c=fr...
20:43:39 Skipping cert with key: EC
20:43:39 * Testing cn=aaa certificate services,o=comodo ca limited,l=salford,st=greater manchester,c=gb...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=global chambersign root - 2008,o=ac camerfirma s.a.,2.5.4.5=#1309413832373433323837,l=madrid (see current address at www.camerfirma.com/address),c=eu...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=thawte primary root ca - g3,ou=(c) 2008 thawte\, inc. - for authorized use only,ou=certification services division,o=thawte\, inc.,c=us...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=geotrust global ca 2,o=geotrust inc.,c=us...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=staat der nederlanden root ca - g2,o=staat der nederlanden,c=nl...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=quovadis root certification authority,ou=root certification authority,o=quovadis limited,c=bm...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing o=türktrust bilgi i̇letişim ve bilişim güvenliği hizmetleri a.ş. (c) aralık 2007,l=ankara,c=tr,cn=türktrust elektronik sertifika hizmet sağlayıcısı...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=baltimore cybertrust root,ou=cybertrust,o=baltimore,c=ie...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=certum trusted network ca,ou=certum certification authority,o=unizeto technologies s.a.,c=pl...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing ou=security communication ev rootca1,o=secom trust systems co.\,ltd.,c=jp...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=quovadis root ca 2,o=quovadis limited,c=bm...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing 1.2.840.113549.1.9.1=#1610696e666f40652d737a69676e6f2e6875,cn=microsec e-szigno root ca 2009,o=microsec ltd.,l=budapest,c=hu...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=network solutions certificate authority,o=network solutions l.l.c.,c=us...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=ec-acc,ou=jerarquia entitats de certificacio catalanes,ou=vegeu https://www.catcert.net/verarrel (c)03,ou=serveis publics de certificacio,o=agencia catalana de certificacio (nif q-0801176-i),c=es...
20:43:39 Signature algorithm: SHA1withRSA
20:43:39 * Testing cn=hellenic academic and research institutions rootca 2015,o=hellenic academic and research institutions cert. authority,l=athens,c=gr...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=digicert global root g2,ou=www.digicert.com,o=digicert inc,c=us...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 * Testing cn=pscprocert,c=ve,o=sistema nacional de certificacion electronica,ou=proveedor de certificados procert,st=miranda,l=chacao,1.2.840.113549.1.9.1=#1617636f6e746163746f4070726f636572742e6e65742e7665...
20:43:39 Signature algorithm: SHA256withRSA
20:43:39 STDERR:
20:43:39 java.security.SignatureException: Signature does not match.
20:43:39 	at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:449)
20:43:39 	at TestCACerts.main(TestCACerts.java:68)
20:43:39 	at PKCS11Test.premain(PKCS11Test.java:88)
20:43:39 	at PKCS11Test.testNSS(PKCS11Test.java:403)
20:43:39 	at PKCS11Test.main(PKCS11Test.java:98)
20:43:39 	at TestCACerts.main(TestCACerts.java:45)
20:43:39 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:43:39 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:43:39 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:43:39 	at java.lang.reflect.Method.invoke(Method.java:498)
20:43:39 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
20:43:39 	at java.lang.Thread.run(Thread.java:748)
20:43:39 
20:43:39 JavaTest Message: Test threw exception: java.security.SignatureException
20:43:39 JavaTest Message: shutting down test
20:43:39 
20:43:39 
20:43:39 TEST RESULT: Failed. Execution failed: `main' threw exception: java.security.SignatureException: Signature does not match.
20:43:39 --------------------------------------------------

**Comment by akolarkunnu** [comment]
It's a duplicate of #125, so closing this.

**Comment by akolarkunnu** [comment]
Failure reason this bug and #125 are different, so reopening this.

**Comment by akolarkunnu** [comment]
sun/security/rsa/TestCACerts.java also fails with same log

**Comment by smlambert** [comment]
Closing stale issues as they are not being addressed and fresh ones can/will be raised via nightly triage.
