### ISSUE TITLE
Add a Jenkinsfile for getDependency jobs 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#689]
Since we now have two getDependency jobs - one for systemtest builds and one for non-systemtest builds, it makes sense to commit the configuration of these jobs in repository in form of Jenkins files.

**Comment by Mesbah-Alam** [comment]
@AdamBrousseau I've updated `test.getDependency` and `systemtest.getDependency` jobs at Adopt and also in the internal Jenkins server to use the new [getDependency Jenkins file](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/getDependency) that was delivered as part of this issue. Could you please make the same updates in the corresponding jobs in the ci.eclipse Jenkins (I do not have permission to do it)?

To summarize, we need the following updates: 
1) in [systemtest.getDependency job at ci.eclipse](https://ci.eclipse.org/openj9/job/systemtest.getDependency/)
  - Switch to using the getDependency Jenkins file as used in the [systemtest.getDependency job at adopt](https://ci.adoptopenjdk.net/view/all/job/systemtest.getDependency/configure).
 - Note we need to introduce a new parameter in the build called `BUILD_TYPE` and set it to `systemtest`.
 - Note we changed the build schedule to `@weekly`.

2. 1) in [test.getDependency job at ci.eclipse](https://ci.eclipse.org/openj9/job/test.getDependency/)
  - Switch to using the getDependency Jenkins file as used in the [test.getDependency job at adopt](https://ci.adoptopenjdk.net/view/all/job/test.getDependency/configure).
 - Note we need to introduce a new parameter in the build called `BUILD_TYPE` and set it to `test`.

**Comment by AdamBrousseau** [comment]
Done
>BUILD_TYPE and set it to test

Your script only does `if systemtest { }; else {}`
