### ISSUE TITLE
jdk_security3: sun/security/pkcs11/Secmod/AddTrustedCert.java fails (KeyStoreException)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#69]
sun/security/pkcs11/Secmod/AddTrustedCert.java fails with java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_READ_ONLY, output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

20:43:46 HOME=/home/jenkins \
20:43:46 LANG=en_US.UTF-8 \
20:43:46 PATH=/bin:/usr/bin \
20:43:46     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/javac \
20:43:46         -J-ea \
20:43:46         -J-esa \
20:43:46         -J-Xmx512m \
20:43:46         -J-Dtest.class.path.prefix=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/Secmod:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/Secmod:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:46         -J-Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/Secmod \
20:43:46         -J-Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/Secmod:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11 \
20:43:46         -J-Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/Secmod \
20:43:46         -J-Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/Secmod:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:46         -J-Dtest.vm.opts='-ea -esa -Xmx512m' \
20:43:46         -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
20:43:46         -J-Dtest.compiler.opts= \
20:43:46         -J-Dtest.java.opts= \
20:43:46         -J-Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:46         -J-Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:46         -J-Dtest.timeout.factor=4.0 \
20:43:46         -d /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/Secmod \
20:43:46         -sourcepath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/Secmod:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11 \
20:43:46         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/Secmod:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/Secmod:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar \
20:43:46         -XDignore.symbol.file=true /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/Secmod/AddTrustedCert.java
20:43:46 
20:43:46 ACTION: main -- Failed. Execution failed: `main' threw exception: java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_READ_ONLY
20:43:46 REASON: User specified action: run main/othervm AddTrustedCert 
20:43:46 TIME:   1.868 seconds
20:43:46 messages:
20:43:46 command: main AddTrustedCert
20:43:46 reason: User specified action: run main/othervm AddTrustedCert 
20:43:46 Mode: othervm [/othervm specified]
20:43:46 elapsed time (seconds): 1.868
20:43:46 configuration:
20:43:46 STDOUT:
20:43:46 SunPKCS11-NSSKeyStore version 1.8
20:43:46 entries: 1
20:43:46 [mykey]
20:43:46 first entry = Trusted certificate entry:
20:43:46 [
20:43:46 [
20:43:46   Version: V3
20:43:46   Subject: EMAILADDRESS=info@opentsa.org, CN=OpenTSA Root CA, O=OpenTSA, L=Dublin, ST=Co. Dublin, C=IE
20:43:46   Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5
20:43:46 
20:43:46   Key:  Sun RSA public key, 2048 bits
20:43:46   modulus: 28015647916364875829141896049677220882914191436294605577513377891910662717336292436491710471594406842772073838695462019009454723293288506992417485761129126311538268002377286178684649711932051555842344360775863345218752895239460508761587090794001550599392104457188635329925564746414056111210478603450167440907565077703922928621867939042884745257219423496925695838757642236269036957557147241224660577528253185760515264362748497612078896510637739121732184250485539505699485155279825000189178169555672844007672373755234739866676449460941418806853690713277829199399068163905100762713680303566487520616527043839846563616127
20:43:46   public exponent: 65537
20:43:46   Validity: [From: Thu Oct 17 20:51:34 UTC 2002,
20:43:46                To: Mon Oct 16 20:51:34 UTC 2006]
20:43:46   Issuer: EMAILADDRESS=info@opentsa.org, CN=OpenTSA Root CA, O=OpenTSA, L=Dublin, ST=Co. Dublin, C=IE
20:43:46   SerialNumber: [    00]
20:43:46 
20:43:46 Certificate Extensions: 6
20:43:46 [1]: ObjectId: 2.5.29.35 Criticality=false
20:43:46 AuthorityKeyIdentifier [
20:43:46 KeyIdentifier [
20:43:46 0000: 2D 9D F7 1D 7E 65 77 9A   F4 D9 B4 99 B1 17 3B C4  -....ew.......;.
20:43:46 0010: 2F C8 AD A5                                        /...
20:43:46 ]
20:43:46 [EMAILADDRESS=info@opentsa.org, CN=OpenTSA Root CA, O=OpenTSA, L=Dublin, ST=Co. Dublin, C=IE]
20:43:46 SerialNumber: [    00]
20:43:46 ]
20:43:46 
20:43:46 [2]: ObjectId: 2.5.29.19 Criticality=false
20:43:46 BasicConstraints:[
20:43:46   CA:true
20:43:46   PathLen:2147483647
20:43:46 ]
20:43:46 
20:43:46 [3]: ObjectId: 2.5.29.15 Criticality=false
20:43:46 KeyUsage [
20:43:46   Key_CertSign
20:43:46   Crl_Sign
20:43:46 ]
20:43:46 
20:43:46 [4]: ObjectId: 2.16.840.1.113730.1.1 Criticality=false
20:43:46 NetscapeCertType [
20:43:46    SSL CA
20:43:46    S/MIME CA
20:43:46 ]
20:43:46 
20:43:46 [5]: ObjectId: 2.5.29.17 Criticality=false
20:43:46 SubjectAlternativeName [
20:43:46   RFC822Name: info@opentsa.org
20:43:46 ]
20:43:46 
20:43:46 [6]: ObjectId: 2.5.29.14 Criticality=false
20:43:46 SubjectKeyIdentifier [
20:43:46 KeyIdentifier [
20:43:46 0000: 2D 9D F7 1D 7E 65 77 9A   F4 D9 B4 99 B1 17 3B C4  -....ew.......;.
20:43:46 0010: 2F C8 AD A5                                        /...
20:43:46 ]
20:43:46 ]
20:43:46 
20:43:46 ]
20:43:46   Algorithm: [SHA1withRSA]
20:43:46   Signature:
20:43:46 0000: 26 A9 2D 41 7E 71 12 DA   BB 89 AE 0C 84 E4 FC FC  &.-A.q..........
20:43:46 0010: 71 6B 13 1E 41 2C 85 A0   51 BA 81 90 4C 9A 2C A4  qk..A,..Q...L.,.
20:43:46 0020: 61 ED 7B 61 AC A4 13 C7   6C 07 E9 46 E4 F6 C3 05  a..a....l..F....
20:43:46 0030: 31 96 C2 42 FC 39 2D 43   37 34 24 8B EB 3E 90 FC  1..B.9-C74$..>..
20:43:46 0040: F5 FE 64 37 1F 8C 24 98   E6 FC 62 FC 9C 2C 05 B4  ..d7..$...b..,..
20:43:46 0050: 7F 59 4E 28 DA 22 64 0B   5C 35 BA 0B DE 81 53 0B  .YN(."d.\5....S.
20:43:46 0060: 80 9B 3A FD BE A7 ED 63   09 EE AB 52 B7 DE 96 12  ..:....c...R....
20:43:46 0070: 1E 58 87 DE C0 61 31 56   86 BB 93 9A DF 20 63 20  .X...a1V..... c 
20:43:46 0080: F6 EF F9 B8 28 1B 6E 0E   36 35 BE A2 8A D2 F9 D1  ....(.n.65......
20:43:46 0090: 54 04 29 18 5E 27 72 65   8B 63 22 A7 43 2A AB 39  T.).^'re.c".C*.9
20:43:46 00A0: AE EF CF D5 FF D1 9C 21   FB 8C 96 D5 12 D1 51 12  .......!......Q.
20:43:46 00B0: 15 33 DB 96 96 AA 5E 55   9D B2 C5 E8 83 22 FA 08  .3....^U....."..
20:43:46 00C0: EF 8C 51 80 A8 59 6B EC   80 19 F7 6E 6B C8 80 53  ..Q..Yk....nk..S
20:43:46 00D0: 8F 30 D8 F8 B3 83 31 ED   E3 5C CE 5C 47 D8 2F 71  .0....1..\.\G./q
20:43:46 00E0: C8 88 78 D0 90 B4 D6 39   64 0D 05 8A 86 C4 63 B5  ..x....9d.....c.
20:43:46 00F0: 9B 63 3F DF A2 E6 28 39   D0 67 27 75 4D E2 CF 1E  .c?...(9.g'uM...
20:43:46 
20:43:46 ]
20:43:46 STDERR:
20:43:46 java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_READ_ONLY
20:43:46 	at sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1048)
20:43:46 	at sun.security.pkcs11.P11KeyStore.engineSetCertificateEntry(P11KeyStore.java:516)
20:43:46 	at java.security.KeyStore.setCertificateEntry(KeyStore.java:1201)
20:43:46 	at AddTrustedCert.main(AddTrustedCert.java:79)
20:43:46 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:43:46 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:43:46 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:43:46 	at java.lang.reflect.Method.invoke(Method.java:498)
20:43:46 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
20:43:46 	at java.lang.Thread.run(Thread.java:748)
20:43:46 Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_READ_ONLY
20:43:46 	at sun.security.pkcs11.wrapper.PKCS11.C_CreateObject(Native Method)
20:43:46 	at sun.security.pkcs11.P11KeyStore.storeCert(P11KeyStore.java:1564)
20:43:46 	at sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1044)
20:43:46 	... 9 more
20:43:46 
20:43:46 JavaTest Message: Test threw exception: java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_READ_ONLY
20:43:46 JavaTest Message: shutting down test
20:43:46 
20:43:46 STATUS:Failed.`main' threw exception: java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_READ_ONLY

**Comment by sophia-guo** [comment]
Duplicate #125 , close it.
