### ISSUE TITLE
get.sh accepts two diferent parameters with same flag -t 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#695]
`get.sh` script accepts a parameter called -`t` or `--type` which , in the comment it says accepts either `jdk` or `jre` as the value. But when I run it, it looks like the script is looking for a folder path to be specified for value of -t .

We also have a must option `--testdir|-t` which is same `-t` in short.

We need to update `--type|-t` with a different short option say `--type|-T`

**Comment by llxia** [comment]
Fixed in #702
