### ISSUE TITLE
Update systemtest/README.md to include steps to run systemtests manually using TestConfig

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#697]
Developers ask questions frequently as to how we can manually run systemtests. There is a simple set of steps that can be followed to achieve this, and it can be documented in the README so that developers can follow along.

**Comment by llxia** [comment]
We already have wiki for this:
https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally#system-tests
