### ISSUE TITLE
Add 3rd party dependencies wget file 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#7]
We depend on some 3rd party jars, which we pick up from external sites.  We can add the file that contains the links to the TestConfig/lib folder, so that a user can run wget -f dependencies.txt to pick them up and have them in TestConfig/lib (where we expect them to be found).

We will also need to update README to indicate these dependencies (will be done as part of issue 1).

**Comment by karianna** [comment]
@smlambert We've tended to use Ansible or a set of shell scripts to pull those down.  Might be worth a chat to @gdams and @neomatrix369 to see if we can merge some of those efforts?

**Comment by smlambert** [comment]
Actually, I guess we do have a shell script that does this https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/get.sh, which we should edit, so that the fetch of the adoptopenjdk binary is optional if you want to run tests with your own SDK.

**Comment by sophia-guo** [comment]
With #12 people could do following to wget third party jars:
cd openjdk-test
get.sh
