### ISSUE TITLE
jdk_security3: sun/security/pkcs11/Signature/TestDSAKeyLength.java

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#70]
sun/security/pkcs11/Signature/TestDSAKeyLength.java fails with java.lang.Exception: Test Failed - expected IKE not thrown (libsoftokn3 version not found, set to 0.0: /usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so, similar to issue #66):

20:43:50 HOME=/home/jenkins \
20:43:50 LANG=en_US.UTF-8 \
20:43:50 PATH=/bin:/usr/bin \
20:43:50     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
20:43:50         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/Signature:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/Signature:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:50         -Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/Signature \
20:43:50         -Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/Signature:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11 \
20:43:50         -Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/Signature \
20:43:50         -Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/Signature:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:50         -Dtest.vm.opts='-ea -esa -Xmx512m' \
20:43:50         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
20:43:50         -Dtest.compiler.opts= \
20:43:50         -Dtest.java.opts= \
20:43:50         -Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:50         -Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:50         -Dtest.timeout.factor=4.0 \
20:43:50         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/Signature:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/Signature:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
20:43:50         TestDSAKeyLength
20:43:50 STDOUT:
20:43:50 Beginning test run TestDSAKeyLength...
20:43:50 Running test with provider SunPKCS11-NSS...
20:43:50 libsoftokn3 version not found, set to 0.0: /usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so
20:43:50 STDERR:
20:43:50 java.lang.Exception: Test Failed - expected IKE not thrown
20:43:50 	at TestDSAKeyLength.main(TestDSAKeyLength.java:69)
20:43:50 	at PKCS11Test.premain(PKCS11Test.java:88)
20:43:50 	at PKCS11Test.testNSS(PKCS11Test.java:403)
20:43:50 	at PKCS11Test.main(PKCS11Test.java:98)
20:43:50 	at TestDSAKeyLength.main(TestDSAKeyLength.java:39)
20:43:50 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:43:50 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:43:50 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:43:50 	at java.lang.reflect.Method.invoke(Method.java:498)
20:43:50 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
20:43:50 	at java.lang.Thread.run(Thread.java:748)
20:43:50 
20:43:50 JavaTest Message: Test threw exception: java.lang.Exception
20:43:50 JavaTest Message: shutting down test
20:43:50 
20:43:50 
20:43:50 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: Test Failed - expected IKE not thrown

**Comment by akolarkunnu** [comment]
The below 3 test cases also fail because of same reason.
sun/security/pkcs11/ec/TestECDH.java
sun/security/pkcs11/ec/TestECDSA.java
sun/security/pkcs11/ec/TestECGenSpec.java

But these failures were included in #125 , I am adding here and removing from there.

**Comment by akolarkunnu** [comment]
It is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8142541

**Comment by smlambert** [comment]
Closing stale issues as they are not being addressed and fresh ones can/will be raised via nightly triage.

**Comment by zzambers** [comment]
Failure of test from description:
`sun/security/pkcs11/Signature/TestDSAKeyLength.java`

actually seems like [JDK-8279941](https://bugs.openjdk.org/browse/JDK-8279941) (rather than bug mentioned higher)
