### ISSUE TITLE
jdk_security3: sun/security/pkcs11/tls/TestKeyMaterial.java fails (could not generate key)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#71]
sun/security/pkcs11/tls/TestKeyMaterial.java fails with java.security.ProviderException: Could not generate key caused by ...
sun.security.pkcs11.wrapper.PKCS11Exception: CKR_MECHANISM_PARAM_INVALID:

20:43:51 HOME=/home/jenkins \
20:43:51 LANG=en_US.UTF-8 \
20:43:51 PATH=/bin:/usr/bin \
20:43:51     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
20:43:51         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/tls:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/tls:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:51         -Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/tls \
20:43:51         -Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/tls:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11 \
20:43:51         -Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/tls \
20:43:51         -Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/tls:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11 \
20:43:51         -Dtest.vm.opts='-ea -esa -Xmx512m' \
20:43:51         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
20:43:51         -Dtest.compiler.opts= \
20:43:51         -Dtest.java.opts= \
20:43:51         -Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:51         -Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:43:51         -Dtest.timeout.factor=4.0 \
20:43:51         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11/tls:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11/tls:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/pkcs11:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/pkcs11:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
20:43:51         TestKeyMaterial
20:43:51 STDOUT:
20:43:51 Beginning test run TestKeyMaterial...
20:43:51 Running test with provider SunPKCS11-NSS...
20:43:51 ..................................................................STDERR:
20:43:51 java.security.ProviderException: Could not generate key
20:43:51 	at sun.security.pkcs11.P11TlsKeyMaterialGenerator.engineGenerateKey(P11TlsKeyMaterialGenerator.java:206)
20:43:51 	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:540)
20:43:51 	at TestKeyMaterial.main(TestKeyMaterial.java:140)
20:43:51 	at PKCS11Test.premain(PKCS11Test.java:88)
20:43:51 	at PKCS11Test.testNSS(PKCS11Test.java:403)
20:43:51 	at PKCS11Test.main(PKCS11Test.java:98)
20:43:51 	at TestKeyMaterial.main(TestKeyMaterial.java:50)
20:43:51 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:43:51 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:43:51 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:43:51 	at java.lang.reflect.Method.invoke(Method.java:498)
20:43:51 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
20:43:51 	at java.lang.Thread.run(Thread.java:748)
20:43:51 Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_MECHANISM_PARAM_INVALID
20:43:51 	at sun.security.pkcs11.wrapper.PKCS11.C_DeriveKey(Native Method)
20:43:51 	at sun.security.pkcs11.P11TlsKeyMaterialGenerator.engineGenerateKey(P11TlsKeyMaterialGenerator.java:164)
20:43:51 	... 12 more
20:43:51 
20:43:51 JavaTest Message: Test threw exception: java.security.ProviderException
20:43:51 JavaTest Message: shutting down test
20:43:51 
20:43:51 
20:43:51 TEST RESULT: Failed. Execution failed: `main' threw exception: java.security.ProviderException: Could not generate key

**Comment by akolarkunnu** [comment]
It is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8180837

**Comment by smlambert** [comment]
Closing stale issues as they are not being addressed and fresh ones can/will be raised via nightly triage.
