### ISSUE TITLE
Include openj9 sanity functional tests to run in thirdparty containers

### ISSUE THREAD

**Issue by chandrams** [AdoptOpenJDK/openjdk-tests#714]
Include openj9 sanity functional tests to run in third party containers

Steps:

- Include a docker file to clone eclipse/openj9 repo
- Include a script to set the env variables and compile the test material and run sanity functional tests

**Comment by chandrams** [comment]
Gave a run of openj9 sanity functional tests in docker container and see the below failures, compared it failures outside docker container, 14 of them are due to native libs not found. A couple of them highlighted fail only in docker container. 

SKIPPED test targets due to capabilities:
        cmdLineTester_pltest_hyp_HV_vmware_0 - capabilities (hypervisor:VMWare)
        cmdLineTester_pltest_hyp_HV_kvm_0 - capabilities (hypervisor:KVM)

FAILED test targets:
        algotest2_0
        ctest_0
        vmtest_0
        jsigjnitest_0
        gc_rwlocktest_0
        shrtest_linux_SE80_0
        thrstatetest_0
        cmdLineTester_jvmtitests_1
        cmdLineTester_jvmtitests_2
        cmdLineTester_jvmtitests_5
        cmdLineTester_jvmtitests_7
        cmdLineTester_jvmtitests_8
        **cmdLineTester_callsitedbgddrext_openj9_0**
        cmdLineTester_pltest_0
        cmdLineTester_pltest_numcpus_bound_linux_0
        **cmdLineTester_SCCommandLineOptionTests_1**

TOTAL: 188   EXECUTED: 111   PASSED: 95   FAILED: 16   SKIPPED: 77

**Comment by chandrams** [comment]
Investigated the below two failures in docker containers and found the first one failing as it uses env variable LOGNAME to validate if the cache is created with the name of the user logged in, this doesn't work in a docker container as LOGNAME is blank.  Requires a test case change. To resolve the second failure, we will need to modify the content of /proc/sys/kernel/core_pattern on the host machine to just j9core and this would need root access.   

1) cmdLineTester_callsitedbgddrext_openj9_0

 [OUT] Could not load dump file and/or could not load XML file: Image file '/openj9/test/TestConfig/test_output_15433322797739/cmdLineTester_callsitedbgddrext_openj9_0/j9core.dmp' not found.
 [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
 [OUT] > DDR is not enabled for this core file, '!' commands are disabled

2) cmdLineTester_SCCommandLineOptionTests_1

[OUT] nameOption2: TEST FAILED
 [OUT] nameOption2: Expected to find the cache name
 [OUT] TEST PASSED
 [ERR] JVMSHRC806I Compressed references persistent shared cache "root" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.

**Comment by llxia** [comment]
For functional tests, native test libs need to be provided. Currently, we do not have a way to run only non-native functional tests.

**Comment by smlambert** [comment]
We were considering a few options, either:

- creating a openjdk-build issue to request native-test-libs get built as part of the openjdkX-openj9 builds
- a job that fetches nightly native-test-libs.tar.gz artifacts from ci.eclipse.org/openj9 
- have logic in this PR to fetch nightly artifacts from ci.eclipse.org/openj9 
- disable the native test targets in this PR 

There are likely other options too

**Comment by chandrams** [comment]
Copied and extracted the native-test-libs.tar.gz and executed the tests, all failures related to native tests passed except cmdLineTester_pltest_0.  Seen outside docker runs too.  Haven't gone through the test yet.
@llxia - Have you come across this failure?

 [ERR] FAILURES DETECTED. Number of failed tests: 2
 [ERR]
 [ERR] 1: j9file_test27
 [ERR]  j9fileTest.c line 3642: opened read-only file for writing fd=0 expected -1
 [ERR]
 [ERR]          LastErrorNumber: -108
 [ERR]          LastErrorMessage: No such file or directory
 [ERR]
 [ERR] 2: j9file_test29
 [ERR]  j9fileTest.c line 3774: j9file_chown() to root succeeded, should have failed
 [ERR]
 [ERR]          LastErrorNumber: -108
 [ERR]          LastErrorMessage: No such file or directory
 [ERR]
>> Success condition was not found: [Output match: ALL TESTS COMPLETED AND PASSED]
>> Failure condition was not found: [Output match: ASSERTION FAILED]


---TEST RESULTS---
Number of PASSED tests: 0 out of 1
Number of FAILED tests: 1 out of 1

**Comment by llxia** [comment]
`cmdLineTester_pltest_0` runs fine in regular build:
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/285/tapResults/

**Comment by chandrams** [comment]
Thanks @llxia. I ran this test as root user outside docker and it had failed looking at the error message I think this test is not supposed to be run as root. So now, executed it as a normal user outside docker and it runs fine.

**Comment by smlambert** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/790
