### ISSUE TITLE
Create openjdk11_hs_openjdktest_arm_linux

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-tests#717]
And maybe openjdk11_hs_perftest_arm_linux too if possible.

We now have https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-arm-hotspot producing builds that seem to be operational, so would be good to be able to run the standard test suite against them and find out how good they really are :-)

**Comment by smlambert** [comment]
sure, we follow this naming convention for test jobs:
https://github.com/AdoptOpenJDK/openjdk-tests/wiki/Naming-Convention-for-Test-Builds-in-Jenkins

A while back, I had polled the slack channel for opinions on arm vs aarch, with most voting for aarch64 and aarch32, so I will create: 
openjdk11_hs_openjdktest_aarch32_linux and openjdk11_hs_perftest_aarch32_linux for now (with option to add a systemtest job later too depending on execution times)

**Comment by smlambert** [comment]
Needs #721 and a test machine
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_aarch32_linux/
https://ci.adoptopenjdk.net/view/Test_perf/job/openjdk11_hs_perftest_aarch32_linux/
