### ISSUE TITLE
jdk_security3: sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager/PreferredKey fails

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#72]
sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager/PreferredKey fails with java.lang.Exception: Failed to get the preferable key aliases

20:47:11 HOME=/home/jenkins \
20:47:11 LANG=en_US.UTF-8 \
20:47:11 PATH=/bin:/usr/bin \
20:47:11     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/javac \
20:47:11         -J-ea \
20:47:11         -J-esa \
20:47:11         -J-Xmx512m \
20:47:11         -J-Dtest.class.path.prefix=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager \
20:47:11         -J-Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager \
20:47:11         -J-Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager \
20:47:11         -J-Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager \
20:47:11         -J-Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager \
20:47:11         -J-Dtest.vm.opts='-ea -esa -Xmx512m' \
20:47:11         -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
20:47:11         -J-Dtest.compiler.opts= \
20:47:11         -J-Dtest.java.opts= \
20:47:11         -J-Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:47:11         -J-Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:47:11         -J-Dtest.timeout.factor=4.0 \
20:47:11         -d /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager \
20:47:11         -sourcepath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager \
20:47:11         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar \
20:47:11         -XDignore.symbol.file=true /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/security/ssl/com/sun/net/ssl/internal/ssl/X509KeyManager/PreferredKey.java
20:47:11 
20:47:11 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Exception: Failed to get the preferable key aliases

**Comment by chandrams** [comment]
From the readme, I understand we can run an individual test (testExampleExtended_SE80_0) as below:
make _testExampleExtended_SE80_0

What is the test name or make target name to run this test?

**Comment by sophia-guo** [comment]
To reproduce the failure you can run make jdk_security3_0. Note if test is excluded in ProblemList.txt you will also need to comment out that excluded tests.

**Comment by chandrams** [comment]
Recreated this issue the test fails as chooseClientAlias() method does not return the DSA key 

 alias = km.chooseClientAlias(new String[] {"DSA", "RSA"},null, null);
String algorithm = km.getPrivateKey(alias).getAlgorithm(); // This returns RSA instead of DSA and this is because DSA key has expired. See keytool output below: 

$ keytool -list -v -keystore ./etc/keystore -storepass passphrase
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 3 entries

Alias name: dummydsa
Creation date: Mar 10, 2007
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=dummy.example.com, OU=Dummy, O=Dummy, L=Cupertino, ST=CA, C=US
Issuer: CN=dummy.example.com, OU=Dummy, O=Dummy, L=Cupertino, ST=CA, C=US
Serial number: 45f3a314
Valid from: Sat Mar 10 22:35:00 PST 2007 until: Tue Mar 07 22:35:00 PST 2017
Certificate fingerprints:
         SHA1: E5:EE:0A:8B:90:37:64:FD:B5:8C:03:D5:ED:3B:9F:2B:48:71:14:08
         SHA256: BB:0E:3C:95:2F:C4:B6:BE:A6:F7:09:DB:82:27:33:8E:81:14:D6:81:EA:F0:9D:5F:B2:DC:A1:AE:7B:93:72:FC
Signature algorithm name: SHA1withDSA
Subject Public Key Algorithm: 1024-bit DSA key
Version: 1

Fails with both openjdk9-openj9 build and openjdk9 build.

**Comment by chandrams** [comment]
There is a bug already raised for this, expired certificate was fixed but the change was backed out due to some other DTLS tests failures. See https://bugs.openjdk.java.net/browse/JDK-8176354

I think this test should be excluded, can I go ahead and raise a PR to exclude this?

**Comment by sophia-guo** [comment]
@chandrams Could you please confirm the test only fails with jdk9? I didn't see the failure recently with jdk8. Thanks.

**Comment by chandrams** [comment]
@sophia-guo It failed with openjdk8 build too

java -showversion PreferredKey
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2017_07_27_20_16-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

algorithm = RSA alias = DSA
Exception in thread "main" java.lang.Exception: Failed to get the preferable key aliases
        at PreferredKey.main(PreferredKey.java:71)

I checked the DSA key in the keystore in openjdk-jdk8u test material it has expired. Can you please let me know with which jdk8 build you tested or if you could retest it. Thanks.

Note - I 'm just running this test alone as a standalone and not jdk_security3 target.

**Comment by sophia-guo** [comment]
Test build are using jdk8 https://api.adoptopenjdk.net/openjdk8/nightly/

**Comment by chandrams** [comment]
I had run only the test PreferredKey as a standalone.  I have tested it using the jdk_security3 target with both Java8 and Java9, the test doesn't run as it is already excluded in ProblemList.txt in openjdk-jdk8u and openjdk-jdk9 repos.  Hence we can close this issue.
