### ISSUE TITLE
Windows grinder in hyc-runtimes-jenkins.swg-devops.com fails with wrong cygwin path

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#720]
Windows grinder in internal jenkins hyc-runtimes-jenkins.swg-devops.com doesn’t work, whereas it works at Adopt. 

Adopt Grinder example: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/475/consoleFull
hyc-runtimes-jenkins.swg-devops.com grinder example: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/898/console

Test output snippet: 
```
13:48:45 BUILD FAILED
13:48:45 C:\Users\jenkins\workspace\Grinder\openjdk-tests\TestConfig\scripts\build_test.xml:87: C:\cygdrive\c\Users\jenkins\workspace\Grinder\openjdk-tests does not exist.
```
Whereas the cygwin path suggests openjdk-test is there of course :
```/cygdrive/c/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/```

Every other path in the build uses `/cygdrive/c/…` but the failing gone is using `C:\cygdrive\c\Users\jenkins\workspace\Grinder\openjdk-tests` which isn’t valid.

Note : the wrong path above is actually the value of `BUILD_ROOT`in https://github.com/eclipse/openj9/blob/master/test/TestConfig/scripts/build_test.xml , which gets constructed via use of `subst` here: https://github.com/eclipse/openj9/blob/f4a00be20932df4512f73af7e9bfac4dfaf8b8d3/test/TestConfig/settings.mk#L141

Not sure if it's related, but we have an open issue for `subst` not working in the ci.eclipse Windows machines here: https://github.com/eclipse/openj9/issues/3897

**Comment by Mesbah-Alam** [comment]
@renfeiw @llxia @AdamBrousseau  FYI

**Comment by llxia** [comment]
I do not think it is a test issue. Functional test build runs fine on windows in OpenJ9:
https://ci.eclipse.org/openj9/view/Test/job/Test-extended.functional-JDK11-win_x86-64_cmprssptrs/

**Comment by Mesbah-Alam** [comment]
FYI @jdekonin

**Comment by smlambert** [comment]
Closing this and raise an internal infra issue to get some open questions answered.

**Comment by smlambert** [comment]
Further note, closing this open issue, because no open tests are failing, we are only seeing this issue on internal machines, which appear to be newly configured.
