### ISSUE TITLE
job openjdk11_j9_openjdktest_x86-64_linux are triggered twice per upstream project 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#724]
job [openjdk11_j9_openjdktest_x86-64_linux](https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/) are triggered twice per upstream project. One is triggered by build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9 ( which is correct). The other one is triggered by build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9-linuxXL . ( which shouldn't, build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9-linuxXL should trigger job [openjdk11_j9_openjdktest_x86-64_linux_largeHeap](https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux_largeHeap/)

**Comment by smlambert** [comment]
This should likely be an issue in openjdk-build repo

**Comment by sophia-guo** [comment]
Agreed

**Comment by sophia-guo** [comment]
Fixed, close this one.
