### ISSUE TITLE
Support system test execution in parallel

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#747]
With [extra variations enabled ](https://github.com/AdoptOpenJDK/openjdk-tests/blob/extraVariations/systemtest/playlist.xml), sanity and extended system build can run for 20+ hrs.
- Test-sanity.system-JDK8-linux_x86-64 - 18hrs
- Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs,Test-extended.system-JDK8-linux_x86-64 and Test-extended.system-JDK11-linux_x86-64 got killed after 20hrs

We should support system test execution in parallel. This could help us to shorten system test build time. Our goal is to complete the system test and functional test builds within 3hrs.

**Comment by llxia** [comment]
Ideally, we can create separate folders and break the [playlist.xml](https://github.com/AdoptOpenJDK/openjdk-tests/blob/extraVariations/systemtest/playlist.xml) into multiple smaller sets. Similar as jck test: https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/jck

I am thinking of separte playlist based on features. i.e., * LoadTest*, SharedClasses*, TestJlm*, modularity, others). If LoadTest set is too big, we can further break it into MathLoadTest*, DaaLoadTest*, LambdaLoadTest*, Mauve*, etc.

@ShelleyLambert @Mesbah-Alam any suggestions? Thanks

**Comment by smlambert** [comment]
That seems like the most logical and direct approach, and is in keeping with existing subdirs approach used by other testing (so leverages what TKG already knows how to deal with this scenario).

**Comment by llxia** [comment]
Thanks @ShelleyLambert . I will give it a try.

**Comment by llxia** [comment]
system tests are running `special` level tests in parallel in internal Jenkins. Close this issue.
