### ISSUE TITLE
Expand test on OpenJ9's concurrent scavenge support

### ISSUE THREAD

**Issue by 0dvictor** [AdoptOpenJDK/openjdk-tests#755]
OpenJ9 is expanding its support on Concurrent Scavenge support to Windows X86-64 and hence the related tests should be enabled/introduced.

**Comment by smlambert** [comment]
Will suggest starting with removing the restriction of running the CS system test targets on os.win:
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/systemtest/playlist.xml#L2771  (removing the ^os.win part).

**Comment by smlambert** [comment]
#756 enabled 12 system test targets for Windows platform, which is a good expansion of testing.  I will like to close this issue now.  If we bring more targets for CS, we will ensure they are enabled for all applicable platforms.
