### ISSUE TITLE
JTReg test fail - Windows : sun/net/www/protocol/file/DirPermissionDenied.java

### ISSUE THREAD

**Issue by ben-walsh** [AdoptOpenJDK/openjdk-tests#760]
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/sun/net/www/protocol/file/DirPermissionDenied.java consistently fails on Windows with ...

"TEST RESULT: Error. failed to clean up files after test"

Examples ...
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/664/testReport/junit/sun_net_www_protocol_file_DirPermissionDenied/java/DirPermissionDenied
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/665/testReport/junit/sun_net_www_protocol_file_DirPermissionDenied/java/DirPermissionDenied
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/666/testReport/junit/sun_net_www_protocol_file_DirPermissionDenied/java/DirPermissionDenied

No such problem is observed running against other platforms e.g. ...
Linux x86_64 - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/682/console
Linux PPC64 - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/667/testReport/junit/sun_net_www_protocol_file_DirPermissionDenied/java/DirPermissionDenied
MacOS - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/670/testReport/sun_net_www_protocol_file_DirPermissionDenied/java/DirPermissionDenied

**Comment by smlambert** [comment]
I think dup of #749

**Comment by sophia-guo** [comment]
Test is excluded in openj9, will also exclude in HS.

**Comment by smlambert** [comment]
Closing this as there is an existing issue covering it and want to clean up the issue list.
