### ISSUE TITLE
System tests fail on openj9 builds with -Xcompressedrefs

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#764]
The openjdk-system tests are failing on openj9 large heap Java 11 builds (and maybe other releases) if the are given -Xcompressedrefs as an argument.  Since the builds are inherently 'noncompressedrefs' the options cannot be honoured.

I guess the test playlists need to be changed to not specify that option?

**Comment by llxia** [comment]
Could you provide a build link for this failure? Thanks

**Comment by lumpfish** [comment]
https://ci.adoptopenjdk.net/job/openjdk11_j9_systemtest_x86-64_linux/165/console
The relevant output from the VM is
Selected VM [compressedrefs] by option -Xcompressedrefs does not exist.
This JVM package only includes the '-Xnocompressedrefs' configuration. Please run the VM without specifying the '-Xcompressedrefs' option or by specifying the '-Xnocompressedrefs' option.
To compile the other configuration, please run configure without '--with-noncompressedrefs.

**Comment by lumpfish** [comment]
openjdk tests are also failing on the large heap builds - the same problem? - https://ci.adoptopenjdk.net/job/openjdk11_j9_openjdktest_x86-64_linux/190/consoleFull

**Comment by llxia** [comment]
From compressedrefs system test build:
- [Build #163](https://ci.adoptopenjdk.net/job/openjdk11_j9_systemtest_x86-64_linux/163/) (Dec 19, 2018 8:27:25 PM) shows it started by `jdk11u-linux-x64-openj9`
```
Started by upstream project build-scripts » jobs » jdk11u » jdk11u-linux-x64-openj9 build number 66
```

- [Build #164](https://ci.adoptopenjdk.net/job/openjdk11_j9_systemtest_x86-64_linux/164/) (Dec 19, 2018 9:04:49 PM) shows it started by `jdk11u-linux-x64-openj9-linuxXL`. 
This is where first failure `option -Xcompressedrefs does not exist` coccured.
```
Started by upstream project build-scripts » jobs » jdk11u » jdk11u-linux-x64-openj9-linuxXL build number 57
```

btw, I do not see large heap system test build in Adopt.

**Comment by lumpfish** [comment]
The link I gave https://ci.adoptopenjdk.net/job/openjdk11_j9_systemtest_x86-64_linux/165/consoleFull was
```
Started by upstream project "build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9-linuxXL" build number 58
```
You are looking at Build 163 instead of 165?

**Comment by llxia** [comment]
Build 163 is the last good build, which is started by `jdk11u-linux-x64-openj9`.
`option -Xcompressedrefs does not exist` failure started at Build 164. Both Build 164 and 165 have the same failure and they are both started by a different job - `jdk11u-linux-x64-openj9-linuxXL build`.

**Comment by lumpfish** [comment]
I think it may only be the large heap builds which reject -Xcompressedrefs.

**Comment by llxia** [comment]
This is a known issue in openjdk-build: https://github.com/AdoptOpenJDK/openjdk-build/issues/790
Close this issue as it is not a test issue.
