### ISSUE TITLE
Third party container tests job should  be triggered by docker image update?

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#773]
Third party container tests jobs are testing jdks from docker hub. It's better that jobs 
https://ci.adoptopenjdk.net/view/Test_external/ be triggered by docker hub updates or by some timers instead of upstream jdk builds?

**Comment by smlambert** [comment]
Agree, we could trigger these builds from the docker builds that produce the docker hub images which I believe are:
https://ci.adoptopenjdk.net/job/openjdk8_build_docker/
https://ci.adoptopenjdk.net/view/Docker%20Images/

We should understand the frequency and plan of the docker builds (and if they are kicked off by build pipelines or are currently separate).  It would be nice to have all builds choreographed in a similar pattern.

**Comment by sophia-guo** [comment]
This build https://ci.adoptopenjdk.net/job/openjdk8_build_docker/ seems like a testing/obsolete one, which probably need to be deleted. @gdams 

Correct, I believe https://ci.adoptopenjdk.net/view/Docker%20Images/ are build producing dlocker images. The build https://ci.adoptopenjdk.net/view/Docker%20Images/job/openjdk_build_docker_multiarch/ is configured as daily and using separate build repo https://github.com/AdoptOpenJDK/openjdk-docker

**Comment by sophia-guo** [comment]
Closed by https://github.com/AdoptOpenJDK/openjdk-tests/issues/1843
