### ISSUE TITLE
Consider using 'special' level for extra test variations

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#775]
Currently we maintain 2 branches master and extraVariations to allow for extra testing without overloading open machine farms.  We should consider adding those extra test variations into master using the new 'special' level, to avoid the need for the second branch.

The special target can then be easily run on internal machine farms where we have extra resources, without being automatically picked up in sanity or extended runs at the open projects.

FYI @llxia - what do you think?

**Comment by llxia** [comment]
yes, I think it is a great idea. It would be nice if we could add these extra test variations into master and maintain only one branch.

While I agree with using `special` level, there are a couple of things to consider:

- playlist `<test>` will double. We cannot use one `<test>` for both `special` and `sanity`/`extended` due to different variations. This means people modify one `<test>` may still need to modify the corresponding special `<test>`.

```
         <test>
		<testCaseName>ClassLoadingTest</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>export JAVA_HOME=$(JDK_HOME)$(D)  && \
	perl $(TEST_RESROOT)$(D)stf$(D)stf.core$(D)scripts$(D)stf.pl  \
	-test-root=$(Q)$(TEST_RESROOT)$(D)stf;$(TEST_RESROOT)$(D)openjdk-systemtest$(Q) \
	-systemtest-prereqs=$(Q)$(TEST_RESROOT)$(D)systemtest_prereqs$(Q)  \
	-java-args=$(Q)$(JVM_OPTIONS)$(Q) \
	-results-root=$(REPORTDIR)  \
	-test=ClassloadingLoadTest; \
	$(TEST_STATUS)</command> 
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>system</group>
		</groups>
	</test>

        <test>
		<testCaseName>ClassLoadingTest_special</testCaseName>
		<variations>
			<variation>NoOptions</variation>
			<variation>Mode101</variation>
			<variation>Mode103</variation>
			<variation>Mode104</variation>
			<variation>Mode107</variation>
			<variation>Mode108</variation>
		</variations>
		<command>export JAVA_HOME=$(JDK_HOME)$(D)  && \
	perl $(TEST_RESROOT)$(D)stf$(D)stf.core$(D)scripts$(D)stf.pl  \
	-test-root=$(Q)$(TEST_RESROOT)$(D)stf;$(TEST_RESROOT)$(D)openjdk-systemtest$(Q) \
	-systemtest-prereqs=$(Q)$(TEST_RESROOT)$(D)systemtest_prereqs$(Q)  \
	-java-args=$(Q)$(JVM_OPTIONS)$(Q) \
	-results-root=$(REPORTDIR)  \
	-test=ClassloadingLoadTest; \
	$(TEST_STATUS)</command> 
		<levels>
			<level>special</level>
		</levels>
		<groups>
			<group>system</group>
		</groups>
	</test>
```

- Since all extra tests will be tagged as special, there is no separation of sanity and extended. `special` build becomes sanity + extended and will take even longer to complete. However, I think this issue should be addressed once we complete [Support system test execution in parallel](https://github.com/AdoptOpenJDK/openjdk-tests/issues/747).

**Comment by smlambert** [comment]
I am not sure I understand the last point, "there is no separation of sanity and extended".
I do not mean to propose we push all variations to 'special', just extra ones... we would keep sanity and extended targets as they are... with some of the more common variations being tested via them.  Less common variations are in 'special', so we have a 3 tiered system.

**sanity** for most common variations - 'NoOptions' being most common, perhaps preference to variations that we can use to test all jdk implementations

**extended** for some variations that are deemed important enough to test regularly

**special** for variations that are less important, or more costly to test

And yes, it does beg the question, do we add a rule or mechanism for reading/naming targets from playlist.xml file that says this target's command is equivalent to this other target, like if `<command>` is missing from the `<test>` definition, it means that the test is a dupe of another target named same, with the new variation/level/platformReqs swapped in.

**Comment by smlambert** [comment]
`  <test>
		<testCaseName>ClassLoadingTest</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>export JAVA_HOME=$(JDK_HOME)$(D)  && \
	perl $(TEST_RESROOT)$(D)stf$(D)stf.core$(D)scripts$(D)stf.pl  \
	-test-root=$(Q)$(TEST_RESROOT)$(D)stf;$(TEST_RESROOT)$(D)openjdk-systemtest$(Q) \
	-systemtest-prereqs=$(Q)$(TEST_RESROOT)$(D)systemtest_prereqs$(Q)  \
	-java-args=$(Q)$(JVM_OPTIONS)$(Q) \
	-results-root=$(REPORTDIR)  \
	-test=ClassloadingLoadTest; \
	$(TEST_STATUS)</command> 
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>system</group>
		</groups>
	</test>
        <test>
		<testCaseName>ClassLoadingTest_special</testCaseName>
		<variations>
			<variation>Mode101</variation>
			<variation>Mode103</variation>
			<variation>Mode104</variation>
			<variation>Mode107</variation>
			<variation>Mode108</variation>
		</variations>
		<levels>
			<level>special</level>
		</levels>
	</test>`

So for your example, 2nd occurrence of the test, should either be named exactly same as first where TKG assigns a name based off 1st, or same name used with a suffix '_level', (as in above ClassLoadingTest_special) and must not contain command (lack of the command block can indicate to testkitgen that there is a 1st occurrence and it should find the 1st occurrence and 'inherit' from it the command while other xml inside of the 2nd occurrences test block would be used.  

We can discuss if this is feasible or needed next week.

This might be one way to support multiple occurrences of `<test>`, keeping playlist file smaller, avoiding duplication of commands and subtle copy/paste errors or changes...  It relies on a test naming standard to be followed/enforced, but that is something that should happen anyway.  

I know TKG already auto-names targets (increment based on variations _0, _1, etc... )

**Comment by llxia** [comment]
> I am not sure I understand the last point, "there is no separation of sanity and extended".

Sorry for not being clear here. I just want to express the fact that `special` group may take even longer to run without parallelization. Currently, extra variations are added to the test without modifying the original level. It can be part of sanity or extended. Once we have special level added, extra variations all belong to `special`.

**Comment by smlambert** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/796
