### ISSUE TITLE
Issue with MBCS_Tests file names

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#778]
Noticed some files in MBCS_Tests have almost the same name, only difference is one has uppercase and one has lowercase. For example:

https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/functional/MBCS_Tests/data

test_AIX_JA_JP.UTF-8
test_AIX_ja_JP.UTF-8

https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/functional/MBCS_Tests/file/data

AIX_JA_JP.UTF-8.tar.gz
AIX_ja_JP.UTF-8.tar.gz

Git is case sensitive but Mac is only case preserving. Therefore, the files with only case difference will not be created when git reset/rebase. And git status complains files are removed/modified. I think this will happen on windows as well.

@takiguc  Is it intended to create file names only based on case sensitivity?

**Comment by smlambert** [comment]
Not sure if related, but have a bunch of "no such file" failures: https://ci.adoptopenjdk.net/view/Test_functional/job/openjdk8_hs_functionaltest_special_x86-64_linux/2/tapResults/

**Comment by takiguc** [comment]
Hello @llxia 

AIX has following locales.
These file name was created based on LANG environment variable and "locale charmap"
$ locale -a | grep -i ja_jp
JA_JP.UTF-8
JA_JP
Ja_JP.IBM-932
Ja_JP.IBM-943
Ja_JP
ja_JP.IBM-eucJP
ja_JP.UTF-8
ja_JP

AIX's locale name was generated by ${LANG%.*}.$(locale charmap).
See following output, file name was case sensitive.
$ echo 'echo ${LANG%.\*}.$(locale charmap)' | LANG=JA_JP sh -s
JA_JP.UTF-8
$ echo 'echo ${LANG%.\*}.$(locale charmap)' | LANG=JA_JP.UTF-8 sh -s
JA_JP.UTF-8
$ echo 'echo ${LANG%.\*}.$(locale charmap)' | LANG=ja_JP.UTF-8 sh -s
ja_JP.UTF-8

Currently, test case is used JA_JP only.
But ja_JP.UTF-8 locale will be used in future.
Anyway, I can remove \*ja_JP.UTF-8\* files.

**Comment by takiguc** [comment]
Hello @smlambert 
Linux x86_64 CI machine did not have Japanese (ja_JP.UTF-8) and Korean (ko_KR.UTF-8) locales.
Could you check ansible playbook was applied ?

**Comment by smlambert** [comment]
I am pretty certain the updated playbooks were not applied yet as the PR is not merged (additional changes were requested on https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/624).

**Comment by smlambert** [comment]
Are there a different naming options that can be used for the ja_JP.UTF-8 files, rather than temporarily deleting them, and especially if they are to be used in future?  As they are named now, people working on osx will not be able to rebase their openjdk-tests repos.

**Comment by takiguc** [comment]
Following 11 files were removed
- functional/MBCS_Tests/data/test_AIX_ja_JP.UTF-8
- functional/MBCS_Tests/data/test_AIX_ko_KR.UTF-8
- functional/MBCS_Tests/file/data/AIX_ja_JP.UTF-8.tar.gz
- functional/MBCS_Tests/file/data/AIX_ko_KR.UTF-8.tar.gz
- functional/MBCS_Tests/i18n/data/aix_ja_JP.UTF-8.txt
- functional/MBCS_Tests/i18n/data/aix_ko_KR.UTF-8.txt
- functional/MBCS_Tests/i18n/expected/aix_ja_JP.UTF-8/BreakIteratorTest.out
- functional/MBCS_Tests/i18n/expected/aix_ja_JP.UTF-8/showlocale.out
- functional/MBCS_Tests/i18n/expected/aix_ko_KR.UTF-8/BreakIteratorTest.out
- functional/MBCS_Tests/i18n/expected/aix_ko_KR.UTF-8/showlocale.out
- functional/MBCS_Tests/jdbc41/data/setjdbc41_AIX_ja_JP.UTF-8
