### ISSUE TITLE
Fix Jenkins setup for jcov tests

### ISSUE THREAD

**Issue by stooke** [AdoptOpenJDK/openjdk-tests#779]
The jcov tests keep failing [1] (note especially the "override ignored" lines), because the Jenkins script downloads and specifies ASM-6.0 [2].
However, this commit [3]  in OpenJDK modifies jcov to require ASM 7.0:
The fix is to change the Jenkins script to specify ASM-7.0 as appropriate.

[1] https://ci.adoptopenjdk.net/view/Build%20Monitor/job/jcov/144/console
[2] https://ci.adoptopenjdk.net/view/Build%20Monitor/job/jcov/configure
[3] http://hg.openjdk.java.net/code-tools/jcov/rev/18b0a143e1c2

**Comment by sophia-guo** [comment]
[This is jcov build jobs](https://ci.adoptopenjdk.net/view/Build%20Monitor/job/jcov/) is jcov build jobs, which will also affect jtreg build jobs(https://ci.adoptopenjdk.net/view/Build%20Monitor/job/jtreg/). In this case the jcov.jar in jtreg build jobs will keep the latest successful jcov jar, which is around last November. @karianna , I guess this issue should be opened in build repo? or is there a specific repo for those dependent jobs?

**Comment by karianna** [comment]
> [This is jcov build jobs](https://ci.adoptopenjdk.net/view/Build%20Monitor/job/jcov/) . The issue will also affect jtreg build jobs(https://ci.adoptopenjdk.net/view/Build%20Monitor/job/jtreg/). In this case the jcov.jar in jtreg build jobs will keep the latest successful jcov jar, which is around last November. @karianna , I guess this issue should be opened in build repo? or is there a specific repo for those dependent build jobs?

Yes please open in openjdk-build

**Comment by stooke** [comment]
To clarify, I should close this issue and reopen in openjdk-build?

**Comment by sophia-guo** [comment]
yes, please. Thanks

**Comment by stooke** [comment]
Closing this and reopening as https://github.com/AdoptOpenJDK/openjdk-build/issues/823

**Comment by smlambert** [comment]
@stooke @sophia-guo - apologies, I should have looked more closely for where to create the issue.
