### ISSUE TITLE
testEnvTeardown target is called before compiling and running tests

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#783]
testEnvTeardown is called before compiling and running tests. Originally idea is we need to do testEnvTeardown before running.

@renfeiw any concern to remove it from compiling process?
Talked with @llxia including remove it from compiling process another step would be moving it to setup stage though it will be another issue.

**Comment by renfeiw** [comment]
@sophia-guo I agree that it should be removed from compiling.

**Comment by sophia-guo** [comment]
Closed by #785
