### ISSUE TITLE
Review all failed tests for the build: openjdk11_hs_openjdktest_aarch32_linux 

### ISSUE THREAD

**Issue by jabrena** [AdoptOpenJDK/openjdk-tests#802]
In order to deliver an official build for aarch32, it is necessary to clean all failed tests that appear in the last build. The build passed the mayority of the tests:
https://ci.adoptopenjdk.net/job/openjdk11_hs_openjdktest_aarch32_linux/

But exist some tests that require more attention:
https://ci.adoptopenjdk.net/job/openjdk11_hs_openjdktest_aarch32_linux/3/#showFailuresLink
https://ci.adoptopenjdk.net/job/openjdk11_hs_openjdktest_aarch32_linux/3/testReport/
https://ci.adoptopenjdk.net/job/openjdk11_hs_openjdktest_aarch32_linux/3/artifact/

It is necessary to analyze and review in team with the team in order to pass the process, following the testing methodology.

**Test failed to analyze:**

- [ ] com/sun/net/httpserver/SelCacheTest.java.SelCacheTest
- [ ] com/sun/net/httpserver/Test1.java.Test1
- [ ] com/sun/net/httpserver/Test6a.java.Test6a
- [ ] com/sun/net/httpserver/Test7a.java.Test7a
- [ ] com/sun/net/httpserver/Test8a.java.Test8a
- [ ] com/sun/net/httpserver/Test9.java.Test9
- [ ] com/sun/net/httpserver/Test9a.java.Test9a
- [ ]  java/lang/String/StringRepeat.java.StringRepeat
- [ ]  java/net/HttpURLConnection/SetAuthenticator/HTTPSetAuthenticatorTest.java.HTTPSetAuthenticatorTest
- [ ]  java/net/HttpURLConnection/SetAuthenticator/HTTPTest.java.HTTPTest
- [ ]  java/net/URLPermission/URLTest.java.URLTest
- [ ]  java/net/httpclient/AsFileDownloadTest.java.AsFileDownloadTest
- [ ]  java/net/httpclient/BasicRedirectTest.java.BasicRedirectTest
- [ ]  java/net/httpclient/CancelledResponse.java.CancelledResponse
- [ ]  java/net/httpclient/ConcurrentResponses.java.ConcurrentResponses
- [ ]  java/net/httpclient/CookieHeaderTest.java.CookieHeaderTest
- [ ]  java/net/httpclient/CustomRequestPublisher.java.CustomRequestPublisher
- [ ]  java/net/httpclient/CustomResponseSubscriber.java.CustomResponseSubscriber
- [ ]  java/net/httpclient/DependentActionsTest.java.DependentActionsTest
- [ ]  java/net/httpclient/DependentPromiseActionsTest.java.DependentPromiseActionsTest
- [ ]  java/net/httpclient/DigestEchoClientSSL.java.DigestEchoClientSSL
- [ ]  java/net/httpclient/EncodedCharsInURI.java.EncodedCharsInURI
- [ ]  java/net/httpclient/EscapedOctetsInURI.java.EscapedOctetsInURI
- [ ]  java/net/httpclient/ExpectContinue.java.ExpectContinue
- [ ]  java/net/httpclient/FlowAdapterPublisherTest.java.FlowAdapterPublisherTest
- [ ]  java/net/httpclient/FlowAdapterSubscriberTest.java.FlowAdapterSubscriberTest
- [ ]  java/net/httpclient/HeadTest.java.HeadTest
- [ ]  java/net/httpclient/HttpsTunnelTest.java.HttpsTunnelTest
- [ ]  java/net/httpclient/ImmutableFlowItems.java.ImmutableFlowItems
- [ ]  java/net/httpclient/InvalidInputStreamSubscriptionRequest.java.InvalidInputStreamSubscriptionRequest
- [ ]  java/net/httpclient/InvalidSSLContextTest.java.InvalidSSLContextTest
- [ ]  java/net/httpclient/InvalidSubscriptionRequest.java.InvalidSubscriptionRequest
- [ ]  java/net/httpclient/LineBodyHandlerTest.java.LineBodyHandlerTest
- [ ]  java/net/httpclient/ManyRequests.java.ManyRequests
- [ ]  java/net/httpclient/ManyRequests2.java.ManyRequests2
- [ ]  java/net/httpclient/ManyRequestsLegacy.java.ManyRequestsLegacy
- [ ]  java/net/httpclient/MappingResponseSubscriber.java.MappingResponseSubscriber
- [ ]  java/net/httpclient/MaxStreams.java.MaxStreams
- [ ]  java/net/httpclient/NoBodyPartOne.java.NoBodyPartOne
- [ ]  java/net/httpclient/NoBodyPartTwo.java.NoBodyPartTwo
- [ ]  java/net/httpclient/NonAsciiCharsInURI.java.NonAsciiCharsInURI
- [ ]  java/net/httpclient/ProxyAuthDisabledSchemesSSL.java.ProxyAuthDisabledSchemesSSL
- [ ]  java/net/httpclient/ProxyTest.java.ProxyTest
- [ ]  java/net/httpclient/RedirectMethodChange.java.RedirectMethodChange
- [ ]  java/net/httpclient/RedirectWithCookie.java.RedirectWithCookie
- [ ]  java/net/httpclient/RequestBodyTest.java.RequestBodyTest
- [ ]  java/net/httpclient/ResponseBodyBeforeError.java.ResponseBodyBeforeError
- [ ]  java/net/httpclient/ResponsePublisher.java.ResponsePublisher
- [ ]  java/net/httpclient/RetryWithCookie.java.RetryWithCookie
- [ ]  java/net/httpclient/ServerCloseTest.java.ServerCloseTest
- [ ]  java/net/httpclient/ShortResponseBody.java.ShortResponseBody
- [ ]  java/net/httpclient/ShortResponseBodyWithRetry.java.ShortResponseBodyWithRetry
- [ ]  java/net/httpclient/SmokeTest.java.SmokeTest
- [ ]  java/net/httpclient/SpecialHeadersTest.java.SpecialHeadersTest
- [ ]  java/net/httpclient/SplitResponseSSL.java.SplitResponseSSL
- [ ]  java/net/httpclient/SplitResponseSSLAsync.java.SplitResponseSSLAsync
- [ ]  java/net/httpclient/SplitResponseSSLKeepAlive.java.SplitResponseSSLKeepAlive
- [ ]  java/net/httpclient/SplitResponseSSLKeepAliveAsync.java.SplitResponseSSLKeepAliveAsync
- [ ]  java/net/httpclient/StreamingBody.java.StreamingBody
- [ ]  java/net/httpclient/ThrowingPublishersCustomAfterCancel.java.ThrowingPublishersCustomAfterCancel
- [ ]  java/net/httpclient/ThrowingPublishersCustomBeforeCancel.java.ThrowingPublishersCustomBeforeCancel
- [ ]  java/net/httpclient/ThrowingPublishersIOAfterCancel.java.ThrowingPublishersIOAfterCancel
- [ ]  java/net/httpclient/ThrowingPublishersIOBeforeCancel.java.ThrowingPublishersIOBeforeCancel
- [ ]  java/net/httpclient/ThrowingPublishersInNextRequest.java.ThrowingPublishersInNextRequest
- [ ]  java/net/httpclient/ThrowingPublishersInRequest.java.ThrowingPublishersInRequest
- [ ]  java/net/httpclient/ThrowingPublishersInSubscribe.java.ThrowingPublishersInSubscribe
- [ ]  java/net/httpclient/ThrowingPublishersSanity.java.ThrowingPublishersSanity
- [ ]  java/net/httpclient/ThrowingPushPromisesAsInputStreamCustom.java.ThrowingPushPromisesAsInputStreamCustom
- [ ]  java/net/httpclient/ThrowingPushPromisesAsInputStreamIO.java.ThrowingPushPromisesAsInputStreamIO
- [ ]  java/net/httpclient/ThrowingPushPromisesAsLinesCustom.java.ThrowingPushPromisesAsLinesCustom
- [ ]  java/net/httpclient/ThrowingPushPromisesAsLinesIO.java.ThrowingPushPromisesAsLinesIO
- [ ]  java/net/httpclient/ThrowingPushPromisesAsStringCustom.java.ThrowingPushPromisesAsStringCustom
- [ ]  java/net/httpclient/ThrowingPushPromisesAsStringIO.java.ThrowingPushPromisesAsStringIO
- [ ]  java/net/httpclient/ThrowingPushPromisesSanity.java.ThrowingPushPromisesSanity
- [ ]  java/net/httpclient/ThrowingSubscribersAsInputStream.java.ThrowingSubscribersAsInputStream
- [ ]  java/net/httpclient/ThrowingSubscribersAsInputStreamAsync.java.ThrowingSubscribersAsInputStreamAsync
- [ ]  java/net/httpclient/ThrowingSubscribersAsLines.java.ThrowingSubscribersAsLines
- [ ]  java/net/httpclient/ThrowingSubscribersAsLinesAsync.java.ThrowingSubscribersAsLinesAsync
- [ ]  java/net/httpclient/ThrowingSubscribersAsString.java.ThrowingSubscribersAsString
- [ ]  java/net/httpclient/ThrowingSubscribersAsStringAsync.java.ThrowingSubscribersAsStringAsync
- [ ]  java/net/httpclient/ThrowingSubscribersSanity.java.ThrowingSubscribersSanity
- [ ]  java/net/httpclient/UnauthorizedTest.java.UnauthorizedTest
- [ ]  java/net/httpclient/UnknownBodyLengthTest.java.UnknownBodyLengthTest
- [ ]  java/net/httpclient/http2/BadHeadersTest.java.BadHeadersTest
- [ ]  java/net/httpclient/http2/BasicTest.java.BasicTest
- [ ]  java/net/httpclient/http2/ContinuationFrameTest.java.ContinuationFrameTest
- [ ]  java/net/httpclient/http2/FixedThreadPoolTest.java.FixedThreadPoolTest
- [ ]  java/net/httpclient/http2/NoBodyTest.java.NoBodyTest
- [ ]  java/net/httpclient/http2/ProxyTest2.java.ProxyTest2
- [ ]  java/net/httpclient/http2/TLSConnection.java.TLSConnection
- [ ]  java/net/httpclient/http2/Timeout.java.Timeout
- [ ]  java/net/httpclient/websocket/WSHandshakeExceptionTest.java.WSHandshakeExceptionTest
- [ ]  java/net/httpclient/whitebox/FlowTestDriver.java.FlowTestDriver
- [ ]  java/net/httpclient/whitebox/SSLEchoTubeTestDriver.java.SSLEchoTubeTestDriver
- [ ]  java/net/httpclient/whitebox/SSLTubeTestDriver.java.SSLTubeTestDriver
- [ ]  java/nio/file/DirectoryStream/SecureDS.java.SecureDS
- [ ]  java/rmi/server/UnicastRemoteObject/exportObject/GcDuringExport.java.GcDuringExport
- [ ]  java/security/KeyAgreement/KeyAgreementTest.java.KeyAgreementTest
- [ ]  java/security/KeyAgreement/KeySizeTest.java.KeySizeTest
- [ ]  java/security/KeyAgreement/KeySpecTest.java.KeySpecTest
- [ ]  java/security/KeyAgreement/MultiThreadTest.java.MultiThreadTest
- [ ]  sun/net/www/http/HttpClient/B8025710.java.B8025710
- [ ]  sun/net/www/protocol/http/RedirectOnPost.java.RedirectOnPost
- [ ]  sun/net/www/protocol/https/ChunkedOutputStream.java.ChunkedOutputStream
- [ ]  sun/net/www/protocol/https/HttpsClient/ProxyAuthTest.java.ProxyAuthTest
- [ ]  sun/net/www/protocol/https/HttpsClient/ServerIdentityTest.java.ServerIdentityTest
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/B6216082.java.B6216082
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/CookieHandlerTest.java.CookieHandlerTest
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/CookieHttpsClientTest.java.CookieHttpsClientTest
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/DNSIdentities.java.DNSIdentities
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/HttpsPost.java.HttpsPost
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/IPAddressIPIdentities.java.IPAddressIPIdentities
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/IPIdentities.java.IPIdentities
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/Identities.java.Identities
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/ImpactOnSNI.java.ImpactOnSNI
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/PostThruProxy.java.PostThruProxy
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/PostThruProxyWithAuth.java.PostThruProxyWithAuth
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/ReadTimeout.java.ReadTimeout
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/Redirect.java.Redirect
- [ ]  sun/net/www/protocol/https/HttpsURLConnection/RetryHttps.java.RetryHttps
- [ ]  sun/net/www/protocol/https/NewImpl/ComHTTPSConnection.java.ComHTTPSConnection
- [ ]  sun/net/www/protocol/https/NewImpl/JavaxHTTPSConnection.java.JavaxHTTPSConnection

**Comment by nickg** [comment]
java/nio/file/DirectoryStream/SecureDS.java.SecureDS --> I submitted a patch to upstream OpenJDK a few months ago to fix this one, you can probably just backport it?
http://hg.openjdk.java.net/jdk/jdk/rev/09a3f379b927

**Comment by nickg** [comment]
> Great! Did this land on jdk/jdk and are you able to create a backport request upstream?

It's in jdk/jdk and jdk/jdk12. I'm not sure how to get it backported to 11 but I can try to find out.

**Comment by karianna** [comment]
> > Great! Did this land on jdk/jdk and are you able to create a backport request upstream?
> 
> It's in jdk/jdk and jdk/jdk12. I'm not sure how to get it backported to 11 but I can try to find out.

You'll need to raise a backport request in the jdk11-updates project (mailing list).  Basically you say "There's a fix JDK-%^$%^£ in jdk/jdk that I'd like to backport.  Here's the patch <insert diff / webrev> can I get a sponsor to create an issue please?"

**Comment by smlambert** [comment]
@sxa - while this is a fairly old issue, we can either update it with the intermittent failures seen in sanity.openjdk tests or reference in a new issue (& close this one).

In a [recent test run](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_arm_linux/109/testReport/), 2 test cases failing out of 1321 run as part of the sanity.openjdk target.  

<img width="1299" alt="Screen Shot 2020-11-17 at 10 38 34 PM" src="https://user-images.githubusercontent.com/2836948/99480316-d7717d80-2925-11eb-8146-2f791317b154.png">

**Comment by sxa** [comment]
This issue was for OpenJDK11 which is now [running green](https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_aarch32_linux) so I vote we close this, declare success with the original issue and spin out a new one for JDK8 ;-)
