### ISSUE TITLE
Setting up openjdk extended tests as weekly job

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#809]
Currently openjdk sanity tests are running daily as jenkins test job( some of them are running the whole set - sanity+extended, will update that. https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_linux/) We'd like to set up extended level tests jobs weekly. https://ci.adoptopenjdk.net/view/Test_weekly/

**Comment by sophia-guo** [comment]
Just noticed that external extended tests are running as daily is this expected?
https://ci.adoptopenjdk.net/view/Test_external/
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk11_hs_externaltest_extended_x86-64_linux/

**Comment by smlambert** [comment]
For now it is what we intended, but I want to switch it to a weekly schedule (and also trigger it in release testing).

**Comment by smlambert** [comment]
Also, we did the external_extended builds in an expensive way, creating entirely separate jobs for them rather than using same job but passing TARGET parameter.  So I have put off this item until now, as we may want to do same as build pipelines, where we generate the job (with a useful job name), and not have it be a separate job config in Jenkins.

**Comment by smlambert** [comment]
We will also want extended.system (and eventually special.system, when MBCS infra issues done) running weekly.

**Comment by sophia-guo** [comment]
I've created jdk8 extended jobs manually and will run once to give the idea how long it takes for different platform/impl.  

The next step is to use same similar story as build jobs to automatically generate jobs by template, which should also work for sanity test jobs. The benefit is when new java version come we don't need to manually create new test jobs and delete/disable the old ones.

**Comment by smlambert** [comment]
Sounds great!  Its fine to use manual approach for now, but as you say, we continue to expand, so we will eventually want the auto-gen approach.

**Comment by sophia-guo** [comment]
Close it as it's done. Auto-gen would be next step for all test jobs. Will open a different issue.
