### ISSUE TITLE
Modify functional tests in thirdparty containers to parameterize some of the settings

### ISSUE THREAD

**Issue by chandrams** [AdoptOpenJDK/openjdk-tests#824]
Issues that need to be addressed in the functional tests run in external tests

 -   environment variables (such as SPEC, JDK_VERION, JDK_IMPL, etc) should be set. They should be passed in as parameters.
-    test target (i.e., _sanity.functional) should be passed in a parameter, so we can run other targets (i.e., extended.functional, special.functional)

**Comment by smlambert** [comment]
Related: openj9 PR https://github.com/eclipse/openj9/pull/4843

**Comment by chandrams** [comment]
Closing this as the above PR is merged
