### ISSUE TITLE
Run external testing in parallel (1 Jenkins job per application)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#834]
Instead of running all the application tests in a single Jenkins job, have a parent job fire off child jobs per app.  This is the same approach we use for system tests.  

Benefits of this approach are:
- easier to triage (smaller console output and junit output doesn't get garbled with others)
- won't hit the timeout as we add new testing (with recent additions a single job can take up to 10hrs, which is our default timeout on jobs)

**Comment by sophia-guo** [comment]
Closed by #991
