### ISSUE TITLE
Stop supporting JAVA_VERSION in testing

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#869]
Currently, we are supporting both `JAVA_VERSION` and `JDK_VERSION` as the parameter in the test Jenkins script and TKG. Initially, this was a temporary approach, as our ultimate goal is to completely switch to use `JDK_VERSION`. We should not keep maintaining the temporary code for `JAVA_VERSION` to `JDK_VERSION` mapping (https://github.com/eclipse/openj9/pull/4645).

This issue is to remove supporting `JAVA_VERSION` completely.

ToDos:
- [x] Jenkinsfilebase needs to update to make sure `JDK_VERSION` works
- [x] Update test jobs and grinders to set `JDK_VERSION` in job configure and remove `JAVA_VERSION` (depends how the test job is invoked, this may not be a blocker)
- [ ] Request upstream jobs to pass in `JDK_VERSION` if needed
- [ ] Remove temporary code for `JAVA_VERSION` to `JDK_VERSION` mapping in Jenkinsfile and TKG
- [ ] Update docs/wiki/readme accordingly

**Comment by llxia** [comment]
If auto detects JDK_VERSION, JDK_IMPL and SPEC are completed https://github.com/eclipse/openj9/issues/442, then `JDK_VERSION` and `JDK_IMPL` are not needed in the regular test builds. However, Jenkinsfilebase still needs to be updated to accept `JDK_VERSION`. If the user chooses `nightly` in Grinder, `JDK_VERSION` and `JDK_IMPL` are still needed.

**Comment by keithc-ca** [comment]
Shall we assume the references to `JAVA_VESION` are just typos that should say `JAVA_VERSION`?

**Comment by llxia** [comment]
yes, description is updated. Thanks

**Comment by AdamBrousseau** [comment]
Can this be blocked on #837? Otherwise I (we) will have to manually update a few hundred Jenkins jobs.

**Comment by llxia** [comment]
I do not think this is necessarily blocked by #837. Although #837 is a good idea, I also would like to investigate if we could generate the job dynamically.

As you mentioned, upstream jobs could pass `JDK_VERSION` into test jobs. At the moment, the test script will check for `JAVA_VERSION` only if `JDK_VERSION` is not set. 
btw, with the completion of eclipse/openj9#442, test job does not need `JDK_VERSION` to be set.

**Comment by llxia** [comment]
Close this as it is a dup of #563
