### ISSUE TITLE
MBCS_Tests CLDR was failed with JDK 11.0.2

### ISSUE THREAD

**Issue by takiguc** [AdoptOpenJDK/openjdk-tests#870]
According to following URL, 2 testcases were failed:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1011/tapTestReport/
* 68 - - MBCS_Tests_CLDR_11_ja_JP_linux_0
* 69 - - MBCS_Tests_CLDR_11_ko_KR_linux_0

JDK 11.0.2 was used for this testing.

I executed current MBCS_Tests testcases with 11.0.1, it worked fine:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1021/tapTestReport/

**Comment by smlambert** [comment]
More details from [tapResults](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1011/tapResults/)

MBCS_Tests_CLDR_11_ja_JP_linux_0 - failed 11 tests of 42
MBCS_Tests_CLDR_11_ko_KR_linux_0 - failed 11 tests of 42

not ok 20 - diff CurrencyTest-ja-JP-DEFAULT.log expected_CurrencyTest-ja-JP-DEFAULT.log
not ok 21 - diff CurrencyTest-ja-JP-CLDR.log expected_CurrencyTest-ja-JP-CLDR.log
not ok 22 - diff CurrencyTest-ja-JP-JRE.log expected_CurrencyTest-ja-JP-JRE.log
not ok 23 - diff CurrencyTest-ja-JP-HOST.log expected_CurrencyTest-ja-JP-HOST.log
not ok 24 - diff CurrencyTest-ja-JP-SPI.log expected_CurrencyTest-ja-JP-SPI.log
not ok 36 - diff TimeZoneTestA-ja-JP-CLDR.log expected_TimeZoneTestA-ja-JP-CLDR.log
not ok 38 - diff TimeZoneTestB-ja-JP-DEFAULT.log expected_TimeZoneTestB-ja-JP-DEFAULT.log
not ok 39 - diff TimeZoneTestB-ja-JP-CLDR.log expected_TimeZoneTestB-ja-JP-CLDR.log
not ok 40 - diff TimeZoneTestB-ja-JP-JRE.log expected_TimeZoneTestB-ja-JP-JRE.log
not ok 41 - diff TimeZoneTestB-ja-JP-HOST.log expected_TimeZoneTestB-ja-JP-HOST.log
not ok 42 - diff TimeZoneTestB-ja-JP-SPI.log expected_TimeZoneTestB-ja-JP-SPI.log

**Comment by takiguc** [comment]
On my investigation, above errors were related following code changes:

Currency issue:
https://bugs.openjdk.java.net/browse/JDK-8212103
not ok 20 - diff CurrencyTest-ja-JP-DEFAULT.log expected_CurrencyTest-ja-JP-DEFAULT.log
not ok 21 - diff CurrencyTest-ja-JP-CLDR.log expected_CurrencyTest-ja-JP-CLDR.log
not ok 22 - diff CurrencyTest-ja-JP-JRE.log expected_CurrencyTest-ja-JP-JRE.log
not ok 23 - diff CurrencyTest-ja-JP-HOST.log expected_CurrencyTest-ja-JP-HOST.log
not ok 24 - diff CurrencyTest-ja-JP-SPI.log expected_CurrencyTest-ja-JP-SPI.log

CLDR issue:
https://bugs.openjdk.java.net/browse/JDK-8212746
not ok 36 - diff TimeZoneTestA-ja-JP-CLDR.log expected_TimeZoneTestA-ja-JP-CLDR.log

TimeZone issue:
https://bugs.openjdk.java.net/browse/JDK-8214318
not ok 38 - diff TimeZoneTestB-ja-JP-DEFAULT.log expected_TimeZoneTestB-ja-JP-DEFAULT.log
not ok 39 - diff TimeZoneTestB-ja-JP-CLDR.log expected_TimeZoneTestB-ja-JP-CLDR.log
not ok 40 - diff TimeZoneTestB-ja-JP-JRE.log expected_TimeZoneTestB-ja-JP-JRE.log
not ok 41 - diff TimeZoneTestB-ja-JP-HOST.log expected_TimeZoneTestB-ja-JP-HOST.log
not ok 42 - diff TimeZoneTestB-ja-JP-SPI.log expected_TimeZoneTestB-ja-JP-SPI.log

**Comment by takiguc** [comment]
I'd like to take care this issue, could you assign it to me ?
