### ISSUE TITLE
update playlist.xml in MBCS_Tests to use jdkVersion+

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#871]
The test framework is enhanced to use jdkVersion+ in `<subset>`. We need to update playlist.xml in MBCS_Tests to use this feature, so that we do not need to manually add new subset when there is new java release.

We can refer to PR #832 as an example.

**Comment by llxia** [comment]
@takiguc Could you please help on this issue? Thanks

**Comment by takiguc** [comment]
OK, I'll handle this issue.

**Comment by llxia** [comment]
Thank you @takiguc

**Comment by toshiona** [comment]
As Takiguchi-san's request, I created PR #895.
