### ISSUE TITLE
update ProblemList_openjdk11 for jdk_beans  

### ISSUE THREAD

**Issue by navyxliu** [AdoptOpenJDK/openjdk-tests#877]
https://github.com/AdoptOpenJDK/openjdk-tests/blob/e17b1e59433c7839df331c81344e972e9240a016/openjdk_regression/ProblemList_openjdk11.txt#L19

I ran into 10 failures in jdk_beans_0 for openjdk11. 

java/beans/PropertyEditor/6380849/TestPropertyEditor.java
java/beans/PropertyEditor/TestColorClass.java
java/beans/PropertyEditor/TestColorClassJava.java
java/beans/PropertyEditor/TestColorClassNull.java
java/beans/PropertyEditor/TestColorClassValue.java
java/beans/PropertyEditor/TestFontClass.java
java/beans/PropertyEditor/TestFontClassJava.java
java/beans/PropertyEditor/TestFontClassNull.java
java/beans/PropertyEditor/TestFontClassValue.java
java/beans/XMLEncoder/java_awt_ScrollPane.java

I tried different Linux systems and they are reproducible.

**Comment by smlambert** [comment]
Thanks for the report @navyxliu , can you check and see if these failures are already reported in the java bug DB?  

Guidance here: https://github.com/AdoptOpenJDK/openjdk-tests/wiki/Guidance-for-Creating-OpenJDK-Test-Defects

**Comment by navyxliu** [comment]
Thanks.  I do find a record in JBS [JDK-8030104](https://bugs.openjdk.java.net/browse/JDK-8030104)

As the JDK-8030104 says, it's not a bug. those 10 tests need to run in headful environment. 
if Xvfb is present, all of them can pass. 

```bash
/usr/bin/nohup Xvfb -fbdir `pwd` -pixdepths 8 16 24 32 :1 &
```

**Comment by smlambert** [comment]
thanks for confirming !
