### ISSUE TITLE
openjdk11_j9_openjdktest_ppc64_aix tests not running

### ISSUE THREAD

**Issue by StephanieMeakins** [AdoptOpenJDK/openjdk-tests#883]
The below tests should run over the weekend (due to the a lack of dedicated test machine). The only tests I can see have all been kicked off by members of the team and it doesn't look like these tests have ever run automatically.

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_ppc64_aix/

@sxa555

**Comment by smlambert** [comment]
I have scheduled these tests to run 2x / week (Wed/Sun).  The build machine is still offline, so the scheduled jobs will fail to find a node to run on.  

I am deleting old jdk9 build workspaces on the offline machine to see if that makes enough space on the machine to bring it back online.  If not, will suggest you raise an issue at openjdk-infrastructure.
