### ISSUE TITLE
Generate test jobs dynamically

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#890]
As we continue to expand, we would like to have an auto-gen approach for creating/updating/maintaining test jobs. Use [Job DSL Plugin](https://wiki.jenkins.io/display/JENKINS/Job+DSL+Plugin), we can auto-generate test jobs in one simple script.

Test jobs will be created based on LEVEL, GROUP, JDK_VERSION and SPEC (i.e., `Test-${LEVEL}.${GROUP}-JDK${JDK_VERSION}-${SPEC}`). A view will also be created to group the tests. (i.e., Test_functional, Test_system, Test_openjdk)

DSL Plugin API: https://jenkinsci.github.io/job-dsl-plugin/

This solution will help the following issues: #809 #837 #869

**Comment by smlambert** [comment]
We could consider doing as build jobs to use folders to contain the test groups / versions, which could eliminate the need for the different tabbed views.

**Comment by llxia** [comment]
yes, I agree. Also, it would be better to have the same name convention between AdoptOpenJDK and elsewhere, it will be easier for us to maintain and easier for users to find builds.
