### ISSUE TITLE
Add support for running personal system test repos in Grinder

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#891]
We need to add support for running personal system test repos in Grinder, so that users can easily run a test with their own system test repos. Currently, they have to manually update common.xml and create AdoptOpenJDK branch. See https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/73#issuecomment-463219623

stf, adopt system test, openj9 system test repo should set as parameters. These parameters can set in Grinder, so that users can set them to their own repos.

To avoid parameter explosion in the exiting Grinder, maybe we should create a separate Grinder job for system test. For example, we can call it `Grinder-systemtest`. `Grinder-systemtest` should use the same Jenkinsfile as the regular Grinder but with specific variables for system test.

**Comment by smlambert** [comment]
Agree, that is a nice way to handle it.
