### ISSUE TITLE
Add openjdk regression tests to test build

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#9]
Right now the test build runs just the 2 example tests provided in this repo.  

Next step is to start running some of the openjdk regression tests.  2 parts to this task:
1) Ensuring the tests are available on the test machines as part of setup stage.
2) Edit the OpenJDK_Playlist/playlist.xml file.  We can leverage what has already been done in the jtreg.sh script (can even call it directly with the appropriate parameters as long as we grab the script as part of setup stage too).  

Depending on how fast the different groups of jtreg tests run, we can tag them as sanity if fast, extended if longer running.  

First group to include in the test build can be the hotspot tests.

**Comment by neomatrix369** [comment]
Some of the work can be found in:
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/makejdk.sh (called only by `makejdk-any-platform.sh`)
https://github.com/AdoptOpenJDK/openjdk-build/tree/master/sbin

**Comment by smlambert** [comment]
@sophia-guo i think you have enabled all the test groups, can this be closed now?

**Comment by sophia-guo** [comment]
yes, correct.
