### ISSUE TITLE
PR build job didn't update commit status during build

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#90]
When a new pull request is opened in the project and the author of the pull request isn't white-listed, builder will ask "Can one of the admins verify this patch?".
"ok to test" to accept this pull request for testing.

Under this scenario, pr build is launched. However PR build job didn't update commit status during build.

Infor from concole;
FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or the user account does not have write access to the repo.

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/PR_sanity_openjdk_test_x86-64_linux/41/
didn't update status in https://github.com/AdoptOpenJDK/openjdk-tests/pull/88

**Comment by sophia-guo** [comment]
It's probably because the user is not in whitelist. @renfeiw is now in the whitelist, we will see as he will have another PR in a short time.

**Comment by smlambert** [comment]
What is the status of this issue, is it resolved and can be closed?

**Comment by smlambert** [comment]
I believe this can be closed, as we use Grinders and Sandbox builds to test changes.  @sophia-guo 
 if you disagree, please re-open.
