### ISSUE TITLE
JenkinsfileBase clean up

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#902]
To avoid parameters explosion, we should try to clean up JenkinsfileBase:

- investigate if we can group up parameters and pass in as an object (i.e., group up the following VENDOR_TEST_REPOS, VENDOR_TEST_BRANCHES, VENDOR_TEST_SHAS, VENDOR_TEST_DIRS)
- combine parameters:
     - KEEP_REPORTDIR (controls at TKG level) and ARCHIVE_TEST_RESULTS (controls at Jenkins level). They should be combined into one parameter.
     - CUSTOMIZED_SDK_URL and SDK_RESOURCE. In the initial design, CUSTOMIZED_SDK_URL should be used when SDK_RESOURCE=customized. But in the current code, if CUSTOMIZED_SDK_URL is provided, we ignore SDK_RESOURCE value. I think they can be combined into one as well.

Please feel free to add more items to this issue if there is any place that we can improve.

**Comment by smlambert** [comment]
Making notes:

SDK_RESOURCE actually holds 4 values, it can be set to 

- nightly - picks up nightly build from Adopt API
- releases - picks up release build from Adopt API
- customized - uses CUSTOMIZED_SDK_URL
- upstream - uses the 2 upstream params, UPSTREAM_JOB_NAME, UPSTREAM_JOB_NUMBER
- 

In the last 2 cases, you could essentially ignore SDK_RESOURCE if the related params are filled. 
 So you could remove them as choices in the SDK_RESOURCE choices list.  

Caveat: if someone mistakenly fills CUSTOMIZED_SDK_URL and UPSTREAM_JOB_NAME, UPSTREAM_JOB_NUMBER, I guess it'll be what ever code is checked last that decides where to pull the SDK from, as there is no way to know what user intended.

**Comment by llxia** [comment]
> * investigate if we can group up parameters and pass in as an object (i.e., group up the following VENDOR_TEST_REPOS, VENDOR_TEST_BRANCHES, VENDOR_TEST_SHAS, VENDOR_TEST_DIRS)

We are using it build script: 
https://github.com/AdoptOpenJDK/openjdk-build/blob/19e9457ad2bc689009be2956b3c1fad3a2249426/pipelines/build/openjdk_build_pipeline.groovy#L151

https://github.com/AdoptOpenJDK/openjdk-build/blob/09f4c1081d006386fc41883141d008d84da09bb1/pipelines/build/build_base_file.groovy#L226

```
[Pipeline] echo
Executing tests: [javaVersion:jdk11u, arch:aarch64, os:linux, variant:hotspot, parameters:[JAVA_TO_BUILD:jdk11u, NODE_LABEL:centos7&&build&&linux&&aarch64, VARIANT:hotspot, ARCHITECTURE:aarch64, TARGET_OS:linux, BUILD_ARGS:], test:[openjdktest, systemtest, perftest]]
```

**Comment by llxia** [comment]
Continue the discussion of https://github.com/AdoptOpenJDK/openjdk-tests/issues/902#issuecomment-464108636:

One alternative solution is that we can combine all of the parameters into one, say `SDK_RESOURCE`:
- if the value is url, then the script goes and downloads the SDK
- if the value is nightly/release, then the script uses generated nightly/release url
- if the value is <build_name>,<build_number>, then copy Jenkins artifacts from the specified build

**Comment by smlambert** [comment]
@llxia - is this still needed?  

Also, I see that there was a more recent effort for doing some cleanup in this file, https://github.com/AdoptOpenJDK/openjdk-tests/pull/1967

**Comment by llxia** [comment]
We can close this issue.
