### ISSUE TITLE
Leftover images and containers issue

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#915]
There are some images and containers are left over by external test jobs. Need to clean  up and figure out why it happens.

**Comment by sophia-guo** [comment]
- Images are built when doing test compile and then left over. They will only be deleted when external test job doing compile again. 

- Container is automatically removed when it exits. All `docker cp` after `docker run --rm` actually do nothing.

**Comment by sophia-guo** [comment]
images left on test-packet-ubuntu1604-x64-1, which can't be deleted with jenkins user.

<img width="809" alt="screen shot 2019-02-22 at 4 14 22 pm" src="https://user-images.githubusercontent.com/18030625/53271647-1759f100-36bd-11e9-8eaf-e1c380371a9d.png">

**Comment by sophia-guo** [comment]
There is another case we cann't handle right now. Test build is aborted either manually or due to timeout during stage `test running`. In this case either containers or image will be left on slave, which has to be manually clean up.

**Comment by smlambert** [comment]
Likely we can ask infra to run a cron job to clean up machines, to mitigate the cases that we can not handle via Jenkins scripts / Jenkins user id.

**Comment by smlambert** [comment]
did your recent PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/1104 address this fully @sophia-guo ?

**Comment by sophia-guo** [comment]
Yes, this was addressed by a few recent PRs. Close it.
