### ISSUE TITLE
Testing docker needs to be updated to include XML/Parser.pm

### ISSUE THREAD

**Issue by Yuehan-Lin** [AdoptOpenJDK/openjdk-tests#917]
Since makeGenTool/mkgen.pl changed, I got this error message when using `sys-rt-docker-local.artifactory.swg-devops.com/demo:openjdk-test`
```
Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module) 
(@INC contains: ./makeGenTool /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 
/usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 
/usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl 
/usr/lib/x86_64-linux-gnu/perl-base .) at makeGenTool/mkgen.pl line 28.
```

**Comment by llxia** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/docker/Dockerfile needs to be updated. Then we can rebuild and push the update image.

@sophia-guo you may see a similar issue in docker testing if the docker file is not updated.

**Comment by sophia-guo** [comment]
@llxia I haven't seen it yet with my yesterday branch and testing with thirdparty containers tests, which use their own docker file. What's the related PR?

**Comment by sophia-guo** [comment]
If docker need to update should all playbook update too?

**Comment by llxia** [comment]
The change is merged yesterday at noon https://github.com/eclipse/openj9/pull/4785
All playbooks and lab machines are updated already according to infra team.

**Comment by sophia-guo** [comment]
The thing is even with playbooks updated if the machines are reconfigured yet? :) Mainly mean machines in adopt?

**Comment by llxia** [comment]
yes, I think so.

**Comment by sophia-guo** [comment]
Same to external system-test. https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_j9_externaltest_x86-64_linux/356/consoleFull

Current external function-test story doesn't run `make run_configure.mk` step when building image.
