### ISSUE TITLE
Thirdpartycontainer test build failures

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#922]
According to Thirdpartycontainer [test build history](https://ci.adoptopenjdk.net/view/Test_external/) tests running on test-packet-ubuntu1604-x64-1 will consistently fail with 

```
05:41:37      [exec] failed to start shim: exec: "docker-containerd-shim": executable file not found in $PATH: unknown
05:41:37 
05:41:37 BUILD FAILED

```

Grinder shows if running on test-packet-ubuntu1604-x64-3 the problem will go away.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1120/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1121/console

**Comment by smlambert** [comment]
I think the failure described above is overridden with different issue, all tests are failing with:

Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module) (@INC contains: ./makeGenTool /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at makeGenTool/mkgen.pl line 28.
20:46:31       [exec] BEGIN failed--compilation aborted at makeGenTool/mkgen.pl line 28.
20:46:31       [exec] Compilation failed in require at testKitGen.pl line 31.
20:46:31       [exec] [0m[91msettings.mk:46: /openjdk-tests/TestConfig/../TestConfig/utils.mk: No such file or directory
20:46:31       [exec] [0m[91mmakefile:39: count.mk: No such file or directory
20:46:31       [exec] [0m[91mmake: *** No rule to make target 'count.mk'.  Stop.
20:46:31       [exec] The command '/bin/sh -c echo "Generating test targets applicable to the platform, implementation and version..." &&     cd /openjdk-tests/TestConfig &&     make -f run_configure.mk &&     make compile' returned a non-zero code: 2

Need to update all docker images to include it

**Comment by sophia-guo** [comment]
Only function-test and system-test under external test will need XML/Parser.pm module when running the tests, which include configure, build and run tests in containers after tests build  stage of building docker images. Those two tests are actually disabled for now.  All other external tests run the tests in their own way, which don't need Testkitgen tool and don't need to do  `make runconfigure ` step. Hence the module is not necessary.

The failure happened when doing the build compile, i.e. build image for external tests.

**Comment by sophia-guo** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/922#issuecomment-468130548 was addressed in https://github.com/AdoptOpenJDK/openjdk-tests/pull/934

**Comment by sophia-guo** [comment]
Failure consistent on test-packet-ubuntu1604-x64-1. https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_externaltest_extended_x86-64_linux/165/console

**Comment by sophia-guo** [comment]
Issue opened in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/716

**Comment by sophia-guo** [comment]
Looks good now. https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1195/console, close this.
