### ISSUE TITLE
New jdk12 openj9 failures

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#931]
Added jdk12 openj9 linux  and linux_XL  test build and here is the first build failures result 
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_x86-64_linux/1/#showFailuresLink
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_x86-64_linux_linuxXL/1/#showFailuresLink

Both has exactly same failures

FYI @ben-walsh

**Comment by ben-walsh** [comment]
Excellent. Consistent with the set of failures observed via the grinder job against the initial Linux JDK12 build - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1138.

**Comment by sophia-guo** [comment]
Tests have been tracked by specific openj9 issues. Close it.
