### ISSUE TITLE
No need to download SDK in external test build when jdks from docker hub is test target. 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#942]

**Comment by smlambert** [comment]
@sophia-guo - is this issue still relevant?  Based on contents of Dockerfiles, I think its been addressed, though I do not find the related PR

**Comment by sophia-guo** [comment]
No. Currently for external tests we still need to download SDK as for each test we test 'java -version'.

**Comment by sophia-guo** [comment]
Updated as by default in jenkins  TEST_JDK_HOME is external test target. This can be closed.
