### ISSUE TITLE
Thirdparty tomcat test failed with cmd `git clone https://github.com/apache/tomcat85.git`it repo

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#944]
Thirdparty tomcat test failed with cmd `git clone https://github.com/apache/tomcat85.git`it repo

```
06:31:30       [exec] Removing intermediate container 0191a3886577
06:31:30       [exec]  ---> 012497d71b94
06:31:30       [exec] Step 12/14 : RUN git clone https://github.com/apache/tomcat85.git
06:31:30       [exec]  ---> Running in 03072ece45a5
06:31:31       [exec] [91mCloning into 'tomcat85'...
06:31:31       [exec] [0m[91mfatal: could not read Username for 'https://github.com': No such device or address
06:31:32       [exec] The command '/bin/sh -c git clone https://github.com/apache/tomcat85.git' returned a non-zero code: 128
06:31:32       [exec] [0m
06:31:32  
06:31:32  BUILD FAILED
06:31:32  /home/jenkins/workspace/openjdk8_hs_externaltest_x86-64_linux/openjdk-tests/TestConfig/scripts
```

https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_externaltest_x86-64_linux/342/consoleFull

**Comment by sophia-guo** [comment]
FYI @Mesbah-Alam Looks like tomcat85 repo wasn't there anymore.

**Comment by Mesbah-Alam** [comment]
@chandrams - was there any specific reason why tomcat version 85 was used here?

**Comment by Mesbah-Alam** [comment]
I suggest we checkout tomcat from its main repo: https://github.com/apache/tomcat - which seems to be the updated one and build tomcat off of that. I've tried this here: https://github.com/AdoptOpenJDK/openjdk-tests/pull/945
