### ISSUE TITLE
Need JDK12 (non test_openjdk) test pipelines

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#954]

**Comment by smlambert** [comment]
While we do not have enough open machines to currently run jdk8, jdk11, and jdk12 test runs daily, we've created the following jobs and will see how the schedule will need to be adjusted, or disable until machine capacity can be increased: 

j9 system:
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_x86-64_linux/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_x86-64_linux_linuxXL/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_ppc64le_linux/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_s390x_linux/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_x86-64_macos/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_x86-64_macos_macosXL/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_x86-64_windows/

hs system:
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_hs_systemtest_x86-64_linux/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_hs_systemtest_ppc64le_linux/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_hs_systemtest_s390x_linux/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_hs_systemtest_x86-64_macos/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_hs_systemtest_x86-64_windows/

**Comment by smlambert** [comment]
external (disabled for now, as we clean jdk8/jdk11 runs): 
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk12_hs_externaltest_x86-64_linux/
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk12_hs_externaltest_extended_x86-64_linux/
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk12_j9_externaltest_x86-64_linux/
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk12_j9_externaltest_extended_x86-64_linux/

**Comment by smlambert** [comment]
perf:
https://ci.adoptopenjdk.net/view/Test_perf/job/openjdk12_hs_perftest_x86-64_linux/
https://ci.adoptopenjdk.net/view/Test_perf/job/openjdk12_j9_perftest_x86-64_linux/

**Comment by smlambert** [comment]
That is the set of test jobs we will bring online for now.
