### ISSUE TITLE
JDK 11: system tests attempt to copy tools.jar which doesn't exist

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-tests#967]
I'm trying to run system tests on a JDK 11 build:

    $  cat run_adopt_openjdk_system_tests_jdk11.sh
    #!/bin/bash
    set -e
    OPENJDK_SOURCES=$1
    OPENJDK_BUILD=$2
    TEST_TARGET=$3
    if [ -z $TEST_TARGET ]; then
      TEST_TARGET="_system"
    fi
    git clone https://github.com/AdoptOpenJDK/openjdk-tests
    cd openjdk-tests
    TOP_DIR=$(pwd)
    TEST_DIR="$TOP_DIR"
    export JAVA_BIN=$OPENJDK_BUILD/bin
    export SPEC=linux_x86-64
    export JDK_IMPL=hotspot
    export BUILD_LIST=systemtest
    export BUILD_ROOT=$TOP_DIR/test-results
    ./get.sh -t $TEST_DIR
    ./maketest.sh $TEST_DIR
    OPENJDK_DIR=$OPENJDK_SOURCES ./maketest.sh $TEST_DIR $TEST_TARGET
    $ rm -rf test-me-system-jdk11 && mkdir test-me-system-jdk11 && pushd test-me-system-jdk11 && bash ../run_adopt_openjdk_system_tests_jdk11.sh /disk/openjdk/upstream-sources/openjdk-11 /path/to/jdk11/build/; popd

That fails with:

    [echoproperties] java8.java.vm.vendor=Oracle Corporation
    [echoproperties] java8.java.vm.version=11.0.3+2
    [echoproperties] java8.jdk.debug=release
    [echoproperties] java8.line.separator=\\n
    [echoproperties] java8.openjdk=version "11.0.3" 2019-04-16
    [echoproperties] java8.os.arch=amd64
    [echoproperties] java8.os.name=Linux
    [echoproperties] java8.os.version=4.20.13-200.fc29.x86_64
    [echoproperties] java8.path.separator=\:
    [echoproperties] java8.sun.arch.data.model=64
    [echoproperties] java8.sun.boot.library.path=/home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2/lib
    [echoproperties] java8.sun.cpu.endian=little
    [echoproperties] java8.sun.cpu.isalist=
    [echoproperties] java8.sun.io.unicode.encoding=UnicodeLittle
    [echoproperties] java8.sun.java.launcher=SUN_STANDARD
    [echoproperties] java8.sun.jnu.encoding=UTF-8
    [echoproperties] java8.sun.management.compiler=HotSpot 64-Bit Tiered Compilers
    [echoproperties] java8.sun.os.patch.level=unknown
    [echoproperties] java8.user.country=US
    [echoproperties] java8.user.dir=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build
    [echoproperties] java8.user.home=/home/sgehwolf
    [echoproperties] java8.user.language=en
    [echoproperties] java8.user.name=sgehwolf
    [echoproperties] java8.user.timezone=
       [delete] Deleting: /tmp/openjdk.java.build.properties.700902521
         [echo] /tmp/openjdk.java.build.properties.700902521 deleted
         [echo] osname is Linux
         [echo] arch is amd64
         [echo] bits is 64
         [echo] java8_platformclass set to linux_x86
         [echo] java8_platform set to linux_x86-64
         [echo] java8_bindir set to /home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin/../bin
         [echo] java8_compiler set to /home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2/bin/javac
         [echo] java8_osname set to linux
         [echo] java8_arch set to x86
         [echo] java8_bits set to 64
         [echo] java8_java_specification_version set to 11
         [echo] java8_home set to /home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin/..
         [echo] java8_compiler set to /home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2/bin/javac

    configure-tools-jar:
         [echo] configure-tools-jar: Copying /home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin/../bin/../lib/tools.jar to /home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/systemtest_prereqs/tools

    BUILD FAILED
    /home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/TestConfig/scripts/build_test.xml:71: The following error occurred while executing this line:
    /home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/systemtest/common.xml:177: The following error occurred while executing this line:
    /home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:304: Warning: Could not find file /home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2/lib/tools.jar to copy.

    Total time: 15 seconds
    make: *** [makefile:82: compile] Error 1

**Comment by smlambert** [comment]
FYI @Yuehan-Lin @llxia

**Comment by jerboaa** [comment]
Somewhere in the output I see:

    AUTO_DETECT is turned on

and

    ant -f scripts/build_test.xml -DTEST_ROOT=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/TestConfig/.. -DBUILD_ROOT=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/test-results -DJAVA_BIN=/home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin -DJDK_VERSION=11 -DJCL_VERSION=latest -DBUILD_LIST=systemtest -DRESOURCES_DIR=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/test-results/TestConfig/resources -DPLATFORM=linux_x86-64 -DJDK_HOME=/home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin/.. -DJVM_VERSION=openjdk11

**Comment by jerboaa** [comment]
Workaround doesn't seem to work:

    export AUTO_DETECT=off
    export JDK_VERSION=11

...

Fails with the same error.

**Comment by lumpfish** [comment]
Can you see a "java.home is xxxxxxxx" message in the build output (near the top)?

**Comment by jerboaa** [comment]
Yes I can:

    setup-java8-properties:
     [echo] java.home is /home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin/..

**Comment by jerboaa** [comment]
FWIW, it should be pretty easy to reproduce locally :-) Steps should be there.

**Comment by smlambert** [comment]
The actual systemtest builds are not suffering from this presently, so very likely a mismatch or version skew of test materials causing this issue.  

From [console output](https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_x86-64_linux/189/consoleFull) of recent passing job: 

20:46:46  + ./openjdk-tests/maketest.sh ./openjdk-tests
20:46:46  AUTO_DETECT is turned on
20:46:46  ant -f ./src/build_envInfo.xml -DJAVA_BIN=/home/jenkins/workspace/openjdk11_hs_systemtest_x86-64_linux/openjdkbinary/j2sdk-image/bin -DJAVAC=/home/jenkins/workspace/openjdk11_hs_systemtest_x86-64_linux/openjdkbinary/j2sdk-image/bin/javac
20:46:46  Buildfile: /home/jenkins/workspace/openjdk11_hs_systemtest_x86-64_linux/openjdk-tests/TestConfig/src/build_envInfo.xml

**Comment by llxia** [comment]
Auto-detection worked as expected in this case (JDK_VERSION is set to 11).

The actual error is `/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:304: Warning: Could not find file /home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2/lib/tools.jar to copy.`

Also, system test printed out confusing message about `java8xxxx`. This is happening for all JDK11 test: https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_x86-64_linux/189/consoleFull

**Comment by llxia** [comment]
re https://github.com/AdoptOpenJDK/openjdk-tests/issues/967#issuecomment-471619569:

We will update AUTO_DETECT  to use true/false.

**Comment by lumpfish** [comment]
The copy comes from this target in openjdk-build/include/top.xml
```
	<target name="configure-tools-jar" depends="setup-java8-properties" unless="${tools_jar_correct}">
		<property name="tools_jar_origin" value="${java8_bindir}/../lib/tools.jar"/>
		<echo message="configure-tools-jar: Copying ${tools_jar_origin} to ${tools_jar_dir}"/>
		<copy file="${tools_jar_origin}" todir="${tools_jar_dir}"/>
		<property name="tools_jar" value="${tools_jar_dir}/${tools_jar_file}"/>
		<available file="${tools_jar_dir}/${tools_jar_file}" property="tools_jar_correct"/>
	</target>
```
So that is guarded by ${tools_jar_correct}, which is set by
```
	<target name="check-for-tools-jar">
		<property name="tools_jar_dir" location="${prereqs_root}/tools"/>
		<property name="tools_jar_file" value="tools.jar"/>
		<condition property="tools_jar_correct">
			<or>
				<not>
					<equals arg1="${java.specification.version}" arg2="1.8"/>
				</not>
				<and>
					<equals arg1="${java.specification.version}" arg2="1.8"/>
					<available file="${tools_jar_dir}/${tools_jar_file}"/>
				</and>
			</or>
		</condition>
	    <available file="${tools_jar_dir}/${tools_jar_file}" property="tools_jar" value="${tools_jar_dir}/${tools_jar_file}"/>
	</target>
```
So ${tools_jar_correct} should be true for your java.specification.version = 11.

Which makes me think that ${tools_jar_correct} may already be set (and properties are immutable).  The build is recursive - is it possible a previous ant earlier in the build was invoked with java8 - via the default ant installation on the machine or via ANT_HOME perhaps?

**Comment by smlambert** [comment]
Thanks @llxia - The jdk8 printouts for systemtest was raised a while back as a problem with that material: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/100 and I didn't catch it here to know it was a red herring in this issue.

**Comment by lumpfish** [comment]
The jdk8 vs jdk9 properties are as a result of historically being able to compile only some test cases using java 8 and some using java 9 (well before the new six monthly cadence was born).  The properties allow for specifying which compiler to use as the 'java 8 compiler' (for pre modularity test cases) and which to use as the 'java 9 compiler' (for post modularity test cases).  The java8.compiler / java9.compiler setting is then used in the test folder build.xml files to invoke the 'correct compiler'.  The default behaviour (if the user does not actively set java8_home and java9_home ant properties) is to set the values based on the java running ant.
At Adoptopenjdk the jdk under test is being used to build the test cases, so the default behaviour applies.  That  means that both java8_home and java9_home will be being set to the jdk under test (e.g. jdk11) and that jdk will be used for compiling all tests (the java8.compiler and java9.compiler properties will be set to the location of the jdk11 compiler).
The build dumps out the system properties of the java which has been specified for the java8.compiler and those for the java9.compiler.  These are being misinterpreted (understandably) as being incorrect because java8.xxxx does not reference a jdk8 instance.
If we want to drop this historical behaviour (and accept that we will be restricted to compiling the test cases with a single javac compiler), then the approach should be to
1. Replace the current 'get the java8_home settings' and 'get the java9_home settings' to just 'get the java_home settings' - i.e. replace java8.xxxx and java9.xxxx with just java.xxxx properties.
2. Change the test case folder build.xml files to guard against compiling against an incompatible javac by interrogating the java.xxxx properties rather than relying on the java8.compiler value.

**Comment by lumpfish** [comment]
What is strange about the problem reported here though is that everything appears to be in order - the 'java 8' setting contain the correct information (that jdk11 is being used as the java8_compiler) and that therefore we should not need to locate and use tools.jar (which is required only if jdk8 is being used for building) - however java.version.specification = 11 is somehow being interpreted as java.version.specification = 1.8 - perhaps as a result of the final 'switch' property already having been set.

**Comment by lumpfish** [comment]
@jerboaa - does it build if you run
```
JAVA_HOME=xxxxxxxx
cd openjdk-systemtest/openjdk-build
make
```
(you would need wget, gnu make and ant on your PATH) ?

**Comment by jerboaa** [comment]
> @jerboaa - does it build if you run
> 
> ```
> JAVA_HOME=xxxxxxxx
> cd openjdk-systemtest/openjdk-build
> make
> ```
> 
> (you would need wget, gnu make and ant on your PATH) ?

I'm building and running tests as described in https://github.com/AdoptOpenJDK/openjdk-tests/issues/967#issue-419568600

Where would I set JAVA_HOME in those steps?

**Comment by lumpfish** [comment]
Please just set JAVA_HOME=xxx manually
Under your cloned openjdk-tests directory you should see a systemtest/openjdk-systemtest/ subdirectory which is where the scripts clone the openjdk-systemtest directory to.  Looking at your script above I think it would be
```
export JAVA_HOME=/home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2
cd test-me-system-jdk11/openjdk-tests/systemtest/openjdk-systemtest/
make
```
Whether that builds completes OK will help in identifying where the problem lies.

**Comment by jerboaa** [comment]
> ```
> export JAVA_HOME=/home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2
> cd test-me-system-jdk11/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build
> make
> ```

This worked.

**Comment by lumpfish** [comment]
Thanks.  I'm wondering if it's something to do with the ant version the openjdk-tests scripts start the build with (which appears to be the one installed on the machine).  What does ant -version output?

**Comment by jerboaa** [comment]
```
$ ant -version
Apache Ant(TM) version 1.10.5 compiled on August 20 2018
```

All I know so far is that in `check-for-tools-jar` target, the property `tools_jar_correct` is **NOT** set. That's why it's trying to copying the tools.jar file. For some strange reason `${java.specification.version}` does not seem to evaluate to `11`.

**Comment by jerboaa** [comment]
This seems to fix it:

```
diff --git a/openjdk.build/include/top.xml b/openjdk.build/include/top.xml
index f524b26..367ff5c 100644
--- a/openjdk.build/include/top.xml
+++ b/openjdk.build/include/top.xml
@@ -279,10 +279,10 @@ limitations under the License.
                <condition property="tools_jar_correct">
                        <or>
                                <not>
-                                       <equals arg1="${java.specification.version}" arg2="1.8"/>
+                                       <equals arg1="${java8_java_specification_version}" arg2="1.8"/>
                                </not>
                                <and>
-                                       <equals arg1="${java.specification.version}" arg2="1.8"/>
+                                       <equals arg1="${java8_java_specification_version}" arg2="1.8"/>
                                        <available file="${tools_jar_dir}/${tools_jar_file}"/>
                                </and>
                        </or>

```

**Comment by Mesbah-Alam** [comment]
JAVA_HOME is set by common.xml here: https://github.com/AdoptOpenJDK/openjdk-tests/blob/5d73fb575929f6868b898831bb2eae3a268fd68d/systemtest/common.xml#L10

I wonder what's the difference between setting JAVA_HOME manually at the beginning, and the script setting it automatically.

**Comment by jerboaa** [comment]
OK. I ran another attempt with this patch:

```
diff --git a/openjdk.build/include/top.xml b/openjdk.build/include/top.xml
index f524b26..ee8622a 100644
--- a/openjdk.build/include/top.xml
+++ b/openjdk.build/include/top.xml
@@ -282,11 +282,12 @@ limitations under the License.
                                        <equals arg1="${java.specification.version}" arg2="1.8"/>
                                </not>
                                <and>
-                                       <equals arg1="${java.specification.version}" arg2="1.8"/>
+                                       <equals arg1="${java8_java_specification_version}" arg2="1.8"/>
                                        <available file="${tools_jar_dir}/${tools_jar_file}"/>
                                </and>
                        </or>
                </condition>
+               <echo message="check-for-tools-jar: java.specification.version is ${java.specification.version}"/>
            <available file="${tools_jar_dir}/${tools_jar_file}" property="tools_jar" value="${tools_jar_dir}/${tools_jar_file}"/>
        </target>
 
```

And I see this in the output:

```
check-for-tools-jar:
     [echo] check-for-tools-jar: java.specification.version is 1.8
[...]
```

But the only JDK I'm pointing it to is JDK 11...

**Comment by lumpfish** [comment]
What output do you get if you run this build.xml against your ant?  When I installed ant on my local machine (using apt-get) it installed a jdk on my machine itself.
```
<project default="echoproperties">
  <target name="echoproperties">
    <echoproperties prefix="java.">
    </echoproperties>
  </target>
</project>
```

**Comment by jerboaa** [comment]
Here you go:

```

echoproperties:
[echoproperties] #Ant properties
[echoproperties] #Tue Mar 12 19:12:32 CET 2019
[echoproperties] java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
[echoproperties] java.awt.printerjob=sun.print.PSPrinterJob
[echoproperties] java.class.path=/usr/share/java/ant.jar\:/usr/share/java/ant-launcher.jar\:/usr/share/java/ant-contrib/ant-contrib.jar\:/usr/share/java/antlr.jar\:/usr/share/java/ant/ant-antlr.jar\:/usr/share/java/bcel.jar\:/usr/share/java/ant/ant-apache-bcel.jar\:/usr/share/java/rhino.jar\:/usr/share/java/bsf.jar\:/usr/share/java/ant/ant-apache-bsf.jar\:/usr/share/java/apache-ivy/ivy.jar\:/usr/share/java/ant/ant-apache-log4j.jar\:/usr/share/java/oro.jar\:/usr/share/java/ant/ant-apache-oro.jar\:/usr/share/java/regexp.jar\:/usr/share/java/ant/ant-apache-regexp.jar\:/usr/share/java/xml-commons-resolver.jar\:/usr/share/java/ant/ant-apache-resolver.jar\:/usr/share/java/xalan-j2.jar\:/usr/share/java/xalan-j2-serializer.jar\:/usr/share/java/ant/ant-apache-xalan2.jar\:/usr/share/java/aqute-bnd/biz.aQute.bndlib.jar\:/usr/share/java/aqute-bnd/biz.aQute.bnd.jar\:/usr/share/java/aqute-bnd/aQute.libg.jar\:/usr/share/java/aqute-bnd/biz.aQute.bnd.annotation.jar\:/usr/share/java/slf4j/api.jar\:/usr/share/java/slf4j/simple.jar\:/usr/share/java/osgi-annotation/osgi.annotation.jar\:/usr/share/java/osgi-core/osgi.core.jar\:/usr/share/java/osgi-compendium/osgi.cmpn.jar\:/usr/share/java/checkstyle.jar\:/usr/share/java/antlr.jar\:/usr/share/java/apache-commons-beanutils.jar\:/usr/share/java/apache-commons-cli.jar\:/usr/share/java/apache-commons-logging.jar\:/usr/share/java/guava/guava.jar\:/usr/share/java/apache-commons-logging.jar\:/usr/share/java/ant/ant-commons-logging.jar\:/usr/share/java/apache-commons-net.jar\:/usr/share/java/ant/ant-commons-net.jar\:/usr/share/java/jarjar/jarjar.jar\:/usr/share/java/objectweb-asm/asm.jar\:/usr/share/java/objectweb-asm/asm-commons.jar\:/usr/share/java/javamail/pop3.jar\:/usr/share/java/javamail/logging-mailhandler.jar\:/usr/share/java/javamail/smtp.jar\:/usr/share/java/javamail/mailapi.jar\:/usr/share/java/javamail/dsn.jar\:/usr/share/java/javamail/imap.jar\:/usr/share/java/javamail/gimap.jar\:/usr/share/java/javamail/jakarta.mail-api.jar\:/usr/share/java/javamail/jakarta.mail.jar\:/usr/share/java/jaf/jakarta.activation-api.jar\:/usr/share/java/jaf/jakarta.activation.jar\:/usr/share/java/ant/ant-javamail.jar\:/usr/share/java/jdepend.jar\:/usr/share/java/ant/ant-jdepend.jar\:/usr/share/java/javaewah/JavaEWAH.jar\:/usr/share/java/jzlib.jar\:/usr/share/java/jsch.jar\:/usr/share/java/jgit/org.eclipse.jgit.jar\:/usr/share/java/jgit/org.eclipse.jgit.ant.jar\:/usr/share/java/slf4j/slf4j-api.jar\:/usr/share/java/slf4j/slf4j-simple.jar\:/usr/share/java/httpcomponents/httpcore.jar\:/usr/share/java/httpcomponents/httpclient.jar\:/usr/share/java/commons-logging.jar\:/usr/share/java/commons-codec.jar\:/usr/share/java/ant/ant-jmf.jar\:/usr/share/java/jsch.jar\:/usr/share/java/ant/ant-jsch.jar\:/usr/share/java/jtidy.jar\:/usr/share/java/junit.jar\:/usr/share/java/hamcrest/core.jar\:/usr/share/java/ant/ant-junit.jar\:/usr/share/java/junit.jar\:/usr/share/java/hamcrest/core.jar\:/usr/share/java/ant/ant-junit4.jar\:/usr/share/java/junit5/junit-platform-launcher.jar\:/usr/share/java/junit5/junit-platform-suite-api.jar\:/usr/share/java/junit5/junit-platform-surefire-provider.jar\:/usr/share/java/junit5/junit-jupiter-engine.jar\:/usr/share/java/junit5/junit-platform-commons.jar\:/usr/share/java/junit5/junit-jupiter-migrationsupport.jar\:/usr/share/java/junit5/junit-jupiter-api.jar\:/usr/share/java/junit5/junit-platform-engine.jar\:/usr/share/java/junit5/junit-vintage-engine.jar\:/usr/share/java/junit5/junit-platform-runner.jar\:/usr/share/java/junit5/junit-jupiter-params.jar\:/usr/share/java/hamcrest/core.jar\:/usr/share/java/junit.jar\:/usr/share/java/opentest4j/opentest4j.jar\:/usr/share/java/ant/ant-junitlauncher.jar\:/usr/share/java/ant/ant-swing.jar\:/usr/share/java/ant/ant-testutil.jar\:/usr/share/java/xz-java.jar\:/usr/share/java/ant/ant-xz.jar\:/usr/lib/jvm/java-1.8.0-openjdk/lib/tools.jar\:/usr/share/ant/lib/ant-junit.jar\:/usr/share/ant/lib/ant-jsch.jar\:/usr/share/ant/lib/ant-junitlauncher.jar\:/usr/share/ant/lib/ant-apache-bcel.jar\:/usr/share/ant/lib/ant-apache-xalan2.jar\:/usr/share/ant/lib/ant-apache-regexp.jar\:/usr/share/ant/lib/ant-testutil.jar\:/usr/share/ant/lib/ant-launcher.jar\:/usr/share/ant/lib/ant-xz.jar\:/usr/share/ant/lib/ant-javamail.jar\:/usr/share/ant/lib/ant-apache-log4j.jar\:/usr/share/ant/lib/ant-swing.jar\:/usr/share/ant/lib/ant-commons-logging.jar\:/usr/share/ant/lib/ant-jmf.jar\:/usr/share/ant/lib/ant-apache-bsf.jar\:/usr/share/ant/lib/ant-antlr.jar\:/usr/share/ant/lib/ant-apache-resolver.jar\:/usr/share/ant/lib/ant-junit4.jar\:/usr/share/ant/lib/ant-bootstrap.jar\:/usr/share/ant/lib/ant-commons-net.jar\:/usr/share/ant/lib/ant-apache-oro.jar\:/usr/share/ant/lib/ant.jar\:/usr/share/ant/lib/ant-jdepend.jar
[echoproperties] java.class.version=52.0
[echoproperties] java.endorsed.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.fc29.x86_64/jre/lib/endorsed
[echoproperties] java.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.fc29.x86_64/jre/lib/ext\:/usr/java/packages/lib/ext
[echoproperties] java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.fc29.x86_64/jre
[echoproperties] java.io.tmpdir=/tmp
[echoproperties] java.library.path=/usr/java/packages/lib/amd64\:/usr/lib64\:/lib64\:/lib\:/usr/lib
[echoproperties] java.runtime.name=OpenJDK Runtime Environment
[echoproperties] java.runtime.version=1.8.0_201-b09
[echoproperties] java.specification.name=Java Platform API Specification
[echoproperties] java.specification.vendor=Oracle Corporation
[echoproperties] java.specification.version=1.8
[echoproperties] java.vendor=Oracle Corporation
[echoproperties] java.vendor.url=http\://java.oracle.com/
[echoproperties] java.vendor.url.bug=http\://bugreport.sun.com/bugreport/
[echoproperties] java.version=1.8.0_201
[echoproperties] java.vm.info=mixed mode
[echoproperties] java.vm.name=OpenJDK 64-Bit Server VM
[echoproperties] java.vm.specification.name=Java Virtual Machine Specification
[echoproperties] java.vm.specification.vendor=Oracle Corporation
[echoproperties] java.vm.specification.version=1.8
[echoproperties] java.vm.vendor=Oracle Corporation
[echoproperties] java.vm.version=25.201-b09

BUILD SUCCESSFUL
Total time: 0 seconds
```

So `java.specification.version` is the version which was used to run ant. Interesting. So that's the reason why JAVA_HOME would be needed. The distro ant script picks up JAVA_HOME as `JAVA_HOME=some-jdk ant -f echoproperties` returns properties correctly from `some-jdk` :)

**Comment by lumpfish** [comment]
So I think the ${tools_jar_correct} property must be being set for the jdk running ant when it is invoked via the openjdk-tests command
```
ant -f scripts/build_test.xml -DTEST_ROOT=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/TestConfig/.. -DBUILD_ROOT=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/test-results -DJAVA_BIN=/home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin -DJDK_VERSION=11 -DJCL_VERSION=latest -DBUILD_LIST=systemtest -DRESOURCES_DIR=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/test-results/TestConfig/resources -DPLATFORM=linux_x86-64 -DJDK_HOME=/home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin/.. -DJVM_VERSION=openjdk11
```
and then later when the build evaluates the properties for the jdk passed via JAVA_BIN it cannot be reset because ant properties are immutable.

Looking at the ant install on my local Ubuntu, the 'ant' command is a script which ends up running
```
exec \"\$JAVACMD\" $ANT_OPTS -classpath \"\$LOCALCLASSPATH\" -Dant.home=\"\$ANT_HOME\" -Dant.library.dir=\"\$ANT_LIB\" $ant_sys_opts org.apache.tools.ant.launch.Launcher $ANT_ARGS -cp \"\$CLASSPATH\""
```
and JAVACMD defaults to the result of running
```
which java
```
An option for a fix might be to force ant to be run with the the JAVA_BIN java - something like
```
JAVACMD=$JAVA_BIN/java ant -f scripts/build_test.xml -DTEST_ROOT=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/TestConfig/.. -DBUILD_ROOT=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/test-results -DJAVA_BIN=/home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin -DJDK_VERSION=11 -DJCL_VERSION=latest -DBUILD_LIST=systemtest -DRESOURCES_DIR=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/test-results/TestConfig/resources -DPLATFORM=linux_x86-64 -DJDK_HOME=/home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin/.. -DJVM_VERSION=openjdk11
runs the org.apache.tools.ant.launch.Launcher class
```
Is that something you could try? I found the ant command in TestConfig/makefile, so please try changing that and rerunning the
```
OPENJDK_DIR=$OPENJDK_SOURCES ./maketest.sh $TEST_DIR $TEST_TARGET
```
part of the script.

I think TestConfig/makefile, is generated via the
```
./maketest.sh $TEST_DIR
```
command, so to implement this as a real fix would need a change to the tooling which generates the makefile.

**Comment by jerboaa** [comment]
@lumpfish My work-around is adding `export JAVA_HOME=/path/to/to/jdk/under/test` when I launch the system test. The ant script picks up JAVA_HOME and will use that over whatever the other default is.

So +1 to:

```
JAVACMD=$JAVA_BIN/java ant -f scripts/build_test.xml -DTEST_ROOT=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/TestConfig/.. -DBUILD_ROOT=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/test-results -DJAVA_BIN=/home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin -DJDK_VERSION=11 -DJCL_VERSION=latest -DBUILD_LIST=systemtest -DRESOURCES_DIR=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/test-results/TestConfig/resources -DPLATFORM=linux_x86-64 -DJDK_HOME=/home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2//bin/.. -DJVM_VERSION=openjdk11
runs the org.apache.tools.ant.launch.Launcher class
```

As `JAVACMD` is referenced as supported environment variable here:
https://ant.apache.org/manual/running.html

The other option is to not rely on `java.specification.version` directly, but use another property which definitely comes from the JDK that's under test.

**Comment by lumpfish** [comment]
@llxia  - are you OK with the suggestion to prefix the initial generated ant command with
```
JAVACMD=$JAVA_BIN/java
```
?

**Comment by llxia** [comment]
I am wondering if we should export JAVA_HOME in TKG, so that both ant and test can get it. Currently, each system test has to export JAVA_HOME before running.

Any thoughts? @Mesbah-Alam @renfeiw

**Comment by Mesbah-Alam** [comment]
I vote for having JAVA_HOME exported in TKG. It simplifies the world.

**Comment by llxia** [comment]
@renfeiw Could we update TKG to export JAVA_HOME? Thanks

**Comment by renfeiw** [comment]
PR to export JAVA_HOME: https://github.com/eclipse/openj9/pull/5155

**Comment by renfeiw** [comment]
I also tried to remove export from playlist.xml and it works in the grinder: https://github.com/AdoptOpenJDK/openjdk-tests/pull/997

**Comment by phiberoptick** [comment]
> Auto-detection worked as expected in this case (JDK_VERSION is set to 11).
> 
> The actual error is `/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-system-jdk11/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:304: Warning: Could not find file /home/sgehwolf/Documents/openjdk/static-build/openjdk-11u-11.0.3+2/lib/tools.jar to copy.`
> 
> Also, system test printed out confusing message about `java8xxxx`. This is happening for all JDK11 test: https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_x86-64_linux/189/consoleFull

Found this while troubleshooting a similar issue with gradle.

It seems that tools.jar was removed in java9.  I was able to remedy the issue by using jdk8-openjdk (8.u212-1-x86_64).

Perhaps you can install it or at least download and build against it?

GL

**Comment by lumpfish** [comment]
The reported issues should no longer occur:
1. The confusing messages about java8xxxx (which was actually being used to identify which test cases can be built with java8 as opposed to tests which required java9 (or later) rather than identifying the java version being used for the build) should have been recently removed (last few days) via the pull requests mentioned in this comment https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/132#issuecomment-486311623.
2. The tools.jar error which occurred only when running via the testkitgen toolset I think should have been fixed via https://github.com/eclipse/openj9/pull/5155. (@renfeiw - can you confirm?)

Are you using the latest test repo updates?

**Comment by jerboaa** [comment]
Yes. I haven't seen this issue in a while.

https://github.com/AdoptOpenJDK/openjdk-tests/issues/967#issuecomment-492053615 seems unrelated to AdoptOpenJDK tests. Is it?

**Comment by renfeiw** [comment]
Yes. The tools.jar error should be fixed. Closing this issue.
