### ISSUE TITLE
Add openjdktest with hotspot implement on s390x_linux

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#969]
- [x] https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_s390x_linux

- [x] https://ci.adoptopenjdk.net/view/all/job/openjdk8_hs_openjdktest_s390x_linux

**Comment by sophia-guo** [comment]
[openjdk8_hs_openjdktest_s390x_linux](https://ci.adoptopenjdk.net/view/all/job/openjdk8_hs_openjdktest_s390x_linux) was created long time ago with old pipeline story, which has changed a lot. When updated job configuration using new pipeline will  get errors like:

```
java.io.FileNotFoundException
	at jenkins.plugins.git.GitSCMFile.lambda$content$2(GitSCMFile.java:159)
	at jenkins.plugins.git.GitSCMFileSystem.lambda$invoke$e8567d7e$1(GitSCMFileSystem.java:183)
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:81)
...org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```
https://ci.adoptopenjdk.net/view/all/job/openjdk8_hs_openjdktest_s390x_linux/244/console

Uncheck the Lightweight checkout will get the errors like

```
 > git rev-list --no-walk 37fe855eb541e5a82ea8d60403ece1a9fcde6f3e # timeout=10
ERROR: /home/jenkins/.jenkins/workspace/openjdk8_hs_openjdktest_s390x_linux@script/buildenv/jenkins/openjdk8_s390x_linux not found
Finished: FAILURE
```
https://ci.adoptopenjdk.net/view/all/job/openjdk8_hs_openjdktest_s390x_linux/243/console

Tried with rename the project and create a new project with same name got exactly same errors. Suspect we need to delete(not disable) the project https://ci.adoptopenjdk.net/view/all/job/openjdk8_hs_openjdktest_s390x_linux and https://ci.adoptopenjdk.net/view/all/job/openjdk8_hs_openjdktest_s390x_linux_test. Also probably need to clean the workspace  ` /home/jenkins/.jenkins/workspace/openjdk8_hs_openjdktest_s390x_linux***` manually on master machine.

**Comment by smlambert** [comment]
I've deleted the 2 test jobs, and recreated https://ci.adoptopenjdk.net/view/all/job/openjdk8_hs_openjdktest_s390x_linux, started a new job, which is waiting on a machine.  Let's see how it goes.

**Comment by sophia-guo** [comment]
Looks good!

**Comment by smlambert** [comment]
Ok, great, do we need someone from infra to remove any files on master?  I think this job, since the name is the same, will delete the old workspace. (however, the job named openjdk8_hs_openjdktest_s390x_linux_test will not be run again, so there may be cleanup needed.
