### ISSUE TITLE
Re-name and clean up top-level directory structure

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#980]
When we initially named some of our directories, we did not align them with our top-level test target names.  In order to make things clearer for those using this test resource, we will rename the following:

- [x] performance to perf

- [x] thirdparty_containers to external

- [x] systemtest to system

- [x] openjdk_regression to openjdk

These renaming changes will also require updates to scripts and documentation.

Additional clean-up, we have shifted triage doc to wiki pages, so we can remove the triage folder.

**Comment by llxia** [comment]
ToDo after renaming systemtest to system:
- [ ] regenerate system test jobs in AdoptOpenJDK to set BUILD_LIST to `system`

- [ ] update BUILD_LIST description in Grinder on all sites

**Comment by karianna** [comment]
Can this be closed now?

**Comment by llxia** [comment]
yes, I think so.
wikis are updated: 
https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally
https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins
