### ISSUE TITLE
Include scratch dir in archived openjdk test artifacts

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#988]
We currently archive some of the contents of the work dir that is created by jtreg, but are not including the scratch dir which would house cores/dmp files if they occur during a test run. 

We should update Jenkinsfilebase to include scratch dir contents:
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L339-L349

**Comment by sophia-guo** [comment]
This should be closed by #1073
