### ISSUE TITLE
Separate each external test into a independent test job

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#991]
Each external test is a complete testcase and take long to run with huge output. We'd like to separate each of it as a independent test jobs. For now no need to update upstream build job

- [x]  reconfigure each openjdk[jdk_version]_j9|hs_externaltest[_extended]_x86-64_linux job as a parent job, which pass in parameter to trigger each downstream external test build

- [x] manually generate each external test jobs(no parameters is needed, auto - generate need administrator permission)

- [x] If test is disabled the corresponding test job will be disabled too

- [x] Test job will not be generated if tests is not applicable to specific version.

**Comment by sophia-guo** [comment]
https://ci.adoptopenjdk.net/view/Test_external/

**Comment by Mesbah-Alam** [comment]
Thanks @sophia-guo !
