### ISSUE TITLE
Testing in parallel holds a Jenkins node executor unnecessarily 

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-tests#994]
Possibly related #747 

I noticed some test jobs running that were orchestrating downstream parallel jobs. The issue is that the orchestrator portion is holding onto a node unnecessarily. I took a quick glace at the code but it does not seem like a 2 minute fix.

https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L154
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L406

**Comment by llxia** [comment]
Yes, this is a known issue. It is on our todo list to fix this.
