### ISSUE TITLE
Add Multi-Byte Character Set locale tests for Windows

### ISSUE THREAD

**Issue by KKES335** [AdoptOpenJDK/openjdk-tests#995]
An issue for the contribution of MBCS tests for Windows to AdoptOpenJDK. 
There are 23 tests as same as Linux/AIX.
Also, there are two types execution in new tests.
The first is that 23 tests can be run on Japanese or Korean Windows.  These tests use Windows locale information. so Japanese or Korean Windows are needed.
The second is that 18 tests can be run on any locale Windows.  These tests wrap 23 tests (5 of 23 tests cannot wrap ) and java is set to Japanese or Korean information by using Locale class and its encoding.

**Comment by takiguc** [comment]
Test result is as follows:

OpenJDK JDK8+OpenJ9 for Windows
91 tests, 33 ok, 0 not ok, 58 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1295/tapResults/

OpenJDK JDK8+OpenJ9 for Linux x86_64
91 tests, 25 ok, 0 not ok, 66 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1294/tapResults/

OpenJDK JDK11+OpenJ9 for Windows
177 tests, 54 ok, 0 not ok, 123 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1293/tapResults/

OpenJDK JDK11+OpenJ9 for Linux x86_64
177 tests, 45 ok, 0 not ok, 132 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1292/tapResults/

**Comment by smlambert** [comment]
Thank you @KKES335 - for providing both a PR and the Grinder results for this.  I will review the PR shortly.

**Comment by KKES335** [comment]
Thank you @smlambert - A PR has been closed. so I will close this issue.

**Comment by smlambert** [comment]
Thanks @KKES335 - we will plan to add these tests to a weekly test job.
